### ISSUE TITLE
java.sql.SQLException: TDengine Error: success

### ISSUE THREAD

**Issue by scolGit** [taosdata/TDengine#1020]
java for 循环调用有时候会出现,
centerOs7
 taos-jdbcdriver 1.0.1
java.sql.SQLException: TDengine Error: success
at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:100)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
  这到底是连上还是没有连接上? 因为有try catch 所以就算连接上也是走了catch

**Comment by xieyinglin** [comment]
请问使用的是哪个版本，可以使用最新版本再测试下
