### ISSUE TITLE
Restful Jdbc couldn't find LogFactory 

### ISSUE THREAD

**Issue by Michael4zhang** [taosdata/TDengine#10262]
**Bug Description**
java中使用restful驱动连接时，抛出了这个异常
```java
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:116)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:123)
	at com.taosdata.jdbc.utils.HttpClientPoolUtil.init(HttpClientPoolUtil.java:62)
	at com.taosdata.jdbc.rs.RestfulDriver.connect(RestfulDriver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at cn.demo.Main.main(Main.java:13)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more

```

**To Reproduce**
新的Maven项目
1. 添加依赖到pom.xml中
```xml
<dependency>
    <groupId>commons-logging</groupId>
    <artifactId>commons-logging</artifactId>
    <version>1.2</version>
</dependency>
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>2.0.35</version>
</dependency>
```
2. 新建一个名字为Main的类， 并添加代码
```java
public static void main(String[] args) throws ClassNotFoundException, SQLException {
    Class.forName("com.taosdata.jdbc.rs.RestfulDriver");
    String jdbcUrl = "jdbc:TAOS-RS://172.16.9.200:6041/location_gps?user=tdsa&password=tdsa#2014";
    Connection conn = DriverManager.getConnection(jdbcUrl);
    Statement statement = conn.createStatement();
    ResultSet rs = statement.executeQuery("select * from d_imei_track");
    while (rs.next()) {
        Long ts = rs.getLong("ts");
        String lon = rs.getString("lon");
        String lat = rs.getString("lat");
        String imei = rs.getString("imei");
        System.out.println("ts=" + ts + ", lon=" + lon + ", lat=" + lat + ", imei=" + imei);
    }
}
```

**Environment (please complete the following information):**
 - OS: MacOS 12.1
 - Memory: 16GB, CPU: Intel Core i7
 - TDengine Version：2.4.0.0

**Comment by huolibo** [comment]
没有使用taosadapter，而是使用TDengine自带的httpd提供restful服务的吗？

**Comment by Michael4zhang** [comment]
服务端暂时不清楚，客户端的没有任何自定义设置，请问这个问题与服务端提供的restful服务有关吗？

**Comment by huolibo** [comment]
想复现下环境，由于我本机使用最新的TDengine版本和taosadapter（提供restful服务），然后创建一个简单的maven环境 没有复现此问题。

**Comment by huolibo** [comment]
尝试升级下jdbc版本呢？比如2.0.36或37

**Comment by Michael4zhang** [comment]
感谢帮助，我刚才用另外一台电脑测试了一下，没有发现问题，但是我的mac就是不行，我是使用了2.4.0.0的tag源码使用cmake打包的客户端，可以在shell中链接server没有问题，但是java就是不行

**Comment by huolibo** [comment]
shell 使用的taos动态库连接，如果shell能够正常使用，可以使用jdbc的TAOS驱动来创建连接。

**Comment by Michael4zhang** [comment]
非常感谢帮助，问题已经解决，但是不知道具体原因是什么，我将我系统内的jdk卸载干净后重新安装jdk就可以了，现在也可以使用libtaos库连接了
