### ISSUE TITLE
java.sql.SQLException: TDengine Error: failed to connect to server

### ISSUE THREAD

**Issue by flytohyj** [taosdata/TDengine#1034]
环境：win10上JAVA程序 连接 linux服务器上的TDengine报错
1.服务器上ping的通 端口6030也能够telnet上。/taos.dll的也已经再system32目录下
2.代码依赖最新的jar包taos-jdbcdriver 1.0.3版本
3.在win10机器64位上采用源码中的 JDBCDemo进行测试，报如下错误
java.sql.SQLException: TDengine Error: failed to connect to server
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:102)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at TSDBSyncSample.doCreateDbAndTable(TSDBSyncSample.java:84)
	at TSDBSyncSample.main(TSDBSyncSample.java:44)
Failed to execute SQL: 
4.同样的代码放到linux机器上 运行成功。
5.采用TDengine-client-windows-x64-1.6.4.4.exe 安装之后 通过cmd 进行连接
Welcome to the TDengine shell from windows, client version:1.6.4.4
DB error: failed to connect to server
现在不知道具体是什么原因？

**Comment by flytohyj** [comment]
![image](https://user-images.githubusercontent.com/3862365/71609011-21435f00-2bc0-11ea-8708-1fdac5fdd491.png)
在taos-jdbcdriver 1.0.3.jar中 如果采用 String jdbcUrl = "jdbc:TSDB://1921.168.14.7:6030/log?user=root&password=taosdata";  直接写 到后面解析的时候 user获取不到
前面加个jdbc:TSDB://1921.168.14.7:6030/log?1=1&user=root&password=taosdata
但还是连接不上
 java.sql.SQLException: TDengine Error: failed to connect to server
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:102)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at TSDBSyncSample.doCreateDbAndTable(TSDBSyncSample.java:84)
	at TSDBSyncSample.main(TSDBSyncSample.java:44)
Failed to execute SQL: 
能帮忙看一下吗
用的都是最新的jar包和部署包 版本 1.6.4.4

**Comment by flytohyj** [comment]
windows日志
==================================================
                new log file                      
==================================================
12/31 12:09:50.940000 0x14488 UTL timezone not configured, use default
12/31 12:09:50.963000 0x14488 UTL locale not configured, set to default:Chinese_China.936
12/31 12:09:50.963000 0x14488 UTL charset not configured, set to default:cp936
12/31 12:09:50.963000 0x14488 UTL    taos config & system info:
12/31 12:09:50.963000 0x14488 UTL ==================================
12/31 12:09:50.963000 0x14488 UTL  serverIp:               127.0.0.1 
12/31 12:09:50.963000 0x14488 UTL  localIp:                0.0.0.0 
12/31 12:09:50.963000 0x14488 UTL  mgmtShellPort:          6030 
12/31 12:09:50.963000 0x14488 UTL  vnodeShellPort:         6035 
12/31 12:09:50.963000 0x14488 UTL  configDir:              C:/TDengine/cfg 
12/31 12:09:50.963000 0x14488 UTL  logDir:                 C:/TDengine/log 
12/31 12:09:50.963000 0x14488 UTL  scriptDir:              C:/TDengine/script 
12/31 12:09:50.963000 0x14488 UTL  numOfThreadsPerCore:    0.000000 
12/31 12:09:50.963000 0x14488 UTL  rpcTimer:               300(ms)
12/31 12:09:50.963000 0x14488 UTL  rpcMaxTime:             600(s)
12/31 12:09:50.963000 0x14488 UTL  shellActivityTimer:     3(s)
12/31 12:09:50.963000 0x14488 UTL  meterMetaKeepTimer:     7200(s)
12/31 12:09:50.963000 0x14488 UTL  metricMetaKeepTimer:    600(s)
12/31 12:09:50.963000 0x14488 UTL  defaultDB:               
12/31 12:09:50.963000 0x14488 UTL  defaultUser:            root 
12/31 12:09:50.963000 0x14488 UTL  sockettype:             udp 
12/31 12:09:50.963000 0x14488 UTL  compressMsgSize:        -1 
12/31 12:09:50.963000 0x14488 UTL  timezone:               not configured 
12/31 12:09:50.963000 0x14488 UTL  locale:                 Chinese_China.936 
12/31 12:09:50.963000 0x14488 UTL  charset:                cp936 
12/31 12:09:50.963000 0x14488 UTL  numOfLogLines:          10000000 
12/31 12:09:50.963000 0x14488 UTL  asyncLog:               1 
12/31 12:09:50.963000 0x14488 UTL  debugFlag:              131 
12/31 12:09:50.963000 0x14488 UTL  rpcDebugFlag:           131 
12/31 12:09:50.963000 0x14488 UTL  tmrDebugFlag:           131 
12/31 12:09:50.963000 0x14488 UTL  cDebugFlag:             131 
12/31 12:09:50.963000 0x14488 UTL  jniDebugFlag:           131 
12/31 12:09:50.963000 0x14488 UTL  odbcDebugFlag:          131 
12/31 12:09:50.963000 0x14488 UTL  uDebugFlag:             131 
12/31 12:09:50.963000 0x14488 UTL  qDebugFlag:             131 
12/31 12:09:50.963000 0x14488 UTL  gitinfo:                d62c5c30231d04a736d437cf428af6e12599bd9f 
12/31 12:09:50.963000 0x14488 UTL  gitinfoOfInternal:      8094a32d78dc519bd883d01ac2ba6ec49ac57a80 
12/31 12:09:50.963000 0x14488 UTL  buildinfo:              Built by ubuntu at 2019-12-16 21:40 
12/31 12:09:50.963000 0x14488 UTL  version:                1.6.4.4 
12/31 12:09:50.963000 0x14488 UTL  dataDir:                C:/TDengine/data
12/31 12:09:50.963000 0x14488 UTL ==================================
12/31 12:09:59.975000 0x12080 ERROR TSC 000000001A89DEC0 reach the max retry:2, code:29
12/31 12:09:59.975000 0x14488 ERROR JNI jobj:0000000002A9F278, conn:0000000000000000, connect to database failed, host=192.168.14.7, user=root, dbname=log, port=6030
12/31 12:09:59.979000 0x14488 ERROR JNI jobj:0000000002A9F208, connection is closed

**Comment by flytohyj** [comment]
找到原因了，我linux服务器上的版本是 手工 编译安装的 是1.6.5
客户端win10用的是1.6.4  造成连接不上
