### ISSUE TITLE
TDengine ERROR (8000000b): Unable to establish connection

### ISSUE THREAD

**Issue by Jackhzf** [taosdata/TDengine#10378]
create table if not exists test.test
        (
            ts timestamp,
            temperature float,
            humidity float,
            note nchar(200),
            name nchar(200),
            url nchar(200),
            message nchar(200),
            content nchar(200)
        ) tags
        (
            location nchar(64),
            groupId int
        )
这是创建的表
08:13:18.972 [Thread-65] DEBUG c.r.s.m.T.insertTest - [debug,137] - ==>  Preparing: insert into test.test0 (ts, temperature, humidity, note,name,url,message,content) values (?, 7.929885, 44.90188, ?, ?, ?, ?, ?)
08:13:18.976 [Thread-65] DEBUG c.r.s.m.T.insertTest - [debug,137] - ==> Parameters: 2022-02-24 08:13:18.376(Timestamp), 6hzIYkQniKlh3wmpKef5ingpZlgX2EzyNoATHlc9nSOJ4pwFSbvtgWwI8HaDZpN0wMIqHF(String), 6hzIYkQniKlh3wmpKef5ingpZlgX2EzyNoATHlc9nSOJ4pwFSbvtgWwI8HaDZpN0wMIqHF(String), 6hzIYkQniKlh3wmpKef5ingpZlgX2EzyNoATHlc9nSOJ4pwFSbvtgWwI8HaDZpN0wMIqHF(String), 6hzIYkQniKlh3wmpKef5ingpZlgX2EzyNoATHlc9nSOJ4pwFSbvtgWwI8HaDZpN0wMIqHF(String), 6hzIYkQniKlh3wmpKef5ingpZlgX2EzyNoATHlc9nSOJ4pwFSbvtgWwI8HaDZpN0wMIqHF(String)
有5列是字符串类型，插入的时候每列赋值70个字符，就会报错

Exception in thread "Thread-65" org.springframework.jdbc.UncategorizedSQLException: 
### Cause: java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection
; uncategorized SQLException; SQL state []; error code [-2147483637]; TDengine ERROR (8000000b): Unable to establish connection; nested exception is java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy114.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy155.insertTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.ruoyi.framework.aspectj.DataSourceAspect.around(DataSourceAspect.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy156.insertTest(Unknown Source)
	at com.ruoyi.system.service.impl.TdEngineServerImpl$1.run(TdEngineServerImpl.java:144)
	at java.lang.Thread.run(Thread.java:748)

如果每列赋值50个字符就没有问题，每列设置70个字符就报错，springbootdemo红代码，循环10次

**Comment by Jackhzf** [comment]
解决了，内存问题
