### ISSUE TITLE
jdbc jni cannot connect in linux

### ISSUE THREAD

**Issue by liu-xinhui** [taosdata/TDengine#11062]
server verion: 2.4.0.12
client version: 2.4.0.14
taos-jdbcdriver：2.0.37
server and client communication by Extranet.

In my develop computer(win 10) its OK(`spring boot project and windows client all OK`).

when I depoy the project to server(docker ubuntu), it OK by command, but the spring boot project error

![image](https://user-images.githubusercontent.com/7698511/160371213-1d37a3ad-cb6b-4793-984d-40a63ee3611d.png)

```
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: JNI ERROR (2354): Ref is not there
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:646)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1025)
	at com.step.iot.core.util.http.JettyConnector.saveToTdEngine(JettyConnector.java:199)
	at com.step.iot.core.util.http.JettyConnector.lambda$enhance$6(JettyConnector.java:135)
	at org.eclipse.jetty.client.HttpRequest$6.onSuccess(HttpRequest.java:466)
	at org.eclipse.jetty.client.RequestNotifier.notifySuccess(RequestNotifier.java:223)
	at org.eclipse.jetty.client.RequestNotifier.notifySuccess(RequestNotifier.java:209)
	at org.eclipse.jetty.client.HttpSender.someToSuccess(HttpSender.java:326)
	at org.eclipse.jetty.client.HttpSender$LastCallback.succeeded(HttpSender.java:921)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendContent(HttpSenderOverHTTP.java:126)
	at org.eclipse.jetty.client.HttpSender$ContentCallback.process(HttpSender.java:845)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
	at org.eclipse.jetty.client.HttpSender$CommitCallback.process(HttpSender.java:763)
	at org.eclipse.jetty.client.HttpSender$CommitCallback.succeeded(HttpSender.java:710)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.onCompleteSuccess(HttpSenderOverHTTP.java:307)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:326)
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:366)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.succeeded(HttpSenderOverHTTP.java:293)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:394)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:835)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: JNI ERROR (2354): Ref is not there
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75)
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:80)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:33)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:19)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:131)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	... 26 common frames omitted
```

Why?

**Comment by fenghua1997** [comment]
1、Configure hostname and host for each node, until all the machines can ping each other.
2、Different components use different port numbers. Ensure that all ports are released or mapped, including TCP and UDP.

**Comment by liu-xinhui** [comment]
@fenghua1997 I have solved this problem，the server does not open udp
