### ISSUE TITLE
jni error (2355): jni result set is null

### ISSUE THREAD

**Issue by minitt** [taosdata/TDengine#11410]
![20220412120633](https://user-images.githubusercontent.com/1438510/162878817-8555e952-d3d8-40b5-8638-182c6b638fea.png)
表里有7亿数据，我20个连接每个连接取300万数据。报错。
如果只取少量数据，不会报错。

tdengine版本:2.4.0.0
jdbc版本:2.0.36
系统:centos7.6

**Comment by huolibo** [comment]
可以提供下测试代码吗？我在本地没有复现问题，我的测试代码如下：
```java
package com.taosdata.jdbc;

import org.junit.Test;

import java.sql.*;
import java.util.Date;
import java.util.Properties;
import java.util.concurrent.CountDownLatch;
import java.util.stream.IntStream;

public class MultiThreadQueryTest {
    static String host = "192.168.1.98";
    static int num = 20;
    CountDownLatch countDownLatch;

    Runnable runnable = new Runnable() {
        @Override
        public void run() {
            Properties properties = new Properties();
            properties.setProperty(TSDBDriver.PROPERTY_KEY_USER, "root");
            properties.setProperty(TSDBDriver.PROPERTY_KEY_PASSWORD, "taosdata");
            Connection connection = null;
            try {
                connection = DriverManager.getConnection("jdbc:TAOS://" + host + ":6030/", properties);
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery("select * from test.meters limit 3000000");
                int count = 0;
                long start = System.nanoTime();
                while (resultSet.next()) {
                    count++;
                }
                System.out.println(new Date() + " 线程：" + Thread.currentThread().getId()
                        + "查询条数：" + count + "耗时：" + (System.nanoTime() - start));
                countDownLatch.countDown();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    };

    @Test
    public void MultiQuery() throws InterruptedException {
        long start = System.nanoTime();
        countDownLatch= new CountDownLatch(num);
        IntStream.range(1, 100).limit(num).parallel().forEach(x -> {
            Thread thread = new Thread(runnable);
            thread.start();
        });
        countDownLatch.await();
        System.out.println("总耗时：" + (System.nanoTime() - start));
    }
}

```

**Comment by 6alex** [comment]
该问题在2.6.0.12版本仍然存在，且无法重现，经常重试几次又能成功
java.sql.SQLException: JNI ERROR (2355): JNI result set is NULL
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75)
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:59)
        at com.taosdata.jdbc.TSDBResultSet.next(TSDBResultSet.java:98)
