### ISSUE TITLE
TDengine ERROR (80000362): Table does not exist

### ISSUE THREAD

**Issue by Aireason727** [taosdata/TDengine#11517]
Springboot项目多数据源切换后，执行查询时报错
TDengine [版本信息：2.4.0.16]

2022-04-15 10:09:18.012  INFO 18500 --- [nio-8080-exec-3] c.t.f.d.DynamicDataSourceContextHolder   : 切换到SLAVE数据源
2022-04-15 10:09:18.635 ERROR 18500 --- [nio-8080-exec-3] com.alibaba.druid.pool.DruidDataSource   : init datasource error, url: jdbc:TAOS://192.168.2.107:6030/test?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8

java.sql.SQLException: TDengine ERROR (80000362): Table does not exist
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76) ~[taos-jdbcdriver-2.0.38.jar:na]
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119) ~[taos-jdbcdriver-2.0.38.jar:na]
	at com.taosdata.jdbc.TSDBStatement.executeQuery(TSDBStatement.java:47) ~[taos-jdbcdriver-2.0.38.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2883) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.filter.FilterAdapter.statement_executeQuery(FilterAdapter.java:2514) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeQuery(FilterEventAdapter.java:302) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2880) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeQuery(StatementProxyImpl.java:221) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1434) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1733) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:927) [druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1401) [druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1397) [druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100) [druid-1.2.8.jar:1.2.8]
	at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:194) [spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) [spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) [spring-jdbc-5.3.12.jar:5.3.12]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) [spring-jdbc-5.3.12.jar:5.3.12]
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80) [mybatis-spring-2.0.6.jar:2.0.6]
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67) [mybatis-spring-2.0.6.jar:2.0.6]

[taos.zip](https://github.com/taosdata/TDengine/files/8493528/taos.zip)

**Comment by huolibo** [comment]
显示表不存在。
04/15 10:09:17.503449 04192082 MND user:root login from 192.168.17.68, result:success
04/15 10:09:17.508607 04192081 MND ERROR msg:0x7f59a4002080, app:0x5 table:0.test.dual, failed to get table meta, table not exist
04/15 10:09:18.031646 04192083 MND user:root login from 192.168.17.68, result:success
04/15 10:09:18.032344 04192082 MND ERROR msg:0x7f59a4002080, app:0x9 table:0.test.dual, failed to get table meta, table not exist

**Comment by Aireason727** [comment]
数据库“test”中是有表“weather”的；只使用TDEngine作为数据源就没问题
![database-table](https://user-images.githubusercontent.com/83942162/163532190-427bd6de-97b7-401b-8ad7-237f8d970b7c.png)

**Comment by gccgdb1234** [comment]
2022-04-15 10:09:18.012 INFO 18500 --- [nio-8080-exec-3] c.t.f.d.DynamicDataSourceContextHolder : 切换到SLAVE数据源
我注意到这条日志
部署环境是两个TDengine，A和B，B是A的备份，用A时没问题，切换到B时出错？

**Comment by Aireason727** [comment]
部署环境中一个是原有的MySQL，一个是新加的TDEngine，启动的时候是先加载的MySQL，之后查询TDEngine中表的时候就报错

**Comment by gccgdb1234** [comment]
那这不是Java Connector的问题，日志中明确看出TDengine中没有想查找的table
要么是数据同步的问题，该从MySQL同步过来的没有同步过来
要么是应用的问题，在切换数据源时仍然试图访问只有MySQL中才有的表

**Comment by Aireason727** [comment]
我试过在环境中部署2个MySQL，A和B，从A切换B，查询B中才有的表，是可以执行的，没有报错

**Comment by gccgdb1234** [comment]
意思是切换到slave 数据源后想查询的表是只有在TDengine中才有的表？

**Comment by Aireason727** [comment]
是的

**Comment by huolibo** [comment]
可以做一个测试来排查是否是mybatis缓存的问题：
在每个sql后面增加一个随机值得 where 条件判断  `AND #{random,jdbcType=VARCHAR} = #{random,jdbcType=VARCHAR}`
看下是否有效

**Comment by Aireason727** [comment]
我试了，应该不是mybatis缓存问题，在MySQL中查询每次都会去数据库查；但一切换到TDEngine就会报错：TDengine ERROR (80000362): Table does not exist

**Comment by huolibo** [comment]
尝试下使用两个TDengine做主从，然后切换下看是否可以正常运行?

**Comment by Aireason727** [comment]
找到原因了，是配置的问题；配置文件application.yml中spring.datasource.druid.validationQuery的值应该是“select 1”或是“select server_status()”，不能是之前MySQL用的“selece 1 from dual”。因该TDEngine中没有虚拟表dual，导致使用“select 1 from dual”语句查询报“Table does not exist”错误
