### ISSUE TITLE
sprigboot项目使用的数据库是TDengine，在本地运行没问题，上线报错这个

### ISSUE THREAD

**Issue by dev007-art** [taosdata/TDengine#11532]
cherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: no taos in java.library.path] with root cause

java.lang.UnsatisfiedLinkError: no taos in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860) ~[na:1.8.0_291]
	at java.lang.Runtime.loadLibrary0(Runtime.java:871) ~[na:1.8.0_291]
	at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_291]
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:28) ~[taos-jdbcdriver-2.0.38.jar!/:na]
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:130) ~[taos-jdbcdriver-2.0.38.jar!/:na]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_291]
	at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[na:1.8.0_291]
	at com.example.tddemo.demo.controller.demoController.demo(demoController.java:27) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]

**Comment by dev007-art** [comment]
有人知道这个是什么原因吗

**Comment by sangshuduo** [comment]
> 有人知道这个是什么原因吗

no taos in java.library.path
没装 taos 客户端
