### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: com.alibaba.fastjson.JSONArray.getTimestamp(I)Ljava/sql/Timestamp;

### ISSUE THREAD

**Issue by Jackhzf** [taosdata/TDengine#11651]
taos-jdbcdriver2.0.37
RestfulResultSet类中，调用parseTimestampColumnData方法，在244行return row.getTimestamp(colIndex);报此异常
JsonArray中有此方法，就是没有调用，就直接抛异常
Caused by: java.lang.NoSuchMethodError: com.alibaba.fastjson.JSONArray.getTimestamp(I)Ljava/sql/Timestamp;
	at com.taosdata.jdbc.rs.RestfulResultSet.parseTimestampColumnData(RestfulResultSet.java:271)
	at com.taosdata.jdbc.rs.RestfulResultSet.parseColumnData(RestfulResultSet.java:184)
	at com.taosdata.jdbc.rs.RestfulResultSet.<init>(RestfulResultSet.java:99)
	at com.taosdata.jdbc.rs.RestfulStatement.executeOneQuery(RestfulStatement.java:124)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:84)
	at com.taosdata.jdbc.rs.RestfulPreparedStatement.execute(RestfulPreparedStatement.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3461)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	... 169 common frames omitted

**Comment by huolibo** [comment]
fastjson 为了兼容 模块化在高版本上将 JSONArray#getTimestamp method返回值调整为 Object。
所以造成在调用高版本fastjson时 方法签名出错。两种解决方式：
1. 降低fastjson版本
2. 将 taos jdbc 升级值38版本

**Comment by Jackhzf** [comment]
好的，谢谢，我是降版本解决的

**Comment by superxbh** [comment]
请问fastjson版本用的哪一版本啊
