### ISSUE TITLE
Can not install node.js connector

### ISSUE THREAD

**Issue by clintzh** [taosdata/TDengine#1179]
**Bug Description**
I'm trying to migrate our database from MongoDB to TDengine.
My application base on node.js, thanks for your efforts, TDengine already have node.js connectors.
According to the documentation of the TDengine's node.js connector, we run the following command
`install td-connector --save`
The installation could not be finished,  the error message in terminal:

```shell
binding.target.mk:109: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/clint/git/mongo2TDengine/node_modules/ref/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/clint/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-76-generic
gyp ERR! command "/home/clint/.nvm/versions/node/v12.14.1/bin/node" "/home/clint/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/clint/git/mongo2TDengine/node_modules/ref
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN mongo2tdengine@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clint/.npm/_logs/2020-02-03T08_38_25_491Z-debug.log
```
**I have tried some approaches according to existing issues**(https://github.com/taosdata/TDengine/issues/635
 https://github.com/taosdata/TDengine/issues/559  https://github.com/taosdata/TDengine/issues/918)

the follows commands are what I have tried, it was useless:
`node-gyp rebuild`
`npm install`
`npm clean-install`

I'm sure node-gyp, gcc and python 2.7 are installed, and `taos` was active.

**To Reproduce**
Just try to install with `install td-connector --save`

**Expected Behavior**
Installation successfully.

**Screenshots**
As above.

**Environment (please complete the following information):**
 - OS: ubuntu 16.04
 - Memory 12GB, CPU Intel core i3-4170, current Disk Space more than 60GB
 - TDengine Version 1.6.4.6
 - GCC Version 5.4.0
 - Python Version 2.7.12
 - Node-gyp Version 6.1.0
 - Node.js Version v12.14.1 (**Install via nvm**)
 - NPM version 6.13.4

**Additional Context**
No.

**Comment by clintzh** [comment]
Node.js connector is community maintained, we will develop with Golang, so I close this issue.
