### ISSUE TITLE
java.sql.SQLException: JNI ERROR (2354): Ref is not there

### ISSUE THREAD

**Issue by zhouyf605** [taosdata/TDengine#12208]
**Bug Description**
应用连接td 集群（3节点）  经常连接报错

2022-05-07 10:08:52.375 ERROR [changestation,48404462-cf1f-4e7f-b05c-7c9308478bb4,2903b233-16aa-4e4f-aa26-cf0e048a64c5] - [http-nio-30050-exec-9] com.alibaba.druid.pool.DruidDataSource  : init datasource error, url: jdbc:TAOS://:/prod?user=data&password=taosdata
java.sql.SQLException: JNI ERROR (2354): Ref is not there
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75)
        at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:80)
        at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:33)
        at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:19)
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:131)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1710)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:939)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1376)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1372)

应用连接td 是jni 配置taos.cfg firstEP  secondEp 方式连接的   大部分时间连接是正常的  不定时的报这种错误，报错时间没有规律

**Comment by zhouyf605** [comment]
tdegine 版本 是2.4.0.10 版本

**Comment by zhouyf605** [comment]
查看源码 好像是是获取连接的时候有时候会是空指针   但是很多时候又是可以连接的  配置方式采用官网 推荐方式URL  不配置主机和端口  jdbc:TAOS://:/prod?   客户端配置文件taos.cfg 里面配置了 firstEp  secondEp  如果配置有问题应该都不能连接 



72     public boolean connect(String host, int port, String dbName, String user, String password) throws SQLException {
 73         if (this.taos != TSDBConstants.JNI_NULL_POINTER) {
 74             closeConnection();
 75             this.taos = TSDBConstants.JNI_NULL_POINTER;
 76         }
 77
 78         this.taos = this.connectImp(host, port, dbName, user, password);
 79         if (this.taos == TSDBConstants.JNI_NULL_POINTER) {
 80             String errMsg = this.getErrMsg(0);
 81             throw TSDBError.createSQLException(TSDBErrorNumbers.ERROR_JNI_CONNECTION_NULL, errMsg);
 82         }

**Comment by yu285** [comment]
please add rpcForceTCP  1   in taos.cfg both client and server side.

then try again
