### ISSUE TITLE
Is there any method to verify the connection is working when using nodejs connector to connect the TDengine server?

### ISSUE THREAD

**Issue by housheng4** [taosdata/TDengine#1309]
在使用nodejs连接器连接tdengine后，有没有提供一个函数可以验证连接信息是否正确，又或者验证连接状态是否正常

**Comment by housheng4** [comment]
今天在windows环境下安装td-connector，出现这个错误，已经按照官网npm install --global --production windows-build-tools和npm install td-connector成功了。但是运行时还是出现这个错误

C:\Users\Administrator\Desktop\TDenginewin\node_modules\ffi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\Users\Administrator\Desktop\TDenginewin\node_modules\ffi\lib\dynamic_library.js:74:11)
    at Object.Library (C:\Users\Administrator\Desktop\TDenginewin\node_modules\ffi\lib\library.js:45:12)
    at new CTaosInterface (C:\Users\Administrator\Desktop\TDenginewin\node_modules\td-connector\nodetaos\cinterface.js:198:22)
    at TDengineConnection._configConn (C:\Users\Administrator\Desktop\TDenginewin\node_modules\td-connector\nodetaos\connection.js:52:19)
    at new TDengineConnection (C:\Users\Administrator\Desktop\TDenginewin\node_modules\td-connector\nodetaos\connection.js:25:8)
    at Object.module.exports.connect (C:\Users\Administrator\Desktop\TDenginewin\node_modules\td-connector\tdengine.js:3:10)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\TDenginewin\index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by liu0x54** [comment]
遇到什么问题了吗？正常情况下，连接成功后，使用该连接发送SQL命令，根据返回结果可以判断是否执行成功，以及错误的原因。

**Comment by housheng4** [comment]
嗯~我不太清楚tdengine可不可以设置客户端的连接最大最小数目，我想做的是在创建连接之后的每次查询或修改操作之前对客户端的信息进行检测

**Comment by housheng4** [comment]
嗯，我看到连接成功后自动打印出success信息，我想找到这个内置的打印函数在哪里？我在连接器里没有找到。。另外conn初始化的游标cursor需不需要在结束时进行关闭释放

**Comment by liu0x54** [comment]
> 嗯，我看到连接成功后自动打印出success信息，我想找到这个内置的打印函数在哪里？我在连接器里没有找到。。另外conn初始化的游标cursor需不需要在结束时进行关闭释放

打印函数在lib里面。cursor不用释放，只要关闭了conn，cursor自动释放

**Comment by housheng4** [comment]
> > 嗯，我看到连接成功后自动打印出success信息，我想找到这个内置的打印函数在哪里？我在连接器里没有找到。。另外conn初始化的游标cursor需不需要在结束时进行关闭释放
> 
> 打印函数在lib里面。cursor不用释放，只要关闭了conn，cursor自动释放

如果不关闭conn的话是不是意味着只要服务启动着连接就会一直保持着不能关闭？

**Comment by zyyang-taosdata** [comment]
> 如果不关闭conn的话是不是意味着只要服务启动着连接就会一直保持着不能关闭？我可以吧cursor存下来吗，这样就不用每次来一个请求就申请一个cursor了。

在应用中，使用完connection后将connection关闭，如果connection已经关闭，是无法使用cursor来获取数据的。
