### ISSUE TITLE
TDengine ERROR (80000216): syntax error near ''张三' (invalid data or symbol)

### ISSUE THREAD

**Issue by XiaShus** [taosdata/TDengine#14852]
**Bug Description**
一条 SQL 在 taos cli 里执行结果是正确的，但是使用 jdbc 方式执行就会抛出异常 

java.sql.SQLException: TDengine ERROR (80000216): syntax error near ''张三' (invalid data or symbol)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:67)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeUpdate(FilterChainImpl.java:2881)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeUpdate(FilterAdapter.java:2518)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeUpdate(FilterEventAdapter.java:321)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeUpdate(FilterChainImpl.java:2879)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeUpdate(StatementProxyImpl.java:229)
	at com.alibaba.druid.pool.DruidPooledStatement.executeUpdate(DruidPooledStatement.java:328)

insert into face_recognition_record USING super_face_recognition_record TAGS ( 'demo' )  values( 1657693787869,'张三','1',1,71.0 )

`
int count=0;
        SqlSession sqlSession = null;
        try{
            sqlSession = MyBatisUtil.getSqlSession();
            String sql= "insert into face_recognition_record USING super_face_recognition_record TAGS ( 'demo' )  values( 1657693787869,'张三','1',1,71.0 )";
            Statement statement = sqlSession.getConnection().createStatement();
            count = statement.executeUpdate(sql);
            sqlSession.commit();
        }catch(Exception e){
            e.printStackTrace();
            sqlSession.rollback();
        }finally{
            MyBatisUtil.closeSqlSession(sqlSession);
        }
`

**Environment (please complete the following information):**
 - Windows10
 - IDEA

**Comment by XiaShus** [comment]
刚发现是有不可见字符导致的

**Comment by jiabaoyu114** [comment]
正常可以在命令行中查询，在demo中就提示taos.error.ProgrammingError: [0x0216]: syntax error near 'unrecognized token: ""'
