### ISSUE TITLE
com.alibaba.druid.pool.DruidDataSource - {dataSource-2} init error java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;

### ISSUE THREAD

**Issue by codenergy** [taosdata/TDengine#14894]
最近将TDengine2.0.3.1升级为2.2.2.10，发现遇到了初始化连接失败，使用的驱动版本是2.0.36，已经尝试解决很长时间，但仍然没有解决，报错如下：

`[ERROR] [2022-07-14 10:35:31.224] [pool-2-thread-1] com.alibaba.druid.pool.DruidDataSource - {dataSource-2} init error
java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;
        at com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Native Method) ~[taos-jdbcdriver-2.0.36.jar!/:?]
        at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:39) ~[taos-jdbcdriver-2.0.36.jar!/:?]
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:120) ~[taos-jdbcdriver-2.0.36.jar!/:?]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1596) ~[druid-1.1.17.jar!/:1.1.17]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1662) ~[druid-1.1.17.jar!/:1.1.17]
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:932) [druid-1.1.17.jar!/:1.1.17]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1369) [druid-1.1.17.jar!/:1.1.17]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1365) [druid-1.1.17.jar!/:1.1.17]
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109) [druid-1.1.17.jar!/:1.1.17]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) [spring-jdbc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) [spring-jdbc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) [spring-jdbc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80) [mybatis-spring-2.0.5.jar!/:2.0.5]
        at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67) [mybatis-spring-2.0.5.jar!/:2.0.5]
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) [mybatis-3.5.5.jar!/:3.5.5]
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:111) [pagehelper-5.2.0.jar!/:?]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) [mybatis-3.5.5.jar!/:3.5.5]
        at com.sun.proxy.$Proxy185.query(Unknown Source) [?:?]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) [mybatis-3.5.5.jar!/:3.5.5]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) [mybatis-spring-2.0.5.jar!/:2.0.5]
        at com.sun.proxy.$Proxy142.selectList(Unknown Source) [?:?]
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223) [mybatis-spring-2.0.5.jar!/:2.0.5]
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152) [mybatis-3.5.5.jar!/:3.5.5]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85) [mybatis-3.5.5.jar!/:3.5.5]
        at com.sun.proxy.$Proxy143.decribeTable(Unknown Source) [?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) [spring-tx-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) [spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at com.sun.proxy.$Proxy144.decribeTable(Unknown Source) [?:?]
        at com.xxx.xxx.analyse.core.dataservice.OriginalDataService.batchSaveData(OriginalDataService.java:63) [classes!/:1.2.0.RELEASE]
        at com.xxx.xxx.analyse.core.callback.OriginalDataPluginCallback.onSuccess(OriginalDataPluginCallback.java:50) [classes!/:1.2.0.RELEASE]
        at com.xxx.xxx.analyse.core.callback.OriginalDataPluginCallback.onSuccess(OriginalDataPluginCallback.java:22) [classes!/:1.2.0.RELEASE]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132) [guava-20.0.jar!/:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) [guava-20.0.jar!/:?]
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) [guava-20.0.jar!/:?]
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811) [guava-20.0.jar!/:?]
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653) [guava-20.0.jar!/:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) [guava-20.0.jar!/:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) [guava-20.0.jar!/:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) [guava-20.0.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]`

**Comment by fenghuazzm** [comment]
之前没问题，升级 TDengine、驱动后出的问题嘛
感觉是版本的

**Comment by codenergy** [comment]
是驱动版本和TD版本不适配，文档应该写错了

**Comment by fenghuazzm** [comment]
感谢反馈，我们明天检查下

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
