### ISSUE TITLE
JdbcRestful return failed to respond

### ISSUE THREAD

**Issue by wangshk** [taosdata/TDengine#14921]
TDengine server: 2.6.0.8
 jdbcdriver: 2.0.36 （也尝试 2.0.38，报错一样）

请求连接(隐去了ip)：
String jdbcUrl = "jdbc:TAOS-RS://*.*.***.**:8030/test?user=root&password=taosdata";

报错：
java.sql.SQLException: ERROR (2318): *.*.***.**:8030 failed to respond
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:72)
	at com.taosdata.jdbc.utils.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:90)
	at com.taosdata.jdbc.rs.RestfulDriver.connect(RestfulDriver.java:60)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)

服务端日志中有如下报错：
07/14 21:20:33.739372 00019495 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7f847c000940
07/14 21:20:38.884372 00019495 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7f847c000940
07/14 21:20:44.037373 00019495 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7f847c000940
07/14 21:20:49.163369 00019495 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7f847c0008c0
07/14 21:20:54.275369 00019495 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7f847c0008c0

**Comment by wangshk** [comment]
07/15 11:03:15.925206 00017899 RPC SHELL new TCP connection from **.**.**.**:49162, fd:31 FD:0x7fb63c000900 numOfFds:2
07/15 11:03:15.949027 00017898 RPC SHELL (nil) read data, FD:0x7fb63c000900 fd:31 TCP malloc mem:0x7fb5b7939010
07/15 11:03:20.948373 00017898 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7fb63c000900
07/15 11:03:21.185506 00017898 RPC SHELL (nil) FD:0x7fb63c000900 RD hang up
07/15 11:03:21.185531 00017898 RPC SHELL (nil) TCP connection is closed, FD:0x7fb63c000900 fd:-1 numOfFds:1
07/15 11:03:21.328193 00017899 RPC SHELL new TCP connection from **.**.**.**:46918, fd:32 FD:0x7fb63c000900 numOfFds:2
07/15 11:03:21.348131 00017898 RPC SHELL (nil) read data, FD:0x7fb63c000900 fd:32 TCP malloc mem:0x7fb5b7939010
07/15 11:03:26.347374 00017898 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7fb63c000900
07/15 11:03:26.470453 00017898 RPC SHELL (nil) FD:0x7fb63c000900 RD hang up
07/15 11:03:26.470481 00017898 RPC SHELL (nil) TCP connection is closed, FD:0x7fb63c000900 fd:-1 numOfFds:1
07/15 11:03:26.522358 00017899 RPC SHELL new TCP connection from **.**.**.**:38624, fd:31 FD:0x7fb63c000900 numOfFds:2
07/15 11:03:26.537522 00017898 RPC SHELL (nil) read data, FD:0x7fb63c000900 fd:31 TCP malloc mem:0x7fb5b7939010
07/15 11:03:31.538370 00017898 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7fb63c000900
07/15 11:03:31.644424 00017898 RPC SHELL (nil) FD:0x7fb63c000900 RD hang up
07/15 11:03:31.644449 00017898 RPC SHELL (nil) TCP connection is closed, FD:0x7fb63c000900 fd:-1 numOfFds:1
07/15 11:03:31.786891 00017899 RPC SHELL new TCP connection from **.**.**.**:40090, fd:32 FD:0x7fb63c000900 numOfFds:2
07/15 11:03:31.816644 00017898 RPC SHELL (nil) read data, FD:0x7fb63c000900 fd:32 TCP malloc mem:0x7fb5b7939010
07/15 11:03:36.816384 00017898 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7fb63c000900
07/15 11:03:36.848219 00017898 RPC SHELL (nil) FD:0x7fb63c000900 RD hang up
07/15 11:03:36.848240 00017898 RPC SHELL (nil) TCP connection is closed, FD:0x7fb63c000900 fd:-1 numOfFds:1
07/15 11:03:37.178924 00017899 RPC SHELL new TCP connection from **.**.**.**:38888, fd:31 FD:0x7fb63c000900 numOfFds:2
07/15 11:03:37.198636 00017898 RPC SHELL (nil) read data, FD:0x7fb63c000900 fd:31 TCP malloc mem:0x7fb5b7939010
07/15 11:03:42.198375 00017898 RPC ERROR SHELL (nil) read error, leftLen:1886152991 retLen:-1 FD:0x7fb63c000900
07/15 11:03:42.393448 00017898 RPC SHELL (nil) FD:0x7fb63c000900 RD hang up
07/15 11:03:42.393479 00017898 RPC SHELL (nil) TCP connection is closed, FD:0x7fb63c000900 fd:-1 numOfFds:1

**Comment by wangshk** [comment]
。
