### ISSUE TITLE
nodejs 的REST 连接 怎么用？我运行示例都报错

### ISSUE THREAD

**Issue by liyaods** [taosdata/TDengine#15664]
`const { options, connect } = require("td2.0-rest-connector");

async function test() {
  options.path = "/rest/sqlt";
  options.host = "localhost";
  let conn = connect(options);
  let cursor = conn.cursor();
  try {
    let res = await cursor.query("SELECT server_version()");
    res.toString();
  } catch (err) {
    console.log(err);
  }
}
test();
`
示例直接运行
PS C:\Users\YUYU\Desktop\app> node test.js

C:\Users\YUYU\Desktop\app\node_modules\td2.0-rest-connector\dist\main\index.js:17
    queryParams = '';
                ^
SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\YUYU\Desktop\app\test.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by liyaods** [comment]
好吧  我的node版本低了
