### ISSUE TITLE
I am using 2.6.0.6 version TDengine and the driver-connector version is 2.0.38. How to solve this problem when I throw this exception during connection?

### ISSUE THREAD

**Issue by zzcxli** [taosdata/TDengine#15730]
2022-08-04 09:26:30.902 ERROR 15004 --- [reate-249416123] com.alibaba.druid.pool.DruidDataSource   : create connection Error

java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;
	at com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:41)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:130)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:787)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:38)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:251)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1659)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838)

2022-08-04 09:26:30.904  INFO 15004 --- [reate-249416123] c.a.druid.pool.DruidAbstractDataSource   : {dataSource-2} failContinuous is true

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
