### ISSUE TITLE
K8s using TDengine cluster error：Unable to resolve FQDN

### ISSUE THREAD

**Issue by JackietLee** [taosdata/TDengine#15926]
项目日志，前面插入成功，一段时间后就开始报错了
> 2022-08-10 01:40:51.579 DEBUG 6 --- [nio-7103-exec-7] c.f.z.c.d.c.b.t.d.s.h.h.d.H.insert       : ==>  Preparing: INSERT INTO hkq_hold_stock_etzvmalrurcebewf_x00006 USING hkq_hold_stock TAGS (?, ?) (ts,live_stock,child_stock,batch_start_age,stock_in,stock_out,stock_die,stock_ko,child_newborn,child_in,child_out,child_die,child_ko,stock_breed) VALUES (?, 6,0,null,0,0,0,0,0,0,0,0,0,0); 
2022-08-10 01:40:51.579 DEBUG 6 --- [nio-7103-exec-7] c.f.z.c.d.c.b.t.d.s.h.h.d.H.insert       : ==> Parameters: etzvmalrurcebewf(String), x00006(String), 2022-08-10 00:31:45.144(Timestamp)
2022-08-10 01:40:51.582 DEBUG 6 --- [nio-7103-exec-7] c.f.z.c.d.c.b.t.d.s.h.h.d.H.insert       : <==    Updates: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1ea20089]
2022-08-10 01:42:55.316  WARN 6 --- [ngPollService-1] c.c.f.a.i.RemoteConfigLongPollService    : Long polling failed, will retry in 1 seconds. appId: cloud-data-center-breed-timesery-data-store-service, cluster: default, namespaces: application-dev.yml, long polling url: http://192.168.0.151:30115/notifications/v2?cluster=default&appId=cloud-data-center-breed-timesery-data-store-service&ip=10.244.1.122&notifications=%5B%7B%22namespaceName%22%3A%22application-dev.yml%22%2C%22notificationId%22%3A388%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-08-10 01:42:56.199 ERROR 6 --- [Create-95476731] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:TAOS://tdengine-0.tdengine-headless.tdengine-cluster.svc.cluster.local:6030/breed?timezone=Asia/Beijing&charset=UTF-8&locale=en_US.UTF-8, errorCode 9044, state 

java.sql.SQLException: JNI ERROR (2354): Unable to resolve FQDN
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75) ~[taos-jdbcdriver-2.0.39.jar!/:na]
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:80) ~[taos-jdbcdriver-2.0.39.jar!/:na]
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:35) ~[taos-jdbcdriver-2.0.39.jar!/:na]
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:21) ~[taos-jdbcdriver-2.0.39.jar!/:na]
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:165) ~[taos-jdbcdriver-2.0.39.jar!/:na]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1643) ~[druid-1.2.11.jar!/:1.2.11]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1709) ~[druid-1.2.11.jar!/:1.2.11]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2813) ~[druid-1.2.11.jar!/:1.2.11]

然后看了下tdengine日志，会有类似这种报错，不知道是不是这个引起的
> 08/10 10:17:38.377891 00000167 UTL ERROR failed to get the ip address, fqdn:tdengine-0.tdengine-headless.tdengine-cluster.svc.cluster.local, since:Name or service not known 
08/10 10:17:38.377946 00000167 RPC ERROR DND-C, failed to resolve FQDN:tdengine-0.tdengine-headless.tdengine-cluster.svc.cluster.local 
08/10 10:17:38.378060 00000167 RPC ERROR DND-C (nil), failed to set up connection(Unable to resolve FQDN) 
08/10 10:17:38.383475 00000167 DND ERROR status rsp is received, error:Unable to resolve FQDN 
08/10 10:17:38.874812 00000195 UTL ERROR failed to get the ip address, fqdn:tdengine-0.tdengine-headless.tdengine-cluster.svc.cluster.local, since:Name or service not known 
08/10 10:17:38.874838 00000195 RPC ERROR TSC, failed to resolve FQDN:tdengine-0.tdengine-headless.tdengine-cluster.svc.cluster.local 
08/10 10:17:38.874844 00000195 RPC ERROR TSC 0x9, failed to set up connection(Unable to resolve FQDN) 
08/10 10:17:38.878461 00000167 TSC ERROR 0x8 get multi-tableMeta failed, code:Unable to resolve FQDN 
08/10 10:17:38.878527 00000196 TSC ERROR 0x8 async result callback, code:Unable to resolve FQDN 
08/10 10:17:38.878551 00000195 MON ERROR failed to exec sql:create table if not exists log.dn2 using log.dn tags(2, 'tdengine-1.tdengine-headless.tdengine-cluster.svc.cluster.local:6030'), reason:Unable to resolve FQDN 
08/10 10:17:39.881386 00000195 UTL ERROR failed to get the ip address, fqdn:tdengine-0.tdengine-headless.tdengine-cluster.svc.cluster.local, since:Name or service not known 
08/10 10:17:39.881409 00000195 RPC ERROR TSC, failed to resolve FQDN:tdengine-0.tdengine-headless.tdengine-cluster.svc.cluster.local 
08/10 10:17:39.881416 00000195 RPC ERROR TSC 0xb, failed to set up connection(Unable to resolve FQDN) 
08/10 10:17:39.888441 00000167 TSC ERROR 0xa get multi-tableMeta failed, code:Unable to resolve FQDN 
08/10 10:17:39.888486 00000197 TSC ERROR 0xa async result callback, code:Unable to resolve FQDN 
08/10 10:17:39.888509 00000195 MON ERROR failed to exec sql:create table if not exists log.dn2 using log.dn tags(2, 'tdengine-1.tdengine-headless.tdengine-cluster.svc.cluster.local:6030'), reason:Unable to resolve FQDN 
08/10 10:17:40.379217 00000207 TSC ERROR 0x3, HB, total dnode:3, online dnode:2

**Comment by xiaods** [comment]
@qq280075924 感觉是你的k8s环境中coredns有问题。建议查一下coredns容器的日志。
