### ISSUE TITLE
excluded fastjson error

### ISSUE THREAD

**Issue by melvin7** [taosdata/TDengine#16075]
**Bug Description**

由于生产环境禁止使用fastjson库，我们尝试通过pom去排除fastjson的引用

`
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:37) ~[taos-jdbcdriver-2.0.40.jar:na]
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162) ~[taos-jdbcdriver-2.0.40.jar:na]
`

但是你们在 `TSDBJNIConnector` 中使用了fastjson，直接导致我们无法排除fastjson的引用，并无法在生产环境中使用。

**Environment (please complete the following information):**
 - TDengine Version [e.g. 2.6.0.12]
 - JDBC Verion 2.0.38-2.0.40

**Comment by codering** [comment]
恩，我也建议减少依赖，包括guava

**Comment by fenghuazzm** [comment]
只使用 JDBC-JNI 确实没用到 fastjson ，可以在 maven 里 exclude 把 fastjson 的引用去掉

**Comment by melvin7** [comment]
在`TSDBJNIConnector ` 中你们使用了fastjson，所以在maven中excludefastjson以后，直接无法运行
TSDBJNIConnector 第37行开始，版本2.0.40

**Comment by melvin7** [comment]
`TSDBJNIConnector ` 中使用fastjson，这个问题一直延续到了3.0.2.2版本
