### ISSUE TITLE
springbootdemo Test Engineering  failed to connect to server

### ISSUE THREAD

**Issue by supersumx** [taosdata/TDengine#1610]
init datasource error, url: jdbc:TAOS://127.0.0.1:6030/log

java.sql.SQLException: TDengine Error: failed to connect to server
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:102) ~[taos-jdbcdriver-1.0.3.jar:na]
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64) ~[taos-jdbcdriver-1.0.3.jar:na]
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56) ~[taos-jdbcdriver-1.0.3.jar:na]
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135) ~[taos-jdbcdriver-1.0.3.jar:na]

**Comment by Shawshank-Smile** [comment]
https://www.taosdata.com/cn/faq/   you may find your answer.  and the client version and the server version must be the same.
