### ISSUE TITLE
binding insert doesn't support high-concurrency ?  2.6.0.6

### ISSUE THREAD

**Issue by qihuagaosh** [taosdata/TDengine#16531]
java.sql.SQLException: TDengine ERROR (2350): failed to bind table name and corresponding tags, reason: invalid operation: not multiple table insert
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
	at com.taosdata.jdbc.TSDBJNIConnector.setBindTableNameAndTags(TSDBJNIConnector.java:314)
	at com.taosdata.jdbc.TSDBPreparedStatement.columnDataAddBatch(TSDBPreparedStatement.java:816)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$5(UploadDataV3.scala:348)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$5$adapted(UploadDataV3.scala:331)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$1(UploadDataV3.scala:331)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$1$adapted(UploadDataV3.scala:311)
java.sql.SQLException: TDengine ERROR (2350): failed to bind table name and corresponding tags, reason: invalid operation: not multiple table insert
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
	at com.taosdata.jdbc.TSDBJNIConnector.setBindTableNameAndTags(TSDBJNIConnector.java:314)
	at com.taosdata.jdbc.TSDBPreparedStatement.columnDataAddBatch(TSDBPreparedStatement.java:816)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$5(UploadDataV3.scala:348)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$5$adapted(UploadDataV3.scala:331)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$1(UploadDataV3.scala:331)
	at logics.UploadDataV3.$anonfun$batchInsertIOTV2$1$adapted(UploadDataV3.scala:311)
	at play.api.db.DefaultDatabase.withConnection(Databases.scala:180)
	at play.api.db.DefaultDatabase.withConnection(Databases.scala:174)
	at logics.UploadDataV3.batchInsertIOTV2(UploadDataV3.scala:311)
	at logics.UploadDataV3.uploadHelper(UploadDataV3.scala:521)
	at logics.UploadDataV3.uploadV3(UploadDataV3.scala:178)
	at controllers.ApplicationV3Sink.$anonfun$uploadDataV3$1(ApplicationV3Sink.scala:79)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the circumstance is and what the associated problem is. Ex. I'm using TDengine for this use case: [...]. But I'm always frustrated when [...]

**Describe your desired behavior**
A clear and concise description of what you want to happen. Ex. I want TDengine to be able to do [...] when I try to do [...] with it.

**Describe your solutions/suggestions if you've any**
A clear and concise description of any solutions/suggestions to this problem or features you've considered.

**Additional context**

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
