### ISSUE TITLE
CAN NOT connect db via jdbc: NI ERROR (2354): success

### ISSUE THREAD

**Issue by qihuagaosh** [taosdata/TDengine#16593]
**Bug Description**
Caused by: java.sql.SQLException: JNI ERROR (2354): success
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75)
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:80)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:35)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:21)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:163)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)

Server/Client  2.6.0.14，  
JDBC:  "com.taosdata.jdbc" % "taos-jdbcdriver" % "2.0.40" 

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html

开源版3.x 支持操作系统参考：https://docs.taosdata.com/reference/support-platform/
