### ISSUE TITLE
Windows10 TD3.0 connect failed 

### ISSUE THREAD

**Issue by steven-design** [taosdata/TDengine#16665]
**Bug Description**
Windows10 TD3.0，通过Java jdbc连接数据库失败

**To Reproduce**
1. 配置本机host 127.0.0.1 td1
2. java spring boot程序数据库连接为：jdbc:TAOS://td1:6030?user=root&password=taosdata
3. 参考示例代码： 
https://github.com/taosdata/TDengine/blob/3.0/docs/examples/java/src/main/java/com/taos/example/JNIConnectExample.java
4. 程序执行数据库连接报错如下：
    Exception in thread "main" java.lang.NoSuchMethodError: setByteArray
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)

**Expected Behavior**
连接数据库正常

**Screenshots**
    Exception in thread "main" java.lang.NoSuchMethodError: setByteArray
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)

**Environment (please complete the following information):**
 - OS: [Windows10 家庭版]
 - Memory 16G, CPU i5 八核, current Disk Space 1T
 - TDengine Version [3.0.1 windowsServer版]

**Additional Context**

**Comment by yu285** [comment]
we will check on this

**Comment by Mark916** [comment]
Is there any result on this problem how we can solve it. I have the same problem...

**Comment by Mark916** [comment]
Please also update source code example  for 3.0* version.We had a lot of trouble running Demo

**Comment by zeweilin** [comment]
I have the same problem... how should i solve this problem ?

**Comment by yu285** [comment]
what is the JDBC version we used ?

it should be 3.0.0 , please confirm this ~

**Comment by yu285** [comment]
I guess it is an authority problem for a Windows user.

There is a taos.dll under C:\TDengine\driver  ，please copy it to  C:\Windows\System32  ,if it already existed just overwrite it

**Comment by steven-design** [comment]
I  try to copy C:\TDengine\driver\taos.dll to C:\Windows\System32,  JDBC version set 3.0.0
but, the problem remains.

**Comment by dafuge** [comment]
解决了的话踢我一下

**Comment by zeje** [comment]
> I guess it is an authority problem for a Windows user.
> 
> There is a taos.dll under C:\TDengine\driver ，please copy it to C:\Windows\System32 ,if it already existed just overwrite it

对我有效，点赞

**Comment by Loadhao** [comment]
同样遇到了此问题，移动了dll文件，但是仍未解决：
java.lang.NoSuchMethodError: setByteArray
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method) ~[taos-jdbcdriver-3.0.0.jar:na]
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43) ~[taos-jdbcdriver-3.0.0.jar:na]
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162) ~[taos-jdbcdriver-3.0.0.jar:na]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1643) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1709) ~[druid-1.2.11.jar:1.2.11]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2813) ~[druid-1.2.11.jar:1.2.11]

**Comment by yu285** [comment]
> 同样遇到了此问题，移动了dll文件，但是仍未解决： java.lang.NoSuchMethodError: setByteArray at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method) ~[taos-jdbcdriver-3.0.0.jar:na] at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43) ~[taos-jdbcdriver-3.0.0.jar:na] at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162) ~[taos-jdbcdriver-3.0.0.jar:na] at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1643) ~[druid-1.2.11.jar:1.2.11] at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1709) ~[druid-1.2.11.jar:1.2.11] at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2813) ~[druid-1.2.11.jar:1.2.11]

可以加微信 a15652223354做具体排查

**Comment by yu285** [comment]
> dafuge



> I try to copy C:\TDengine\driver\taos.dll to C:\Windows\System32, JDBC version set 3.0.0 but, the problem remains.

可以加微信 a15652223354做具体排查

**Comment by yu285** [comment]
> 解决了的话踢我一下

可以加微信 a15652223354做具体排查
