### ISSUE TITLE
TDengine ERROR (80000203): Invalid value in client

### ISSUE THREAD

**Issue by ltlf** [taosdata/TDengine#16853]
Exception in thread "main" java.sql.SQLException: TDengine ERROR (80000203): Invalid value in client
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
	at com.taosdata.jdbc.TSDBJNIConnector.insertLines(TSDBJNIConnector.java:376)
	at com.taosdata.jdbc.SchemalessWriter.write(SchemalessWriter.java:35)
	at taos.LineProtocolExample.main(LineProtocolExample.java:39)
![image](https://user-images.githubusercontent.com/16397723/190303467-523189d4-7e12-45a2-bec6-42a79e6f12ae.png)

**Comment by sangshuduo** [comment]
请问 TDengine 是什么版本？JDBC 版本？TDengine 是运行在 Linux 上吗？
