### ISSUE TITLE
JDBC Driver read timestamp format issue

### ISSUE THREAD

**Issue by ipaddicting** [taosdata/TDengine#17425]
**Bug Description**
When the timestamp filed has 0 value in milliseconds e.g. `2022-10-18 01:20:14.300 ` will be read from the database as `2022-10-18T01:20:14.3Z`, which causes a parsing error.

**To Reproduce**
1. create a stable & a table
2. insert a record and make sure the timestamp has 0 value in milliseconds, e.g. `2022-10-18 01:20:14.300 `
3. use the JDBC driver to retrieve that record

**Expected Behavior**
Parse the timestamp correctly without exception.

**Environment (please complete the following information):**
 - TDengine 3.0.1.4 officail image
 - TDengine Client 3.0.1.4
 - TDengine JDBC Driver 3.0.0

**Additional Context**
Stack traces：
```
02:26:47 ERROR [co.fo.fc.si.fl.ap.ErrorMapper] (executor-thread-0) Failed to handle request: java.time.format.DateTimeParseException: Text '2022-10-18T01:20:14.3Z' could not be parsed at index 19
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:600)
	at com.taosdata.jdbc.rs.RestfulResultSet.parseTimestampColumnData(RestfulResultSet.java:163)
	at com.taosdata.jdbc.rs.RestfulResultSet.parseColumnData(RestfulResultSet.java:137)
	at com.taosdata.jdbc.rs.RestfulResultSet.<init>(RestfulResultSet.java:93)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:87)
	at com.taosdata.jdbc.rs.RestfulStatement.executeQuery(RestfulStatement.java:36)
```

Screenshot of table data：
<img width="680" alt="Screen Shot 2022-10-18 at 11 13 51" src="https://user-images.githubusercontent.com/244768/196327170-f34098de-2f45-4cd0-bfa0-0c7af5da2313.png">

**Comment by ipaddicting** [comment]
Repository代码部分：
```
    fun get(deviceId: String, start: Instant, end: Instant): List<DeviceActivity> {
        val sql =
            "SELECT ts,status,ip FROM device_activities_${deviceId} WHERE ts > ${start.toEpochMilli()} AND ts <= ${end.toEpochMilli()} ORDER BY ts DESC"
        val resultSet = ConnectionFactory.get()!!.use { connection ->
            connection.createStatement().use { statement ->
                statement.executeQuery(sql)
            }
        }
        val results = mutableListOf<DeviceActivity>()
        while (resultSet.next()) {
            val entity = DeviceActivity(Instant.ofEpochMilli(resultSet.getTimestamp("ts").time))
            entity.status = DeviceStatus.valueOf(resultSet.getString("status"))
            entity.ip = resultSet.getString("ip")
            results.add(entity)
        }
        return results
    }
```

ConnectionFactory代码部分：
```
object ConnectionFactory {
    private val jdbcUrl: String = System.getenv("TDENGINE_JDBC_URL") ?: System.getProperty("tdengine.jdbc.url")

    /**
     * Retrieve a connection of TSDB.
     */
    fun get(): Connection? = DriverManager.getConnection(jdbcUrl)
}
```

不过从异常栈信息来看，更多是JDBC Driver内部处理的问题。

**Comment by huolibo** [comment]
Hello, I can't repeat the problem. here is an example : 
```java
import com.taosdata.jdbc.utils.SpecifyAddress;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.sql.*;

public class TimestampFotmatParseTest {
    private final String host = "127.0.0.1";
    private Connection conn;
    private final String dbName = "time";

    @Test
    public void timeParse() throws SQLException {
        try (Statement statement = conn.createStatement()) {
            ResultSet resultSet = statement.executeQuery("select * from " + dbName);
            resultSet.next();
            Assert.assertEquals("2022-10-18 01:20:14.3", resultSet.getString(1));
        }
    }

    @Before
    public void before() throws SQLException {
        String url = "jdbc:TAOS-RS://" + host + ":6041/?user=root&password=taosdata&timezone=UTF-8";
        conn = DriverManager.getConnection(url);
        try (Statement statement = conn.createStatement()) {
            statement.executeUpdate("create database if not exists " + dbName);
            statement.executeQuery("use " + dbName);
            statement.executeUpdate("create table if not exists " + dbName + " (ts timestamp, c1 int)");
            statement.execute("insert into " + dbName + " values ('2022-10-18 01:20:14.300',1)");
        }

    }
}

```

**Comment by ipaddicting** [comment]
I can reproduce it locally... 

```
            ConnectionFactory.get()!!.use { connection ->
                connection.use {
                    connection.createStatement().use { statement ->
                        statement.executeUpdate("insert into device_activities_tbox000 values('2022-10-18 01:20:14.300', 'Online', '192.168.1.1')")
                    }
                }
            }

            val result = ConnectionFactory.get()!!.use { connection ->
                connection.use {
                    connection.createStatement().use { statement ->
                        statement.executeQuery("select * from device_activities_tbox000")
                    }
                }
            }
```

The plain value of timestamp retrieved from database is ''2022-10-18T01:20:14.3Z", at index 19 is ".3Z", as below screenshot shows:

<img width="482" alt="Screen Shot 2022-10-19 at 12 43 30" src="https://user-images.githubusercontent.com/244768/196599567-85f5a613-bf20-4959-b1ef-4453299b54fb.png">

I think something wrong with the rfc3339Parser, BTW I'm using JDK 17.

**Comment by huolibo** [comment]
Oh, I see.
TDengine JDBC Driver  is only tested on JDK 8 and 11. There actually have some problem on JDK 17 :)

**Comment by ipaddicting** [comment]
I see... No wonder why this problem suddenly emerged, just upgraded to JDK 17 for a new project.
