### ISSUE TITLE
macos Monterey Run Tdengine 3.0.15 error

### ISSUE THREAD

**Issue by twtmiss** [taosdata/TDengine#17601]
macos Monterey 12.6 Intel芯片 安装了TDengine-server-3.0.1.5-macOS-x64.pkg

**操作复现：**
1. 用命令行连接数据库，手动创建7个数据库后，再创建数据库提示"Out of dnodes"

2. 用exit命令退出连接后，再连接数据库提示"failed to connect to server, reason: Unable to establish connection"

**排查错误**

1. 使用"launchctl list | grep taosd"，输出为空，launchctl list中没有taosd

2. 重启电脑无效

3. 双击应用程序文件夹中的TDengine.app，点击yes没有任何效果，再次双击仍然提示正在运行
<img width="423" alt="image" src="https://user-images.githubusercontent.com/36953621/197470593-32b06280-cce9-4397-ba4b-50075ad8145c.png">

4. /usr/local/lib目录下存在libtaos.dylib
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/36953621/197471061-9cd3d6e9-3378-4cb7-9d16-3793f20a66d4.png">

5. 用losf命令查看6030-6049端口都没有被使用的进程

6. 用docker运行最新的tdengine数据库，在本地终端可以正常连接，关闭tdnengine容器后没有办法使用

我想问一下我应该怎样才可以把数据库从电脑中完全卸载，或者有什么其他的解决方法吗

**Comment by afwerar** [comment]
用rmtaos命令可以卸载tdengine

**Comment by twtmiss** [comment]
> 用rmtaos命令可以卸载tdengine

哦哦谢谢啦，我想问一下卸载，重启电脑，再重新安装，并且启动服务后，连接数据库提示"Conn is broken"，这个应该怎么解决呢。。。。

<img width="686" alt="image" src="https://user-images.githubusercontent.com/36953621/197481121-bae4eb08-8b13-4a7c-8e4c-39eaa7c10ee3.png">

**Comment by sangshuduo** [comment]
> > 用rmtaos命令可以卸载tdengine
> 
> 哦哦谢谢啦，我想问一下卸载，重启电脑，再重新安装，并且启动服务后，连接数据库提示"Conn is broken"，这个应该怎么解决呢。。。。
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/36953621/197481121-bae4eb08-8b13-4a7c-8e4c-39eaa7c10ee3.png">

请修改 /etc/taos/taos.cfg 中增加 debugFlag 143 和 rpcDebugFlag 143，重新启动 taosd 和 taosc，然后把日志 /var/log/taos 目录下的文件打包上传到这里，我们看一下。谢谢

**Comment by twtmiss** [comment]
> 请修改 /etc/taos/taos.cfg 中增加 debugFlag 143 和 rpcDebugFlag 143，重新启动 taosd 和 taosc，然后把日志 /var/log/taos 目录下的文件打包上传到这里，我们看一下。谢谢

我把`/usr/local/Cellar/tdengine/`、`/var/lib/taos`、`/var/log/taos`这三个目录下的所有文件删掉再重新安装就可以了。好像是执行`rmtaos`命令不会删除`/var/lib/taos`目录下的文件。

不好意思麻烦您啦，谢谢啦

**Comment by twtmiss** [comment]
> 请修改 /etc/taos/taos.cfg 中增加 debugFlag 143 和 rpcDebugFlag 143，重新启动 taosd 和 taosc，然后把日志 /var/log/taos 目录下的文件打包上传到这里，我们看一下。谢谢

删除所有文件重新后，可以正常运行。

修改 taos.cfg 的 supportVnodes 参数为100，重新启动taosd，命令行可以正常连接。

在`Springboot`项目里用`taos-jdbcdriver(3.0.2)`连接taos数据库（发现提示连接失败，想起忘记开启`com.tdengine.taosadapter`服务）。再次启动后调用接口执行创建数据库命令，总共创建10个数据库:
```
CREATE DATABASE IF NOT EXISTS aaa001  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa002  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa003  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa004  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa005  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa006  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa007  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa008  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa009  cachemodel 'last_row';
CREATE DATABASE IF NOT EXISTS aaa010 cachemodel 'last_row';
```
SpringBoot后台报错：
```
19:40:05.876 [http-nio-8080-exec-2] ERROR c.s.f.w.e.GlobalExceptionHandler - [handleException,83] - 
### Error querying database.  Cause: java.sql.SQLException: TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection
### The error may exist in file [/Users/twtmiss/工作/2萨纳斯/project/lts-rebot-project/sarnath/target/classes/mybatis/robot/TdengineMapper.xml]
### The error may involve com.sarnath.project.robot.mapper.TdengineMapper.ifExsitDatabase-Inline
### The error occurred while setting parameters
### SQL: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row'
### Cause: java.sql.SQLException: TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection
; uncategorized SQLException; SQL state []; error code [11]; TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection; nested exception is java.sql.SQLException: TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection
org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: java.sql.SQLException: TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection
### The error may exist in file [/Users/twtmiss/工作/2萨纳斯/project/lts-rebot-project/sarnath/target/classes/mybatis/robot/TdengineMapper.xml]
### The error may involve com.sarnath.project.robot.mapper.TdengineMapper.ifExsitDatabase-Inline
### The error occurred while setting parameters
### SQL: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row'
### Cause: java.sql.SQLException: TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection
; uncategorized SQLException; SQL state []; error code [11]; TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection; nested exception is java.sql.SQLException: TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy107.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:83)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy161.ifExsitDatabase(Unknown Source)
	at com.sarnath.project.robot.service.impl.TdengineServiceImpl.ifExsitDatabase(TdengineServiceImpl.java:31)
	at com.sarnath.project.robot.service.impl.TdengineServiceImpl$$FastClassBySpringCGLIB$$2a2a7417.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.sarnath.framework.aspectj.DataSourceAspect.around(DataSourceAspect.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.sarnath.project.robot.service.impl.TdengineServiceImpl$$EnhancerBySpringCGLIB$$8b9c6e91.ifExsitDatabase(<generated>)
	at com.sarnath.project.robot.controller.TdengineController.ifExsitDatabase(TdengineController.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.sarnath.common.filter.RepeatableFilter.doFilter(RepeatableFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.sarnath.framework.security.filter.JwtAuthenticationTokenFilter.doFilterInternal(JwtAuthenticationTokenFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: TDengine ERROR (b): sql: CREATE DATABASE IF NOT EXISTS WuXiTongHui CACHEMODEL 'last_row', desc: Unable to establish connection
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:71)
	at com.taosdata.jdbc.rs.RestfulPreparedStatement.execute(RestfulPreparedStatement.java:216)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3409)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3407)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:60)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:143)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy203.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 121 common frames omitted
```
此时我再去命令行测试，发现连接失败，提示` Conn is broken`。重启数据库也提示连接失败

<img width="810" alt="image" src="https://user-images.githubusercontent.com/36953621/197518048-e6468d67-b6ff-4260-ada2-d9ba5266d013.png">

[taos.zip](https://github.com/taosdata/TDengine/files/9851394/taos.zip)

**Comment by twtmiss** [comment]
重启电脑后，launchctl中找不到`com.tdengine.taosd`

<img width="819" alt="image" src="https://user-images.githubusercontent.com/36953621/197521120-104b388e-fa44-486c-8f24-0e1f87112efd.png">

**Comment by sangshuduo** [comment]
请在一个终端中执行 sudo taosd 看输出什么？如果看到输出文字有 offline to oneline 说明 taosd 可以正常启动，然后在另一个终端执行刚才的 java 程序，看 taosd 是否正常，如果不正常输出了什么

**Comment by sangshuduo** [comment]
10/25 09:14:50.259047 4542440960 DND ERROR dnode:1, localEp MacBook-Pro-16.local:6030 different from MacBook-Pro-16:6030
10/25 09:14:50.259222 4542440960 DND ERROR localEp MacBook-Pro-16.local:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured
==
hostname 变了

**Comment by twtmiss** [comment]
> 10/25 09:14:50.259047 4542440960 DND ERROR dnode:1, localEp MacBook-Pro-16.local:6030 different from MacBook-Pro-16:6030 10/25 09:14:50.259222 4542440960 DND ERROR localEp MacBook-Pro-16.local:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured = = hostname 变了

哦哦好的，我再看看怎么解决吧。麻烦您啦，谢谢啦
