### ISSUE TITLE
td-connector  run error ,     NodeV10.20.1   

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#1808]
` const taos = require('td-connector');

console.log('11111111111111');
var conn = taos.connect({host:"127.0.0.1", user:"root", password:"taosdata", config:"/etc/taos",port:0});       //error from this line 

`

Run give me errors as below, 
/root/tst/wework_server/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
    ^

Error: Dynamic Symbol Retrieval Error: /lib/libtaos.so: **undefined symbol: taos_subfields_cou**nt
    at DynamicLibrary.get (/root/tst/wework_server/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /root/tst/wework_server/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (<anonymous>)
    at Object.Library (/root/tst/wework_server/node_modules/ffi/lib/library.js:47:28)
    at new CTaosInterface (/root/tst/wework_server/node_modules/td-connector/nodetaos/cinterface.js:198:22)
    at TDengineConnection._configConn (/root/tst/wework_server/node_modules/td-connector/nodetaos/connection.js:52:19)
    at new TDengineConnection (/root/tst/wework_server/node_modules/td-connector/nodetaos/connection.js:25:8)
    at Object.module.exports.connect (/root/tst/wework_server/node_modules/td-connector/tdengine.js:3:10)
    at Object.<anonymous> (/root/tst/wework_server/connector.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by sytpb** [comment]
@StoneT2000

**Comment by StoneT2000** [comment]
What operating system are you using? Also can you try removing node_modules and then reinstalling with npm install

**Comment by sytpb** [comment]
centos   ,  yes , reinstalled with npm install , problem still  happen .

**Comment by StoneT2000** [comment]
Can you try reinstalling taos? Maybe there was an error with the taos client library

**Comment by sytpb** [comment]
OH?  TDengine-client-1.6.5.8-Linux-x64.tar.gz (3.4M)   this one ?        I only install the server package , --  TDengine-server-1.6.5.8-Linux-x64.tar.gz (5.3M) ,      didn't install client package ..

**Comment by StoneT2000** [comment]
You need the client, can you install it and try rerunning npm install and test your code again? You need the /lib/libtaos.so

**Comment by sytpb** [comment]
I have check my linux ,  i have this so already. .. 
[root@VM_0_16_centos /]# ls /lib/libtaos.so
/lib/libtaos.so

**Comment by sexbee** [comment]
ubuntu update to  tdengine version is 1.6.5.9 error:
/usr/local/koaicu/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
    ^

Error: Dynamic Symbol Retrieval Error: /lib/libtaos.so: undefined symbol: taos_subfields_count
    at DynamicLibrary.get (/usr/local/koaicu/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /usr/local/koaicu/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (<anonymous>)
    at Object.Library (/usr/local/koaicu/node_modules/ffi/lib/library.js:47:28)
    at new CTaosInterface (/usr/local/koaicu/node_modules/td-connector/nodetaos/cinterface.js:198:22)
    at TDengineConnection._configConn (/usr/local/koaicu/node_modules/td-connector/nodetaos/connection.js:52:19)
    at new TDengineConnection (/usr/local/koaicu/node_modules/td-connector/nodetaos/connection.js:25:8)

**Comment by StoneT2000** [comment]
Hi, can you try using node v10

**Comment by StoneT2000** [comment]
Ok, part of the C/C++ API was changed I believe, an update to the connector will come sometime by this weekend. taos_sub_fields_count is used for counting the fields returned by a subscription but that seems to have been deprecated.

**Comment by StoneT2000** [comment]
Although the PR has not been merged, you can do `npm install td-connector` and get the newest version 1.6.1 and try it out now, it should work now.
