### ISSUE TITLE
3.0.1.7 jdbc connect error

### ISSUE THREAD

**Issue by homeless2010** [taosdata/TDengine#18576]
* taos service linux x86 3.0.1.7
* taos windows cline3.0.1.7
* jdbc-driver:3.0.2
* jdk8 异常：
Exception in thread "main" java.lang.NoSuchMethodError: setByteArray
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:157)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.taosdata.example.JdbcDemo.init(JdbcDemo.java:44)
	at com.taosdata.example.JdbcDemo.main(JdbcDemo.java:24)
* jdk17异常：
Exception in thread "main" java.lang.NoSuchMethodError: Lcom/taosdata/jdbc/TSDBResultSetBlockData;.setByteArray(II[B)V
at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:157)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
at com.taosdata.example.JdbcDemo.init(JdbcDemo.java:44)
at com.taosdata.example.JdbcDemo.main(JdbcDemo.java:24)

**Comment by yu285** [comment]
把 C:\TDengine\driver\taos.dll 拷贝到 C:\Windows\System32\ 目录下

再试试

**Comment by lovekobe24** [comment]
同样的问题，解决了吗
