### ISSUE TITLE
shell链接数据库可以成功执行sql，但使用java mybatis执行报错

### ISSUE THREAD

**Issue by w327853501** [taosdata/TDengine#18928]
java报错：
Caused by: java.sql.SQLException: TDengine ERROR (80000216): invalid operation: '630KVA 场外' (Illegal byte sequence)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119)
	at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:98)
	at com.taosdata.jdbc.TSDBPreparedStatement.execute(TSDBPreparedStatement.java:261)

超级表结构：
taos> describe plcs;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 plc_name                       | NCHAR                |         100 |          |
 box_name                       | NCHAR                |         100 |          |
 variant_name                   | NCHAR                |         100 |          |
 variant_value                  | DOUBLE               |           8 |          |
 variant_id                     | NCHAR                |          50 |          |
 plc_id                         | NCHAR                |         100 | TAG      |
 box_id                         | NCHAR                |         100 | TAG      |
Query OK, 8 row(s) in set (0.000162s)

shell执行sql：
taos> INSERT INTO 'tq_taos.Plc_418b5d83eb9c4b7d8493fb512dbf0b11_0' USING plcs TAGS ('0','418b5d83eb9c4b7d8493fb512dbf0b11') ( ts, plc_name, box_name, variant_name, variant_value, v
ariant_id ) VALUES ( 1670916594017, '污水 ADL400', '630KVA 场外', 'B相电压污水', '235.6999969', '2' ) , 'tq_taos.Plc_418b5d83eb9c4b7d8493fb512dbf0b11_0' USING plcs TAGS ('0','418b5
d83eb9c4b7d8493fb512dbf0b11') ( ts, plc_name, box_name, variant_name, variant_value, variant_id ) VALUES ( 1670916594019, '污水 ADL400', '630KVA 场外', 'A相电压污水', '235.6999969', '1' )  ;
Query OK, 7 of 7 row(s) in database (0.004205s)

**Comment by w327853501** [comment]
数据库 2.4.0.16
jdbc驱动 2.0.38

**Comment by w327853501** [comment]
已解决
&charset=UTF-8
