### ISSUE TITLE
在centos下，配置内容为主机名时，java访问报错

### ISSUE THREAD

**Issue by martinma6** [taosdata/TDengine#18944]
配置文件内容：
fqdn                       hnbhbt.com
serverPort              6030

-------------------------
启动服务后，在本机能通过taos登录数据库

java异常：
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	... 108 common frames omitted
Caused by: java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:73)
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:158)
	at com.taosdata.jdbc.TSDBStatement.executeQuery(TSDBStatement.java:48)
	at com.taosdata.jdbc.TSDBPreparedStatement.executeQuery(TSDBPreparedStatement.java:178)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	... 146 common frames omitted
[31m2022-12-14 14:04:33.249[0;39m [00000001-00150003] [34mINFO [0;39m [36mcom.hnbhbt.device.utils.IotSocketClient[0;39m - 当前设备key:【00000001】, 接收到设备数据: <<<<<< 【】
[31m2022-12-14 14:04:33.249[0;39m [00000001-00150003] [34mINFO [0;39m [36mcom.hnbhbt.device.utils.IotSocketClient[0;39m - 当前设备key:【00000001】, 发送消息到设备: >>>>>> 【000BB4B00103002A0001A5C2】

**Comment by martinma6** [comment]
已解决，在hosts中增加一个主机名对应的IP的配置
