### ISSUE TITLE
spring boot mybatis demo running error

### ISSUE THREAD

**Issue by weiian112** [taosdata/TDengine#19221]
直接运行mybatisdemo（https://github.com/taosdata/TDengine/tree/3.0/examples/JDBC/mybatisplus-demo）异常，提示如下：
![Uploading 61468e0293fafe8c5a089900c1792fb.png…]()
主要的异常提示就是Error creating bean h2console  exception,not found setByteArray
进行代码调整：
1.删除了引用的h2的jar包，同时代码注入了sqlsessionfactory

2.同时在weathermapper上增加了@mapper注解，测试项目能启动成功了，但是运行单元测试用例的时候还是一直报下面这个错误
java.lang.NoSuchMethodError: setByteArray

 at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
 at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:43)
 at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
 at java.sql.DriverManager.getConnection(DriverManager.java:664)
 at java.sql.DriverManager.getConnection(DriverManager.java:208)
 at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
 at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
 at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
 at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
 at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
 at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
 at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
 at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
 at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
 at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
 at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
 at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
 at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
 at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 
个人将要达到的目标：
1. 利用spring boot mybatis 整合pgsql以及涛思数据库双数据源的问题
2. 整合mybatis、涛思方便进行便捷性开发

**Comment by weiian112** [comment]
补充：jdbc驱动是3.0.0，就是开源示例中的

**Comment by weiian112** [comment]
补充Java版本是：1.8.0_333-b02)

**Comment by sangshuduo** [comment]
TDengine 什么版本？

**Comment by yu285** [comment]
此前装过2.0 的客户端，dll文件版本过旧，做关闭处理
