### ISSUE TITLE
java客户端模式连接tdengine 3.0.1.6报错com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)

### ISSUE THREAD

**Issue by ltlf** [taosdata/TDengine#19252]
jdk版本：1.8
客户端使用的mac笔记本
客户端jdbc驱动：
<groupId>com.taosdata.jdbc</groupId>
<artifactId>taos-jdbcdriver</artifactId>
<version>3.0.0</version>
tdengine server版本：3.0.1.6
使用官网jdbc示例连接6030时报错如下：
java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;
at com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Native Method)
at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:41)
at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1596)
at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1662)
at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2697)
2022-12-29 13:20:11.608 [Druid-ConnectionPool-Create-1194398327] INFO  com.alibaba.druid.pool.DruidAbstractDataSource:1743 - {dataSource-1} failContinuous is true
烦请看下是什么原因呢，谢谢

**Comment by easyang** [comment]
我也是
jdk版本：1.8
客户端使用的mac笔记本
客户端jdbc驱动：
com.taosdata.jdbc
taos-jdbcdriver : 3.0.2
tdengine server版本：3.0.2.2

/Library/Java/Extensions:
libtaos.dylib -> /usr/local/lib/libtaos.dylib

 java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;
	at com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Native Method) ~[taos-jdbcdriver-3.0.0.jar:?]
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:41) ~[taos-jdbcdriver-3.0.0.jar:?]
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162) ~[taos-jdbcdriver-3.0.0.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[HikariCP-3.1.0.jar:?]

**Comment by yu285** [comment]
这个问题我们在看，有反馈会通知大家

**Comment by GuoShengBing** [comment]
我也是
jdk版本：1.8
系统：mac os 13
客户端jdbc驱动：
com.taosdata.jdbc
taos-jdbcdriver : 3.0.2
tdengine server版本：3.0.2.2
tdengine client版本：3.0.2.2

Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1361) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1208) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]

**Comment by sangshuduo** [comment]
请参考： https://github.com/taosdata/TDengine/issues/18164
