### ISSUE TITLE
python安装问题

### ISSUE THREAD

**Issue by Eduardo95** [taosdata/TDengine#193]

**Comment by Eduardo95** [comment]
我按照github上的步骤源码安装了tdengine，然后使用官网上的教程安装了python包，但是import的时候报错
>>> import taos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/df-test/TDengine/src/connector/python/python3/taos/__init__.py", line 2, in <module>
    from .connection import TDengineConnection
  File "/df-test/TDengine/src/connector/python/python3/taos/connection.py", line 2, in <module>
    from .cursor import TDengineCursor
  File "/df-test/TDengine/src/connector/python/python3/taos/cursor.py", line 1, in <module>
    from .cinterface import CTaosInterface
  File "/df-test/TDengine/src/connector/python/python3/taos/cinterface.py", line 137, in <module>
    class CTaosInterface(object):
  File "/df-test/TDengine/src/connector/python/python3/taos/cinterface.py", line 139, in CTaosInterface
    libtaos = ctypes.CDLL('libtaos.so')
  File "/root/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtaos.so: cannot open shared object file: No such file or directory

请问这是什么问题

**Comment by Eduardo95** [comment]
已解决

**Comment by byronsong** [comment]
请问你是怎么解决的？
我是64位centOS
执行命令：cp /usr/lib/libtaos.so /usr/lib64/
后OK了。

那么tdengine官方安装程序，是不是应该判断是32位系统，还是64位系统，然后将类库文件安装到正确路径。而不是需要每个人都手工纠正一遍？

**Comment by hzcheng** [comment]
centos系统下貌似不会将/usr/lib文件夹放到C的动态链接列表里。可以通过在
~/.bash_profile文件中加上：
```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib"
```
然后
```
source ~/.bash_profile
```

**Comment by byronsong** [comment]
嗯。想起来了。
是通过pip安装的libtaos
那么或者应该可以在pip命令中指定target dir，安装到指定目录中。

Python没有认真学。就直接用了。
见笑了。

**Comment by treemp3** [comment]
CentOS7.6 minimal版本pip3安装python3客户端后，需要执行cp /usr/lib/libtaos.so /usr/lib64/
不然会报错：OSError: libtaos.so: cannot open shared object file: No such file or directory
官方可以写到faq里面，方便大家查询。
