### ISSUE TITLE
订阅成功但是无法poll到数据

### ISSUE THREAD

**Issue by 13196789316** [taosdata/TDengine#19392]
**Bug Description**
执行java方法：ConsumerRecords<V> poll(Duration timeout) throws SQLException;
无法拉取到数据，始终为空。订阅显示成功。

**Screenshots**
![738c0f72f2714bbbbb210bed0588750](https://user-images.githubusercontent.com/31721964/210737429-d3df9a3f-803e-4996-a369-71e1bed23f54.png)

**Environment (please complete the following information):**
1. docker安装tdengine 3.0.2.1
2. windows本地安装tdengine-server 3.0.2.2
3. pom添加依赖
`    <dependency>
        <groupId>com.taosdata.jdbc</groupId>
        <artifactId>taos-jdbcdriver</artifactId>
        <version>3.0.0</version>
    </dependency>`

**Comment by yu285** [comment]
客户端服务端保持一致都用3022，驱动更新到 3.0.2 再试试

**Comment by 13196789316** [comment]
@yu285 更新后可以poll。但是报了新的异常：
`
java.lang.IllegalArgumentException: newPosition > limit: (7676147 > 532)
	at java.nio.Buffer.createPositionException(Buffer.java:269) ~[na:1.8.0_333]
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_333]
	at com.taosdata.jdbc.TSDBResultSetBlockData.setByteArray(TSDBResultSetBlockData.java:226) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.taosdata.jdbc.tmq.TMQConnector.fetchRawBlockImp(Native Method) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.taosdata.jdbc.tmq.TMQConnector.fetchBlock(TMQConnector.java:237) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.taosdata.jdbc.tmq.TMQResultSet.next(TMQResultSet.java:32) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.taosdata.jdbc.tmq.TaosConsumer.poll(TaosConsumer.java:143) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.yuemia.cms.analysis.config.tdengine.TdengineSubscribeHandler.execute(TdengineSubscribeHandler.java:81) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_333]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_333]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_333]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_333]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_333]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_333]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_333]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_333]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_333]

`

**Comment by 13196789316** [comment]
已经统一了时区
