### ISSUE TITLE
no taos in java.library.path

### ISSUE THREAD

**Issue by fjyulu** [taosdata/TDengine#19520]
**Bug Description**
I use the taos jdbc in mysql springboot project the dependency is below
Yes In my ***macbook computor***
![image](https://user-images.githubusercontent.com/46312795/211850212-5373e3d6-edc4-4539-b2d7-9f5c4c922007.png)

when I start the error in console in below
```
Caused by: java.lang.UnsatisfiedLinkError: no taos in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:844)
	at java.lang.System.loadLibrary(System.java:1136)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:28)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.baomidou.dynamic.datasource.creator.HikariDataSourceCreator.createDataSource(HikariDataSourceCreator.java:51)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createHikariDataSource(DataSourceCreator.java:188)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDataSource(DataSourceCreator.java:92)
	at com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider.createDataSourceMap(AbstractDataSourceProvider.java:45)
	at com.baomidou.dynamic.datasource.provider.YmlDynamicDataSourceProvider.loadDataSources(YmlDynamicDataSourceProvider.java:43)
	at com.baomidou.dynamic.datasource.DynamicRoutingDataSource.afterPropertiesSet(DynamicRoutingDataSource.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 46 common frames omitted
```

And yes I read the FAQ in taos website.
![image](https://user-images.githubusercontent.com/46312795/211849058-5f66c00b-244a-4971-8861-825634e5dae2.png)

But I just can't resolve the error according to it
here is my question:
where can I download the ***libtaos.dylib ***

What I have done is: 
* I get the libtaos.so.2.4.0.30 from somewhere 
* I save it in /opt/libtaos.so.2.4.0.30
* I use the command ln -s /opt/libtaos.so.2.4.0.30 /usr/local/lib/libtaos.dylib

and it just not work

Can anybody help me?

**Comment by sangshuduo** [comment]
dylib is share library format on macOS. I suppose you are using macOS then you need download correct format client installation package instead of download so format which is for Linux.

**Comment by fjyulu** [comment]
Hi thanks a lot for your reply
I have tried download the ***libtaos.so.2.4.0.30*** from taos website , and below is my step
* put the download file under /opt
* link the file to /user/local/lib/libtaos.dylib
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/46312795/212035038-ddee25fe-813f-4490-a991-d1da9cef4cdb.png">
just like the picture I post
but when I run my project the error message occur like below
```
Caused by: java.lang.UnsatisfiedLinkError: /opt/libtaos.so.2.4.0.30: dlopen(/opt/libtaos.so.2.4.0.30, 0x0001): tried: '/opt/libtaos.so.2.4.0.30' (not a mach-o file), '/usr/lib/libtaos.so.2.4.0.30' (no such file)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:844)
	at java.lang.System.loadLibrary(System.java:1136)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:28)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.baomidou.dynamic.datasource.creator.HikariDataSourceCreator.createDataSource(HikariDataSourceCreator.java:51)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createHikariDataSource(DataSourceCreator.java:188)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDataSource(DataSourceCreator.java:92)
	at com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider.createDataSourc
```
it seems found the ***/opt/libtaos.so.2.4.0.30***, but not meet the requirement which I know nothing about it

below is my config 
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/46312795/212035784-f19e4ccd-3ca6-4b7b-ac9a-499690735874.png">
 
### FYI
* I can't use the latest version cuz the **taos cluster ** run for a long time, and have huge data in it.the version **2.4.0.30** is the taos sever's version
* my computer is mbp with m1 chip

Is there any chance for me run the project in my own  computer...
really appreciating for your reply

Best regard

**Comment by sangshuduo** [comment]
dylib is share library format on macOS. I suppose you are using macOS then you need download correct format client installation package instead of download so format which is for Linux.

**Comment by lucyilys** [comment]
@fjyulu May I ask how to download libtaos.so on the taos official website? I can't find the entrance or connection on it

**Comment by sangshuduo** [comment]
> @fjyulu May I ask how to download libtaos.so on the taos official website? I can't find the entrance or connection on it↳

go to https://docs.tdengine.com then choose what version of TDengine you need, Download TDengine-client installation package according to what OS you use and what package format you are familiar.

**Comment by sangshuduo** [comment]
> I can't understand you reply, and I give up for it anyway thanks a lot for your reply↳

Download the correct package for macOS should resolve your problem

**Comment by lucyilys** [comment]
@sangshuduo 解决了，感谢
