### ISSUE TITLE
 C:\Windows\System32\taos.dll already loaded in another classloader when multi client access to TDengine

### ISSUE THREAD

**Issue by njzhangfei** [taosdata/TDengine#19917]
操作系统：window10
tdengine版本： Version:3.0.1.8

问题：
多个项目同时访问tdengine，使用订阅服务会报如下错误：
C:\Windows\System32\taos.dll already loaded in another classloader

java日志：
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.lanswon.quartz.util.JobInvokeUtil.invokeMethod(JobInvokeUtil.java:60)
	at com.lanswon.quartz.util.JobInvokeUtil.invokeMethod(JobInvokeUtil.java:38)
	at com.lanswon.quartz.util.QuartzDisallowConcurrentExecution.doExecute(QuartzDisallowConcurrentExecution.java:23)
	at com.lanswon.quartz.util.AbstractQuartzJob.execute(AbstractQuartzJob.java:38)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.UnsatisfiedLinkError: Native Library C:\Windows\System32\taos.dll already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1903)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1853)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:28)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.lanswon.quartz.topics.subWarningTaskTopic.SubWarningTopic.topic(SubWarningTopic.java:107)
	at com.lanswon.quartz.task.SubWarningTask.warning(SubWarningTask.java:96)
	... 10 common frames omitted

**Comment by njzhangfei** [comment]
虽然说jvm当中，是不允许加载一个dll两次的，但tdengine为什么不能像类似mysql这样的数据库，换种连接方式，防止出现类似问题？

**Comment by njzhangfei** [comment]
虽然说jvm当中，是不允许加载一个dll两次的，但tdengine为什么不能像类似mysql这样的数据库，换种连接方式，防止出现类似问题？

**Comment by sangshuduo** [comment]
很快 Java connector 会支持基于 WebSocket 的接口
