### ISSUE TITLE
ModuleNotFoundError: No module named 'taos.sqlalchemy'; 'taos' is not a package

### ISSUE THREAD

**Issue by freedomme** [taosdata/TDengine#20474]
import taos
from sqlalchemy import create_engine, text
import pandas

engine = create_engine("taos://root:taosdata@localhost:6030/power")
conn = engine.connect()
df = pandas.read_sql(text("SELECT * FROM power.meters"), conn)
conn.close()
# print index
print(df.index)
# print data type  of element in ts column
print(type(df.ts[0]))
print(df.head(3))

Traceback (most recent call last):
  File "C:\stockdata\taos.py", line 1, in <module>
    import taos
  File "C:\stockdata\taos.py", line 5, in <module>
    engine = create_engine("taos://root:taosdata@localhost:6030/power")
  File "<string>", line 2, in create_engine
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\create.py", line 556, in create_engine
    entrypoint = u._get_entrypoint()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\url.py", line 754, in _get_entrypoint
    cls = registry.load(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 363, in load
    return impl.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'taos.sqlalchemy'; 'taos' is not a package

**Comment by sangshuduo** [comment]
try 'pip install -U taospy'
