### ISSUE TITLE
mybatis 删除报错

### ISSUE THREAD

**Issue by zrwsmd** [taosdata/TDengine#20718]
我用mybatis执行删除操作，

mapper.java
     void deleteByTraceId(@Param("startTimestamp") Timestamp startTimestamp,@Param("endTimestamp")Timestamp endTimestamp,@Param("traceId")Long traceId);

mapper.xml
  <delete id="deleteByTraceId">
    delete from trace_field_meta
    where ts<![CDATA[ >= ]]>#{startTimestamp,jdbcType=TIMESTAMP} and ts<![CDATA[ <= ]]>#{endTimestamp,jdbcType=TIMESTAMP} and
        traceId = #{traceId,jdbcType=BIGINT}
  </delete>

报错
   Caused by: java.sql.SQLException: TDengine ERROR (80002655): The DELETE statement must have a definite time window range
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:86)
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119)
	at com.taosdata.jdbc.TSDBStatement.executeImpl(TSDBStatement.java:186)
	at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:172)
	at com.taosdata.jdbc.TSDBPreparedStatement.execute(TSDBPreparedStatement.java:201)
     ....

 还有下面这个区间不是这么用的吗

 select * from 表名 where   timestamp>150 and time<9000 或者
select * from 表名 where   timestamp between 150 and 9000
为什么报错syntax error near ">150 and time<9000

**Comment by feici02** [comment]
应该是由于mapper.xml中的语法错误导致的，请修改正确后再尝试：
![image](https://user-images.githubusercontent.com/5568663/229037145-8f00e15a-ec18-4570-b1ad-44b4002b323c.png)
