### ISSUE TITLE
java代码，使用RestfulDriver创建连接池失败

### ISSUE THREAD

**Issue by 2406450951** [taosdata/TDengine#20976]
版本：3.0.4
jdk版本：11
环境：win10

`@Test 
    public void createDataSourceTest()throws Exception{
        HikariConfig config = new HikariConfig();
        // jdbc properties
        config.setDriverClassName("com.taosdata.jdbc.rs.RestfulDriver");
        config.setJdbcUrl("jdbc:TAOS-RS://localhost:6041/hertzbeat");
        config.setUsername("root");
        config.setPassword("taosdata");
        //minimum number of idle connection
        config.setMinimumIdle(10);
        //maximum number of connection in the pool
        config.setMaximumPoolSize(10);
        //maximum wait milliseconds for get connection from pool
        config.setConnectionTimeout(30000);
        // maximum lifetime for each connection
        config.setMaxLifetime(0);
        // max idle time for recycle idle connection
        config.setIdleTimeout(0);
        //validation query
        config.setConnectionTestQuery("select server_status()");
        HikariDataSource hikariDataSource = new HikariDataSource(config);
        System.out.println("创建连接池成功！！！");
    }`
异常信息：
`java.sql.SQLException: ERROR (2318): Connect to localhost:6041 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:72)
	at com.taosdata.jdbc.utils.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:129)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:65)
	at com.taosdata.jdbc.rs.RestfulDriver.connect(RestfulDriver.java:150)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.dromara.hertzbeat.manager.pojo.dto.AppCount.main(AppCount.java:100)
13:11:17.451 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.`

**Comment by 2406450951** [comment]
使用jdbc方式创建连接池会成功
`@Test
    public void createDataSourceTest()throws Exception{
        HikariConfig config = new HikariConfig();
        // jdbc properties
        config.setDriverClassName("com.taosdata.jdbc.TSDBDriver");
        config.setJdbcUrl("jdbc:TAOS://localhost:6030/hertzbeat");
        config.setUsername("root");
        config.setPassword("taosdata");
        //minimum number of idle connection
        config.setMinimumIdle(10);
        //maximum number of connection in the pool
        config.setMaximumPoolSize(10);
        //maximum wait milliseconds for get connection from pool
        config.setConnectionTimeout(30000);
        // maximum lifetime for each connection
        config.setMaxLifetime(0);
        // max idle time for recycle idle connection
        config.setIdleTimeout(0);
        //validation query
        config.setConnectionTestQuery("select server_status()");
        HikariDataSource hikariDataSource = new HikariDataSource(config);
        System.out.println("创建连接池成功！！！");
    }`
![image](https://user-images.githubusercontent.com/48074721/232973515-6b033ee4-b540-4b66-9579-38f643fcf820.png)

**Comment by 2406450951** [comment]
3.0.4版本想要使用RS方式，必须启动C:\TDengine\taosadpter.exe
