### ISSUE TITLE
springboot  + mybatis plus + tdengine   create table failed

### ISSUE THREAD

**Issue by hjy30312** [taosdata/TDengine#20994]
**Bug Description**
springboot  + mybatis plus + tdengine   创建超级表报错 

使用dynamic-datasource-spring-boot-starter，  2个数据库pgsql和tdengine。

```
@Mapper
@DS("taos")
public interface TdEngineMapper {

    // 创建超级表
//    @Update("create stable IF NOT EXISTS #{productId} (ts timestamp, #{columnName} #{columnType}) TAGS (location  nchar(10))")
    @Insert("create stable IF NOT EXISTS test (ts timestamp, wendu double) TAGS (location  nchar(10))")
    void createStable(@Param("productId")String productId, @Param("columnName")String columnName, @Param("columnType")String columnType);

```
错误日志如下：
```
### The error may exist in com/manascloud/mplatform/framework/business/mapper/tdengine/TdEngineMapper.java (best guess)
### The error may involve com.manascloud.mplatform.framework.business.mapper.tdengine.TdEngineMapper.createStable-Inline
### The error occurred while setting parameters
### SQL: create stable IF NOT EXISTS test (ts timestamp, wendu double) TAGS (location  nchar(10))
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near "stable"
  位置：8
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "stable"
  位置：8
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239) ~[spring-jdbc-5.3.3.jar:5.3.3]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.3.jar:5.3.3]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.sun.proxy.$Proxy133.insert(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.sun.proxy.$Proxy145.createStable(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar:5.3.3]
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:50) ~[dynamic-datasource-spring-boot-starter-3.5.2.jar:3.5.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.3.jar:5.3.3]
	at com.sun.proxy.$Proxy146.createStable(Unknown Source) ~[na:na]
```
**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 3.0.2.6]

**Additional Context**

**Comment by sangshuduo** [comment]
org.postgresql.util.PSQLException: ERROR: syntax error at or near "stable"
==
postgre 不支持 create stable 吧

**Comment by hjy30312** [comment]
使用dynamic-datasource-spring-boot ， 用的是com.taosdata.jdbc.TSDBDriver这个驱动。
```
  datasource:
    dynamic:
      primary: postgresql #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        postgresql:
          driverClassName: org.postgresql.Driver
          password: xxxxxxxx
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:postgresql://xxxxxxx:5432/miot
          username: postgres
        taos:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.taosdata.jdbc.TSDBDriver
          url: jdbc:TAOS://xxxxxxx:6030/power?timezone=UTC-8&charset=UTF-8&allowMultiQueries=true
          username: root
          password: xxxxxxx

**Comment by sangshuduo** [comment]
primary: postgresql #设置默认的数据源或者数据源组
改成 primary: taos 
试试

**Comment by hjy30312** [comment]
知道原因了， 使用了事务导致的这个报错

**Comment by Wuyiz** [comment]
> 知道原因了， 使用了事务导致的这个报错

不好意思打扰了，为啥加了@Transactional注解就会报错啊，我也是遇到这个问题了，排查的很莫名其妙，后来发现注解去了就可以正常插入建表，是tdengine不支持spring提供多个事务注解嘛？
