### ISSUE TITLE
超级表创建至5万以上子表时，写入报超时

### ISSUE THREAD

**Issue by flykarry** [taosdata/TDengine#21043]
**Bug Description**
java客户端，一个超级表，单列模式，ts, val，三个tag：customerid, paramId, energyType
计划创建20万个子表，当前从ins_databases中查看，我的库共51980个表，写入频繁报超时

```java
08:14:37.986 [pool-1-thread-2] ERROR com.accu.common.utils.ThreadPools - 线程池异常
java.lang.RuntimeException: java.sql.SQLException: ERROR (2307): java.util.concurrent.TimeoutException
	at com.accu.CommonTest.lambda$insertTest$0(CommonTest.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: ERROR (2307): java.util.concurrent.TimeoutException
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:72)
	at com.taosdata.jdbc.ws.WSStatement.execute(WSStatement.java:90)
	at com.taosdata.jdbc.ws.WSStatement.executeUpdate(WSStatement.java:46)
	at com.accu.CommonTest.lambda$insertTest$0(CommonTest.java:83)
	... 3 common frames omitted
```

**To Reproduce**
```java
 public Connection getRestConn() {
        try {
            Class.forName("com.taosdata.jdbc.rs.RestfulDriver");
            String jdbcUrl = "jdbc:TAOS-RS://192.168.13.240:6041/ecs_test?user=root&password=taosdata";
            Properties connProps = new Properties();
            connProps.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
            Connection conn = DriverManager.getConnection(jdbcUrl, connProps);
            return conn;
        } catch (ClassNotFoundException | SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Test
    public void insertTest() throws Exception {
        Date date = new Date();
        var restConn = getRestConn();
        for (int z = 0; z < 20; z++) { //20个线程处理
            int finalZ = z;
            ThreadPools.execute(() -> {
                for (int i = 520; i < 25000; i++) { //2.5万个表
                    var meter = i + 25000 * finalZ;
                    var customerId = 1486944392209022978L + meter % 20;  //20个客户
                    Statement stmt = null;
                    try {
                        stmt = restConn.createStatement();
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                    StopWatch stopWatch = new StopWatch();
                    stopWatch.start();
                    for (int j = 0; j < 5; j++) {
                        var paramId = (148694439220902297L + meter) * 10 + j;
                        var tableId = "T" + paramId;
                        String sql = null;
                        for (int k = 0; k < 43800; k++) {//5年数据
                            var date1 = TimeUtils.addHour(date, k);
                            if (k % 4379 == 0 && sql != null) {
                                try {
                                    stmt.executeUpdate(sql);
                                    Thread.sleep(1000);
                                } catch (SQLException | InterruptedException e) {
                                    throw new RuntimeException(e);
                                }
                                sql = null;
                            } else {
                                //拼接sql
                                if (j % 3 == 0) { //制造2个NL参数
                                    if (sql == null) {
                                        sql = "insert into " + tableId + " using energybasedata tags ('" + customerId + "','" + paramId + "','NL') values (" + date1.getTime() + ", " + new Random().nextInt(500000) + ")";
                                    } else {
                                        sql += "(" + date1.getTime() + ", " + new Random().nextInt(500000) + ")";
                                    }
                                } else { //制造3个YC参数
                                    if (sql == null) {
                                        sql = "insert into " + tableId + " using energybasedata tags ('" + customerId + "','" + paramId + "','YC') values (" + date1.getTime() + ", " + new Random().nextDouble() * 100 + ")";
                                    } else {
                                        sql += "(" + date1.getTime() + ", " + new Random().nextDouble() * 100 + ")";
                                    }
                                }
                            }
                        }
                    }
                    stopWatch.stop();
                    System.out.println(TimeUtils.formatToCommonType(new Date()) + " " + Thread.currentThread().getName() + "第" + meter + "个表的5个参数5年数据，耗时：" + stopWatch.getTime(TimeUnit.MILLISECONDS) + "毫秒");
                }
            });
        }
        Thread.sleep(24 * 1000 * 60 * 60 * 200L);
    }
```

**Environment (please complete the following information):**
docker部署，以下为宿主机
 - OS: ubuntu 22.04.1
 - Memory, CPU, current Disk Space 16G内存，4核2.1G，1T机械磁盘（机器较老）
 - TDengine Version：3.0.4.0

**Comment by yu285** [comment]
3.0早期版本的问题都已经都优化了，但是3.0.2.5 之前可能与现在的最新版（3.3.0.0）并不兼容，所以无法直接升级。因此建议重新部署一下最新的 3.3.0.0 ，后续升级都很方便，直接安装最新版软件即可。

开源版支持操作系统范围：https://docs.taosdata.com/reference/support-platform/


如果还有具体的使用问题，可以加微信：a15652223354
