### ISSUE TITLE
Unable to establish connection

### ISSUE THREAD

**Issue by bs7729** [taosdata/TDengine#21607]
**Bug Description**

java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:86)
        at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119)
        at com.taosdata.jdbc.TSDBStatement.executeQueryImpl(TSDBStatement.java:74)
        at com.taosdata.jdbc.TSDBStatement.executeQuery(TSDBStatement.java:57)
        at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1421)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1720)
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2774)

**Expected Behavior**
不定时出现问题,一般1个星期出现,有时候一天就会出现,一天出现这问题比较少,出现这问题时候无法恢复正常时,重启一下java程序后就正常了.
**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/64937539/35cb59ed-0fff-4f22-997f-5c6aa7475d27)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.6]
 - Memory, CPU, current Disk Space
 - 
![image](https://github.com/taosdata/TDengine/assets/64937539/227e6617-d154-4eb8-ab80-da7248dbca14)

 - TDengine Version [3.0.3.1]
 - taos-jdbcdriver [3.1.0]

**Comment by sangshuduo** [comment]
先升级到最新版本，如果还有同样问题请提供发生时刻附近的 log

**Comment by bs7729** [comment]
好的

**Comment by 123sdfa** [comment]
您好，请问您这个问题解决了吗？我使用dynamic-datasource和Druid连接TDengine，刚启动的时候没问题，10多分钟后再次查询就不行了，报错：Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60007, active 0, maxActive 5, creating 1, createElapseMillis 120031
![image](https://github.com/taosdata/TDengine/assets/12029897/23462711-f848-4c1c-8cd6-31f9056fe74b)
