### ISSUE TITLE
ava.sql.SQLException: JNI ERROR (0x2354): Unable to establish connection

### ISSUE THREAD

**Issue by hucaicai** [taosdata/TDengine#21892]
Caused by: java.sql.SQLException: JNI ERROR (0x2354): Unable to establish connection
  at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:85)
  at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:82)
  at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:35)
  at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:21)
  at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:160)
  at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
  at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
  at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
  at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
  at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
  at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
  at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
  at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
  at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
  at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)

请问是什么原因?
客户端版本：TDengine-client-3.0.4.1

**Comment by sangshuduo** [comment]
官网文档搜索 Unable to establish connection 可以搜到排查方法
