### ISSUE TITLE
使用dataX写入数据时，如何将字段类型做转换？

### ISSUE THREAD

**Issue by Memorry0** [taosdata/TDengine#22071]
我在做数据迁移测试时，将原来在TD2.2的表结构调整了一下，然后在TD3中重新建的表，表的属性有变化，例如原来“温度”字段是nchar，现在是int。但在官方文档中，没找到类型转换的函数或写法，这样导致了写入时报【java.sql.SQLException: TDengine ERROR (80000216): syntax error near '' (invalid numeric data)】的错误。
** 希望能提供一下转换的案例，感谢。**[](url)
具体报错如下：
`2023-07-14 14:37:49.972 [taskGroup-0] INFO  TaskGroupContainer - taskGroupId=[0] start [1] channels for [1] tasks.
2023-07-14 14:37:49.981 [taskGroup-0] INFO  Channel - Channel set byte_speed_limit to -1, No bps activated.
2023-07-14 14:37:49.985 [taskGroup-0] INFO  Channel - Channel set record_speed_limit to -1, No tps activated.
2023-07-14 14:37:50.028 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] taskId[0] attemptCount[1] is started
2023-07-14 14:37:50.351 [0-0-0-writer] INFO  DefaultDataHandler - connection[ jdbcUrl: jdbc:TAOS://172.168.1.167:6030/testDB?timestampFormat=TIMESTAMP&useUnicode=true&characterEncoding=utf8, username: xxxx] established.
2023-07-14 14:37:50.367 [0-0-0-writer] INFO  DefaultDataHandler - tdengine server version[3.0.5.0] dbname[testDB]
2023-07-14 14:37:56.289 [0-0-0-writer] WARN  DefaultDataHandler - use one row insert. because:TDengine ERROR (80000216): syntax error near '' (invalid numeric data)
2023-07-14 14:37:56.307 [0-0-0-writer] ERROR DefaultDataHandler - TDengine ERROR (80000216): syntax error near '' (invalid numeric data)
2023-07-14 14:37:56.311 [0-0-0-writer] ERROR StdoutPluginCollector - 
java.sql.SQLException: TDengine ERROR (80000216): syntax error near '' (invalid numeric data)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.taosdata.jdbc.TSDBStatement.executeUpdateImpl(TSDBStatement.java:119) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:107) ~[taos-jdbcdriver-3.0.3.jar:na]
	at com.alibaba.datax.plugin.writer.tdengine30writer.DefaultDataHandler.executeUpdate(DefaultDataHandler.java:328) [tdengine30writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.tdengine30writer.DefaultDataHandler.writeBatchToNormalTable(DefaultDataHandler.java:602) [tdengine30writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.tdengine30writer.DefaultDataHandler.writeBatchToSupTableWithoutTbname(DefaultDataHandler.java:228) [tdengine30writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.tdengine30writer.DefaultDataHandler.writeBatch(DefaultDataHandler.java:200) [tdengine30writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.tdengine30writer.DefaultDataHandler.writeEachRow(DefaultDataHandler.java:170) [tdengine30writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.tdengine30writer.DefaultDataHandler.handle(DefaultDataHandler.java:135) [tdengine30writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.tdengine30writer.TDengineWriter$Task.startWrite(TDengineWriter.java:109) [tdengine30writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2023-07-14 14:37:56.323 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据: 
{"exception":"TDengine ERROR (80000216): syntax error near '' (invalid numeric data)","record":[{"byteSize":8,"index":0,"rawData":1675736625000,"type":"DATE"},{"byteSize":1,"index":1,"rawData":1,"type":"LONG"},{"byteSize":1,"index":2,"rawData":2,"type":"LONG"},{"byteSize":2,"index":3,"rawData":10,"type":"LONG"},{"byteSize":5,"index":4,"rawData":"24.07","type":"DOUBLE"},{"byteSize":3,"index":5,"rawData":-76,"type":"LONG"},{"byteSize":15,"index":6,"rawData":"537470A002E003C","type":"STRING"},{"byteSize":0,"index":7,"rawData":"","type":"STRING"},{"byteSize":0,"index":8,"rawData":"","type":"STRING"},{"byteSize":0,"index":9,"rawData":"","type":"STRING"},{"byteSize":0,"index":10,"rawData":"","type":"STRING"},{"byteSize":18,"index":11,"rawData":"835557887030853632","type":"STRING"},{"byteSize":18,"index":12,"rawData":"835619364240621568","type":"STRING"},{"byteSize":18,"index":13,"rawData":"835979636365066240","type":"STRING"},{"byteSize":3,"index":14,"rawData":"101","type":"STRING"},{"byteSize":15,"index":15,"rawData":"100000800000010","type":"STRING"},{"byteSize":8,"index":16,"rawData":1675736629790,"type":"DATE"},{"byteSize":18,"index":17,"rawData":"734530596264480768","type":"STRING"}],"type":"writer"}
2023-07-14 14:37:56.357 [0-0-0-writer] ERROR DefaultDataHandler - TDengine ERROR (80000216): syntax error near '' (invalid numeric data)
2023-07-14 14:37:56.359 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据: 
{"exception":"TDengine ERROR (80000216): syntax error near '' (invalid numeric data)","record":[{"byteSize":8,"index":0,"rawData":1675738792000,"type":"DATE"},{"byteSize":1,"index":1,"rawData":1,"type":"LONG"},{"byteSize":1,"index":2,"rawData":0,"type":"LONG"},{"byteSize":2,"index":3,"rawData":10,"type":"LONG"},{"byteSize":5,"index":4,"rawData":"24.04","type":"DOUBLE"},{"byteSize":3,"index":5,"rawData":-75,"type":"LONG"},{"byteSize":15,"index":6,"rawData":"537470A002E003C","type":"STRING"},{"byteSize":0,"index":7,"rawData":"","type":"STRING"},{"byteSize":0,"index":8,"rawData":"","type":"STRING"},{"byteSize":10,"index":9,"rawData":"112.249443","type":"STRING"},{"byteSize":9,"index":10,"rawData":"30.309171","type":"STRING"},{"byteSize":18,"index":11,"rawData":"835557887030853632","type":"STRING"},{"byteSize":18,"index":12,"rawData":"835619364240621568","type":"STRING"},{"byteSize":18,"index":13,"rawData":"835979636365066240","type":"STRING"},{"byteSize":3,"index":14,"rawData":"101","type":"STRING"},{"byteSize":15,"index":15,"rawData":"100000800000010","type":"STRING"},{"byteSize":8,"index":16,"rawData":1675738814509,"type":"DATE"},{"byteSize":18,"index":17,"rawData":"734530596264480768","type":"STRING"}],"type":"writer"}
2023-07-14 14:37:56.394 [0-0-0-writer] ERROR DefaultDataHandler - TDengine ERROR (80003002): invalid value:,env_humidy=,longitude=,latitude=,farm_id=835557887030853632,house_id=835619364240621568,column_id=835979636365066240,type_conf_id=607970402957787136,tag_number=L"100000100011909",insert_time=1675736030838i64 1675736025000
2023-07-14 14:37:56.401 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据: 
{"exception":"TDengine ERROR (80003002): invalid value:,env_humidy=,longitude=,latitude=,farm_id=835557887030853632,house_id=835619364240621568,column_id=835979636365066240,type_conf_id=607970402957787136,tag_number=L\"100000100011909\",insert_time=1675736030838i64 1675736025000","record":[{"byteSize":8,"index":0,"rawData":1675736025000,"type":"DATE"},{"byteSize":1,"index":1,"rawData":1,"type":"LONG"},{"byteSize":1,"index":2,"rawData":0,"type":"LONG"},{"byteSize":1,"index":3,"rawData":2,"type":"LONG"},{"byteSize":5,"index":4,"rawData":"23.26","type":"DOUBLE"},{"byteSize":3,"index":5,"rawData":-63,"type":"LONG"},{"byteSize":15,"index":6,"rawData":"537470A002E003C","type":"STRING"},{"byteSize":0,"index":7,"rawData":"","type":"STRING"},{"byteSize":0,"index":8,"rawData":"","type":"STRING"},{"byteSize":0,"index":9,"rawData":"","type":"STRING"},{"byteSize":0,"index":10,"rawData":"","type":"STRING"},{"byteSize":18,"index":11,"rawData":"835557887030853632","type":"STRING"},{"byteSize":18,"index":12,"rawData":"835619364240621568","type":"STRING"},{"byteSize":18,"index":13,"rawData":"835979636365066240","type":"STRING"},{"byteSize":18,"index":14,"rawData":"607970402957787136","type":"STRING"},{"byteSize":15,"index":15,"rawData":"100000100011909","type":"STRING"},{"byteSize":8,"index":16,"rawData":1675736030838,"type":"DATE"},{"byteSize":18,"index":17,"rawData":"787006744873140228","type":"STRING"}],"type":"writer"}`

**Comment by Memorry0** [comment]
![td2totd3](https://github.com/taosdata/TDengine/assets/39758006/f91ffbc5-7c78-4c3e-8a84-d37beb55e7dd)

**Comment by zmlgirl** [comment]
现在  datax 即便解决了这个数据类型的问题，也不能解决 2.* 数据迁移到 3.* 的，驱动不兼容，datax 目前只支持配置一个版本的 jdbc 驱动。这个任务我们内部暂时没有明确的时间表，可以暂时尝试别的方式迁移数据，或者通过企业版团队/开源社区（taosdata 的 DataX 仓库）提需求给我们，我们会根据内部优先级来排期处理。
