### ISSUE TITLE
td3.1.0.0  原生方式6030端口连接无法连接

### ISSUE THREAD

**Issue by z153114659** [taosdata/TDengine#22546]
我的TD和项目再一台服务器上，下面是我的 taos-jdbcdriver版本
    <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.2.3</version>
        </dependency>

      jdbc-url: jdbc:TAOS://*****:6030/******?user=root&password=taosdata
      driver-class-name: com.taosdata.jdbc.TSDBDriver

以下士报错信息
Exception in thread "taskExecutor--50" java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:159)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
        at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
        at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
        at com.sun.proxy.$Proxy88.insert(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)

**Comment by sangshuduo** [comment]
官方示例程序可以跑吗？

**Comment by z153114659** [comment]
> 官方示例程序可以跑吗？
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'temperatureMapper' defined in URL [jar:file:/tmp/app.jar!/BOOT-INF/classes!/com/taosdata/example/mybatisplusdemo/mapper/TemperatureMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /usr/lib/libtaos.so: libjemalloc.so.2: cannot open shared object file: No such file or directory
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1518) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1401) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:925) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[spring-context-5.3.1.jar!/:5.3.1]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.1.jar!/:5.3.1]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.0.jar!/:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [spring-boot-2.4.0.jar!/:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.0.jar!/:2.4.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.0.jar!/:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.0.jar!/:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [spring-boot-2.4.0.jar!/:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [spring-boot-2.4.0.jar!/:2.4.0]
        at com.taosdata.example.mybatisplusdemo.MybatisplusDemoApplication.main(MybatisplusDemoApplication.java:12) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_271]

**Comment by z153114659** [comment]
我的usr /lib下   有这些包
binfmt.d  dracut     games  kbd     libtaos.so    locale      modules-load.d  python2.7  sendmail.postfix  systemd     udev
cpp       firewalld  gcc    kdump   libtaos.so.1  modprobe.d  NetworkManager  rpm        sse2              tmpfiles.d  yum-plugins
debug     firmware   grub   kernel  libtaosws.so  modules     polkit-1        sendmail   sysctl.d          tuned

**Comment by sangshuduo** [comment]
看起来是 java.lang.UnsatisfiedLinkError: /usr/lib/libtaos.so: libjemalloc.so.2: cannot open shared object file: No such file or directory 找不到 libjemalloc 的问题

你的系统是 CentOS 吗？具体版本是什么？安装的 TDengine 什么版本？什么格式的安装包？

**Comment by z153114659** [comment]
我是两台服务器 一台服务器装的TD 3.1.0.0 本地安装的   然后我在另外一台服务器上装了3.1.0.0的客户端  然后再客户端这台服务器跑JAVA项目的时候 就报错了 6041端口没问题

**Comment by z153114659** [comment]
> 看起来是 java.lang.UnsatisfiedLinkError: /usr/lib/libtaos.so: libjemalloc.so.2: cannot open shared object file: No such file or directory 找不到 libjemalloc 的问题
> 
> 你的系统是 CentOS 吗？具体版本是什么？安装的 TDengine 什么版本？什么格式的安装包？

CentOS Linux release 7.9.2009 (Core)

**Comment by sangshuduo** [comment]
看起来是客户端安装包没有包含 libjemalloc

**Comment by sangshuduo** [comment]
可以在使用客户端那台机器安装服务端软件，使用 systemctl disable taosd 保证不启动服务端，应该可以临时解决问题。客户端安装包的问题我们看一下

**Comment by sangshuduo** [comment]
我在 一个 全新的 CentOS 7.9 docker 镜像里安装官方 3.1.0.0 客户端安装包，执行官方示例程序，没有复现找不到 libjemalloc 的问题

**Comment by z153114659** [comment]
> 我在 一个 全新的 CentOS 7.9 docker 镜像里安装官方 3.1.0.0 客户端安装包，执行官方示例程序，没有复现找不到 libjemalloc 的问题

谢谢  我这边还在看   java.lang.UnsatisfiedLinkError: no taos in java.library.path  这个是要在JAR包依赖里添加这个依赖？

**Comment by sangshuduo** [comment]
如果发生错误 Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path
请检查是否安装 TDengine 客户端安装包或编译 TDengine 安装。如果确定已经安装过还出现这个错误，可以在命令行 java 后加 -Djava.library.path=/usr/lib 来指定寻找共享库的路径。

**Comment by z153114659** [comment]
> 如果发生错误 Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path 请检查是否安装 TDengine 客户端安装包或编译 TDengine 安装。如果确定已经安装过还出现这个错误，可以在命令行 java 后加 -Djava.library.path=/usr/lib 来指定寻找共享库的路径。

ENTRYPOINT ["java","-jar","-Xms2048m","-Xmx2048m","-Dspring.profiles.active=native","-Djava.library.path=/usr/lib","/tmp/app.jar"]
dockerfile里加了这个参数了 还是不行

**Comment by z153114659** [comment]
> 如果发生错误 Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path 请检查是否安装 TDengine 客户端安装包或编译 TDengine 安装。如果确定已经安装过还出现这个错误，可以在命令行 java 后加 -Djava.library.path=/usr/lib 来指定寻找共享库的路径。

没有加参数前  打印出来的路径是/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib

**Comment by z153114659** [comment]
> 如果发生错误 Exception in thread "main" java.lang.UnsatisfiedLinkError: no taos in java.library.path 请检查是否安装 TDengine 客户端安装包或编译 TDengine 安装。如果确定已经安装过还出现这个错误，可以在命令行 java 后加 -Djava.library.path=/usr/lib 来指定寻找共享库的路径。

JAVA项目打包成镜像会有问题 建议官方文档可以特殊说明下
