### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'libtaos.so'

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#2255]
[root@hecs-x-xlarge-2-linux-20200611173655 xxq-backend]# yarn start 
yarn run v1.22.4

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'libtaos.so'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at new DynamicLibrary (/root/www/xxq-backend/node_modules/ffi/lib/dynamic_library.js:67:21)
    at Object.Library (/root/www/xxq-backend/node_modules/ffi/lib/library.js:45:12)
    at new CTaosInterface (/root/www/xxq-backend/node_modules/td-connector/nodetaos/cinterface.js:198:22)
    at TDengineConnection._configConn (/root/www/xxq-backend/node_modules/td-connector/nodetaos/connection.js:52:19)
    at new TDengineConnection (/root/www/xxq-backend/node_modules/td-connector/nodetaos/connection.js:25:8)
    at Object.module.exports.connect (/root/www/xxq-backend/node_modules/td-connector/tdengine.js:3:10)
    at Object.<anonymous> (/root/www/xxq-backend/routes/conn-node.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error Command failed with exit code 1.

**Comment by sytpb** [comment]
permission problem .    npm install  with --unsafe-perm 

npm install td-connector  --unsafe-perm

**Comment by sytpb** [comment]
please refer to   #484   


npm install td-connector --unsafe-perm just solve the td-connector installing problem .

**Comment by StoneT2000** [comment]
This isn't a td-connector issue by the way, it just depends on the permissions set for the libtaos.so and other files.
