### ISSUE TITLE
写入达到50c/s，遇到一些瓶颈问题

### ISSUE THREAD

**Issue by Gausx** [taosdata/TDengine#22861]
**Performance Issue** 
使用TDengine测试工具，写入速度可以达到144c/s，但是当前写入达到50c/s之后，频繁报
java.sql.SQLException: TDengine ERROR (0x80000917): failed to execute batch bind, reason: Sync write stall
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:95)
	at com.taosdata.jdbc.TSDBJNIConnector.executeBatch(TSDBJNIConnector.java:322)
	at com.taosdata.jdbc.TSDBPreparedStatement.columnDataExecuteBatch(TSDBPreparedStatement.java:895)

**Environment (please complete the following information):**

* OS: [e.g. CentOS 7.0]
linux  java原生参数绑定
* Memory, CPU, current Disk Space
16C256G 5台机器
* TDengine Version [e.g. 1.6.1.7]
3.1.1.0

麻烦可以看看指点下排查方向嘛

**Comment by yu285** [comment]
50c 这个 c 的单位是什么呢
