### ISSUE TITLE
TDengine Error: version of client and server not match

### ISSUE THREAD

**Issue by AlexForMRD** [taosdata/TDengine#232]
使用官方示例的时候报错:
java.sql.SQLException: TDengine Error: version of client and server not match
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:96)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at TSDBSyncSample.doCreateDbAndTable(TSDBSyncSample.java:84)
	at TSDBSyncSample.main(TSDBSyncSample.java:44)

TDengine是运行在Linux上的CentOS7.2, 示例程序是在Win7上运行的. 请问下这个是什么原因造成的呢?

**Comment by guanshengliang** [comment]
服务端和客户端的版本号必须相同
现在windows客户端的只发了一个版本，为1.6.1.2
那么linux上服务端版本也需要相应替换

**Comment by AlexForMRD** [comment]
我们现在是通过官网的RPM包来安装的, RPM的包是1.6.1.1, 如果是要版本匹配的话, 就匹配不了, 建议你们弄一个版本list出来, 这样就可以使用对应的版本了. 就像现在这样: 我要找Windows版本的1.6.1.1就找不到, 或者我要安装Linux的1.6.1.2也找不到.
