### ISSUE TITLE
当有3个mnode 时候 会出现taos.error.ConnectionError: [0x090c]: Sync leader is unreachable

### ISSUE THREAD

**Issue by rookiesince** [taosdata/TDengine#23564]
部署环境环境方式：k8s
客户端连接：python
1个mnode
(td) [root@k8s-master tdengine]# python ss.py 
client info: 3.2.0.0
server info: ver:3.2.0.0
build:Built at 2023-10-19 19:36

3个mnode
Traceback (most recent call last):
  File "ss.py", line 19, in <module>
    test_connection()
  File "ss.py", line 11, in test_connection
    password="taosdata",
  File "/root/tdengine/td/lib64/python3.6/site-packages/taos/__init__.py", line 65, in connect
    return TaosConnection(*args, **kwargs)
  File "/root/tdengine/td/lib64/python3.6/site-packages/taos/connection.py", line 25, in __init__
    self._conn = self._chandle.connect(self._host, self._user, self._password, self._database, self._port)
  File "/root/tdengine/td/lib64/python3.6/site-packages/taos/cinterface.py", line 1993, in connect
    return taos_connect(host, user, password, db, port)
  File "/root/tdengine/td/lib64/python3.6/site-packages/taos/cinterface.py", line 235, in taos_connect
    raise ConnectionError(errstr, errno)
taos.error.ConnectionError: [0x090c]: Sync leader is unreachable

**Comment by yu285** [comment]
服务端
show mnode 
show dnode
show vgroups
截图发下

**Comment by rookiesince** [comment]
![Uploading 1.png…]()
查不到show vgroups

**Comment by rookiesince** [comment]
taos> show dnodes ;
     id      |            endpoint            | vnodes | support_vnodes |    status    |       create_time       |       reboot_time       |              note              |
=============================================================================================================================================================================
           1 | tdengine-0.tdengine.tdengin... |      9 |             16 | ready        | 2023-11-13 10:07:22.483 | 2023-11-13 10:07:22.249 |                                |
           2 | tdengine-1.tdengine.tdengin... |      9 |             16 | ready        | 2023-11-13 10:07:35.757 | 2023-11-13 10:07:36.227 |                                |
           3 | tdengine-2.tdengine.tdengin... |     10 |             16 | ready        | 2023-11-13 10:07:48.782 | 2023-11-13 10:07:49.229 |                                |
Query OK, 3 row(s) in set (0.001226s)

taos> show mnodes ;
     id      |            endpoint            |      role      |   status    |       create_time       |        role_time        |
==================================================================================================================================
           1 | tdengine-0.tdengine.tdengin... | leader         | ready       | 2023-11-13 10:07:22.491 | 2023-11-13 10:07:22.430 |
           2 | tdengine-1.tdengine.tdengin... | follower       | ready       | 2023-11-13 10:08:55.517 | 2023-11-13 10:08:59.227 |
           3 | tdengine-2.tdengine.tdengin... | follower       | ready       | 2023-11-13 10:09:08.735 | 2023-11-13 10:09:14.467 |
Query OK, 3 row(s) in set (0.000929s)

taos> show vgroups ;

DB error: database not specified (0.000061s)

**Comment by yu285** [comment]
show vgroups 前要 use 库名；

**Comment by rookiesince** [comment]
taos> show vgroups
    > ;
  vgroup_id  |            db_name             |   tables    | v1_dnode |  v1_status  | v2_dnode |  v2_status  | v3_dnode |  v3_status  | v4_dnode |  v4_status  |  cacheload  | cacheelements | tsma |
======================================================================================================================================================================================================
          18 | log                            |           7 |        1 | leader      | NULL     | NULL        | NULL     | NULL        | NULL     | NULL        |           0 |             0 |    0 |
          19 | log                            |          13 |        2 | leader      | NULL     | NULL        | NULL     | NULL        | NULL     | NULL        |           0 |             0 |    0 |
Query OK, 2 row(s) in set (0.001272s)

**Comment by rookiesince** [comment]
![Uploading 1.png…]()

**Comment by SCY-ICT** [comment]
请问解决了吗 我也遇到这个问题了

**Comment by rookiesince** [comment]
没有  在集群内 没有这个问题 ，集群外不行

**Comment by SCY-ICT** [comment]
我用jdbc执行的会出问题，命令行不会，一样的版本
