### ISSUE TITLE
集群模式下，消费者组中消费者poll时报错java.sql.SQLException: ERROR (0x2318): java.util.concurrent.TimeoutException: ERROR (0x231e): failed to complete the task within the specified time

### ISSUE THREAD

**Issue by meichuannenku** [taosdata/TDengine#23615]
TDengine使用的3.2.0.0版本，驱动版本为3.2.7。
执行subscribe方法时不报错，但是执行poll方法时可能会报错。
消费者组中有两个消费者，报错的为其中固定的一个。执行poll方法时，可能会阻塞一段时间然后报错，也可能正常执行。
错误信息：Caused by: java.sql.SQLException: ERROR (0x2318): java.util.concurrent.TimeoutException: ERROR (0x231e): failed to complete the task:{"action":"poll","args":{"blocking_time":100,"req_id":2}} within the specified time : 60000,MILLISECONDS
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:87)
	at com.taosdata.jdbc.ws.Transport.send(Transport.java:90)
	at com.taosdata.jdbc.ws.tmq.WSConsumer.poll(WSConsumer.java:109)
	at com.taosdata.jdbc.tmq.TaosConsumer.poll(TaosConsumer.java:93)
	at com.uniorange.dcs.consumer.ConsumerHandler.execute(ConsumerHandler.java:101)
此错误只在集群模式下会有，单体模式下消费者组可以正常使用
尝试增大CONNECT_MESSAGE_TIMEOUT参数的值，但是没有什么效果

**Comment by meichuannenku** [comment]
使用3.2.2驱动的时候会发生正常使用一段时间后报错，更换为3.2.7后则不会。如果报错只会在一开始就报错。如果一开始正常运行了，那么一段时间后也不会报错。（报错的一直是消费者组中的同一个消费者）

**Comment by yu285** [comment]
收到，我们看下

**Comment by meichuannenku** [comment]
> 收到，我们看下

您好，请问您那边怎么样了？有发现问题吗？

**Comment by meichuannenku** [comment]
> 收到，我们看下

您好，请问您那边怎么样了？

**Comment by yuyanmengxuan** [comment]
我试了好几个版本完全poll不到数据，但是查询SHOW CONSUMERS;
可以查到状态redeay.最后都超时了
