### ISSUE TITLE
spring环境下 连接时连不上，报Connection timed out异常

### ISSUE THREAD

**Issue by goldenzjy2023** [taosdata/TDengine#23624]
用了github上的springbootdemo和JDBCDemo下的JdbcRestfulDemo，启动都报failed: Connection timed out: connect错误。
环境：
我装的时TDengine3.2.0，taos-jdbcdriver试过3.2.7和3.0.0；测试和TDengine不在同一台电脑；
JDK1.8
确认taosAdapter和6041端口已开，因为DBeaver能连上并看到表和数据。
具体错误：
java.sql.SQLException: ERROR (0x2318): Connect to 10.20.40.7:6041 [/10.20.40.7] failed: Connection timed out: connect
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:87)
	at com.taosdata.jdbc.utils.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:174)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:89)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:78)
	at com.taosdata.example.JdbcRestfulDemo.main(JdbcRestfulDemo.java:25)

**Comment by goldenzjy2023** [comment]
解决了

**Comment by gdman5566** [comment]
请问如何解决的呢
