### ISSUE TITLE
TD3.2.1版本下，跑官方测试RestInsertExample程序出现Connection refused异常，但是RESTConnectExample运行连接正常

### ISSUE THREAD

**Issue by luohao518** [taosdata/TDengine#23840]
官方提供的RESTConnectExample运行正常，跑RestInsertExample执行sql语句异常：

Connected to the target VM, address: '127.0.0.1:7707', transport: 'socket'
16:53:57.040 [main] INFO org.apache.http.impl.execchain.RetryExec -- I/O exception (org.apache.http.conn.HttpHostConnectException) caught when processing request to {}->http://td1:6041: Connect to td1:6041 [td1/172.18.9.155] failed: Connection refused: no further information
16:53:57.042 [main] INFO org.apache.http.impl.execchain.RetryExec -- Retrying request to {}->http://td1:6041
16:53:59.076 [main] INFO org.apache.http.impl.execchain.RetryExec -- I/O exception (org.apache.http.conn.HttpHostConnectException) caught when processing request to {}->http://td1:6041: Connect to td1:6041 [td1/172.18.9.155] failed: Connection refused: no further information
16:53:59.077 [main] INFO org.apache.http.impl.execchain.RetryExec -- Retrying request to {}->http://td1:6041
16:54:01.116 [main] INFO org.apache.http.impl.execchain.RetryExec -- I/O exception (org.apache.http.conn.HttpHostConnectException) caught when processing request to {}->http://td1:6041: Connect to td1:6041 [td1/172.18.9.155] failed: Connection refused: no further information
16:54:01.118 [main] INFO org.apache.http.impl.execchain.RetryExec -- Retrying request to {}->http://td1:6041
16:54:03.170 [main] INFO org.apache.http.impl.execchain.RetryExec -- I/O exception (org.apache.http.conn.HttpHostConnectException) caught when processing request to {}->http://td1:6041: Connect to td1:6041 [td1/172.18.9.155] failed: Connection refused: no further information
16:54:03.171 [main] INFO org.apache.http.impl.execchain.RetryExec -- Retrying request to {}->http://td1:6041
Exception in thread "main" java.sql.SQLException: ERROR (0x2318): Connect to td1:6041 [td1/172.18.9.155] failed: Connection refused: no further information
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:87)
	at com.taosdata.jdbc.utils.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:140)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:89)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:78)
	at com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:56)
	at com.haisum.td.test.RestInsertExample.insertData(RestInsertExample.java:65)
	at com.haisum.td.test.RestInsertExample.main(RestInsertExample.java:72)
Disconnected from the target VM, address: '127.0.0.1:7707', transport: 'socket'

环境:
 - OS: CentOS 7.0
 - TDengine Version 3.2.1
 - JDK17
 - 客户端驱动也是3.2.1，jdbc是3.2.7

**Comment by yu285** [comment]
>http://td1:6041/: Connect to td1:6041 [td1/172.18.9.155] failed: Connection refused: no further information

对这个地址+端口（td1:6041 ）发送 curl 信息能得到返回吗？

**Comment by cctse** [comment]
遇到两次拒绝服务的情况了，ws写入数据提示 
dial tcp 192.168.0.xxx:6041: connect: connection refused
持续好几个小时，重启服务后恢复正常。 ws拒绝服务时，其他程序用原生接口写入数据正常
