### ISSUE TITLE
tdengine查询过程中出现坐标越界的问题

### ISSUE THREAD

**Issue by wwding** [taosdata/TDengine#23983]
**Bug Description**

tdengine在查询的过程中出现下标越界的问题；

如果不分页就不会有这个问题，或者分页一次性查完也没有这个问题，尝试重启数据库，重新安装数据库，将数据导入，更改sql，即使是一个简单的sql：例如：select xx from table where device_no = xxx limit 10 问题依然存在。
 后面又经过两天，问题自动消失了；

然后发现一个新问题，数据查询时，如果排序就会有问题，依然报下标越界的问题，但是td的其他表，也使用了排序并没有出现问题，而且这个sql之前是没有问题的，猜测是不是和数据入库，或者后期表结构变更有关系
具体报错的sql如下：
分页：
### Cause: java.lang.IllegalArgumentException: newPosition > limit: (1074321995 > 2859)
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 92 common frames omitted
Caused by: java.lang.IllegalArgumentException: newPosition > limit: (1074321995 > 2859)
	at java.nio.Buffer.createPositionException(Buffer.java:269)
排序：
: 
"nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalArgumentException: newPosition > limit: (1311428 > 5228)",

如果查出原因的话请联系我，谢谢 

email：wwding_1024@163.com

**Comment by wwding** [comment]
以上问题，如果不分页就不会有问题

**Comment by yu285** [comment]
数据库版本/驱动版本号是？ 查询在服务端的shell 有问题吗

**Comment by wwding** [comment]
陈老师您好！
数据库版本号为：3.0.6.0

驱动版本号：
<taos-jdbcdriver-version>3.2.1</taos-jdbcdriver-version>
sql如果直接在dbaver,或者直接通过taos命令行执行，sql是没有问题的
| |
丁稳稳
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Yu ***@***.***> |
| 发送日期 | 2023年12月8日 11:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [taosdata/TDengine] tdengine查询过程中出现坐标越界的问题 (Issue #23983) |

数据库版本/驱动版本号是？ 查询在服务端的shell 有问题吗
