### ISSUE TITLE
Druid1.2.16 +TD3.0.7，com.alibaba.druid.sql.parser.ParserException 

### ISSUE THREAD

**Issue by TomatoLay** [taosdata/TDengine#24036]
springboot+集成 druid 没有使用多数据源，直接连接tdengine，虽然sql查询语句可以正常执行，但是druid会提示，druid高版本基本都试过，还是会出现该问题。
```
com.alibaba.druid.sql.parser.ParserException: not supported.pos 65, line 1, column 56, token IDENTIFIER smart_park
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:615) ~[druid-1.2.16.jar!/:na]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:101) ~[druid-1.2.16.jar!/:na]
        at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:365) [druid-1.2.16.jar!/:na]
        at com.alibaba.druid.sql.SQLUtils.format(SQLUtils.java:358) [druid-1.2.16.jar!/:na]
        at org.springblade.core.mp.plugins.SqlLogInterceptor.statement_close(SqlLogInterceptor.java:128) [blade-starter-mybatis-3.1.1.RELEASE.jar!/:na]
        at com.alibaba.druid.filter.FilterChainImpl.statement_close(FilterChainImpl.java:2887) [druid-1.2.16.jar!/:na]
        at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.close(StatementProxyImpl.java:128) [druid-1.2.16.jar!/:na]
        at com.alibaba.druid.pool.DruidPooledStatement.close(DruidPooledStatement.java:507) [druid-1.2.16.jar!/:na]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.closeInternal(DruidPooledPreparedStatement.java:195) [druid-1.2.16.jar!/:na]
        at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:190) [druid-1.2.16.jar!/:na]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:187) [druid-1.2.16.jar!/:na]
        at org.apache.ibatis.executor.BaseExecutor.closeStatement(BaseExecutor.java:283) [mybatis-3.5.10.jar!/:3.5.10]
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:52) [mybatis-3.5.10.jar!/:3.5.10]
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) [mybatis-3.5.10.jar!/:3.5.10]
        at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_371]
```

**Comment by Kiki513H** [comment]
我也想问这个问题  有方案解决拍我一下 谢谢

**Comment by xclwpd** [comment]
问题解决了吗？我也遇到了这个问题

**Comment by yu285** [comment]
> 问题解决了吗？我也遇到了这个问题

可以加微信远程排查一下 a15652223354
