### ISSUE TITLE
td新建索引服务拒绝链接

### ISSUE THREAD

**Issue by xnxz123** [taosdata/TDengine#24084]
在单节点或者三节点集群环境都出现了，用的镜像tdengine/tdengine:3.0.7.1，容器化部署1.0 vCpu2.0 GiB
create database if not exists log_server_test buffer 10 keep 30;
use log_server_test;

CREATE STABLE `device_log` 
(`ts` TIMESTAMP, `sceneName` VARCHAR(64), `type` VARCHAR(8), `content` VARCHAR(512), 
`index` VARCHAR(8), `recordType` VARCHAR(8),`avatar` varchar(1024),`deviceName`varchar(128),
`errorMsg` varchar(256),`virtualUserNickname`varchar(64),`env`varchar(32),`id`varchar(64),
`operatorId`varchar(64),`sceneId`varchar(64),`source`varchar(16),`elementId` VARCHAR(64), `userId` VARCHAR(64)
) 
TAGS (`iotId` VARCHAR(64));
在执行建索引语句时报错
CREATE INDEX device_log_iotid_idx ON log_server_test.device_log (iotId,elementId);
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [8984]: ERROR (0x2318): Connect to 192.168.79.56:6041 [/192.168.79.56] failed: Connection refused
 at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
 at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:607)
 at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:510)
 at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
 at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:517)
 at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:971)
 at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4134)
 at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
 at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
 at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
 at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5151)
 at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: ERROR (0x2318): Connect to 192.168.79.56:6041 [/192.168.79.56] failed: Connection refused
 at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:82)
 at com.taosdata.jdbc.utils.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:140)
 at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:89)
 at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:78)
 at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
 at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
 ... 12 more

**Comment by yu285** [comment]
检查下服务端有重启迹象吗？
