### ISSUE TITLE
 java.sql.SQLException: TDengine ERROR (80000216): syntax error near "select start_time, train_id from tf where st

### ISSUE THREAD

**Issue by auhjin** [taosdata/TDengine#24085]
**Bug Description**
通过pyspark访问Tdengine，出现如题错误 软件版本Spark2.4.0 pyspark 2.4.0 TDengine2.4.0.20 python3.7
taos-jdbcdriver-2.0.34.jar taos-jdbcdriver-2.0.40.jar
还尝试了TDengine 3.2.1.0 taos-jdbcdriver-3.2.1.jar , 如下错误，好像缺少什么方法
```
 java.lang.NoSuchMethodError: commitCallbackHandler
        at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
        at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:52)
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:138)
```
```python
# 获取历史故障数据（由TDengine中取出）
spark.read\
.format("jdbc")\
.option("url", conf.get("tdengine", "tdengine.url"))\
.option("driver", "com.taosdata.jdbc.TSDBDriver")\
.option("user", conf.get("tdengine", "tdengine.user"))\
.option("password", conf.get("tdengine", "tdengine.password"))\
.option("database", "pm242db")\
.option("dbtable", "select start_time, train_id from tf where status = 0 and space > 4")\
.load()\
.createOrReplaceTempView("fault_record_tdengine")
```
**Expected Behavior**

**Screenshots**
![image](https://github.com/taosdata/TDengine/assets/35133142/54d61919-e5aa-4392-b7e7-0b4e9de36673)

**Environment (please complete the following information):**
 - OS: CentOS 7.9
 - TDengine Version 2.4.0.20

**Additional Context**
现在通过Pyspark 连接mysql 和 Redis 都没有问题

**Comment by auhjin** [comment]
pyspark、 tdengine等所有组件都是通过docker容器进行运行；
tdengine容器的权限也有问题吗？ 好像还显示没有权限记录日志
![image](https://github.com/taosdata/TDengine/assets/35133142/970618db-4283-481c-b11d-4778502a6292)

**Comment by auhjin** [comment]
我找到问题了，SQL语句的使用方式写的不对

**Comment by auhjin** [comment]
我找到问题了，SQL语句的使用方式写的不对
