### ISSUE TITLE
taosd 3.2.0.0 启动core 掉

### ISSUE THREAD

**Issue by xuyinghao** [taosdata/TDengine#24186]
#0  0x00007fa366a19337 in raise () from /lib64/libc.so.6
#1  0x00007fa366a1ab68 in abort () from /lib64/libc.so.6
#2  0x00007fa366a12156 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fa366a12202 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000008d7c0e in taosAssertDebug (condition=false, file=0x9b2490 "/home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/common/src/tdataformat.c", line=2354, format=0x9b2474 "assert info not provided")
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/util/src/tlog.c:777
#5  0x000000000083b517 in tColDataGetValue (pColData=0x7fa33439cef0, iVal=12, pColVal=0x7fa3527fad60) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/common/src/tdataformat.c:2354
#6  0x00000000005678a3 in tBlockDataUpsertBlockRow (pBlockData=0x7fa3527fbcf8, pBlockDataFrom=0x7fa3527fb228, iRow=12, flag=0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbUtil.c:1307
#7  0x0000000000567e5f in tBlockDataAppendRow (pBlockData=0x7fa3527fbcf8, pRow=0x7fa3527fb1f0, pTSchema=0x0, uid=211115389305520154) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbUtil.c:1349
#8  0x0000000000548bda in tsdbCommitTableData (pCommitter=0x7fa3527fafe0, id=...) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:1543
#9  0x0000000000548fc2 in tsdbCommitFileDataImpl (pCommitter=0x7fa3527fafe0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:1611
#10 0x0000000000545f99 in tsdbCommitFileData (pCommitter=0x7fa3527fafe0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:807
#11 0x0000000000546658 in tsdbCommitData (pCommitter=0x7fa3527fafe0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:956
#12 0x00000000005439b9 in tsdbCommit (pTsdb=0x7fa34411fae0, pInfo=0x7fa250000a20) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:187
#13 0x000000000050742f in vnodeCommitImpl (pInfo=0x7fa250000a20) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/vnd/vnodeCommit.c:453
#14 0x0000000000506fd5 in vnodeCommitTask (arg=0x7fa250000a20) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/vnd/vnodeCommit.c:374
#15 0x000000000050aac5 in loop (arg=0x0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/vnd/vnodeModule.c:169
#16 0x00007fa3671c4e65 in start_thread () from /lib64/libpthread.so.0
#17 0x00007fa366ae188d in clone () from /lib64/libc.so.6

**Comment by ranchunfu** [comment]
### 背景：
三节点集群，版本为3.0.3.0，某个子节点突然挂了，服务起不起来，每次重启都出现core。
升级到3.2.2.0版本后，问题现象不变。
安装日志如下：
```
[root@kwepwebenv17493 robin]# sudo rpm -ivh TDengine-server-3.2.2.0-Linux-x64.rpm 
Preparing...                          ################################# [100%]
	file /usr/local/taos/bin/taos from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/bin/set_core.sh from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/bin/taosBenchmark from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/bin/taosadapter from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/bin/taosd from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/bin/udfd from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/cfg/taos.cfg from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/cfg/taosadapter.service from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/cfg/taosadapter.toml from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/driver/libtaosws.so from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/C#/taosdemo/README.md from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/C#/taosdemo/taosdemo.cs from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/JDBCDemo/README-jdbc-windows.md from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/JDBCDemo/pom.xml from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/mybatisplus-demo/pom.xml from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/taosdemo/pom.xml from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/JDBCDemo/readme.md from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/taosdemo/readme.md from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/JDBCDemo/src/main/java/com/taosdata/example/JdbcDemo.java from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/JDBCDemo/src/main/java/com/taosdata/example/JdbcRestfulDemo.java from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/JDBC/springbootdemo/src/main/resources/application.properties from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/c/CMakeLists.txt from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/c/demo.c from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/c/prepare.c from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/c/tmq.c from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/lua/OpenResty/rest/tdpool/init.lua from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/lua/OpenResty/rest/test.lua from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/lua/build.sh from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/lua/lua51/lua_connector51.c from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/lua/lua_connector.c from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/python/PYTHONConnectorChecker/__pycache__/PythonChecker.cpython-36.opt-1.pyc from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/python/PYTHONConnectorChecker/__pycache__/PythonChecker.cpython-36.pyc from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/python/__pycache__/read_example.cpython-36.opt-1.pyc from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/python/__pycache__/read_example.cpython-36.pyc from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/python/taosdemo/__pycache__/taosdemo.cpython-36.opt-1.pyc from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/python/taosdemo/__pycache__/taosdemo.cpython-36.pyc from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/examples/python/taosdemo/taosdemo.py from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/include/taos.h from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/include/taosdef.h from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/include/taoserror.h from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/include/taosudf.h from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/include/taosws.h from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/script/post.sh from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
	file /usr/local/taos/script/preun.sh from install of tdengine-3.2.2.0-3.el7.x86_64 conflicts with file from package tdengine-3.0.3.0-3.el7.x86_64
[root@kwepwebenv17493 robin]# 

```

### 定位过程：
用gdb查询core文件的堆栈信息，发现打印的堆栈信息还是用的3.0.3.0版本的代码，不是3.2.2.0的代码
```
[New LWP 12750]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/taosd'.
Program terminated with signal 6, Aborted.
#0  0x00007fe4d93b7337 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64
(gdb) bt
#0  0x00007fe4d93b7337 in raise () from /lib64/libc.so.6
#1  0x00007fe4d93b8b68 in abort () from /lib64/libc.so.6
#2  0x00007fe4d93b0156 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fe4d93b0202 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000008d7c0e in taosAssertDebug (condition=false, file=0x9b2490 "/home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/common/src/tdataformat.c", line=2354, format=0x9b2474 "assert info not provided")
    at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/util/src/tlog.c:777
#5  0x000000000083b517 in tColDataGetValue (pColData=0x7fe3e000d700, iVal=12, pColVal=0x7fe4c9fcfd60) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/common/src/tdataformat.c:2354
#6  0x00000000005678a3 in tBlockDataUpsertBlockRow (pBlockData=0x7fe4c9fd0cf8, pBlockDataFrom=0x7fe4c9fd0228, iRow=12, flag=0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbUtil.c:1307
#7  0x0000000000567e5f in tBlockDataAppendRow (pBlockData=0x7fe4c9fd0cf8, pRow=0x7fe4c9fd01f0, pTSchema=0x0, uid=211115389305520154) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbUtil.c:1349
#8  0x0000000000548bda in tsdbCommitTableData (pCommitter=0x7fe4c9fcffe0, id=...) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:1543
#9  0x0000000000548fc2 in tsdbCommitFileDataImpl (pCommitter=0x7fe4c9fcffe0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:1611
#10 0x0000000000545f99 in tsdbCommitFileData (pCommitter=0x7fe4c9fcffe0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:807
#11 0x0000000000546658 in tsdbCommitData (pCommitter=0x7fe4c9fcffe0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:956
#12 0x00000000005439b9 in tsdbCommit (pTsdb=0x7fe4b811fae0, pInfo=0x7fe3d8000a20) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/tsdb/tsdbCommit.c:187
#13 0x000000000050742f in vnodeCommitImpl (pInfo=0x7fe3d8000a20) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/vnd/vnodeCommit.c:453
#14 0x0000000000506fd5 in vnodeCommitTask (arg=0x7fe3d8000a20) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/vnd/vnodeCommit.c:374
#15 0x000000000050aac5 in loop (arg=0x0) at /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/dnode/vnode/src/vnd/vnodeModule.c:169
#16 0x00007fe4d9b62e65 in start_thread () from /lib64/libpthread.so.0
#17 0x00007fe4d947f88d in clone () from /lib64/libc.so.6
(gdb) 
```

### 求助
1、如何验证3.2.2.0安装成功？
2、该问题如何解决？
3、能否将问题节点的数据迁移到新节点，并正常查看？

**Comment by xuyinghao** [comment]
升级到 3.2.2.0 解决core 问题
