### ISSUE TITLE
JVM crashed by error "TDengine ERROR (8000010a): Ref is not there" 

### ISSUE THREAD

**Issue by lighkLife** [taosdata/TDengine#24338]
**Bug Description**
持续向 TDEngine 插入数据，偶尔会出现 JVM 崩溃的情况，报错日志如下：
```java
2024-01-04 01:48:00.208 ERROR 77887 -- [ffer-consumer-0] .c.c.i.h.c.s.s.i.TdEngineSendServiceImpl : 保存点位历史数据失败

java.sql.SQLException: TDengine ERROR (8000010a): Ref is not there
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
        at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119)
        at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:67)
        at com.chinawyny.custom.iot.hub.common.sender.service.impl.TdEngineSendServiceImpl.saveRtd(TdEngineSendServiceImpl.java:94)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.i(PointBuffer.java:96)
        at com.chinawyny.custom.iot.hub.common.utils.MethodUtils.tryRun(MethodUtils.java:15)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.g(PointBuffer.java:90)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.q(PointBuffer.java:73)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.s(PointBuffer.java:64)
        at java.lang.Thread.run(Thread.java:750)

2024-01-04 01:48:00.208 ERROR 77887 -- [ffer-consumer-0] .c.c.i.h.c.s.s.i.TdEngineSendServiceImpl : 保存点位历史数据失败

java.sql.SQLException: TDengine ERROR (8000010a): Ref is not there
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76)
        at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:119)
        at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:67)
        at com.chinawyny.custom.iot.hub.common.sender.service.impl.TdEngineSendServiceImpl.saveRtd(TdEngineSendServiceImpl.java:94)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.i(PointBuffer.java:96)
        at com.chinawyny.custom.iot.hub.common.utils.MethodUtils.tryRun(MethodUtils.java:15)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.g(PointBuffer.java:90)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.q(PointBuffer.java:73)
        at com.chinawyny.custom.iot.hub.common.sender.queue.PointBuffer.s(PointBuffer.java:64)
        at java.lang.Thread.run(Thread.java:750)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1f14000668, pid=77887, tid=0x00007f1f8a7f4700
#
# JRE version: OpenJDK Runtime Environment (8.0_392-b08) (build 1.8.0_392-392-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.392-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00007f1f14000668
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/local/jdk/app/digital_energy_web/hs_err_pid77887.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
panic: signal: aborted
```

**To Reproduce**
持续向数据库插入数据，速度： 30 条数据/秒

**Expected Behavior**
JVM 不要发生崩溃现象

**Screenshots**

**Environment (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
 - Kernel： Linux 3.10.0-957.el7.x86_64 #1 SMP Fri Jan 11 17:34:50 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
 - libc:glibc 2.17 NPTL 2.17
 - rlimit: STACK 8192k, CORE 0k, NPROC 125298, NOFILE 4096, AS infinity
 - load average:0.00 0.01 0.05
 - Memory: 32 GB
 - CPU: total 20 (initial active 20) (10 cores per cpu, 2 threads per core)
 - Current Disk Space: 
 - TDengine Server Version:  2.4.0.41
 - TDengine Client  Version:  2.4.0.41
 - TDengine JDBC  Version:  2.4.0.40
 - Java: OpenJDK 64-Bit Server VM (25.392-b08) for linux-amd64 JRE (1.8.0_392-392-b08)

**Additional Context**
[hs_err_pid149584.log](https://github.com/taosdata/TDengine/files/13827383/hs_err_pid149584.log)

**Comment by yu285** [comment]
2.x 已经不维护支持了。迁移到3.x 上吧，官网博客搜 “迁移”即可。
