### ISSUE TITLE
I/O exception (java.net.SocketTimeoutException) caught when processing request to

### ISSUE THREAD

**Issue by laisanshan** [taosdata/TDengine#24700]
我的数据是在超级表下分开各个普通表，在我select count(ts) from db.普通表时报连接超时的错误
I/O exception (java.net.SocketTimeoutException) caught when processing request to {}->http://xx.xx.xx.xx:36041: Read timed out
org.apache.http.impl.execchain.RetryExec | 113 | Retrying request to {}->http://xx.xx.xx.xx:36041
### Cause: java.sql.SQLException: ERROR (2318): Read timed out
; uncategorized SQLException; SQL state []; error code [8984]; ERROR (2318): Read timed out; nested exception is java.sql.SQLException: ERROR (2318): Read timed out
。。。
Caused by: java.sql.SQLException: ERROR (2318): Read timed out
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:72)
	at com.taosdata.jdbc.utils.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:129)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:65)
。。。
我的普通表大概有18435285条，超级表下大概有二三十个普通表
![image](https://github.com/taosdata/TDengine/assets/73273373/d2fb58b9-98e7-4cc2-9002-033b6df0b368)

这是在我的TDengineGUI里执行的语句是可以执行的，我查阅资料尝试改jdbc的连接超时时间和mybatis-plus的超时时间，没有效果。我的项目是用application.yml配置，把tdengine用mybatis-plus进行映射使用

如果你有相关思路或者解决办法，请帮助我  谢谢！

**Comment by yu285** [comment]
通过curl 发送sql 到6041 端口可以正常得到结果吗
