### ISSUE TITLE
Can not connected tdengine server when set `batchfetch` to `true`

### ISSUE THREAD

**Issue by zappa119** [taosdata/TDengine#25285]
Here is my tdengine env:
System: Windows
Platform: Docker
Tdengine Version: 3.2.3.0
JDBC Driver Version: 3.2.9

Description:
When i set `batchfetch` to `true`, i can not connnect the tdengine server and get the result
properties.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
<img width="1561" alt="image" src="https://github.com/taosdata/TDengine/assets/17660456/d488cdc0-d3ed-4160-a2b2-437ef45bcac7">

Here is the Exception:
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.sql.SQLException: ERROR (0x2318): java.util.concurrent.TimeoutException: ERROR (0x231e): failed to complete the task:{"action":"query","args":{"req_id":6203756545937768449,"sql":"select * from tmr_test.data_test limit 10"}} within the specified time : 60000,MILLISECONDS
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:87)
	at com.taosdata.jdbc.ws.Transport.send(Transport.java:91)
	at com.taosdata.jdbc.ws.WSStatement.execute(WSStatement.java:82)
	at com.taosdata.jdbc.ws.WSStatement.executeQuery(WSStatement.java:41)
	at com.taosdata.jdbc.ws.WSStatement.executeQuery(WSStatement.java:34)
	at org.test.tdengine.Test.main(Test.java:20)

but when i set `batchfetch` to `false` (seems default is false), i can connect the tdengine success and get the query result

<img width="1557" alt="image" src="https://github.com/taosdata/TDengine/assets/17660456/5c288efa-073f-4e2e-a58e-ff8d7c89a331">

Please help me, thanks.

**Comment by yu285** [comment]
we will check on this

**Comment by zappa119** [comment]
this issue has been resolved.
changed fastjson dependency, seems fastjson has conflict.
conflict fastjson dependency version: 2.0.46
worked fastjson dependency version: 1.2.83
Thanks.

**Comment by happywzy** [comment]
遇到了同样的问题，感谢~
