### ISSUE TITLE
Why does this error occur when I use DataX to copy TDengine data to HDFS

### ISSUE THREAD

**Issue by liyuan-hu** [taosdata/TDengine#25447]
024-04-23 11:08:19.244 [0-0-0-writer] INFO  HdfsWriter$Task - write to file : [hdfs://192.168.22.36:8020/origin_data/emei/db/current_avgco2_full__b3661017_f0dc_40f6_84a9_06e2f094c255/current_avgco2__d5c6d957_d91c_4226_b5a8_eb414720077d]
2024-04-23 11:08:19.585 [0-0-0-reader] ERROR TDengineReader$Task - TDengine ERROR (2350): sql: select * from power.current_avgco2_output_stb
java.sql.SQLException: TDengine ERROR (2350): sql: select * from power.current_avgco2_output_stb
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:76) ~[taos-jdbcdriver-2.0.39.jar:na]
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:69) ~[taos-jdbcdriver-2.0.39.jar:na]
	at com.taosdata.jdbc.rs.RestfulStatement.executeQuery(RestfulStatement.java:37) ~[taos-jdbcdriver-2.0.39.jar:na]
	at com.alibaba.datax.plugin.reader.TDengineReader$Task.startRead(TDengineReader.java:208) ~[tdenginereader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2024-04-23 11:08:19.803 [0-0-0-writer] INFO  HdfsWriter$Task - end do write
2024-04-23 11:08:19.816 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] taskId[0] is successed, used[606]ms
2024-04-23 11:08:19.816 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] completed it's tasks.
2024-04-23 11:08:29.201 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2024-04-23 11:08:29.201 [job-0] INFO  AbstractScheduler - Scheduler accomplished all tasks.
2024-04-23 11:08:29.201 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] do post work.
2024-04-23 11:08:29.201 [job-0] INFO  HdfsWriter$Job - start rename file [hdfs://192.168.22.36:8020/origin_data/emei/db/current_avgco2_full__b3661017_f0dc_40f6_84a9_06e2f094c255/current_avgco2__d5c6d957_d91c_4226_b5a8_eb414720077d] to file [hdfs://192.168.22.36:8020/origin_data/emei/db/current_avgco2_full/current_avgco2__d5c6d957_d91c_4226_b5a8_eb414720077d].
2024-04-23 11:08:29.203 [job-0] INFO  HdfsWriter$Job - 文件［hdfs://192.168.22.36:8020/origin_data/emei/db/current_avgco2_full__b3661017_f0dc_40f6_84a9_06e2f094c255/current_avgco2__d5c6d957_d91c_4226_b5a8_eb414720077d］内容为空,请检查写入是否正常！
2024-04-23 11:08:29.203 [job-0] INFO  HdfsWriter$Job - start delete tmp dir [hdfs://192.168.22.36:8020/origin_data/emei/db/current_avgco2_full__b3661017_f0dc_40f6_84a9_06e2f094c255] .
2024-04-23 11:08:29.209 [job-0] INFO  HdfsWriter$Job - finish delete tmp dir [hdfs://192.168.22.36:8020/origin_data/emei/db/current_avgco2_full__b3661017_f0dc_40f6_84a9_06e2f094c255] .
2024-04-23 11:08:29.209 [job-0] INFO  JobContainer - DataX Reader.Job [tdenginereader] do post work.
2024-04-23 11:08:29.210 [job-0] INFO  JobContainer - DataX jobId [0] completed successfully.

**Comment by yu285** [comment]
we don't support datax plugin
