### ISSUE TITLE
现在无法通过JDBC连接上数据库，会报异常，之前是可以的

### ISSUE THREAD

**Issue by ternormal** [taosdata/TDengine#25452]
会报com.alibaba.fastjson.JSONException: can not cast to JSONObject.
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:260)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:70)
	at com.taosdata.jdbc.rs.RestfulDriver.connect(RestfulDriver.java:150)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	... 2 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.alibaba.fastjson.JSONObject
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:258)
	... 6 more

使用的依赖
<dependency>
	<groupId>com.taosdata.jdbc</groupId>
	<artifactId>taos-jdbcdriver</artifactId>
	
	<version>2.0.42</version>
</dependency>

**Comment by yu285** [comment]
2.x 版本目前官方已经不维护支持了，请迁移升级到最新的 3.x 版本吧。操作手册为：https://www.taosdata.com/tdengine-engineering/17753.html。3.x 和 2.x 相比是全方位更加优越的，关于3.x 的主要特性可以结合这篇文章和官方文档一起了解：https://www.taosdata.com/tdengine-engineering/21550.html
