### ISSUE TITLE
supertable creation fails with batchfetch=true but succeeds without this parameter

### ISSUE THREAD

**Issue by jsk970** [taosdata/TDengine#25603]
使用JdbcTemplate创建超级表。
代码片段：
 PreparedStatementSetter preparedStatementSetter = ps ->{
            ps.setString(1,superTableName);
        };
        jdbcTemplate.update(sql.toString(), preparedStatementSetter);

![image](https://github.com/taosdata/TDengine/assets/27145361/5928c111-2b07-462b-a04c-ffbb0b129362)

预编译sql:
CREATE STABLE IF NOT EXISTS ? (ts timestamp,int_v int,float_v float,double_v double,bool_v bool,binary_v binary(1024),extend_json nchar(4000)) tags (device_uuid binary(1024))

版本信息：
服务版本：[tdengine/tdengine:3.2.3.0]
驱动版本：taos-jdbcdriver 3.2.10

异常信息：
Caused by: java.sql.SQLException: (0x2600):syntax error near "? (ts timestamp,int_v int,float_v float,double_v double,bool_v bool,binary_v binary(1024),extend_json nchar(4000)) tags (device_uuid binary(1024))"
	at com.taosdata.jdbc.ws.TSWSPreparedStatement.executeUpdate(TSWSPreparedStatement.java:224)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3201)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1091)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeUpdate(FilterEventAdapter.java:491)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3199)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeUpdate(PreparedStatementProxyImpl.java:194)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:256)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:867)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 44 more

**Comment by jsk970** [comment]
![image](https://github.com/taosdata/TDengine/assets/27145361/8ce78bf3-5e0c-4fe1-820f-690b464d1fec)

**Comment by jsk970** [comment]
针对动态参数表名创建超级表 目前 异常报错 (0x22a):Stmt API usage error
![image](https://github.com/taosdata/TDengine/assets/27145361/bb8d37d0-fe44-4f69-ad1f-2631ad442492)

**Comment by yu285** [comment]
收到，我们看下

**Comment by sheyanjie-qq** [comment]
创建超级表不支持参数绑定，参数绑定只支持写入和查询。
