### ISSUE TITLE
windows下连接远程Linux的taos数据库错误

### ISSUE THREAD

**Issue by Luozde** [taosdata/TDengine#265]
您好，我在windows下的Java连接远程的Linux数据库遇到下面这个错误 Error: invalid time stamp
在windows cmd上连接远程数据库也同样遇到这个错误Error: invalid time stamp，请问该怎么处理？

---------------windows10 cmd命令行下连接远程Linux数据库错误----------------------------
c:\TDengine>taos -h 192.168.182.128
TSDB error: invalid time stamp

---------------windows10 Java连接远程Linux数据库错误--------------------------------------
java.sql.SQLException: TDengine Error: invalid time stamp
at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:96)
at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
at com.taosdata.jdbc.TSDBConnection.(TSDBConnection.java:56)
at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:208)
at TestTDengine.App.getConn(App.java:39)
at TestTDengine.App.main(App.java:20)
option file:/etc/taos/taos.cfg not found, all options are set to system default

**Comment by hzcheng** [comment]
您好，您server端的时间和您client的时间差是不是大于15分钟？

**Comment by Luozde** [comment]
嗯嗯，是的刚刚发现了，服务端的时间用的是美东时区的，同步与客户端的时区和时间就正常了，谢谢啦
