### ISSUE TITLE
node.js客户端启动报错

### ISSUE THREAD

**Issue by zqx1993** [taosdata/TDengine#267]
系统：macos
python：2.7.10
Command Line Tools: ![image](https://user-images.githubusercontent.com/12184327/62384971-56527380-b586-11e9-8d5c-bb693eacc9a3.png)

报错内容如下:
/Users/zqx/idco/iot_data_engine/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: dlopen(libtaos.dylib, 2): image not found
    at new DynamicLibrary (/Users/zqx/idco/iot_data_engine/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/zqx/idco/iot_data_engine/node_modules/ffi/lib/library.js:45:12)
    at new CTaosInterface (/Users/zqx/idco/iot_data_engine/node_modules/td-connector/nodetaos/cinterface.js:182:22)
    at TDengineConnection._configConn (/Users/zqx/idco/iot_data_engine/node_modules/td-connector/nodetaos/connection.js:52:19)
    at new TDengineConnection (/Users/zqx/idco/iot_data_engine/node_modules/td-connector/nodetaos/connection.js:25:8)
    at Object.module.exports.connect (/Users/zqx/idco/iot_data_engine/node_modules/td-connector/tdengine.js:3:10)
    at TDengineManager.connect (/Users/zqx/idco/iot_data_engine/src/library/td_engine/index.js:9:21)
    at Object.<anonymous> (/Users/zqx/idco/iot_data_engine/test/td_test.js:2:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

**Comment by StoneT2000** [comment]
您的node js version 是什么？
npm show ffi 显示的 version 是什么？

**Comment by StoneT2000** [comment]
我们目前不支持MacOS的客户端

**Comment by sexbee** [comment]
@StoneT2000  意思是：目前即使从nodejs连接也要在linux系统下？

**Comment by StoneT2000** [comment]
对，连接器需要libtaos的library，我们目前不支持macos compatible 的 libtaos library

**Comment by xinqiyang** [comment]
这个大概啥时候可以解决吗？

**Comment by sangshuduo** [comment]
@xinqiyang 目前 develop 分支已经支持了 Mac OS X 的编译，还没有作为正式版本发布，不排除有什么 bug，欢迎自己编译测试

**Comment by studyinhub** [comment]
这个不应该，现在用 macOS 的挺多的
