### ISSUE TITLE
When connecting to TDengine and publishing to the server to query the STable by C#, the aggregate function will report an error

### ISSUE THREAD

**Issue by shaoyingfei** [taosdata/TDengine#2720]
TDEngine Version 1.6.5.7
c#通过Maikebing.Data.Taos，发布到Windows Server 2012 R2服务器IIS，查询超级表时，使用聚合函数会报错。本地调试是正常的，错误信息是 var code = TDengine.Query(_taos, _commandText); code结果为86，不为0

**Comment by maikebing** [comment]
https://github.com/taosdata/TDengine/blob/ver-1.6.5.7/src/inc/taoserror.h#L107

**Comment by maikebing** [comment]
这个应该是查询时生成临时文件失败报的错误，统一报成了86，具体还得提供下日志和查询语句来看看

**Comment by maikebing** [comment]
![image](https://user-images.githubusercontent.com/3445167/87913944-7e422c00-caa2-11ea-9f77-3227f3d4950f.png)

**Comment by shaoyingfei** [comment]
查询语句：select AVG(Value) as Value from chemicalfactory.tagpoint where tagName='TE_110' and realDate >= '2020-06-21 00:47:06' and realDate <='2020-07-21 00:47:06' interval(10M);
错误信息：System.ArgumentNullException: Value cannot be null.
Parameter name: dataReader
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   at System.Data.DataTable.Load(IDataReader reader)
   at Maikebing.Data.Taos.DataReaderExtensions.ToDataTable(IDataReader reader) in E:\项目\化工安全\FactoryDemo\src\Maikebing.Data.Taos\DataReaderExtensions.cs:line 97
   at DemoFrame_Dao.TDEngine.TDEngineHelper.getData(String strSql) in E:\项目\化工安全\FactoryDemo\DemoFrame_Dao\TDEngine\TDEngineHelper.cs:line 247
