### ISSUE TITLE
使用websocket参数绑定写入,批量最大为32767,>=2的15次方报错 (0x118):Invalid parameters

### ISSUE THREAD

**Issue by gukun00** [taosdata/TDengine#27588]
**描述**
使用websocket参数绑定写入,批量最大为32767,>=2的15次方报错 (0x118):Invalid parameters

**复现**
使用官方WSParameterBindingFullDemo示例，numOfRow=32768

`
Failed to insert to table meters using stmt, url: jdbc:TAOS-RS://127.0.0.1:6041/?batchfetch=true; ErrCode:0; ErrMessage: (0x118):Invalid parameters
Exception in thread "main" java.sql.SQLException: (0x118):Invalid parameters
	at com.taosdata.jdbc.ws.TSWSPreparedStatement.executeBatch(TSWSPreparedStatement.java:704)
	at com.gukun.springboot.tdengine.demo.mybatis.service.demo.WSParameterBindingFullDemo.bindInteger(WSParameterBindingFullDemo.java:83)
	at com.gukun.springboot.tdengine.demo.mybatis.service.demo.WSParameterBindingFullDemo.main(WSParameterBindingFullDemo.java:29)
`

**问题**
websocket是否有条数限制，文档是否有遗漏，或者有什么参数配置可以控制这个批量写入条数

**Comment by gukun00** [comment]
控制websocket批量条数为：32767，及正常运行

**Comment by yu285** [comment]
单个sql ， 最大长度为1m ,文档有提及。
