### ISSUE TITLE
正常使用taos数据库过程中 taos突然无法启动或者需要向github进行连接 但是taosd服务正常

### ISSUE THREAD

**Issue by lh61500** [taosdata/TDengine#27810]
**Bug Description**
使用taos数据库的过程中 突然无法使用 键入taos 提示需要键入后续指令 无法进入shell 
而过了一阵以后 键入taos 提示需要github连接失败

**To Reproduce**
不知道为什么 昨天还用的好好的 突然就进不去了

**Expected Behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/910723d9-3799-4ec0-8c57-b7261f8fad07)

**Environment (please complete the following information):**
 - OS:ubuntun20
 - Memory, CPU, current Disk Space
 - TDengine Version latest

**Additional Context**
taos
Traceback (most recent call last):
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/home/likang/miniconda3/environments/question/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /taosdevops/dev-ops-now-bios/tree/master/team-members (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/likang/.local/bin/taos", line 5, in <module>
    from taos.cli import main
  File "/home/likang/.local/lib/python3.12/site-packages/taos/cli.py", line 40, in <module>
    @click.argument("user", type=click.Choice(bio.list_persons()))
                                              ^^^^^^^^^^^^^^^^^^
  File "/home/likang/.local/lib/python3.12/site-packages/taos/bio.py", line 19, in list_persons
    return _get_from_gh()
           ^^^^^^^^^^^^^^
  File "/home/likang/.local/lib/python3.12/site-packages/taos/bio.py", line 13, in _get_from_gh
    response = requests.get(url, headers={'User-Agent': config.USER_AGENT})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/likang/miniconda3/environments/question/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /taosdevops/dev-ops-now-bios/tree/master/team-members (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))

**Comment by lh61500** [comment]
已经解决 是安装的taos不是一个东西 先卸载taos 然后运行这里的/usr/local/taos/bin/taos才可以打开taos
