### ISSUE TITLE
DB error: Table schema is old

### ISSUE THREAD

**Issue by charlist8324** [taosdata/TDengine#28846]
**Environment (please complete the following information):**
 - OS: [ CentOS 6.9]
 - TDengine Version [3.3.3.0]

无模式写入一个超级表，运行一段时间发现，使用order by 关键字会报 ：DB error: Table schema is old，
去掉order by 关键字正常查询，如下图：
![1](https://github.com/user-attachments/assets/fdea2a44-ecca-489a-9af7-16c6ca471f19)
去掉order by正常，如下图：
![2](https://github.com/user-attachments/assets/9eea5440-c6e6-4879-8eb1-f3939846bdaa)

**Comment by charlist8324** [comment]
dbeaver查询报错：
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [1563]: TDengine ERROR (0x61b): sql: select * from crystal_db.`AlarmRecord` order by _ts desc limit 100, desc: Table schema is old
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:607)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:510)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:517)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:971)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4135)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5151)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: TDengine ERROR (0x61b): sql: select * from crystal_db.`AlarmRecord` order by _ts desc limit 100, desc: Table schema is old
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:86)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:100)
	at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:78)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

**Comment by yu285** [comment]
可以加微信a15652223354 做具体排查
