### ISSUE TITLE
connection creation failed相关问题咨询

### ISSUE THREAD

**Issue by yuozhu** [taosdata/TDengine#29267]
客户使用tdengine数据库时连接失败

Log文件：
[2024-12-21 14:47:26.011] [error] [ExceptionsHandler] [error] connection creation failed, url: ws://root:taosdata@localhost:6041/ws TDWebSocketClientError: connection creation failed, url: ws://root:taosdata@localhost:6041/ws
    at WsClient.connect (D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\addons\connectors\connectors_tdengine\node_modules\@tdengine\websocket\lib\src\client\wsClient.js:47:20)
    at async WsSql.open (D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\addons\connectors\connectors_tdengine\node_modules\@tdengine\websocket\lib\src\sql\wsSql.js:30:13)
    at async sqlConnect (D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\addons\connectors\connectors_tdengine\node_modules\@tdengine\websocket\lib\src\index.js:33:16)
    at async T.connect (D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\addons\connectors\connectors_tdengine\index.js:1:4007)
    at async T.getCatalogs (D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\addons\connectors\connectors_tdengine\index.js:1:4110)
    at async h.getCatalogs (D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\addons\connectors\connectors_tdengine\index.js:1:1155)
    at async D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\resources\app.asar\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at async D:\byz\toolInstall\shanhaijing_4_4_1_Install\CetusView\resources\app.asar\node_modules\@nestjs\core\router\router-proxy.js:9:17
    
    
![070b247e86667a37a9b50f0f7a95dbef](https://github.com/user-attachments/assets/272b5037-2c94-4782-84ce-0667fd1b8ffa)

 
账户密码使用的是初始的，且客户告知原本在dbeaver里是能连上的
 
 
![lQLPJxCSpB6fAxnNAfjNA2Cw-LOiwFLLoccHQAM4xfsRAA_864_504](https://github.com/user-attachments/assets/e3a4d0b9-53b1-4067-b524-bd1d83990b86)

**Comment by SolitaryCheng** [comment]
你是否使用的 Bun.sh 并通过 Docker 部署的 TDengine？我也遇到了类似的问题：

```
45 |             throw (new wsError_1.WebSocketQueryError(result.msg.code, result.msg.message));
46 |         }
47 |         catch (e) {
48 |             console.error(e);
49 |             log_1.default.error(e.code, e.message);
50 |             throw (new wsError_1.TDWebSocketClientError(wsError_1.ErrorCode.ERR_WEBSOCKET_CONNECTION_FAIL, `connection creation failed, url: ${this._url}`));
                                      ^
TDWebSocketClientError: connection creation failed, url: ws://root:custom_pwd@localhost:6041/ws
 code: "104"

      at /Users/cheng/Development/crypto/cheng-trade-agent/node_modules/@tdengine/websocket/lib/src/client/wsClient.js:50:34
      at processTicksAndRejections (native:7:39)
```

在 Docker 容器的日志中排查，发现：

```
2024-12-24 02:35:53 12/23 18:35:53.423486 00000035 WEB ERROR 
2024-12-24 02:35:53 
2024-12-24 02:35:53 2024/12/23 18:35:53 [Recovery] 2024/12/23 - 18:35:53 panic recovered:
2024-12-24 02:35:53 GET /ws HTTP/1.1
2024-12-24 02:35:53 Host: localhost:6041
2024-12-24 02:35:53 Accept: */*
2024-12-24 02:35:53 Connection: keep-alive
2024-12-24 02:35:53 Sec-Websocket-Key: E5Hgcfp5QdM4pF8h+dru/A==
2024-12-24 02:35:53 Sec-Websocket-Version: 13
2024-12-24 02:35:53 Upgrade: websocket
2024-12-24 02:35:53 User-Agent: Bun/1.1.32
2024-12-24 02:35:53 
2024-12-24 02:35:53 
2024-12-24 02:35:53 websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2024-12-24 02:35:53 /mnt/workspace/main/TDinternal/community/tools/taosadapter/controller/ws/ws/ws.go:28 (0xb29a07)
2024-12-24 02:35:53 /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0x9619f3)
2024-12-24 02:35:53 /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/recovery.go:101 (0x9619d4)
2024-12-24 02:35:53 /mnt/workspace/main/TDinternal/community/tools/taosadapter/log/web.go:52 (0x971a3b)
```

我先尝试修改 @tdengine/websocket 中的 wsConnector，给 w3cwebsocket 设置正确的 header：

```
            this._wsConn = new websocket_1.w3cwebsocket(
                origin.concat(pathname).concat(search), // url
                undefined,                              // protocols
                undefined,                              // origin
               { 'Connection':'Upgrade' },    // headers
                undefined,                              // requestOptions
                { maxReceivedFrameSize: 0x60000000, maxReceivedMessageSize: 0x60000000 }
            );
```

但我发现实际发出的请求 header 仍然是 `Connection: keep-alive`。
于是我开始尝试通过 Nginx 反向代理解决该问题：

```
server {
    listen 16041;
    listen [::]:16041;
    server_name localhost;
    
    location /ws {
        # 强制设置为 WebSocket 请求
        set $upgrade_header "websocket";
        set $connection_header "Upgrade";

        # 无论客户端请求头如何，都强制使用这些值
        proxy_http_version 1.1;
        proxy_set_header Upgrade $upgrade_header;
        proxy_set_header Connection $connection_header;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin $scheme://$host;
        
        proxy_pass http://localhost:6041;
    }
}
```

并设置：`TDENGINE_WS_URL=ws://localhost:16041`。
程序发起连接后，Docker 日志并无报错，但客户端仍然会报错 `connection creation failed`。
通过 debug 后发现错误来自于 wsEventCallback：

```
29 |         try {
30 |             WsEventCallback._msgActionRegister.set(id, {
31 |                 sendTime: new Date().getTime(),
32 |                 reject: rej,
33 |                 resolve: res,
34 |                 timer: setTimeout(() => rej(new wsError_1.WebSocketQueryError(wsError_1.ErrorCode.ERR_WEBSOCKET_QUERY_TIMEOUT, `action:${id.action},req_id:${id.req_id} timeout with ${id.timeout} milliseconds = =`)), id.timeout)
                                                 ^
WebSocketQueryError: action:websocket_connection,req_id:2385892146675713 timeout with 5000 milliseconds = =
 code: "105"

      at /Users/cheng/Development/crypto/cheng-trade-agent/node_modules/@tdengine/websocket/lib/src/client/wsEventCallback.js:34:45
```

同时发现 wsConnector 的 `this._wsConn.readyState` 的值会很快从 0 变为 3。
尝试很多方法无果后，我开始替换 wsConnector 中的 w3cwebsocket 方法，遂成功。
以下是相关代码：

```
- const websocket_1 = require("websocket");
+ const websocket_1 = require("ws");

-          this._wsConn = new websocket_1.w3cwebsocket(
-              origin.concat(pathname).concat(search), // url
-              undefined,                              // protocols
-              undefined,                              // origin
-              undefined,                              // headers
-              undefined,                              // requestOptions
-              { maxReceivedFrameSize: 0x60000000, maxReceivedMessageSize: 0x60000000 }
-          );
+          this._wsConn = new websocket_1.WebSocket(
+              origin.concat(pathname).concat(search), // url
+              { maxPayload: 0x60000000 }
+          );
```
