### ISSUE TITLE
JDBC connection issue

### ISSUE THREAD

**Issue by nana0518** [taosdata/TDengine#2961]
**General Questions**
在阿里服务器上装了2.0.0.0版本的服务，能正常启动并且可以taos进去命令行。在windows环境下，启动springboot的demo程序连接服务器上的taos服务，报出连接失败的问题
在resources目录下放置了libtaos.so.2.0.0.0文件，并且在pom.xml中也做了配置，指向该so文件。

请大家指教！

**Comment by xiaopingcs** [comment]
我们2.0window客户端还没有发布，所以会连接失败。2.0 windows 客户端发版可能需要2到3周时间。

**Comment by nana0518** [comment]
> 我们2.0window客户端还没有发布，所以会连接失败。2.0 windows 客户端发版可能需要2到3周时间。

前提：已通过taos命令进入命令行，并创建bill的数据库。
问题：放在安装有2.0.0.0版本的服务器上运行，java -jar springbootdemo-0.0.1-SNAPSHOT.jar 执行jar，启动报错，java.sql.SQLException: TDengine Error: invalid num of fields!，日志如下：

java.library.path:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2020-08-07 09:56:57.022 ERROR 22918 --- [           main] com.alibaba.druid.pool.DruidDataSource   : init datasource error, url: jdbc:TAOS://101.132.177.238:6030/bill

java.sql.SQLException: TDengine Error: invalid num of fields!
        at com.taosdata.jdbc.TSDBResultSet.<init>(TSDBResultSet.java:106) ~[taos-jdbcdriver-2.0.0.jar!/:na]
        at com.taosdata.jdbc.TSDBStatement.executeQuery(TSDBStatement.java:66) ~[taos-jdbcdriver-2.0.0.jar!/:na]
        at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1408) ~[druid-1.1.17.jar!/:1.1.17]
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1672) ~[druid-1.1.17.jar!/:1.1.17]
