### ISSUE TITLE
query by JDBC, java.sql.SQLException: this operation is NOT supported currently

### ISSUE THREAD

**Issue by 18378333917** [taosdata/TDengine#3047]
jdbc结合mybatis进行普通的查询，查询语句：`select    ts, len, reqid,msg,method,deviceid,productid from device_record     where deviceid = ? and ts > ? and ts < ? and reqid = ?`
taos-jdbcdriver版本为2.0.2
异常信息：
`Caused by: java.sql.SQLException: this operation is NOT supported currently!
        at com.taosdata.jdbc.TSDBStatement.getMoreResults(TSDBStatement.java:188) ~[taos-jdbcdriver-2.0.2.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.getMoreResults(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:na]
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:241) ~[mybatis-3.5.3.jar!/:3.5.3]
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:187) ~[mybatis-3.5.3.jar!/:3.5.3]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65) ~[mybatis-3.5.3.jar!/:3.5.3]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.5.3.jar!/:3.5.3]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63) ~[mybatis-3.5.3.jar!/:3.5.3]
        at com.sun.proxy.$Proxy95.query(Unknown Source) ~[na:na]
        at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67) ~[mybatis-plus-core-3.3.1.jar!/:3.3.1]
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.5.3.jar!/:3.5.3]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.3.jar!/:3.5.3]
        at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:163) ~[mybatis-plus-core-3.3.1.jar!/:3.3.1]
        at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:90) ~[mybatis-plus-core-3.3.1.jar!/:3.3.1]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) ~[mybatis-3.5.3.jar!/:3.5.3]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.3.jar!/:3.5.3]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76) ~[mybatis-3.5.3.jar!/:3.5.3]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.3.jar!/:2.0.3]
        ... 21 common frames omitted`

**Comment by zhiyuYang90** [comment]
这个问题是我们最近在改的一个bug，mybatis+taos-jdbcdirver-2.0.2+TDengine2.0会报错，后面会更新jdbc的版本

**Comment by amen943** [comment]
> 这个问题是我们最近在改的一个bug，mybatis+taos-jdbcdirver-2.0.2+TDengine2.0会报错，后面会更新jdbc的版本。mybatis+taos-jdbcdirver-1.0.3+TDengine1.6.6.1这个可以

我用soringboot+mybaits 插入报错：
### Cause: java.sql.SQLException: TDengine Error: Unexpected generic error in RPC
; uncategorized SQLException; SQL state []; error code [-2147483636]; TDengine Error: Unexpected generic error in RPC; nested exception is java.sql.SQLException: TDengine Error: Unexpected generic error in RPC

**Comment by zyyang-taosdata** [comment]
我们修复了这个bug，请使用taos-jdbcdriver-2.0.3版本。
maven添加taos-jdbcdriver-2.0.3的依赖：
```xml
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.3</version>
</dependency>
```

**Comment by amen943** [comment]
> 我们修复了这个bug，请使用taos-jdbcdriver-2.0.3版本。
> maven添加taos-jdbcdriver-2.0.3的依赖：
> 
> ```
> <dependency>
>             <groupId>com.taosdata.jdbc</groupId>
>             <artifactId>taos-jdbcdriver</artifactId>
>             <version>2.0.3</version>
> </dependency>
> ```

thank u. it work!!!
