### ISSUE TITLE
我已经获取到链接了，执行不了SQL语句，是哪里配置有问题吗

### ISSUE THREAD

**Issue by kingLi88** [taosdata/TDengine#316]
提示内容：
com.taosdata.jdbc.TSDBConnection@7382f612
com.taosdata.jdbc.TSDBStatement@67f89fa3
java.sql.SQLException: TDengine Error: failed to connect to server
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:131)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:57)
	at com.zp.TD.main(TD.java:33)

**Comment by guanshengliang** [comment]
是windows平台还是linux平台?
