### ISSUE TITLE
windows10,nodejs10 error

### ISSUE THREAD

**Issue by lsjt96263** [taosdata/TDengine#3323]
PS D:\taos> node
> const taos = require('td2.0-connector');
undefined
> var conn = taos.connect({host:"192.168.117.144", user:"root", password:"taosdata", config:"/etc/taos",port:6030});
Thrown:
Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (D:\taos\node_modules\ffi\lib\dynamic_library.js:74:11)
    at Object.Library (D:\taos\node_modules\ffi\lib\library.js:45:12)
    at new CTaosInterface (D:\taos\node_modules\td2.0-connector\nodetaos\cinterface.js:200:22)
    at TDengineConnection._configConn (D:\taos\node_modules\td2.0-connector\nodetaos\connection.js:52:19)
    at new TDengineConnection (D:\taos\node_modules\td2.0-connector\nodetaos\connection.js:25:8)
    at Object.module.exports.connect (D:\taos\node_modules\td2.0-connector\tdengine.js:3:10)
>

**Environment (please complete the following information):**
 - OS: windows 10 
 - TDengine Version 2.0
nodejs -- "td2.0-connector@2.0.1",
has install TDengine-client-2.0.2.1-Windows-x64

**Comment by xiaopingcs** [comment]
我们暂时还不支持在windows环境下的nodejs和go的connector
