### ISSUE TITLE
Two problems with Flink when storing

### ISSUE THREAD

**Issue by leyoucoder** [taosdata/TDengine#3345]
**Bug Description**
taos集群和flink集群同为6台，taos版本2.0.2.1，flink版本1.7.1.flink任务启动时报错：
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector
                   at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:133)
                   at java.sql.DriverManager.getConnection(DriverManager.java:664)
                   at java.sql.DriverManager.getConnection(DriverManager.java:208)
                   。。。。。。
多启动几次，报错信息会换成另一个：
Caused by: java.lang.UnsatisfiedLinkError: Native Library /usr/local/taos/driver/libtaos.so.2.0.2.1 already loaded in another classloader
                   at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
                   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
                   at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                   at java.lang.System.loadLibrary(System.java:1122)
最开始的时候，我们的解决方案是把taos集群对应的libtao.so文件放入flink项目的resource目录下，数据存储成功，但是这个错误仍会时不时出现。但是换成java单体项目测试存储taos，则没有任何问题

**Comment by zyyang-taosdata** [comment]
在应用开发时，确保com.taosdata.jdbc.TSDBDriver只进行了一次加载和初始化。
