### ISSUE TITLE
python3.7+flask import失败问题

### ISSUE THREAD

**Issue by txeagle** [taosdata/TDengine#337]
第一次这样执行，没问题的
(flaskapi37) [root@localhost ~]$>python
Python 3.7.3 (default, Jun  4 2019, 23:18:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taos
>>> 

然后我执行一下 python run.py 报错了
(flaskapi37) [root@localhost flaskapi]$>python run.py 
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from app.resources.RaspStatus import RaspStatus
  File "/root/www/flaskapi/app/resources/RaspStatus.py", line 5, in <module>
    from Taos import Taos
  File "/root/www/flaskapi/Taos.py", line 14, in <module>
    import taos
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/__init__.py", line 2, in <module>
    from .connection import TDengineConnection
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/connection.py", line 2, in <module>
    from .cursor import TDengineCursor
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/cursor.py", line 1, in <module>
    from .cinterface import CTaosInterface
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/cinterface.py", line 137, in <module>
    class CTaosInterface(object):
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/cinterface.py", line 139, in CTaosInterface
    libtaos = ctypes.CDLL('libtaos.so')
  File "/usr/local/python3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtaos.so: cannot open shared object file: No such file or directory

我再去尝试第一次的命令，也会报错
(flaskapi37) [root@localhost flaskapi]$>python
Python 3.7.3 (default, Jun  4 2019, 23:18:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/__init__.py", line 2, in <module>
    from .connection import TDengineConnection
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/connection.py", line 2, in <module>
    from .cursor import TDengineCursor
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/cursor.py", line 1, in <module>
    from .cinterface import CTaosInterface
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/cinterface.py", line 137, in <module>
    class CTaosInterface(object):
  File "/root/pythonvenv/flaskapi37/lib/python3.7/site-packages/taos/cinterface.py", line 139, in CTaosInterface
    libtaos = ctypes.CDLL('libtaos.so')
  File "/usr/local/python3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtaos.so: cannot open shared object file: No such file or directory

![图片](https://user-images.githubusercontent.com/19180021/62912904-90a8e580-bdbc-11e9-9ca5-b1f09eb3131d.png)
![图片](https://user-images.githubusercontent.com/19180021/62912919-a4544c00-bdbc-11e9-8fb2-475ef69ffc7c.png)

**Comment by txeagle** [comment]
补充一下，退出shell，重新连接，又可以执行下面这句了
[root@localhost ~]$>source pythonvenv/flaskapi37/bin/activate
(flaskapi37) [root@localhost ~]$>python
Python 3.7.3 (default, Jun  4 2019, 23:18:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taos
>>>

**Comment by fangpanpan** [comment]
所以您现在可以import成功，不会出现找不到"libtaos.so"的错误了？

**Comment by txeagle** [comment]
还是会报错，不过情况跟刚才又有一点不一样

重新打开shell，执行python import taos或者python run.py没问题了
但是一旦执行uwsgi --ini uwsgi.ini，就会报这个错误
OSError: libtaos.so: cannot open shared object file: No such file or directory

而且一旦执行uwsgi --ini uwsgi.ini报错，再去执行python import taos或者python run.py也会报错

**Comment by txeagle** [comment]
所以应该算两个部分的问题：
1、uwsgi --ini uwsgi.ini会报错
2、uwsgi --ini uwsgi.ini报错后，会连带导致python import taos或者python run.py也报错

**Comment by fangpanpan** [comment]
也就是说用uwsgi --ini uwsgi.ini 启动项目后就会报错，不知道您uwsgi.ini里的配置是如何设的？

**Comment by txeagle** [comment]
问题暂时解决了，不能用python3.7.3，换成python3.6.8可以了

不过对这个问题还是有些费解，uwsgi --ini uwsgi.ini报错后，会连带导致python import taos或者python run.py也报错，必须退出shell并重新登录

**Comment by treemp3** [comment]
python3.6.8需要执行cp /usr/lib/libtaos.so /usr/lib64/
