### ISSUE TITLE
nodejs connector run error with td ver 2.0.3 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#3397]
node V10.X

td2.0-connector installed 

node node-example.js happen error ,log as below, 

.............................

   at TDengineCursor.execute (/root/www/node-conn/node_modules/td2.0-connector/nodetaos/cursor.js:142:11)
    at /root/www/node-conn/node_modules/td2.0-connector/nodetaos/taosquery.js:40:25
    at new Promise (<anonymous>)
    at TaosQuery.execute (/root/www/node-conn/node_modules/td2.0-connector/nodetaos/taosquery.js:35:26)
    at Object.<anonymous> (/root/www/node-conn/node-example.js:89:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:23376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2001)
(node:23376) UnhandledPromiseRejectionWarning: TDError.DatabaseError.ProgrammingError: invalid SQL: syntax error near " note!"");" () expected)
    at TDengineCursor.execute (/root/www/node-conn/node_modules/td2.0-connector/nodetaos/cursor.js:142:11)
    at /root/www/node-conn/node_modules/td2.0-connector/nodetaos/taosquery.js:40:25
    at new Promise (<anonymous>)
    at TaosQuery.execute (/root/www/node-conn/node_modules/td2.0-connector/nodetaos/taosquery.js:35:26)
    at Object.<anonymous> (/root/www/node-conn/node-example.js:89:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:23376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2002)
**(node:23376) UnhandledPromiseRejectionWarning: TDError.DatabaseError.ProgrammingError: invalid SQL: syntax error near " note!"");" () expected)**
    at TDengineCursor.execute (/root/www/node-conn/node_modules/td2.0-connector/nodetaos/cursor.js:142:11)
    at /root/www/node-conn/node_modules/td2.0-connector/nodetaos/taosquery.js:40:25
    at new Promise (<anonymous>)
    at TaosQuery.execute (/root/www/node-conn/node_modules/td2.0-connector/nodetaos/taosquery.js:35:26)
    at Object.<anonymous> (/root/www/node-conn/node-example.js:89:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:23376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2003)

**Comment by liu0x54** [comment]
Hi, which node-example.js are you running, seems different with the one in github.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/56432938/92319713-cebf1a00-f04d-11ea-8f92-f67b8c7ea299.png">
In which the line 89 is not calling taosquery.
You can paste the source code of node-example.js here

**Comment by sytpb** [comment]
/usr/local/taos/examples/nodejs             node-example.js
![image](https://user-images.githubusercontent.com/12178686/92319897-b4863b80-f04f-11ea-9270-cccf58f51285.png)

**Comment by liu0x54** [comment]
maybe there are some mistake in the packing scripts. You can try the one in the TDengine/tests/examples/nodejs/

**Comment by sytpb** [comment]
yes , it is ok  ,  i use the new code from github .  thanks a lot .
