### ISSUE TITLE
error while running  Bind with query ... 

### ISSUE THREAD

**Issue by sytpb** [taosdata/TDengine#3462]
some code from node-example.js 

const taos = require('td2.0-connector');
 var conn1 = taos.connect({host:"127.0.0.1", user:"root", password:"taosdata", config:"/etc/taos",port:0})
 var cursor = conn1.cursor(); // Initializing a new cursor

    var query = cursor .query('insert into db.weather values(?, ?, ?, ?, ?);').bind(insertData);
    query.execute();

Maybe , it is not bug , i am not sure ... 

##logs  as below ,,, 
Successfully connected to TDengine
Query OK, 1 row(s) affected (0.00110770s)
Unhandled Rejection at: Promise Promise {
  <rejected> { TDError.DatabaseError.OperationalError: Invalid use of fetchall, either result or fields from query are null. First execute a query first
      at TDengineCursor.fetchall (/root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/cursor.js:176:11)
      at /root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/taosquery.js:42:71
      at new Promise (<anonymous>)
      at TaosQuery.execute (/root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/taosquery.js:35:26)
      at Object.<anonymous> (/root/www/wxExpress/react-backend/comm/tst.js:28:8)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3) name: 'TDError.DatabaseError.OperationalError' } } reason: { TDError.DatabaseError.OperationalError: Invalid use of fetchall, either result or fields from query are null. First execute a query first
    at TDengineCursor.fetchall (/root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/cursor.js:176:11)
    at /root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/taosquery.js:42:71
    at new Promise (<anonymous>)
    at TaosQuery.execute (/root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/taosquery.js:35:26)
    at Object.<anonymous> (/root/www/wxExpress/react-backend/comm/tst.js:28:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) name: 'TDError.DatabaseError.OperationalError' }

**Comment by sytpb** [comment]
I found that data have been inserted in DB , ...

**Comment by localvar** [comment]
please replace `query` with `execute` and try again.

**Comment by sytpb** [comment]
show me as follow with execute... 

TDError.DatabaseError.ProgrammingError: invalid SQL: unrecognized token: "? and cargo_qty = ?;"
at TDengineCursor.execute (/root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/cursor.js:142:11)

**Comment by sytpb** [comment]
another case SQL is Select   using execute 
![image](https://user-images.githubusercontent.com/12178686/92705493-55456580-f386-11ea-9e87-6504ad3644b5.png)

error as follow , 

oot/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/cursor.js:142
    throw new errors.ProgrammingError(this._chandle.errStr(this._result))
    ^
TDError.DatabaseError.ProgrammingError: invalid SQL: unrecognized token: "? and cargo_qty = ?;"
    at TDengineCursor.execute (/root/www/wxExpress/react-backend/node_modules/td2.0-connector/nodetaos/cursor.js:142:11)

**Comment by zyyang-taosdata** [comment]
execute('XXX').bind() is not supported for td2.0.X, please use like this:
execute('insert into db.weather ....');

**Comment by sytpb** [comment]
> execute('XXX').bind() is not supported for td2.0.X, please use like this:
> execute('insert into db.weather ....');

but ,the data have been inserted in DB ....

**Comment by zyyang-taosdata** [comment]
if you can use execute() without bind, please use execute(). we will check the nodejs connector later.

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
