### ISSUE TITLE
TDengine Error: Invalid client version

### ISSUE THREAD

**Issue by zhuhedong** [taosdata/TDengine#3464]
用你们spring boot demo 无法链接到数据库
Caused by: java.sql.SQLException: TDengine Error: Invalid client version
 at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:100) ~[taos-jdbcdriver-2.0.4.jar:na]
 at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64) ~[taos-jdbcdriver-2.0.4.jar:na]
 at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56) ~[taos-jdbcdriver-2.0.4.jar:na]
 at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135) ~[taos-jdbcdriver-2.0.4.jar:na]
 at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1596) ~[druid-1.1.17.jar:1.1.17]
 at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1662) ~[druid-1.1.17.jar:1.1.17]
 at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:932) ~[druid-1.1.17.jar:1.1.17]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1929) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1871) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]

docker 安装的 版本是tdengine/tdengine:2.0.0.0

**Comment by bbbisou** [comment]
lz你解决了吗？

**Comment by Sunyao-work** [comment]
@zhuhedong 这个问题如何解决啊？我当前用C#类库和java的jar包都访问报Invalid client version

**Comment by Kittoa** [comment]
同问
