### ISSUE TITLE
java.sql.SQLException: TDengine Error: failed to create subscription

### ISSUE THREAD

**Issue by Flyerison** [taosdata/TDengine#3506]
server: centos7.6 docker tdengine2.0.3.0
client: JDBC2.0.4 windows
客户端订阅数据发生错误，显示SQL异常，但命令行运行没问题
connection = DriverManager.getConnection(url + "?user=" + username + "&password=" + password, properties);
String rawSql = "select * from " + table（mq_iot_device）;
subscribe = ((TSDBConnection) connection).subscribe(topic, rawSql, false);
java.sql.SQLException: TDengine Error: failed to create subscription
	at com.taosdata.jdbc.TSDBConnection.subscribe(TSDBConnection.java:94)
	at com.iot.config.TDMQScribeConfig$TDengineMQConsumer.run(TDMQScribeConfig.java:121)
	at java.lang.Thread.run(Thread.java:745)
其中关键的日志应该是下面几句：
09/14 03:23:16.941325 0x7f639ffed700 RPC SHELL new TCP connection from 172.16.11.138:59768, fd:27 FD:0x7f6390000900 numOfFds:2
09/14 03:23:16.941345 0x7f63a07ee700 RPC TCP malloc mem: 0x7f63840008c0
09/14 03:23:16.941355 0x7f63a07ee700 MND user:root, auth info is returned
09/14 03:23:16.941359 0x7f63a07ee700 RPC SHELL 0x27d42a0 server connection is allocated, uid:0x24c4b263
09/14 03:23:16.941366 0x7f63a07ee700 RPC SHELL 0x27d42a0 0x882ba0, table-meta received from 0x8a0b10ac:59768, parse code:0x0 len:323 sig:0x02000000:0x00000000:18468 code:0x0
**09/14 03:23:16.941382 0x7f63c4ff9700 DND 0x882ba0, msg:table-meta will be processed in mread queue
09/14 03:23:16.941386 0x7f63c4ff9700 MND app:0x882ba0:0x7f6384000dd0, table:0.iot.mq_iot_device, table meta msg is received from thandle:0x27d42a0, createFlag:0
09/14 03:23:16.941405 0x7f63c4ff9700 RPC malloc mem: 0x7f63bc35c5e0
09/14 03:23:16.941421 0x7f63c4ff9700 MND app:0x882ba0:0x7f6384000dd0, table:0.iot.mq_iot_device, uid:3298534948883 table meta is retrieved
09/14 03:23:16.941436 0x7f63c4ff9700 RPC SHELL 0x27d42a0 0x882ba0, table-meta-rsp is sent to 0x8a0b10ac:59768, code:0x0 len:1141 sig:0x38000000:0x02000000:18468**
09/14 03:23:16.941504 0x7f63c4ff9700 RPC free mem: 0x7f63840008c0
09/14 03:23:16.942278 0x7f63cddf0700 RPC SHELL 0x27d2830 0x7f63880064e0, close the connection since no activity
09/14 03:23:16.942294 0x7f63cddf0700 RPC SHELL 0x27d2830 TCP connection will be closed, FD:0x7f63900008c0
0
哪位大佬帮忙看下
另外提一嘴就是官方数据订阅示例运行时会直接导致docker TDengine关闭~~但上面运行的没事，只会报错

**Comment by sangshuduo** [comment]
代码可以贴的再完整一些吗？

**Comment by Flyerison** [comment]
```
public void run() {
    try {
        String host = “xxx”;
        Class.forName("com.taosdata.jdbc.TSDBDriver");
        Properties properties = new Properties();
        properties.setProperty(TSDBDriver.PROPERTY_KEY_HOST, host);
        connection = DriverManager.getConnection(url + "?user=" + username + "&password=" + password, properties);
        String rawSql = "select * from " + table;
        subscribe = ((TSDBConnection) connection).subscribe(topic, rawSql, false);
        while (true) {
            try {
                // 休息100millis 缓解服务端压力
                Thread.sleep(100);
                TSDBResultSet resultSet = subscribe.consume();
                if (resultSet == null) {
                    continue;
                }
                // 返回结果的处理逻辑
                handler(resultSet);
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (OperationsException e) {
                e.printStackTrace();
            }
        }
    } catch (ClassNotFoundException | SQLException e) {
        e.printStackTrace();
    } finally {
        try {
            if (null != subscribe)
                subscribe.close(true); // 关闭订阅
            if (connection != null)
                connection.close();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }
}
```
都是按照文档来的，关键代码就几行，错误发生在subscribe = ((TSDBConnection) connection).subscribe(topic, rawSql, false);

**Comment by sangshuduo** [comment]
host 或者 table 里有指定 db 吗？

**Comment by zyyang-taosdata** [comment]
请检查jdbcUrl中是否指定了默认数据库，jdbc:TAOS://<hostname>:<port>/<defaultDBName>,如果没有指定默认的dbname，请在sql语句中指定库名，例如：select * from dbName.tbName where ...如果仍然报错，请提供更多报错的信息。

**Comment by Flyerison** [comment]
得，我直接写个demo贴出来
`import com.taosdata.jdbc.TSDBConnection;
import com.taosdata.jdbc.TSDBDriver;
import com.taosdata.jdbc.TSDBResultSet;
import com.taosdata.jdbc.TSDBSubscribe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Properties;
import java.util.concurrent.TimeUnit;

public class SubscribeDemo {
    private static final String topic = "mq_iot_device9999";
    private static final String sql = "select * from mq_iot_device;";
    public static void main(String[] args) {
        Connection connection = null;
        TSDBSubscribe subscribe = null;
        try {
            Class.forName("com.taosdata.jdbc.TSDBDriver");
            Properties properties = new Properties();
            properties.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
            properties.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
            String jdbcUrl = "jdbc:TAOS://tdengine.aiot.com:6030/iot?user=root&password=taosdata";
            connection = DriverManager.getConnection(jdbcUrl, properties);
            subscribe = ((TSDBConnection) connection).subscribe(topic, sql, true); // 创建订阅
            int count = 0;
            while (count < 10) {
                TimeUnit.SECONDS.sleep(1); // 等待1秒，避免频繁调用 consume，给服务端造成压力
                TSDBResultSet resultSet = subscribe.consume(); // 消费数据
                if (resultSet == null) {
                    continue;
                }
                ResultSetMetaData metaData = resultSet.getMetaData();
                while (resultSet.next()) {
                    int columnCount = metaData.getColumnCount();
                    for (int i = 1; i <= columnCount; i++) {
                        System.out.print(metaData.getColumnLabel(i) + ": " + resultSet.getString(i) + "\t");
                    }
                    System.out.println();
                    count++;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (null != subscribe)
                    subscribe.close(true); // 关闭订阅
                if (connection != null)
                    connection.close();
            } catch (SQLException throwables) {
                throwables.printStackTrace();
            }
        }
    }
}`
指定了，log日志也出现了DB名称 table:0.iot.mq_iot_device，iot是database，mq_iot_device是表，至于这个0什么鬼？SQL里写DB也试过了，一样
![image](https://user-images.githubusercontent.com/28044926/93157055-0ad43800-f73c-11ea-8c71-0813979ac92e.png)
报错信息就这些了，还要什么报错信息麻烦具体说下，ε=(´ο｀*)))唉

**Comment by zyyang-taosdata** [comment]
我验证了你的测试用例，是可以正常运行订阅的。在select语句前面指定一下库名
select * from iot.mq_iot_device
避免你在创建订阅的时候使用了不正确的库名。

**Comment by Flyerison** [comment]
emmmmm，是TDengine2.0.3的FQDN环境问题。。。。
