### ISSUE TITLE
通过java程序插入2个亿条记录后中断，再启动执行异常

### ISSUE THREAD

**Issue by Luozde** [taosdata/TDengine#351]
您好，我通过springboot插入2个亿左右的数据后中断程序，再启动时java程序时，执行sql时报错，保持如下：
```
java.sql.SQLException: TDengine Error: others
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:131)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:57)
	at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:113)
	at com.luozd.tdengine.consumer1.Consumer1Application.testInsert(Consumer1Application.java:53)
	at com.luozd.tdengine.consumer1.Consumer1Application.run(Consumer1Application.java:34)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:764)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203)
	at com.luozd.tdengine.consumer1.Consumer1Application.main(Consumer1Application.java:28)
```
在客户端插入也是报TDengine Error: others
如果将这些数据插入新表中又正常了

**Comment by hzcheng** [comment]
您可以查看下/var/log/taos文件夹下的服务端日志中的ERROR信息
```
grep ERROR /var/log/taos/taosdlog*
```
把输出结果贴下看下把
