### ISSUE TITLE
about druid connection

### ISSUE THREAD

**Issue by ZhangJiaLei123** [taosdata/TDengine#3636]
我尝试使用druid连接池进行连接(并不是springboot项目), 但是连接
提示异常:
``` java
java.sql.SQLException: connect error, url jdbc:TAOS://192.168.0.11:6030, driverClass com.taosdata.jdbc.TSDBDriver
```
官方提供的demo也是运行错误:
``` java 
java.sql.SQLException: No suitable driver found for jdbc:TAOS://192.168.0.11:6030/?user=root&password=taosdata
```

**Comment by zyyang-taosdata** [comment]
如果你使用的是tdengine-2.0.X.X版本的，尝试使用taos-jdbcdriver-2.0.6.jar，JdbcUrl：jdbc:TAOS://192.168.0.11:6030/log?user=root&password=taosdata

**Comment by ZhangJiaLei123** [comment]
谢谢您的回复!
在使用您建议的方法后,我的测试任然报错。
我服务器使用的环境如下:
``` xml
Server: TDengine-server-2.0.3.1-Linux-x64
Windows10: taos-jdbcdriver-2.0.6.jar
```
服务器（防火墙已关闭）数据库类表如下： 
``` xml 
taos> show databases;
              name              |      created_time       |   ntables   |   vgroups   | replica | quorum |  days  |    keep1,keep2,keep(D)     |  cache(MB)  |   blocks    |   minrows   |   maxrows   | wallevel |    fsync    | comp | precision |    status    |
===================================================================================================================================================================================================================================================================
 log                            | 2020-09-22 14:27:21.173 |           4 |           1 |       1 |      1 |     10 | 30,30,30                   |           1 |           3 |         100 |        4096 |        1 |        3000 |    2 | us        | ready        |
 farm_iot                       | 2020-09-22 16:51:33.728 |           1 |           1 |       1 |      1 |      2 | 3650,3650,3650             |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        | ready        |
 db                             | 2020-09-23 09:54:28.496 |           2 |           1 |       1 |      1 |      2 | 3650,3650,3650             |          16 |           6 |         100 |        4096 |        1 |        3000 |    2 | ms        | ready        |
Query OK, 3 row(s) in set (0.000821s)

```
运行官方的JDBCDemo结果如下:
``` xml 
---------------------------------------------------------------
Start testing...
---------------------------------------------------------------

JDBC URL to use:
jdbc:TAOS://192.168.0.11:6030/log?user=root&password=taosdata

---------------------------------------------------------------
开始创建数据库和表...
java.sql.SQLException: TDengine Error: Unable to establish connection
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:135)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:98)
	at com.blxt.tdengine.TSDBSyncSample.doCreateDbAndTable(TSDBSyncSample.java:91)
	at com.blxt.tdengine.TSDBSyncSample.main(TSDBSyncSample.java:47)
```

**Comment by zyyang-taosdata** [comment]
从你的描述我看到，你是在windows环境下用TSDBSyncSample的代码去访问TDengine实例，请做如下检查：
1. 在你的windows10开发机器上，C:\TDengine目录下执行命令行工具taos.exe -h 192.168.0.11
2. 如果在windows的client端，无法连接到server端的taosd实例，请参考官网的文档，配置fqdn
FAQ：
[官网FAQ](https://www.taosdata.com/cn/documentation/faq/)

**Comment by liangyuanpeng** [comment]
问题解决了吗 @ZhangJiaLei123

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
