### ISSUE TITLE
Index out of bounds when using idea to explore database

### ISSUE THREAD

**Issue by lonelyleaf** [taosdata/TDengine#3638]
**Bug Description**
When using idea to explore taos after connected,idea report `java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0`

**To Reproduce**
1. use idea's database feature and inpormt `taos-jdbcdriver-2.0.6.jar` as driver
2. refresh database 
3. get the error

**Expected Behavior**
I have two database and have uesd `taosdemo` to generate data,so I shoud see to database and there table,but I got
none of them.
![db](https://user-images.githubusercontent.com/9879800/93885637-f6350880-fd16-11ea-98d8-271f8766e0a7.png)

**Idea's log output**
```
2020-09-22 20:52:18,911 [ 276189]   INFO - atabaseCredentialsAuthProvider - Connecting as: root 
2020-09-22 20:52:18,911 [ 276189]   INFO - .DatabaseConnectionEstablisher - Connecting to: jdbc:TAOS://192.168.2.58:6030/log 
2020-09-22 20:52:38,130 [ 295408]   INFO - ution.rmi.RemoteProcessSupport - G:\JetBrain\apps\IDEA-U\ch-0\202.7319.50\jbr\bin\java -Djava.rmi.server.hostname=127.0.0.1 -Duser.timezone=UTC -Xmx1258m -Xms128m -Dfile.encoding=UTF-8 -classpath G:\JetBrain\apps\IDEA-U\ch-0\202.7319.50\lib\util.jar;G:\JetBrain\apps\IDEA-U\ch-0\202.7319.50\lib\trove4j.jar;G:\JetBrain\apps\IDEA-U\ch-0\202.7319.50\lib\groovy-2.5.11.jar;G:\JetBrain\apps\IDEA-U\ch-0\202.7319.50\plugins\DatabaseTools\lib\jdbc-console.jar;H:\taos-jdbcdriver-2.0.6.jar com.intellij.database.remote.RemoteJdbcServer com.taosdata.jdbc.TSDBDriver 
2020-09-22 20:52:38,497 [ 295775]   INFO - ution.rmi.RemoteProcessSupport - Port/ID: 43813/RemoteDriverImpl3517cfb3 
2020-09-22 20:52:38,528 [ 295806]   INFO - atabaseCredentialsAuthProvider - Connecting as: root 
2020-09-22 20:52:38,528 [ 295806]   INFO - .DatabaseConnectionEstablisher - Connecting to: jdbc:TAOS://192.168.2.58:6030/log 
2020-09-22 20:52:38,566 [ 295844]   INFO - ution.rmi.RemoteProcessSupport - java.library.path:G:\JetBrain\apps\IDEA-U\ch-0\202.7319.50\jbr\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;D:\Program Files (x86)\VMware\VMware Workstation\bin\;D:\Program Files\vnstudio\Scripts;D:\Program Files\vnstudio\;C:\Python\Python38\Scripts\;C:\Python\Python38\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Python\Python38-32\Scripts\;C:\Python\Python38-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Go\bin;C:\Java\jdk-11.0.1\bin;C:\maven-3.5.3\bin;C:\gradle-6.2.1\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;D:\New Folder\]System32;C:\Program Files\nodejs\;C:\Users\49990\AppData\Local\Microsoft\WindowsApps;C:\Users\49990\go\bin;C:\Users\49990\AppData\Local\Yarn\bin;C:\Users\49990\AppData\Roaming\npm;. 
2020-09-22 20:52:38,619 [ 295897]   INFO - ution.rmi.RemoteProcessSupport - Driver: com.taosdata.jdbc.TSDBDriver 1.0.0 
2020-09-22 20:52:38,621 [ 295899]   INFO - ution.rmi.RemoteProcessSupport - getDatabaseProductName: TAOS 
2020-09-22 20:52:38,621 [ 295899]   INFO - ution.rmi.RemoteProcessSupport - getDatabaseMajorVersion.getDatabaseMinorVersion: 0.0 
2020-09-22 20:52:38,621 [ 295899]   INFO - ution.rmi.RemoteProcessSupport - Detected: TAOS 0.0 
2020-09-22 20:52:38,719 [ 295997]   INFO - ution.rmi.RemoteProcessSupport - Terminating: 43813/RemoteDriverImpl3517cfb3 
2020-09-22 20:52:38,743 [ 296021]   INFO - ution.rmi.RemoteProcessSupport - Process finished with exit code -1 
2020-09-22 20:52:39,784 [ 297062]   INFO - ution.rmi.RemoteProcessSupport - Terminating: 30329/RemoteDriverImpl2453e8ff 
2020-09-22 20:52:39,805 [ 297083]   INFO - ution.rmi.RemoteProcessSupport - Process finished with exit code -1 
2020-09-22 20:52:53,371 [ 310649]   WARN - ic.GenericDatabaseErrorHandler - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.set(ArrayList.java:473)
	at com.taosdata.jdbc.TSDBResultSetRowData.setString(TSDBResultSetRowData.java:168)
	at com.taosdata.jdbc.TSDBDatabaseMetaData.getTableTypes(TSDBDatabaseMetaData.java:576)
	at com.intellij.database.remote.jdbc.impl.RemoteDatabaseMetaDataImpl.getTableTypes(RemoteDatabaseMetaDataImpl.java:749)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
	at com.sun.proxy.$Proxy153.getTableTypes(Unknown Source)
	at com.intellij.database.dialects.base.introspector.jdbc.wrappers.DatabaseMetaDataWrapper.lambda$getAllTableTypes$30(DatabaseMetaDataWrapper.java:780)
	at com.intellij.database.remote.jdbc.helpers.JdbcNativeUtil.computeRemote(JdbcNativeUtil.java:95)
	at com.intellij.database.dialects.base.introspector.jdbc.wrappers.DatabaseMetaDataWrapper.getAllTableTypes(DatabaseMetaDataWrapper.java:780)
	at com.intellij.database.dialects.base.introspector.jdbc.JdbcIntrospector.introspectSchemas(JdbcIntrospector.java:254)
	at com.intellij.database.dialects.base.introspector.jdbc.JdbcIntrospector.lambda$introspectAuto$0(JdbcIntrospector.java:226)
	at com.intellij.database.model.BaseModel.modify(BaseModel.java:127)
	at com.intellij.database.model.BaseModel.modify(BaseModel.java:110)
	at com.intellij.database.model.BaseModel.modify(BaseModel.java:96)
	at com.intellij.database.model.BaseModel.modify(BaseModel.java:91)
	at com.intellij.database.dialects.base.introspector.jdbc.JdbcIntrospector.introspectAuto(JdbcIntrospector.java:220)
	at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession$IntrospectionProcessor.processDatabases(DatabaseModelLoader.java:270)
	at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.lambda$introspect$1(DatabaseModelLoader.java:324)
	at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.withFacade(DatabaseModelLoader.java:570)
	at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.lambda$introspect$2(DatabaseModelLoader.java:312)
	at com.intellij.database.dataSource.DataSourceSyncManager.lambda$static$0(DataSourceSyncManager.java:51)
	at com.intellij.database.console.session.SessionsUtil$function$1.invoke(SessionsUtil.kt:20)
	at com.intellij.database.console.session.DatabaseSessionManager$Facade.compute(DatabaseSessionManager.kt:338)
	at com.intellij.database.console.session.DatabaseSessionManager$Facade.runSync(DatabaseSessionManager.kt:273)
	at com.intellij.database.dataSource.DataSourceSyncManager.lambda$static$1(DataSourceSyncManager.java:49)
	at com.intellij.database.dataSource.DataSourceSyncManager$SyncProcessor$1.perform(DataSourceSyncManager.java:306)
	at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.introspect(DatabaseModelLoader.java:312)
	at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.lambda$run$0(DatabaseModelLoader.java:200)
	at com.intellij.database.dataSource.LocalDataSource.performBatch(LocalDataSource.java:1333)
	at com.intellij.database.dataSource.DatabaseModelLoader$IntrospectionSession.run(DatabaseModelLoader.java:198)
	at com.intellij.database.dataSource.DataSourceSyncManager$SyncProcessor.performSync(DataSourceSyncManager.java:308)
	at com.intellij.database.util.AsyncTask$Frame$compute$$inlined$supply$1$1.run(AsyncTask.kt:486)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.database.util.AsyncTask$Frame$compute$$inlined$supply$1.get(AsyncTask.kt:515)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.database.dataSource.AsyncUtil.underProgress(AsyncUtil.java:180)
	at com.intellij.database.dataSource.AsyncUtil.lambda$asyncFriendlyExecutor$1(AsyncUtil.java:56)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Screenshots**
![index-out-of-bound](https://user-images.githubusercontent.com/9879800/93885155-6d1dd180-fd16-11ea-88bb-3a39f592421f.png)

**Environment (please complete the following information):**
 - OS: client:windwos10  server:ubuntu18
 - Memory:4g, CPU:2core, current Disk Space:30G
 - TDengine Version  server:2.0.3.1 jdbc:2.0.6

**Comment by zyyang-taosdata** [comment]
This problem is caused by JDBC returning an empty result set when IDEA tries to retrieve database metadata, and we are working on this issue.
这个问题是因为IDEA在试图获取database的metadata时，jdbc返回了空的结果集引起的，我们正在解决这个问题。

**Comment by zsy-cn** [comment]
我也遇到了同样的问题，使用taos-jdbcdriver-2.0.8连接数据库，错误依然存在
环境：
- 服务端：Centos7  、 TDengine-server-2.0.6.0-Linux-x64.rpm (4.2M)
- 客户端：Windows10 、 TDengine-client-2.0.6.0-Windows-x64.exe 、 taos-jdbcdriver-2.0.8
```
16:18	Connected

16:18	taos
			Index 0 out of bounds for length 0.
```

**Comment by zyyang-taosdata** [comment]
> 我也遇到了同样的问题，使用taos-jdbcdriver-2.0.8连接数据库，错误依然存在
> 环境：
> 
> * 服务端：Centos7  、 TDengine-server-2.0.6.0-Linux-x64.rpm (4.2M)
> * 客户端：Windows10 、 TDengine-client-2.0.6.0-Windows-x64.exe 、 taos-jdbcdriver-2.0.8
> * 客户端软件：DataGrip
> 
> ```
> 16:18	Connected
> 
> 16:18	taos
> 			Index 0 out of bounds for length 0.
> ```

好的，我会检查这个问题

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
