### ISSUE TITLE
TAOSD crashed when subscribing data from server after super table been dropped.

### ISSUE THREAD

**Issue by codering** [taosdata/TDengine#3768]
**Bug Description**
在mac上通过docker运行的tdengine, 按照官网文档上写的用java客户端订阅. （顺便请关注下这个问题：#3732 ）
![image](https://user-images.githubusercontent.com/2271825/95537120-7483f100-0a1f-11eb-8b82-9c2d188e065b.png)

当把订阅的超级表删除后，按截图代码逻辑会一直重试订阅。
出现好几次订阅错误后，整个server crash(docker实例exit)，客户端就连接不上了，然后我的应用也会crash.

```
java.sql.SQLException: TDengine Error: invalid resultset pointer!
        at com.taosdata.jdbc.TSDBResultSet.next(TSDBResultSet.java:129)
...
java.sql.SQLException: TDengine Error: invalid resultset pointer!
        at com.taosdata.jdbc.TSDBResultSet.next(TSDBResultSet.java:129)
...
java.sql.SQLException: TDengine Error: invalid resultset pointer!
        at com.taosdata.jdbc.TSDBResultSet.next(TSDBResultSet.java:129)
...
java.sql.SQLTransientConnectionException: tdengine-hikari - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)


```
**Environment (please complete the following information):**
 - OS: 官方docker镜像
 - Memory, CPU, current Disk Space
 - TDengine Version：2.0.4.0
- TDengine client Version:  taos-jdbcdriver-2.0.7

**Additional Context**
顺便说下:
- 后面尝试了订阅一个不存在的超级表，就肯定会导致server crash
- 如果我停掉server,  我的整个应用也会crash.....
- 我觉得订阅失败或者连接失败，不应该把我的整个应用搞crash。。。

**Comment by codering** [comment]
吐槽下：玩了一周，发现tdengine对开发者接入一点都不友好！！！

这都开源1年了吧。。。我发现大量issue都停留在如何跑起来或者如果如何连接server的问题，就算跑起来了也会有什么内存，CPU居高不下的问题。完全达不到开箱即用的程度，开发者前期投入的时间成本太多了。

**Comment by hjxilinx** [comment]
TDengine 还是一个新的项目，我们也在尽力让 TDengine 更易用、好用。
您的发现的问题，我们会尽快处理。感谢您的支持！

**Comment by localvar** [comment]
这个问题已经修复，代码已合并至 develop 分支，会包含在下一个发布版本中，我先将问题关闭，后续如果还有问题，您可以重新打开或创建新问题。
