### ISSUE TITLE
Go client can't connect to server

### ISSUE THREAD

**Issue by Linuxlovers** [taosdata/TDengine#3787]
依赖 docker run -d --hostname="mytest" --name tdengine -p 6030-6042:6030-6042  tdengine/tdengine:latest
镜像使用https://www.taosdata.com/blog/2020/08/03/1509.html
fqdn https://www.taosdata.com/blog/2020/09/08/1816.html
v2.0.3，DB error: Unable to resolve FQDN when client connect to server in docker. · Issue #3427 · taosdata/TDengine
https://github.com/taosdata/TDengine/issues/3427

https://github.com/taosdata/TDengine/issues/1565  docker连接问题

https://github.com/taosdata/TDengine/issues/3427

#### go

```go
package main

import (
	"database/sql"
	"flag"
	"fmt"
	_ "github.com/taosdata/driver-go/taosSql"
	"math/rand"
	"os"
	"runtime"
	"strconv"
	"sync"
	"time"
	//"golang.org/x/sys/unix"
)

const (
	maxLocationSize = 32
	maxSqlBufSize   = 65480
)

var locations = [maxLocationSize]string{
	"Beijing", "Shanghai", "Guangzhou", "Shenzhen",
	"HangZhou", "Tianjin", "Wuhan", "Changsha",
	"Nanjing", "Xian"}

type config struct {
	hostName             string
	serverPort           int
	user                 string
	password             string
	dbName               string
	supTblName           string
	tablePrefix          string
	numOftables          int
	numOfRecordsPerTable int
	numOfRecordsPerReq   int
	numOfThreads         int
	startTimestamp       string
	startTs              int64

	keep int
	days int
}

var configPara config
var taosDriverName = "taosSql"
var url string

func init() {
	flag.StringVar(&configPara.hostName, "h", "10.110.156.64", "The host to connect to TDengine server.")
	flag.IntVar(&configPara.serverPort, "p", 6030, "The TCP/IP port number to use for the connection to TDengine server.")
	flag.StringVar(&configPara.user, "u", "root", "The TDengine user name to use when connecting to the server.")
	flag.StringVar(&configPara.password, "P", "taosdata", "The password to use when connecting to the server.")
	flag.StringVar(&configPara.dbName, "d", "test", "Destination database.")
	flag.StringVar(&configPara.tablePrefix, "m", "d", "Table prefix name.")
	flag.IntVar(&configPara.numOftables, "t", 2, "The number of tables.")
	flag.IntVar(&configPara.numOfRecordsPerTable, "n", 10, "The number of records per table.")
	flag.IntVar(&configPara.numOfRecordsPerReq, "r", 3, "The number of records per request.")
	flag.IntVar(&configPara.numOfThreads, "T", 1, "The number of threads.")
	flag.StringVar(&configPara.startTimestamp, "s", "2020-10-01 08:00:00", "The start timestamp for one table.")
	flag.Parse()

	configPara.keep = 365 * 20
	configPara.days = 30
	configPara.supTblName = "meters"

	startTs, err := time.ParseInLocation("2006-01-02 15:04:05", configPara.startTimestamp, time.Local)
	if err == nil {
		configPara.startTs = startTs.UnixNano() / 1e6
	}
}

func printAllArgs() {
	fmt.Printf("\n============= args parse result: =============\n")
	fmt.Printf("dbName:               %v\n", configPara.hostName)
	fmt.Printf("serverPort:           %v\n", configPara.serverPort)
	fmt.Printf("usr:                  %v\n", configPara.user)
	fmt.Printf("password:             %v\n", configPara.password)
	fmt.Printf("dbName:               %v\n", configPara.dbName)
	fmt.Printf("tablePrefix:          %v\n", configPara.tablePrefix)
	fmt.Printf("numOftables:          %v\n", configPara.numOftables)
	fmt.Printf("numOfRecordsPerTable: %v\n", configPara.numOfRecordsPerTable)
	fmt.Printf("numOfRecordsPerReq:   %v\n", configPara.numOfRecordsPerReq)
	fmt.Printf("numOfThreads:         %v\n", configPara.numOfThreads)
	fmt.Printf("startTimestamp:       %v[%v]\n", configPara.startTimestamp, configPara.startTs)
	fmt.Printf("================================================\n")
}

func main() {
	printAllArgs()
	fmt.Printf("Please press enter key to continue....\n")
	fmt.Scanln()

	url = "root:taosdata@/tcp(" + configPara.hostName + ":" + strconv.Itoa(configPara.serverPort) + ")/"
	//url = fmt.Sprintf("%s:%s@/tcp(%s:%d)/%s?interpolateParams=true", configPara.user, configPara.password, configPara.hostName, configPara.serverPort, configPara.dbName)
	// open connect to taos server
	//db, err := sql.Open(taosDriverName, url)
	//if err != nil {
	//  fmt.Println("Open database error: %s\n", err)
	//  os.Exit(1)
	//}
	//defer db.Close()

	createDatabase(configPara.dbName, configPara.supTblName)
	fmt.Printf("======== create database success! ========\n\n")

	//create_table(db, stblName)
	multiThreadCreateTable(configPara.numOfThreads, configPara.numOftables, configPara.dbName, configPara.tablePrefix)
	fmt.Printf("======== create super table and child tables success! ========\n\n")

	//insert_data(db, demot)
	multiThreadInsertData(configPara.numOfThreads, configPara.numOftables, configPara.dbName, configPara.tablePrefix)
	fmt.Printf("======== insert data into child tables success! ========\n\n")

	//select_data(db, demot)
	selectTest(configPara.dbName, configPara.tablePrefix, configPara.supTblName)
	fmt.Printf("======== select data success!  ========\n\n")

	fmt.Printf("======== end demo ========\n")
}

func createDatabase(dbName string, supTblName string) {
	db, err := sql.Open(taosDriverName, url)
	if err != nil {
		fmt.Println("Open database error: %s\n", err)
		os.Exit(1)
	}
	defer db.Close()

	// drop database if exists
	sqlStr := "drop database if exists " + dbName
	_, err = db.Exec(sqlStr)
	checkErr(err, sqlStr)

	time.Sleep(time.Second)

	// create database
	sqlStr = "create database " + dbName + " keep " + strconv.Itoa(configPara.keep) + " days " + strconv.Itoa(configPara.days)
	_, err = db.Exec(sqlStr)
	checkErr(err, sqlStr)

	// use database
	//sqlStr = "use " + dbName
	//_, err = db.Exec(sqlStr)
	//checkErr(err, sqlStr)

	sqlStr = "create table if not exists " + dbName + "." + supTblName + " (ts timestamp, current float, voltage int, phase float) tags(location binary(64), groupId int);"
	_, err = db.Exec(sqlStr)
	checkErr(err, sqlStr)
}

func multiThreadCreateTable(threads int, ntables int, dbName string, tablePrefix string) {
	st := time.Now().UnixNano()

	if (threads < 1) {
		threads = 1;
	}

	a := ntables / threads;
	if (a < 1) {
		threads = ntables;
		a = 1;
	}

	b := ntables % threads;
	last := 0;
	endTblId := 0
	wg := sync.WaitGroup{}
	for i := 0; i < threads; i++ {
		startTblId := last
		if (i < b) {
			endTblId = last + a
		} else {
			endTblId = last + a - 1
		}
		last = endTblId + 1
		wg.Add(1)
		go createTable(dbName, tablePrefix, startTblId, endTblId, &wg)
	}
	wg.Wait()

	et := time.Now().UnixNano()
	fmt.Printf("create tables spent duration: %6.6fs\n", (float32(et-st))/1e9)
}

func createTable(dbName string, childTblPrefix string, startTblId int, endTblId int, wg *sync.WaitGroup) {
	//fmt.Printf("subThread[%d]: create table from %d to %d \n", unix.Gettid(), startTblId, endTblId)
	// windows.GetCurrentThreadId()

	db, err := sql.Open(taosDriverName, url)
	if err != nil {
		fmt.Println("Open database error: %s\n", err)
		os.Exit(1)
	}
	defer db.Close()

	for i := startTblId; i <= endTblId; i++ {
		sqlStr := "create table if not exists " + dbName + "." + childTblPrefix + strconv.Itoa(i) + " using " + dbName + ".meters tags('" + locations[i%maxLocationSize] + "', " + strconv.Itoa(i) + ");"
		//fmt.Printf("sqlStr:               %v\n", sqlStr)
		_, err = db.Exec(sqlStr)
		checkErr(err, sqlStr)
	}
	wg.Done()
	runtime.Goexit()
}

func generateRowData(ts int64) string {
	voltage := rand.Int() % 1000
	current := 200 + rand.Float32()
	phase := rand.Float32()
	values := "( " + strconv.FormatInt(ts, 10) + ", " + strconv.FormatFloat(float64(current), 'f', 6, 64) + ", " + strconv.Itoa(voltage) + ", " + strconv.FormatFloat(float64(phase), 'f', 6, 64) + " ) "
	return values
}
func insertData(dbName string, childTblPrefix string, startTblId int, endTblId int, wg *sync.WaitGroup) {
	//fmt.Printf("subThread[%d]: insert data to table from %d to %d \n", unix.Gettid(), startTblId, endTblId)
	// windows.GetCurrentThreadId()

	db, err := sql.Open(taosDriverName, url)
	if err != nil {
		fmt.Println("Open database error: %s\n", err)
		os.Exit(1)
	}
	defer db.Close()

	tmpTs := configPara.startTs;
	//rand.New(rand.NewSource(time.Now().UnixNano()))
	for tID := startTblId; tID <= endTblId; tID++ {
		totalNum := 0
		for {
			sqlStr := "insert into " + dbName + "." + childTblPrefix + strconv.Itoa(tID) + " values "
			currRowNum := 0
			for {
				tmpTs += 1000
				valuesOfRow := generateRowData(tmpTs)
				currRowNum += 1
				totalNum += 1

				sqlStr = fmt.Sprintf("%s %s", sqlStr, valuesOfRow)

				if (currRowNum >= configPara.numOfRecordsPerReq || totalNum >= configPara.numOfRecordsPerTable) {
					break
				}
			}

			res, err := db.Exec(sqlStr)
			checkErr(err, sqlStr)

			count, err := res.RowsAffected()
			checkErr(err, "rows affected")

			if (count != int64(currRowNum)) {
				fmt.Printf("insert data, expect affected:%d, actual:%d\n", currRowNum, count)
				os.Exit(1)
			}

			if (totalNum >= configPara.numOfRecordsPerTable) {
				break
			}
		}
	}

	wg.Done()
	runtime.Goexit()
}
func multiThreadInsertData(threads int, ntables int, dbName string, tablePrefix string) {
	st := time.Now().UnixNano()

	if (threads < 1) {
		threads = 1;
	}

	a := ntables / threads;
	if (a < 1) {
		threads = ntables;
		a = 1;
	}

	b := ntables % threads;
	last := 0;
	endTblId := 0
	wg := sync.WaitGroup{}
	for i := 0; i < threads; i++ {
		startTblId := last
		if (i < b) {
			endTblId = last + a
		} else {
			endTblId = last + a - 1
		}
		last = endTblId + 1
		wg.Add(1)
		go insertData(dbName, tablePrefix, startTblId, endTblId, &wg)
	}
	wg.Wait()

	et := time.Now().UnixNano()
	fmt.Printf("insert data spent duration: %6.6fs\n", (float32(et-st))/1e9)
}
func selectTest(dbName string, tbPrefix string, supTblName string) {
	db, err := sql.Open(taosDriverName, url)
	if err != nil {
		fmt.Println("Open database error: %s\n", err)
		os.Exit(1)
	}
	defer db.Close()

	// select sql 1
	limit := 3
	offset := 0
	sqlStr := "select * from " + dbName + "." + supTblName + " limit " + strconv.Itoa(limit) + " offset " + strconv.Itoa(offset)
	rows, err := db.Query(sqlStr)
	checkErr(err, sqlStr)

	defer rows.Close()
	fmt.Printf("query sql: %s\n", sqlStr)
	for rows.Next() {
		var (
			ts       string
			current  float32
			voltage  int
			phase    float32
			location string
			groupid  int
		)
		err := rows.Scan(&ts, &current, &voltage, &phase, &location, &groupid)
		if err != nil {
			checkErr(err, "rows scan fail")
		}

		fmt.Printf("ts:%s\t current:%f\t voltage:%d\t phase:%f\t location:%s\t groupid:%d\n", ts, current, voltage, phase, location, groupid)
	}
	// check iteration error
	if rows.Err() != nil {
		checkErr(err, "rows next iteration error")
	}

	// select sql 2
	sqlStr = "select avg(voltage), min(voltage), max(voltage) from " + dbName + "." + tbPrefix + strconv.Itoa(rand.Int()%configPara.numOftables)
	rows, err = db.Query(sqlStr)
	checkErr(err, sqlStr)

	defer rows.Close()
	fmt.Printf("\nquery sql: %s\n", sqlStr)
	for rows.Next() {
		var (
			voltageAvg float32
			voltageMin int
			voltageMax int
		)
		err := rows.Scan(&voltageAvg, &voltageMin, &voltageMax)
		if err != nil {
			checkErr(err, "rows scan fail")
		}

		fmt.Printf("avg(voltage):%f\t min(voltage):%d\t max(voltage):%d\n", voltageAvg, voltageMin, voltageMax)
	}
	// check iteration error
	if rows.Err() != nil {
		checkErr(err, "rows next iteration error")
	}

	// select sql 3
	sqlStr = "select last(*) from " + dbName + "." + supTblName
	rows, err = db.Query(sqlStr)
	checkErr(err, sqlStr)

	defer rows.Close()
	fmt.Printf("\nquery sql: %s\n", sqlStr)
	for rows.Next() {
		var (
			lastTs      string
			lastCurrent float32
			lastVoltage int
			lastPhase   float32
		)
		err := rows.Scan(&lastTs, &lastCurrent, &lastVoltage, &lastPhase)
		if err != nil {
			checkErr(err, "rows scan fail")
		}

		fmt.Printf("last(ts):%s\t last(current):%f\t last(voltage):%d\t last(phase):%f\n", lastTs, lastCurrent, lastVoltage, lastPhase)
	}
	// check iteration error
	if rows.Err() != nil {
		checkErr(err, "rows next iteration error")
	}
}
func checkErr(err error, prompt string) {
	if err != nil {
		fmt.Printf("%s\n", prompt)
		panic(err)
	}
}

```

#### 输出

```bash
============= args parse result: =============
dbName:               172.15.1.6
serverPort:           6030
usr:                  root
password:             taosdata
dbName:               test
tablePrefix:          d
numOftables:          2
numOfRecordsPerTable: 10
numOfRecordsPerReq:   3
numOfThreads:         1
startTimestamp:       2020-10-01 08:00:00[1601510400000]
================================================
Please press enter key to continue....

drop database if exists test
panic: taos_connect() fail!

goroutine 1 [running]:
main.checkErr(0x575720, 0xc000056420, 0xc0000b87e0, 0x1c)
        D:/go_path/go_dev/taos/main/test.go:410 +0xe6
main.createDatabase(0x54e675, 0x4, 0x54e9a6, 0x6)
        D:/go_path/go_dev/taos/main/test.go:153 +0x22c
main.main()
        D:/go_path/go_dev/taos/main/test.go:124 +0x188
exit status 2

```

#### python

```python
"""
This is the sample code for TDengine python2 client.
"""
import taos
import sys
import datetime
import random


def exitProgram(conn):
    conn.close()
    sys.exit()


if __name__ == '__main__':
    start_time = datetime.datetime(2019, 7, 1)
    time_interval = datetime.timedelta(seconds=60)

    # Connect to TDengine server.
    #
    # parameters:
    # @host     : TDengine server IP address
    # @user     : Username used to connect to TDengine server
    # @password : Password
    # @database : Database to use when connecting to TDengine server
    # @config   : Configuration directory
    if len(sys.argv) > 1:
        hostname = sys.argv[1]
        conn = taos.connect(host=hostname, user="root", password="taosdata", config="/etc/taos")
    else:
        # conn = taos.connect(host="127.0.0.1", user="root", password="taosdata", config="/etc/taos")
        conn = taos.connect(host="10.110.156.64",port=6030, user="root", password="taosdata", config="/etc/taos")

    # Generate a cursor object to run SQL commands
    c1 = conn.cursor()
    # Create a database named db
    try:
        c1.execute('create database if not exists db ')
    except Exception as err:
        conn.close()
        raise (err)

    # use database
    try:
        c1.execute('use db')
    except Exception as err:
        conn.close()
        raise (err)

    # create table
    try:
        c1.execute('create table if not exists t (ts timestamp, a int, b float, c binary(20))')
    except Exception as err:
        conn.close()
        raise (err)

    # insert data
    for i in range(10):
        try:
            value = c1.execute("insert into t values ('%s', %d, %f, '%s')" % (
            start_time, random.randint(1, 10), random.randint(1, 10) / 10.0, 'hello'))
            # if insert, value is the affected rows
            print(value)
        except Exception as err:
            conn.close()
            raise (err)
        start_time += time_interval

    # query data and return data in the form of list
    try:
        c1.execute('select * from db.t')
    except Exception as err:
        conn.close()
        raise (err)

    # Column names are in c1.description list
    cols = c1.description
    # Use fetchall to fetch data in a list
    data = c1.fetchall()

    for col in data:
        print(col)

    print('Another query method ')

    try:
        c1.execute('select * from db.t')
    except Exception as err:
        conn.close()
        raise (err)

    # Use iterator to go through the retreived data
    for col in c1:
        print(col)

    conn.close()
```

#### 输出

```bash
Traceback (most recent call last):
  File "D:/project/20200304/mqtt_control/tmp/taosdata/example.py", line 4, in <module>
    import taos
  File "C:\Env\mqtt_control\lib\site-packages\taos\__init__.py", line 2, in <module>
    from .connection import TDengineConnection
  File "C:\Env\mqtt_control\lib\site-packages\taos\connection.py", line 1, in <module>
    from .cursor import TDengineCursor
  File "C:\Env\mqtt_control\lib\site-packages\taos\cursor.py", line 1, in <module>
    from .cinterface import CTaosInterface
  File "C:\Env\mqtt_control\lib\site-packages\taos\cinterface.py", line 137, in <module>
    class CTaosInterface(object):
  File "C:\Env\mqtt_control\lib\site-packages\taos\cinterface.py", line 144, in CTaosInterface
    libtaos.taos_use_result.restype = ctypes.c_void_p
  File "C:\software\python3.68\lib\ctypes\__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "C:\software\python3.68\lib\ctypes\__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'taos_use_result' not found
```

端口 都通了 在官方群咨询 没有解决办法

遇到同样问题 的人  对方也是弄了好久 无解

我不禁怀疑这个项目的真实性 实用性

**Comment by localvar** [comment]
非常抱歉给您带来了不好的体验。
因为 go 和 python 都有问题，可否麻烦您验证下使用 taos shell 是否可以连接成功？这可以帮助我们判断问题是出在这两个 connector 上，还是更底层。谢谢！

**Comment by Kittoa** [comment]
我发现当程序和taosd都在一台服务器上，运行没问题，但是在两台机器上就会出现这个连接失败的问题，不清楚啥原因

**Comment by localvar** [comment]
> 我发现当程序和taosd都在一台服务器上，运行没问题，但是在两台机器上就会出现这个连接失败的问题，不清楚啥原因
这主要是 fqdn 相关的问题，请在启动docker时使用 `--hostname` 指定 主机名，另请参考：https://www.taosdata.com/blog/2020/09/11/1824.html

**Comment by liangyuanpeng** [comment]
问题解决了吗？ @Kittoa  可以分享一下相关的解决方式信息

**Comment by chaoshengit** [comment]
go遇到同样的问题， 未解决

**Comment by huskar-t** [comment]
@chaoshengit @liangyuanpeng @Kittoa @Linuxlovers 
[use the -h parameter to specify hostname instead of ip.](https://www.taosdata.com/blog/2020/09/11/1824.html)

when you use docker, you need to publish tcp and udp ports at the same time.
`docker run -d --hostname="mytest" --name tdengine -p 6030-6042:6030-6042 -p 6030-6042:6030-6042/udp tdengine/tdengine:latest`

**Comment by fenghua1997** [comment]
This issue was closed because it has been inactive for too many days.
