### ISSUE TITLE
Invalid result set pointer

### ISSUE THREAD

**Issue by huangbotao** [taosdata/TDengine#3807]
**Bug Description**
When I use JDBC (2.0.4.0) busrt insert data into tdengine, sometime may throw this exception:
```
java.lang.RuntimeException: Invalid result set pointer
	at com.taosdata.jdbc.TSDBJNIConnector.freeResultSet(TSDBJNIConnector.java:187)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:96)
	at cn.bigdata.flink.dataclean.function.TDengineSinkFunction.invoke(TDengineSinkFunction.java:90)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. create stable: 
`CREATE TABLE STB_ACC (TS TIMESTAMP, POINT_VALUE DOUBLE) TAGS(DOMAIN binary(30), STATION binary(30), DEV_TYPE binary(30), DEV_ID binary(30), POINT_NAME binary(30), DATA_FLAG binary(20));`
2. insert data:
`insert into CO2123333 USING stb_METE tags ( 'EMS','CO21','METE','CO21D','COSa','origin')values(1602235860000, 1.0)`
...
...

3. then some times the error while occured

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 6.5]
 - TDengine Version [2.0.4.0]
 - not in batch insert mode, thread num was 2

**Comment by sangshuduo** [comment]
Please use latest JDBC driver 2.0.8

**Comment by huangbotao** [comment]
> Please use latest JDBC driver 2.0.8

thx for your reply. but if update jdbc driver, should i update taos server to the same version?

**Comment by huangbotao** [comment]
> Please use latest JDBC driver 2.0.8

when i update to 2.0.8 there is some exception throws:
```
java.lang.UnsatisfiedLinkError: no taos in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:25)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:193)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:201)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:196)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:93)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:404)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:90)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:139)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:61)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getConnection(DefaultSqlSession.java:298)
	at cn.bigdata.flink.dataclean.function.TDengineSinkFunction.open(TDengineSinkFunction.java:72)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
```

```
java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:193)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:201)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:196)
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:93)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:404)
	at org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:90)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:139)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:61)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getConnection(DefaultSqlSession.java:298)
	at cn.bigdata.flink.dataclean.function.TDengineSinkFunction.open(TDengineSinkFunction.java:72)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by huangbotao** [comment]
> Please use latest JDBC driver 2.0.8

**Comment by huangbotao** [comment]
when change to 2.0.8 the error still exists：
```
java.lang.RuntimeException: Invalid result set pointer
	at com.taosdata.jdbc.TSDBJNIConnector.freeResultSet(TSDBJNIConnector.java:187)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:96)
	at cn.bigdata.flink.dataclean.function.TDengineSinkFunction.invoke(TDengineSinkFunction.java:62)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zyyang-taosdata** [comment]
我得要client的日志来排查这个问题了：
1. 清理历史日志，如果客户端是windows，日志文件在C:\\TDengine\log目录下。
2. 编辑配置文件C:\\TDengine\cfg\taos.cfg，将debugFlag修改为135
3.重新启动java应用，并制造上面这个报错，将C:\\TDengine\log日志发给我，或者粘贴在本issue

**Comment by huangbotao** [comment]
> 我得要client的日志来排查这个问题了：
> 
> 1. 清理历史日志，如果客户端是windows，日志文件在C:\TDengine\log目录下。
> 2. 编辑配置文件C:\TDengine\cfg\taos.cfg，将debugFlag修改为135
>    3.重新启动java应用，并制造上面这个报错，将C:\TDengine\log日志发给我，或者粘贴在本issue，谢谢～

问题解决了。应该运行环境的问题，重新安装了taos client，和它依赖的glibc。
