### ISSUE TITLE
TDengine Error: Last session not finished

### ISSUE THREAD

**Issue by moziie** [taosdata/TDengine#3907]
**Bug Description**
打印的错误报告
Exception in thread "[ThreadPoolExecutor]dc3-thread-700" org.springframework.jdbc.UncategorizedSQLException: 
Error updating database.  Cause: java.sql.SQLException: TDengine Error: Last session not finished
The error may exist in file [D:\fanwu-datamonitor\dc3-center\dc3-manager\target\classes\mapper\TDengineMapper.xml]
The error may involve defaultParameterMap
The error occurred while setting parameters
SQL: import into db000117vo using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)         values (?,?,                 ?,?)
Cause: java.sql.SQLException: TDengine Error: Last session not finished
; uncategorized SQLException; SQL state []; error code [-2147483641]; TDengine Error: Last session not finished; nested exception is java.sql.SQLException: TDengine Error: Last session not finished
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy153.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
	at com.sun.proxy.$Proxy154.insertVoltage(Unknown Source)
	at com.dc3.center.data.service.impl.PointValueServiceImpl.lambda$addPointValue$0(PointValueServiceImpl.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: TDengine Error: Last session not finished
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:135)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:87)
	at com.taosdata.jdbc.SavedPreparedStatement.executeSql(SavedPreparedStatement.java:450)
	at com.taosdata.jdbc.SavedPreparedStatement.executeBatchInternal(SavedPreparedStatement.java:259)
	at com.taosdata.jdbc.TSDBPreparedStatement.execute(TSDBPreparedStatement.java:304)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 9 more

**To Reproduce**
1. 在一分钟内执行for循环做3000次线程threadExcutor插入，定时任务每分钟跑一次
2. 线程最大数量1024，核心线程数量100，空闲时间5秒，超出最大线程数处理策略CallerRunsPolicy
3. 在第3分钟出现报错
4.tdengine中7个超级表，每个超级表下3000个子表，一共21000个子表
5.插入语句，集成mybatis实现，每次执行类似如下7条语句
import into db000117v1 using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)  values (?,?,?,?)；
import into db000117v2 using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)  values (?,?,?,?)；
import into db000117v3 using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)  values (?,?,?,?)；
import into db000117v4 using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)  values (?,?,?,?)；
import into db000117v5 using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)  values (?,?,?,?)；
import into db000117v6 using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)  values (?,?,?,?)；
import into db000117v7 using voltages tags (Beijing.daxing0117,DID100117,MID200117,UID300115)         (ts,voltageA,voltageB,voltageC)  values (?,?,?,?)；
**Expected Behavior**
官方文档中写道“数据插入 TDengine单核每秒能至少处理一万个插入请求。每个插入请求可以带多条记录，一次插入一条记录与插入10条记录，消耗的计算资源差别很小。因此每次插入，条数越大，插入效率越高。如果一个插入请求带200条以上记录，单核就能达到每秒插入100万条记录的速度。但对前端数据采集的要求越高，因为需要缓存记录，然后一批插入。”
所以程序应该能很轻松的插入数据而不应该报错。

**Screenshots**
![image](https://user-images.githubusercontent.com/70946068/96398328-2da3b180-11fe-11eb-85ca-f51553ddc118.png)

**Environment (please complete the following information):**
 -CentOS 8.0
 - 8核16G
 - TDengine Version 2.0.3.0

**Comment by zyyang-taosdata** [comment]
从exectue方法来看，你也没有执行批量插入，而是每次插入一条记录。批量插入的sql
```sql
insert into dbname.tbName values(xxx,xxxx,xxx),(xxxx,xxxx,xxx)...
```
使用mybatis框架，相比使用原声的jdbc接口进行插入，性能会有所下降。

> 所以程序应该能很轻松的插入数据而不应该报错。
正确多线程插入，在一个Runnable任务中，保持使用同一个Connection连接来进行插入，并在完成插入后关闭相关资源。
从你的代码来看，很有可能没有做相关资源的释放。

我会检查这个Last session not finished的报错信息，但是你应该先检查你的程序是否正确。

**Comment by moziie** [comment]
好的多谢 我改一下程序
