### ISSUE TITLE
**jdbcTemplate.execute("use metric_data") java.sql.SQLException: this operation is NOT supported currently

### ISSUE THREAD

**Issue by 419845351** [taosdata/TDengine#4096]
报错信息：
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [use metric_data]; SQL state [null]; error code [0]; this operation is NOT supported currently!; nested exception is java.sql.SQLException: this operation is NOT supported currently!

yml文件配置：
tdengine:
datasource: #TDengine数据源
driverClassName: com.taosdata.jdbc.TSDBDriver
jdbcUrl: jdbc:TAOS://192.168.155.46:6030/
username: root
password: taosdata
druid:
initialSize: 5
minIdle: 5
maxActive: 5
maxWait: 60000
validationQuery: select server_status();
validationQueryTimeout: 5000
testOnBorrow: false
testOnReturn: false
testWhileIdle: true
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 600000
maxEvictableIdleTimeMillis: 900000

DataSourceConfig内容：
@primary
@bean(name = "baseDatasource")
@ConfigurationProperties(prefix="spring.datasource")
public DataSource baseDatasource() {
return DataSourceBuilder.create().build();
}

@Bean(name = "tdengineDatasource")
@ConfigurationProperties(prefix="tdengine.datasource")
public DataSource tdengineDatasource() {
    return DataSourceBuilder.create().build();
}

DAO内容:
JdbcTemplate jdbcTemplate = new JdbcTemplate(tdengineDatasource);//tdengine数据库
jdbcTemplate.execute("use metric_data");

**Comment by zyyang-taosdata** [comment]
请把报错的java异常信息贴一下

**Comment by 419845351** [comment]
以下是我的报错信息，请查收，谢谢


org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [use metric_data]; SQL state [null]; error code [0]; this operation is NOT supported currently!; nested exception is java.sql.SQLException: this operation is NOT supported currently!
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:415)
	at com.rsi.rc.ce.service.impl.MetricDataServiceImpl.add(MetricDataServiceImpl.java:301)
	at com.rsi.rc.ce.service.impl.MetricDataServiceImpl$$FastClassBySpringCGLIB$$683cc948.invoke(<generated&gt;)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.rsi.rc.ce.service.impl.MetricDataServiceImpl$$EnhancerBySpringCGLIB$$b5590ce9.add(<generated&gt;)
	at com.rsi.rc.ce.conctroller.MetricDataConctroller.init(MetricDataConctroller.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: this operation is NOT supported currently!
	at com.taosdata.jdbc.TSDBStatement.getWarnings(TSDBStatement.java:159)
	at com.zaxxer.hikari.pool.HikariProxyStatement.getWarnings(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.handleWarnings(JdbcTemplate.java:1367)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:377)
	... 65 more





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午5:09
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;".|囿剑洳虹'_"<419845351@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] 在项目中配置了两个数据源,执行**jdbcTemplate.execute("use metric_data");**报错：java.sql.SQLException: this operation is NOT supported currently! (#4096)





 
请把报错的java异常信息贴一下

**Comment by zyyang-taosdata** [comment]
感谢您的问题，我在修复这个问题。

**Comment by 419845351** [comment]
因为我们最近准备用这种方式做项目，请问有没有具体修复日期呢，要是不行我们就要换一种方式了。

**Comment by yuhuafeng1109** [comment]
我也遇到这个问题，还没有解决吗 @419845351 @zyyang-taosdata

**Comment by 419845351** [comment]
试试不用jdbcTemplate。我现在直接使用DataSource管理Connection，效果是一样的。

**Comment by hutianjin19940308** [comment]
> 感谢您的问题，我在修复这个问题。

需要修复多久呢 技术选型阶段等不及啊

**Comment by hutianjin19940308** [comment]
> 试试不用jdbcTemplate。我现在直接使用DataSource管理Connection，效果是一样的。

具体点呢  mybatis 动态数据源没想到其他解决方案

**Comment by 419845351** [comment]
就是正常添加多数据源，网上很多例子。如果有mysql，就把mysql作为主数据源，仍然可以使用mybatis。剩下的拼接sql就好了。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hutianjin19940308&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月27日(星期五) 下午3:45
收件人:&nbsp;&quot;taosdata/TDengine&quot;<TDengine@noreply.github.com&gt;;
抄送:&nbsp;&quot;jiangjiang&quot;<419845351@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] **jdbcTemplate.execute(&quot;use metric_data&quot;) java.sql.SQLException: this operation is NOT supported currently (#4096)

**Comment by hutianjin19940308** [comment]
就是taos不给动态数据源托管 直接单独配置个类似jdbc 工具执行sql 是吧

**Comment by hutianjin19940308** [comment]
> 就是正常添加多数据源，网上很多例子。如果有mysql，就把mysql作为主数据源，仍然可以使用mybatis。剩下的拼接sql就好了。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;hutianjin19940308&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月27日(星期五) 下午3:45 收件人:&nbsp;&quot;taosdata/TDengine&quot;<TDengine@noreply.github.com&gt;; 抄送:&nbsp;&quot;jiangjiang&quot;<419845351@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [taosdata/TDengine] **jdbcTemplate.execute(&quot;use metric_data&quot;) java.sql.SQLException: this operation is NOT supported currently (#4096)

就是taos不给动态数据源托管 直接单独配置个类似jdbc 工具执行sql 是吧

**Comment by 419845351** [comment]
嗯，自己定义数据源，自己创建链接，自己拼接sql. ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hutianjin19940308&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月27日(星期五) 下午4:20
收件人:&nbsp;&quot;taosdata/TDengine&quot;<TDengine@noreply.github.com&gt;;
抄送:&nbsp;&quot;jiangjiang&quot;<419845351@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] **jdbcTemplate.execute(&quot;use metric_data&quot;) java.sql.SQLException: this operation is NOT supported currently (#4096)

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
