### ISSUE TITLE
求助：windows连接tdengine集群 v.2.0.5,客户端能连但程序连接失败

### ISSUE THREAD

**Issue by nzxxs4** [taosdata/TDengine#4185]
![image](https://user-images.githubusercontent.com/46189402/98778161-e55a6680-242c-11eb-97b7-81b40512f778.png)
windows客户端版本，jdbc版本，linux服务器版本都是2.0.5
连接的是配置文件指定的主节点fistEP那个
用的是官网Druid例子https://www.taosdata.com/cn//documentation20/connector-java/

**Comment by nzxxs4** [comment]
图片是看不了吗。。这是控制台部分报错信息
java.sql.SQLException: connect error, url jdbc:TAOS://a-d182:6030/log, driverClass com.taosdata.jdbc.TSDBDriver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1627)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:861)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1229)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at com.je.test.test.main(test.java:31)
[2020-11-11 14:59:33.703] [ERROR] [main] [com.alibaba.druid.pool.DruidDataSource] {dataSource-1} init error
java.sql.SQLException: connect error, url jdbc:TAOS://a-d182:6030/log, driverClass com.taosdata.jdbc.TSDBDriver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1627)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:861)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1229)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at com.je.test.test.main(test.java:31)
[2020-11-11 14:59:33.704] [INFO] [main] [com.alibaba.druid.pool.DruidDataSource] {dataSource-1} inited
Exception in thread "main" java.sql.SQLException: connect error, url jdbc:TAOS://a-d182:6030/log, driverClass com.taosdata.jdbc.TSDBDriver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1627)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:861)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1229)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at com.je.test.test.main(test.java:31)

**Comment by zyyang-taosdata** [comment]
感谢您的问题，从您的报错信息来看需要更新一下jdbc-driver的版本，请更新maven依赖到taos-jdbcdriver-2.0.10。windows环境下的开发可以参考一下这篇文章。
https://github.com/taosdata/TDengine/blob/develop/tests/examples/JDBC/JDBCDemo/README-jdbc-windows.md
