### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector

### ISSUE THREAD

**Issue by wx979369175** [taosdata/TDengine#4238]
java使用JDBC建立简介，在windows系统上可以正常运行，打包放到docker容器中运行时，出现如下异常：
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector] with root cause
java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:193)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)

使用驱动及依赖版本均为2.0.6

**Comment by zyyang-taosdata** [comment]
taos-jdbcdriver的2.0.6版本，TSDBDriver的193行是注释，所以从你提供的信息可以知道，你的taos-jdbcdriver用的肯定不是2.0.6。错误发生在JDBC的Driver初始化，确保你在docker容器已经安装了taos客户端，taos0-jdbcdriver尽量使用新的，最近的是2.0.11了

**Comment by 419845351** [comment]
请问docker容器安装客户端是通过TDengine-client-2.0.6.0-Linux-x64.tar.gz包么？我在容器里
执行：sh install_client.sh 
提示：install_client.sh: 65: Syntax error: "(" unexpected
![image](https://user-images.githubusercontent.com/29766247/99473077-d02d8c80-2984-11eb-9cd0-82d92271eaab.png)
不太懂docker里要怎么安装客户端，麻烦您了。@zyyang-taosdata

**Comment by stephenkgu** [comment]
./install_client.sh 可以吗？

**Comment by MelodyI** [comment]
在运行docker的时候，映射taos驱动：
```
-v /usr/local/taos/driver/libtaos.so.2.1.1.0:/usr/lib/libtaos.so
```
完整的例子(指定时区)：
```
docker run -d \
    --name application-name \
    --hostname docker-hostname \
    -v /usr/local/taos/driver/libtaos.so.2.1.1.0:/usr/lib/libtaos.so \
    -v /usr/share/zoneinfo:/usr/share/zoneinfo \
    -e TZ=Asia/Shanghai \
    -p 8080:8080 \
    docker-image-name
```

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
