### ISSUE TITLE
Authentication failure using JDBC connection on Windows 7

### ISSUE THREAD

**Issue by AisTop** [taosdata/TDengine#425]
**Bug Description**
win7 已经安装TDengine client ， 已经确认不缺少dll 等包。 
在jdbc连接过程中，出现认证错误。
代码如下：
          Class.forName("com.taosdata.jdbc.TSDBDriver");
	  String jdbcUrl = "jdbc:TAOS://192.168.0.44:0/db?user=root&password=baian20198";
	  Connection conn = DriverManager.getConnection(jdbcUrl);
	  return conn;
error:
   java.sql.SQLException: TDengine Error: authentication failure
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:100)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:64)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:56)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.ba.locationdata.test.testTdEngine.getConn(testTdEngine.java:34)
	at com.ba.locationdata.test.testTdEngine.main(testTdEngine.java:15)

经过多次确认， 用户名和密码都是正确的， 在shell 端可以正常登陆。  
 TDengine 版本为：1.6.0.0。
麻烦确认下这个是不是bug。

**Comment by johnnyhou327** [comment]
@AisTop As the version is fairly old, this may very likely be a known bug. Please try the latest version and see if the same error occurs.

**Comment by AisTop** [comment]
thinks
