### ISSUE TITLE
存入三万条左右数据就报错  python

### ISSUE THREAD

**Issue by leonpython1** [taosdata/TDengine#438]
Traceback (most recent call last):
  File "D:\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "D:\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/liyuMES/dtutil/tdengine_util.py", line 94, in <module>
    random.randint(1, 100000))
  File "D:/liyuMES/dtutil/tdengine_util.py", line 29, in create_plc_data_tdengine
    c1.execute(sql)
  File "C:\Python27\lib\site-packages\taos\cursor.py", line 112, in execute
    res = CTaosInterface.query(self._connection._conn, stmt)
  File "C:\Python27\lib\site-packages\taos\cinterface.py", line 243, in query
    return CTaosInterface.libtaos.taos_query(connection, ctypes.c_char_p(sql.encode('utf-8')))
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by leonpython1** [comment]
我是用测试数据，生成7万条，先建了超级表，然后用自动创建子表的方法。执行了几次都是创建3万多条之后报错，也没报空间不足之类的错误。sql语句正确；

**Comment by hzcheng** [comment]
请问您的server是版本和客户端版本是什么？另外，python是在windows上运行的python2版本吗？如果方便话，可不可以将测试代码发我们下。谢谢！

**Comment by leonpython1** [comment]
请问一下，有配置sql语句长度的设置吗，我在插入大量数据，现在一条insert插入2000个值，再大就报错了 。  上一个问题解决了，时间插入的不对。

**Comment by fangpanpan** [comment]
> 请问一下，有配置sql语句长度的设置吗，我在插入大量数据，现在一条insert插入2000个值，再大就报错了 。 上一个问题解决了，时间插入的不对。

sql语句不能大于64k。

**Comment by leonpython1** [comment]
之前数据库里有总计27亿条数据，都是我批量插入进去的。中途电脑关机重启了，现在数据量为什么变少了，现在有6e。？

**Comment by hzcheng** [comment]
您搜索下在/var/log/taos下运行
```
grep ERROR taosd*
```
将grep出来的信息贴一下吧

**Comment by leonpython1** [comment]
taosdlog.1:08/30 16:55:29.471412 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:29.810596 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:30.154690 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:30.516405 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:30.856383 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:31.218294 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:31.580900 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:31.908748 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:32.256138 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:32.607565 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted
taosdlog.1:08/30 16:55:32.959036 7f89db54d700 ERROR DND vid:1, head file:/var/lib/taos/tsdb/vnode1/db/v1f1796.head corrupted

**Comment by leonpython1** [comment]
hello  请问这个应该怎么解决 或者我如何避免这种问题出现？

**Comment by fangpanpan** [comment]
请问您用了import吗？以及您用的版本号？

**Comment by leonpython1** [comment]
1.6.1.7  肯定import了

**Comment by fangpanpan** [comment]
您可以拉一下最新代码试一下吗？

**Comment by leonpython1** [comment]
可以 。还有taos.error.ProgrammingError: invalid query message

**Comment by leonpython1** [comment]
你好  请问 报错 TSDB error : too many sessions on server  是不是插入数据太多太快了，我是多线程批量插入，过几分钟就报这个错，或者报 failed to connect to server

**Comment by fangpanpan** [comment]
> 你好 请问 报错 TSDB error : too many sessions on server 是不是插入数据太多太快了，我是多线程批量插入，过几分钟就报这个错，或者报 failed to connect to server


请问您每次建立一个taos_connect，操作结束后会将它关闭吗？

**Comment by leonpython1** [comment]
每次连接完  执行完insert语句，都关闭了

**Comment by fangpanpan** [comment]
能将您的python代码发过来吗？如果您的问题能复现的话，您可以删除日志后重启taosd然后再运行一次后将日志也发过来吗？（重启前请打开日志，在taos.cfg里将debugflag 改成135）
