### ISSUE TITLE
java.sql.SQLException: this operation is NOT supported currently

### ISSUE THREAD

**Issue by lanyue52011** [taosdata/TDengine#4684]
Connection conn = DriverManager.getConnection(jdbcUrl);
                Statement stmt = conn.createStatement();
                String sqlstr = "select longitude '纬度',latitude '经度',dose_rate '计量率', height as '高度',count_rate as '计数率', ts '时间', device_code as '设备编码' from tablename>>data.csv";
                stmt.setEscapeProcessing(true);
                stmt.execute(sqlstr);

java.sql.SQLException: this operation is NOT supported currently!
	at com.taosdata.jdbc.TSDBStatement.setEscapeProcessing(TSDBStatement.java:143)
	at TSDBSyncSample.doExecuteQuery(TSDBSyncSample.java:163)
	at TSDBSyncSample.main(TSDBSyncSample.java:46)

**Comment by zyyang-taosdata** [comment]
现有的driver实现没有对SQL进行转义处理，请直接注释调用setEscapeProcessing方法。

**Comment by lanyue52011** [comment]
注释“setEscapeProcessing”后执行出现下面的异常：
java.sql.SQLException: TDengine Error: syntax error near ">> data.csv"
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:135)
	at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:175)
	at TSDBSyncSample.doExecuteQuery(TSDBSyncSample.java:167)
	at TSDBSyncSample.main(TSDBSyncSample.java:48)

**Comment by 100571753** [comment]
![QCPXS4 XN2T7LSE}{ 08`W](https://user-images.githubusercontent.com/24711685/130184701-922f53d4-c7c5-4d22-a375-9d7dc6cbc17f.png)
我也遇到这个问题了。springboot+mybatis+durid框架下产生的，这该怎么解决呢

**Comment by cdf30088** [comment]
我尝试更换 maven依赖的版本会有变化

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
