### ISSUE TITLE
SHOW STABLES LIKE frequently, a fatal error happened

### ISSUE THREAD

**Issue by leoasc** [taosdata/TDengine#4691]
**Bug Description**

在项目中会用到物模型与超表的同步，采用 “SHOW STABLES LIKE '超表名称' ”的方法验证物模型对应的超表是否存在，但是此方法稍微频繁一点就会报致命错误，且无法捕获：
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at TDengineDriver.TDengine.Query(IntPtr, System.String)
   at TDengineDriver.TDengine.Query(IntPtr, System.String)
   at TDengineDriver.Program+<>c__DisplayClass0_0.<Main>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
采用MakeBing封装的连接器和官方示例都会发生此异常。

**To Reproduce**
1. 采用官方驱动中的C#示例
2. 写一个循环，执行  SHOW STABLES LIKE 语句
3.执行程序，一般数秒内便会报错
测试验证用的项目代码：
https://space.dingtalk.com/s/gwHOAoirfALOAtVT0QPaACA3ZTAyZDJiZDY5ZWE0OTJkOGY0ZTRiNjE0M2ZiYWZhNA 密码: An4S

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Win10
 - Memory 16G, CPU, current Disk Space
 - TDengine Version Server:2.0.10,Client:2.0.3,2.0.10

**Additional Context**

**Comment by Aries-Lee1991** [comment]
请附上日志等详细信息。

**Comment by leoasc** [comment]
暂时改为 show stables 不加 like ,这样不会出错

**Comment by localvar** [comment]
问题已经修复，但已经赶不上即将发布的版本，将包含在再下一个版本中。
