### ISSUE TITLE
td2-connector error:  

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#4738]
**Bug Description**
select * from m12345;

Error: reinterpret: Cannot reinterpret from NULL pointer
    at Object.reinterpret (/usr/local/kou/node_modules/ref/lib/ref.js:780:21)
    at Object.convertFloat (/usr/local/kou/node_modules/td2.0-connector/nodetaos/cinterface.js:107:14)
    at CTaosInterface.fetchBlock (/usr/local/kou/node_modules/td2.0-connector/nodetaos/cinterface.js:374:52)
    at TDengineCursor.fetchall (/usr/local/kou/node_modules/td2.0-connector/nodetaos/cursor.js:199:38)
    at /usr/local/kou/node_modules/td2.0-connector/nodetaos/taosquery.js:42:71
    at new Promise (<anonymous>)
    at TaosQuery.execute (/usr/local/kou/node_modules/td2.0-connector/nodetaos/taosquery.js:35:26)
    at TaosPhysService.taosphycolsearch (/usr/local/kou/services/TaosPhysService.js:97:18)

taosdata version: 2.0.12.0  
td2.0-connector: 2.0.3

**Comment by sangshuduo** [comment]
操作是连本机还是连远程？

**Comment by sexbee** [comment]
操作本机。不过这个问题似乎和本机or远程没关系吧？

**Comment by sexbee** [comment]
直接client query是正常的；如果数据里没有null 也是正常的。这个问题在不同版本的td-connector里会交替出现。

**Comment by sangshuduo** [comment]
我用 2.0.12.1 和 td2.0-connector 2.0.4 做了一个简单测试，使用 tests/examples/nodejs/nodejsChecker.js ，不能重现这个问题

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/825729/103451265-b6f65a80-4cfc-11eb-93cf-e8b2069a0584.png">

**Comment by sangshuduo** [comment]
没有更新，关闭
