### ISSUE TITLE
I start 100 goroutine to connect and create,then I get the result:panic: Unable to establish connection

### ISSUE THREAD

**Issue by leeningli** [taosdata/TDengine#4788]
**Bug Description**
Client Version:2.0.12.0
1C2G ubuntu
go1.15.6

**To Reproduce**
this is my code:

```package main

import (
        "database/sql"
        "fmt"
        _ "github.com/taosdata/driver-go/taosSql"
        "strconv"
        "sync"
        "time"
        "gopkg.in/ini.v1"
)

var (
        TaosDB *sql.DB
        defaulttag string
        taosconfig *TaosConfig

)

const (
        DRIVERNAME = "taosSql"
        MAX_SQL = 1*1024
)

func init(){
        taosconfig = NewTaosConfig("./conf/taos.conf")
        connecorUrl := taosconfig.User+":"+taosconfig.Pwd+`@/tcp(`+taosconfig.Url+`)/`+taosconfig.DbName
        var err error
        TaosDB,err = sql.Open(DRIVERNAME,connecorUrl)
        if err != nil {
                panic(err.Error())
        }

}

func Close() {
        if TaosDB != nil {
                TaosDB.Close()
        }
}

func CreateDatabase(db string) error{
        _,err := TaosDB.Exec("create database "+db)
        return err
}

func useDatabase(db string) error{
        stmt,err := TaosDB.Prepare("use "+db)
        if err != nil {
                return err
        }
        _,err = stmt.Exec()
        return err
}


type TaosConfig struct {
        Url            string
        User      string
        Pwd    string
        DbName           string
}

func NewTaosConfig(configpath string) *TaosConfig {
        conf := &TaosConfig{}
        conf.loadConfig(configpath)
        return conf
}

func (conf *TaosConfig) loadConfig(path string) {
        cfg, err := ini.Load(path)
        if err != nil {
                panic("new config failed,err==" + err.Error())
        }

        /*
                [main]

                [tdengine]
                url = 30
                user = 120
                pwd = false
                db = 1000
        */
        conf.Url = cfg.Section("tdengine").Key("url").MustString("127.0.0.1:0")
        conf.Pwd = cfg.Section("tdengine").Key("pwd").MustString("taosdata")
        conf.User = cfg.Section("tdengine").Key("user").MustString("root")
        conf.DbName = cfg.Section("tdengine").Key("db").MustString("log")
}


func main(){
        err := CreateDatabase("rapm1")
        fmt.Println("error msg==",err)
        useDatabase("rapm1")
        create1000_1_waitgroup()
}
func create1000_1_waitgroup() {
        start := time.Now()
        wg := sync.WaitGroup{}
        wg.Add(100)
        for i:=0;i<100;i++{
                go  func(j int){
                tbn := "tbn"+strconv.Itoa(j)
                s := "create table "+ tbn+" (ts timestamp,value double) tags (org binary(8),az binary(8),dcn binary(8),ip binary(8))"
                connecorUrl := taosconfig.User+":"+taosconfig.Pwd+`@/tcp(`+taosconfig.Url+`)/rapm1`
                taosDB,err := sql.Open(DRIVERNAME,connecorUrl)
                if err != nil {
                        panic(err.Error())
                }
                _,err = taosDB.Exec(s)
                if err != nil {
                        panic(err.Error())
                }
                wg.Done()}(i)
        }
        wg.Wait()
        fmt.Println("1000_1 cost===",time.Since(start))
}```


this is my result:
```
root@VM-0-16-ubuntu:/data/nanili/tdengine# go run td.go 
error msg== <nil>
panic: Unable to establish connection

goroutine 88 [running]:
main.create1000_1_waitgroup.func1(0xc00001a1b0, 0x50)
        /data/nanili/tdengine/td.go:113 +0x2f1
created by main.create1000_1_waitgroup
        /data/nanili/tdengine/td.go:103 +0xb5
exit status 2
```

**Comment by sangshuduo** [comment]
1C2G 配置很低，可能撑不住100个连接

**Comment by leeningli** [comment]
> 1C2G 配置很低，可能撑不住100个连接

ok，I change to 16C32G, It appears ok.
I'll close this issue.
