### ISSUE TITLE
python error when import taos: "OSError: libtaos.so: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by wffeige** [taosdata/TDengine#484]
报错信息
[root@python TDengine]# python3
Python 3.6.4 (default, Dec 22 2017, 14:32:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/taos/__init__.py", line 2, in <module>
    from .connection import TDengineConnection
  File "/usr/local/lib/python3.6/site-packages/taos/connection.py", line 2, in <module>
    from .cursor import TDengineCursor
  File "/usr/local/lib/python3.6/site-packages/taos/cursor.py", line 1, in <module>
    from .cinterface import CTaosInterface
  File "/usr/local/lib/python3.6/site-packages/taos/cinterface.py", line 137, in <module>
    class CTaosInterface(object):
  File "/usr/local/lib/python3.6/site-packages/taos/cinterface.py", line 139, in CTaosInterface
    libtaos = ctypes.CDLL('libtaos.so')
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtaos.so: cannot open shared object file: No such file or directory

**Comment by wffeige** [comment]
参考解决方案 https://github.com/taosdata/TDengine/issues/401

[root@python TDengine]# find / -name "libtaos.so"
/usr/lib/libtaos.so
[root@python TDengine]# export LD_LIBRARY_PATH=/usr/lib/
[root@python TDengine]# echo $LD_LIBRARY_PATH           
/usr/lib/
[root@python TDengine]# python 
Python 3.6.4 (default, Dec 22 2017, 14:32:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taos
>>>
