### ISSUE TITLE
question about TDengine Error: success 

### ISSUE THREAD

**Issue by opjk** [taosdata/TDengine#4916]
建表报异常， TDengine Error: success 啥意思呢。成功抛出了异常？
15:08:55.161 [project-executor-10] ERROR c.g.s.o.s.i.DaValueServiceImpl - [insertOne,122] - 执行sql失败
java.sql.SQLException: TDengine Error: success
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:135)
	at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:178)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)

**Comment by zyyang-taosdata** [comment]
TDengine的版本，taos-jdbcdriver的版本

**Comment by zyyang-taosdata** [comment]
https://github.com/taosdata/TDengine/issues/4916

**Comment by EcoleKeine** [comment]
@zyyang-taosdata 
为什么close那么多未解决的issue，并关联到这个未解决的issue？

**Comment by yungyu16** [comment]
太坑了这个tdengine

**Comment by zyyang-taosdata** [comment]
> @zyyang-taosdata 为什么close那么多未解决的issue，并关联到这个未解决的issue？

我们集中关闭了一批长期没有更新的问题
