### ISSUE TITLE
query  alert  "DB error: Invalid Vgroup ID "

### ISSUE THREAD

**Issue by wooyhui** [taosdata/TDengine#4929]
query  alert  "DB error: Invalid Vgroup ID "

**Comment by sangshuduo** [comment]
show dnodes;

show mnodes;

use \<dbname>; show vgroups; 

请问这几个命令的输出是什么？

**Comment by huangbotao** [comment]
你好，我这边也常出现这样的问题。

``` shell

taos> show dnodes;
   id   |           end_point            | vnodes | cores  |    status    |  role   |       create_time       |       offline reason       |
============================================================================================================================================
      1 | tnode-online1:6030             |     25 |      8 | ready        | any     | 2021-01-13 12:36:48.711 |                            |
      2 | tnode-online2:6030             |     24 |      8 | ready        | any     | 2021-01-13 12:37:30.663 |                            |
      3 | tnode-online3:6030             |     24 |      8 | ready        | any     | 2021-01-13 12:37:35.786 |                            |
Query OK, 3 row(s) in set (0.001068s)

taos> show mnodes;
   id   |           end_point            |      role      |       create_time       |
=====================================================================================
      1 | tnode-online1:6030             | master         | 2021-01-13 12:36:48.711 |
      2 | tnode-online2:6030             | slave          | 2021-01-13 12:37:31.330 |
      3 | tnode-online3:6030             | slave          | 2021-01-13 12:37:37.285 |
Query OK, 3 row(s) in set (0.000859s)

taos> use metric_data;
Database changed.

taos> show vgroups;
    vgId     |   tables    |   status   | onlineVnodes | v1Dnode |  v1Status   | v2Dnode |  v2Status   | v3Dnode |  v3Status   |
================================================================================================================================
           3 |       17000 | ready      |            3 |       3 | slave       |       2 | slave       |       1 | master      |
           4 |       17000 | ready      |            3 |       3 | slave       |       2 | slave       |       1 | master      |
           5 |       17000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
           6 |       17000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
           7 |       17000 | ready      |            2 |       3 | unsynced    |       2 | master      |       1 | slave       |
           8 |       17000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
           9 |       17000 | ready      |            2 |       3 | unsynced    |       2 | master      |       1 | slave       |
          10 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          11 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          12 |       17000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          13 |       16039 | ready      |            0 |       3 | offline     |       2 | unsynced    |       1 | unsynced    |
          14 |       16000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
          15 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          16 |       16000 | ready      |            2 |       3 | unsynced    |       2 | master      |       1 | slave       |
          17 |       16000 | ready      |            3 |       3 | slave       |       2 | master      |       1 | slave       |
          18 |       16000 | ready      |            2 |       3 | unsynced    |       2 | master      |       1 | slave       |
          19 |       16000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
          20 |       16000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
          21 |       16000 | ready      |            2 |       3 | unsynced    |       2 | master      |       1 | slave       |
          22 |       16000 | ready      |            2 |       3 | unsynced    |       2 | master      |       1 | slave       |
          23 |       16000 | ready      |            2 |       3 | slave       |       2 | unsynced    |       1 | master      |
          24 |       16000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
          25 |       16000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
          26 |       16000 | ready      |            3 |       3 | master      |       2 | slave       |       1 | slave       |
Query OK, 24 row(s) in set (0.000809s)



```

**Comment by sangshuduo** [comment]
最近还有这个问题吗？

**Comment by wooyhui** [comment]
目前还没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 晚上11:38
收件人:&nbsp;"taosdata/TDengine"<TDengine@noreply.github.com&gt;;
抄送:&nbsp;"吴艳辉"<1613476341@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taosdata/TDengine] query  alert  "DB error: Invalid Vgroup ID " (#4929)





 
最近还有这个问题吗？

**Comment by shaoguanlee** [comment]
我这边也发现了这个问题,不过不是在查询时,而是在数据插入时发生的
`
Caused by: java.sql.SQLException: TDengine ERROR (503): Invalid Vgroup ID
at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:73)
at com.taosdata.jdbc.rs.RestfulStatement.executeOneUpdate(RestfulStatement.java:129)
at com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:50)
at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:546)
at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:543)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)
... 38 more
`
`
taos> select server_version();
 server_version() |
===================
 2.0.20.12        |
Query OK, 1 row(s) in set (0.000182s)
`
