### ISSUE TITLE
flume 加载taos.so出现java.lang.UnsatisfiedLinkError: no taos in java.library.path

### ISSUE THREAD

**Issue by dacaibi2019** [taosdata/TDengine#5002]
# flume 加载taos.so出现java.lang.UnsatisfiedLinkError: no taos in java.library.path

## 一、环境说明：

| 服务端环境          | 客户端环境：        |
| ------------------- | ------------------- |
| linux: 7.6          | linux: 7.6          |
| taos server: 2.0.10 | taos client: 2.0.10 |
|                     | flume: 1.9.0        |

## 二、目标

```
通过flume收集日志数据，经过自定义sink处理，把处理的结果直接插入到TDengine上去分析处理。
```

## 三、问题

```
开发完的代码打成jar包放到flume的lib文件中，写好flume的配置文件，启动后一直报 java.lang.UnsatisfiedLinkError: no taos in java.library.path
```

## 四、分析过程

当看到这个错误，分析能引起错误的原因有几个方面：

1. 客户端没有安装好，缺少libtaos.so

2. 程序在加载动态库去搜寻没有搜到。

  解决的思路是：

1.    验证linux客户端。
2.    让系统加载可以搜寻到动态库的位置。

五、具体做法

1. 验证linux客户端

   我用taos -H tdserver  直接能连接上，并且能操作。

   用官方给的例子，打成jar包在linux上运行也能成功。

   在linux能执行成功：

   ![1611297785386](C:\Users\ADMINI~1\AppData\Local\Temp\1611297785386.png)

代码如下：

```java
package com.taosdata.example;

import com.taosdata.jdbc.TSDBDriver;

import java.sql.*;
import java.util.Properties;

public class JdbcChecker {
    private static String host;
    private static String dbName = "test";
    private static String tbName = "weather";
    private Connection connection;

    /**
     * get connection
     **/
    private void init() {
        try {
            Class.forName("com.taosdata.jdbc.TSDBDriver");
            Properties properties = new Properties();
            properties.setProperty(TSDBDriver.PROPERTY_KEY_HOST, host);
            properties.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
            properties.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
            properties.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
            System.out.println("get connection starting...");
            connection = DriverManager.getConnection("jdbc:TAOS://" + host + ":0/", properties);
            if (connection != null)
                System.out.println("[ OK ] Connection established.");
        } catch (ClassNotFoundException | SQLException e) {
            throw new RuntimeException("connection failed: " + host);
        }
    }

    /**
     * create database
     */
    private void createDatabase() {
        String sql = "create database if not exists " + dbName;
        exuete(sql);
    }

    /**
     * use database
     */
    private void useDatabase() {
        String sql = "use " + dbName;
        exuete(sql);
    }

    /**
     * select
     */
    private void checkSelect() {
        final String sql = "select * from test.weather;";
        executeQuery(sql);
    }

    private void executeQuery(String sql) {
        try (Statement statement = connection.createStatement()) {
            long start = System.currentTimeMillis();
            ResultSet resultSet = statement.executeQuery(sql);
            long end = System.currentTimeMillis();
            printSql(sql, true, (end - start));
            printResult(resultSet);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void printResult(ResultSet resultSet) throws SQLException {
        ResultSetMetaData metaData = resultSet.getMetaData();
        while (resultSet.next()) {
            for (int i = 1; i <= metaData.getColumnCount(); i++) {
                String columnLabel = metaData.getColumnLabel(i);
                String value = resultSet.getString(i);
                System.out.printf("%s: %s\t", columnLabel, value);
            }
            System.out.println();
        }
    }

    private String formatString(String str) {
        StringBuilder sb = new StringBuilder();
        int blankCnt = (26 - str.length()) / 2;
        for (int j = 0; j < blankCnt; j++)
            sb.append(" ");
        sb.append(str);
        for (int j = 0; j < blankCnt; j++)
            sb.append(" ");
        sb.append("|");
        return sb.toString();
    }


    /**
     * insert
     */
    private void checkInsert() {
        final String sql = "insert into test.weather (ts, temperature, humidity) values(now, 20.5, 34);";
        exuete(sql);
    }

    /**
     * create table
     */
    private void createTable() {
        final String sql = "create table if not exists " + dbName + "." + tbName + " (ts timestamp, temperature float, humidity int);";
        exuete(sql);
    }

    private final void printSql(String sql, boolean succeed, long cost) {
        System.out.println("[ " + (succeed ? "OK" : "ERROR!") + " ] time cost: " + cost + " ms, execute statement ====> " + sql);
    }

    private final void exuete(String sql) {
        try (Statement statement = connection.createStatement()) {
            long start = System.currentTimeMillis();
            boolean execute = statement.execute(sql);
            long end = System.currentTimeMillis();
            printSql(sql, execute, (end - start));
        } catch (SQLException e) {
            e.printStackTrace();
            
        }
    }

    private void close() {
        try {
            if (connection != null) {
                this.connection.close();
                System.out.println("connection closed.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void checkDropTable() {
        final String sql = "drop table if exists " + dbName + "." + tbName + "";
        exuete(sql);
    }

    public static void main(String[] args) {
        for (int i = 0; i < args.length; i++) {
            if ("-host".equalsIgnoreCase(args[i]) && i < args.length - 1) {
                host = args[++i];
            }
            if ("-db".equalsIgnoreCase(args[i]) && i < args.length - 1) {
                dbName = args[++i];
            }
            if ("-t".equalsIgnoreCase(args[i]) && i < args.length - 1) {
                tbName = args[++i];
            }
        }

        if (host == null) {
            System.out.println("Usage: java -jar JDBCConnectorChecker.jar -host <hostname>");
            return;
        }

        JdbcChecker checker = new JdbcChecker();
        checker.init();
        checker.createDatabase();
        checker.useDatabase();
        checker.checkDropTable();
        checker.createTable();
        checker.checkInsert();
        checker.checkSelect();
        checker.checkDropTable();
        checker.close();
    }

}
```

2. 让系统加载可以搜寻到动态库的位置。

   taos.so 在/lib/ 、/usr/lib/   /usr/lib64/都有

   a. 设置LD_LIBRARY_PATH  重新启动flume仍然报以上错误。     

```shell
export LD_LIBRARY_PATH=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
```

​      b.设置/etch/ld.so.conf  重新启动flume仍然报以上错误。

```shell
include ld.so.conf.d/*.conf
/usr/lib/
/usr/lib64/

设置完后用ldconfig让其生效
```

​    c.把动态库放到默认路径下/lib    /usr/lib    重新启动flume仍然报以上错误。

   经过查询这些位置都已经有动态库

   d.在代码里设置java.library.path的环境变量，重新启动flume仍然报以上错误。

```java
System.setProperty("java.library.path","/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib");
```

   f. 修改flum-ng命令的环境变量，重新启动flume仍然报以上错误。

```shell
set_LD_LIBRARY_PATH(){
#Append the FLUME_JAVA_LIBRARY_PATH to whatever the user may have specified in
#flume-env.sh
  if [ -n "${FLUME_JAVA_LIBRARY_PATH}" ]; then
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${FLUME_JAVA_LIBRARY_PATH}"
  fi
  export LD_LIBRARY_PATH="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib:${LD_LIBRARY_PATH}:${FLUME_JAVA_LIBRARY_PATH}"
}
```

自定义sink代码如下：

```java
package com.ztxa.sink;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

import com.taosdata.jdbc.TSDBDriver;
import org.apache.flume.Channel;
import org.apache.flume.Context;
import org.apache.flume.Event;
import org.apache.flume.EventDeliveryException;
import org.apache.flume.Transaction;
import org.apache.flume.conf.Configurable;
import org.apache.flume.sink.AbstractSink;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Preconditions;

public class TaosSinker extends AbstractSink implements Configurable {
    private static final Logger logger = LoggerFactory.getLogger(TaosSinker.class);
    private Connection connection;
    private static String host ="tbserver";
    private Statement stmt;
    private String columnName;
    private String url;
    private String user;
    private String password;
    private String tableName;

    // 在整个sink结束时执行一遍
    @Override
    public synchronized void stop() {
        try {
            if (connection != null) {
                this.connection.close();
                System.out.println("connection closed.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        super.stop();
    }

    // 在整个sink开始时执行一遍，用来初始化数据库连接
    @Override
    public synchronized void start() {
        // TODO Auto-generated method stub
        super.start();
        try {
            setEnv();
            System.setProperty("java.library.path","/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib");
            logger.error(System.getProperty("java.library.path"));
//            System.load("/usr/lib64/libtaos.so");
            Class.forName("com.taosdata.jdbc.TSDBDriver");
            Properties properties = new Properties();
            properties.setProperty(TSDBDriver.PROPERTY_KEY_HOST, host);
            properties.setProperty(TSDBDriver.PROPERTY_KEY_CHARSET, "UTF-8");
            properties.setProperty(TSDBDriver.PROPERTY_KEY_LOCALE, "en_US.UTF-8");
            properties.setProperty(TSDBDriver.PROPERTY_KEY_TIME_ZONE, "UTC-8");
            System.out.println("get connection starting...");

            connection = DriverManager.getConnection("jdbc:TAOS://" + host + ":0/", properties);
            if (connection != null)
                logger.error("[ OK ] Connection established.");
        } catch (ClassNotFoundException | SQLException e) {
            throw new RuntimeException("connection failed: " + host);
        }

    }

    // 不断循环调用，处理消息Event（本例就是插入数据库）
    public Status process() throws EventDeliveryException {
        //事务，
        Channel ch = getChannel();
        Transaction txn = ch.getTransaction();
        Event event = null;
        txn.begin();
        while (true) {
            event = ch.take();
            if (event != null) {
                break;
            }
        }
        try {
            String rawbody = new String(event.getBody());
            final String sql = "insert into test.weather (ts, temperature, humidity) values(now, 20.5, "+rawbody+");";
            logger.error("sql:"+sql);
            exuete(sql);
            return Status.READY;
        } catch (Throwable th) {
            txn.rollback();

            if (th instanceof Error) {
                throw (Error) th;
            } else {
                throw new EventDeliveryException(th);
            }
        } finally {
            txn.close();
        }

    }
    //从配置文件中读取各种属性，并进行一些非空验证
    public void configure(Context context) {
        url = context.getString("url");
        Preconditions.checkNotNull(url, "url must be set!!");
        user = context.getString("user");
        Preconditions.checkNotNull(user, "user must be set!!");
        password = context.getString("password");
    }
    private final void exuete(String sql) {
        try (Statement statement = connection.createStatement()) {
            long start = System.currentTimeMillis();
            boolean execute = statement.execute(sql);
            long end = System.currentTimeMillis();
            printSql(sql, execute, (end - start));
        } catch (SQLException e) {
            e.printStackTrace();

        }
    }

    private final void printSql(String sql, boolean succeed, long cost) {
        logger.error("[ " + (succeed ? "OK" : "ERROR!") + " ] time cost: " + cost + " ms, execute statement ====> " + sql);
    }

    /***
     * 设置LD_LIBBRARY_PATH的加载路径
     */
    private final void setEnv(){
        ProcessBuilder pb = new ProcessBuilder("executable.so");
    }

}
```

flume的配置如下：

```shell
#agent2 name
agent2.sources=source2
agent2.sinks=sink2
agent2.channels=channel2

#Spooling Directory
#set source2
agent2.sources.source2.type=spooldir
agent2.sources.source2.spoolDir=/home/test/exec/log
agent2.sources.source2.channels=channel2
agent2.sources.source2.fileHeader = false
agent2.sources.source2.interceptors = i1
agent2.sources.source2.interceptors.i1.type = timestamp

#set sink2
agent2.sinks.sink2.type=com.ztxa.sink.TaosSinker
agent2.sinks.sink2.url =jdbc:TAOS://tdserver:6030/cms
agent2.sinks.sink2.user=abcd
agent2.sinks.sink2.password=111111
agent2.sinks.sink2.channel=channel2

#set channel2
agent2.channels.channel2.type=memory
agent2.channels.channel2.capacity=10000
agent2.channels.channel2.transactionCapacity=1000
agent2.channels.channel2.keep-alive=30
```

寻求下帮助，还有没有别的办法让能解决这个问题。

错误日志如下：

```shell
[root@root flume]# bin/flume-ng agent -c ./conf -f ./conf/tao.conf -Dflume.root.logger=INFO,console -n agent2
Info: Including Hive libraries found via () for Hive access
+ exec /usr/local/jdk1.8/bin/java -Xmx20m -Dflume.root.logger=INFO,console -cp '/opt/flume/conf:/opt/flume/lib/*:/lib/*' -Djava.library.path= org.apache.flume.node.Application -f ./conf/tao.conf -n agent2
2021-01-22 15:07:20,468 (lifecycleSupervisor-1-0) [INFO - org.apache.flume.node.PollingPropertiesFileConfigurationProvider.start(PollingPropertiesFileConfigurationProvider.java:62)] Configuration provider starting
2021-01-22 15:07:20,473 (conf-file-poller-0) [INFO - org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:138)] Reloading configuration file:./conf/tao.conf
2021-01-22 15:07:20,479 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:source2
2021-01-22 15:07:20,480 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:sink2
2021-01-22 15:07:20,480 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:source2
2021-01-22 15:07:20,480 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:channel2
2021-01-22 15:07:20,481 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty(FlumeConfiguration.java:1117)] Added sinks: sink2 Agent: agent2
2021-01-22 15:07:20,481 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:source2
2021-01-22 15:07:20,481 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:sink2
2021-01-22 15:07:20,481 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:sink2
2021-01-22 15:07:20,481 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:source2
2021-01-22 15:07:20,481 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:sink2
2021-01-22 15:07:20,481 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:channel2
2021-01-22 15:07:20,482 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:source2
2021-01-22 15:07:20,482 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:channel2
2021-01-22 15:07:20,482 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:channel2
2021-01-22 15:07:20,484 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:source2
2021-01-22 15:07:20,484 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addComponentConfig(FlumeConfiguration.java:1203)] Processing:sink2
2021-01-22 15:07:20,484 (conf-file-poller-0) [WARN - org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.validateConfigFilterSet(FlumeConfiguration.java:623)] Agent configuration for 'agent2' has no configfilters.
2021-01-22 15:07:20,501 (conf-file-poller-0) [INFO - org.apache.flume.conf.FlumeConfiguration.validateConfiguration(FlumeConfiguration.java:163)] Post-validation flume configuration contains configuration for agents: [agent2]
2021-01-22 15:07:20,501 (conf-file-poller-0) [INFO - org.apache.flume.node.AbstractConfigurationProvider.loadChannels(AbstractConfigurationProvider.java:151)] Creating channels
2021-01-22 15:07:20,507 (conf-file-poller-0) [INFO - org.apache.flume.channel.DefaultChannelFactory.create(DefaultChannelFactory.java:42)] Creating instance of channel channel2 type memory
2021-01-22 15:07:20,511 (conf-file-poller-0) [INFO - org.apache.flume.node.AbstractConfigurationProvider.loadChannels(AbstractConfigurationProvider.java:205)] Created channel channel2
2021-01-22 15:07:20,511 (conf-file-poller-0) [INFO - org.apache.flume.source.DefaultSourceFactory.create(DefaultSourceFactory.java:41)] Creating instance of source source2, type spooldir
2021-01-22 15:07:20,525 (conf-file-poller-0) [INFO - org.apache.flume.sink.DefaultSinkFactory.create(DefaultSinkFactory.java:42)] Creating instance of sink: sink2, type: com.ztxa.sink.TaosSinker
2021-01-22 15:07:20,529 (conf-file-poller-0) [INFO - org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:120)] Channel channel2 connected to [source2, sink2]
2021-01-22 15:07:20,536 (conf-file-poller-0) [INFO - org.apache.flume.node.Application.startAllComponents(Application.java:162)] Starting new configuration:{ sourceRunners:{source2=EventDrivenSourceRunner: { source:Spool Directory source source2: { spoolDir: /home/test/exec/log } }} sinkRunners:{sink2=SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@11bdb69f counterGroup:{ name:null counters:{} } }} channels:{channel2=org.apache.flume.channel.MemoryChannel{name: channel2}} }
2021-01-22 15:07:20,536 (conf-file-poller-0) [INFO - org.apache.flume.node.Application.startAllComponents(Application.java:169)] Starting Channel channel2
2021-01-22 15:07:20,536 (conf-file-poller-0) [INFO - org.apache.flume.node.Application.startAllComponents(Application.java:184)] Waiting for channel: channel2 to start. Sleeping for 500 ms
2021-01-22 15:07:20,588 (lifecycleSupervisor-1-2) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.register(MonitoredCounterGroup.java:119)] Monitored counter group for type: CHANNEL, name: channel2: Successfully registered new MBean.
2021-01-22 15:07:20,588 (lifecycleSupervisor-1-2) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.start(MonitoredCounterGroup.java:95)] Component type: CHANNEL, name: channel2 started
2021-01-22 15:07:21,037 (conf-file-poller-0) [INFO - org.apache.flume.node.Application.startAllComponents(Application.java:196)] Starting Sink sink2
2021-01-22 15:07:21,037 (conf-file-poller-0) [INFO - org.apache.flume.node.Application.startAllComponents(Application.java:207)] Starting Source source2
2021-01-22 15:07:21,037 (lifecycleSupervisor-1-0) [ERROR - com.ztxa.sink.TaosSinker.start(TaosSinker.java:55)] /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2021-01-22 15:07:21,038 (lifecycleSupervisor-1-4) [INFO - org.apache.flume.source.SpoolDirectorySource.start(SpoolDirectorySource.java:85)] SpoolDirectorySource source starting with directory: /home/test/exec/log
get connection starting...
2021-01-22 15:07:21,080 (lifecycleSupervisor-1-0) [ERROR - org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)] Unable to start SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@11bdb69f counterGroup:{ name:null counters:{} } } - Exception follows.
java.lang.UnsatisfiedLinkError: no taos in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:25)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:119)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.ztxa.sink.TaosSinker.start(TaosSinker.java:65)
	at org.apache.flume.sink.DefaultSinkProcessor.start(DefaultSinkProcessor.java:45)
	at org.apache.flume.SinkRunner.start(SinkRunner.java:79)
	at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:249)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-01-22 15:07:21,084 (lifecycleSupervisor-1-0) [WARN - org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:258)] Component SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@11bdb69f counterGroup:{ name:null counters:{} } } stopped, since it could not besuccessfully started due to missing dependencies
2021-01-22 15:07:21,083 (lifecycleSupervisor-1-4) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.register(MonitoredCounterGroup.java:119)] Monitored counter group for type: SOURCE, name: source2: Successfully registered new MBean.
2021-01-22 15:07:21,088 (lifecycleSupervisor-1-4) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.start(MonitoredCounterGroup.java:95)] Component type: SOURCE, name: source2 started
^C2021-01-22 15:07:25,354 (agent-shutdown-hook) [INFO - org.apache.flume.node.Application.stopAllComponents(Application.java:125)] Shutting down configuration: { sourceRunners:{source2=EventDrivenSourceRunner: { source:Spool Directory source source2: { spoolDir: /home/test/exec/log } }} sinkRunners:{sink2=SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@11bdb69f counterGroup:{ name:null counters:{} } }} channels:{channel2=org.apache.flume.channel.MemoryChannel{name: channel2}} }
2021-01-22 15:07:25,354 (agent-shutdown-hook) [INFO - org.apache.flume.node.Application.stopAllComponents(Application.java:129)] Stopping Source source2
2021-01-22 15:07:25,354 (agent-shutdown-hook) [INFO - org.apache.flume.lifecycle.LifecycleSupervisor.unsupervise(LifecycleSupervisor.java:169)] Stopping component: EventDrivenSourceRunner: { source:Spool Directory source source2: { spoolDir: /home/test/exec/log } }
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:149)] Component type: SOURCE, name: source2 stopped
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:155)] Shutdown Metric for type: SOURCE, name: source2. source.start.time == 1611299241088
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:161)] Shutdown Metric for type: SOURCE, name: source2. source.stop.time == 1611299245355
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.append-batch.accepted == 0
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.append-batch.received == 0
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.append.accepted == 0
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.append.received == 0
2021-01-22 15:07:25,355 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.channel.write.fail == 0
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.event.read.fail == 0
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.events.accepted == 0
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.events.received == 0
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.generic.processing.fail == 0
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: SOURCE, name: source2. src.open-connection.count == 0
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.source.SpoolDirectorySource.stop(SpoolDirectorySource.java:138)] SpoolDir source source2 stopped. Metrics: SOURCE:source2{src.events.accepted=0, src.open-connection.count=0, src.append.received=0, src.channel.write.fail=0, src.append-batch.received=0, src.generic.processing.fail=0, src.append-batch.accepted=0, src.append.accepted=0, src.events.received=0, src.event.read.fail=0}
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.node.Application.stopAllComponents(Application.java:139)] Stopping Sink sink2
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.lifecycle.LifecycleSupervisor.unsupervise(LifecycleSupervisor.java:169)] Stopping component: SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@11bdb69f counterGroup:{ name:null counters:{} } }
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.node.Application.stopAllComponents(Application.java:149)] Stopping Channel channel2
2021-01-22 15:07:25,356 (agent-shutdown-hook) [INFO - org.apache.flume.lifecycle.LifecycleSupervisor.unsupervise(LifecycleSupervisor.java:169)] Stopping component: org.apache.flume.channel.MemoryChannel{name: channel2}
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:149)] Component type: CHANNEL, name: channel2 stopped
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:155)] Shutdown Metric for type: CHANNEL, name: channel2. channel.start.time == 1611299240588
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:161)] Shutdown Metric for type: CHANNEL, name: channel2. channel.stop.time == 1611299245357
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: CHANNEL, name: channel2. channel.capacity == 10000
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: CHANNEL, name: channel2. channel.current.size == 0
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: CHANNEL, name: channel2. channel.event.put.attempt == 0
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: CHANNEL, name: channel2. channel.event.put.success == 0
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: CHANNEL, name: channel2. channel.event.take.attempt == 0
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.stop(MonitoredCounterGroup.java:177)] Shutdown Metric for type: CHANNEL, name: channel2. channel.event.take.success == 0
2021-01-22 15:07:25,357 (agent-shutdown-hook) [INFO - org.apache.flume.lifecycle.LifecycleSupervisor.stop(LifecycleSupervisor.java:78)] Stopping lifecycle supervisor 10
2021-01-22 15:07:25,359 (agent-shutdown-hook) [INFO - org.apache.flume.node.PollingPropertiesFileConfigurationProvider.stop(PollingPropertiesFileConfigurationProvider.java:84)] Configuration provider stopping

```

**Comment by zyyang-taosdata** [comment]
尝试将libtaos.so放入到java/jre/amd64目录下

**Comment by holypost** [comment]
> 尝试将libtaos.so放入到java/jre/amd64目录下
我是 docker安装的 tdengine，进入该镜像，目录都有哪个.so文件，意思是要拷贝到宿主机的相关目录么
