### ISSUE TITLE
Cause: java.sql.SQLException: TDengine Error: Unable to establish connection

### ISSUE THREAD

**Issue by jinglings** [taosdata/TDengine#5075]
环境介绍：
1.使用springboot + mybatisPlus + taos, 使用windows 连接centos,windows客户端也安装了，服务端也设置了fqdn
2.taos版本为2.0.5.1；
错误结果:  用户可以连接登录成功，获取到connection，**但是执行sql查询的时候报错：Cause: java.sql.SQLException: TDengine Error: Unable to establish [connection；请问是什么原因？**

**Comment by sangshuduo** [comment]
2.0.5.1太老了，中间解决了很多bug，请升级到最新版本再试一下

**Comment by chenqunjian** [comment]
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: TDengine Error: Unable to establish connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:84)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:70)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 42 more
Caused by: java.sql.SQLException: TDengine Error: Unable to establish connection
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:105)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:66)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:52)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:121)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)

**Comment by chenqunjian** [comment]
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: TDengine Error: Unable to establish connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:84)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:70)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 42 more
Caused by: java.sql.SQLException: TDengine Error: Unable to establish connection
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:105)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:66)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:52)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:121)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)


我也遇到这样问题  JDBC连接用的是2.0.19
