### ISSUE TITLE
Use JDBC-RESTful to prompt when creating a table：Database not specified or available

### ISSUE THREAD

**Issue by HendSame** [taosdata/TDengine#5257]
问题：
使用JDBC-RESTful在创建表的时候提示：Database not specified or available

TDengine docker 安装的：
docker run -d -p 6030:6030 -p 6035:6035 -p 6041:6041 -p 6030-6040:6030-6040/udp tdengine/tdengine

JDBC-RESTful
````
      <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.18</version>
        </dependency>
````
数据库连接池：HikariDataSource

现象：
1、数据连接是可以创建成功的，说明服务端是正常
2、但是创建表时报错了

SQL 

````
CREATE TABLE IF NOT EXISTS alarm_record (
   ts TIMESTAMP, 
   scope INT,
   name BINARY(200),
   id0 BINARY(200),
   id1 BINARY(200),
   start_time BIGINT,
   alarm_message BINARY(200),
   rule_name BINARY(200),
   ime_bucket BIGINT
   );
````

**Comment by moziie** [comment]
没有指定使用哪个数据库吧

**Comment by HendSame** [comment]
@moziie 看了源码（com.taosdata.jdbc.rs.RestfulStatement#executeUpdate(String sql),会自己执行一次：use databases； 

![image](https://user-images.githubusercontent.com/9264192/109110205-a2b96180-7771-11eb-96f2-843b77126b03.png)

**Comment by Shawshank-Smile** [comment]
指定一下库试试。

**Comment by jadedrip** [comment]
@Shawshank-Smile 从源码看，底层用了 http链接池来执行命令，这可能导致执行 use database 的链接并不是 create table 的链接，感觉你们的这个 java 驱动有问题。

**Comment by HendSame** [comment]
是的，不知道有没有人在用这个，指定了库也是不行，时好时坏

**Comment by IZ-ONE** [comment]
你这个问题解决了么,我现在也碰到了这个问题，在进行数据同步时: 源库是2.0.15，使用jdcb进行数据查询 ；目标库是2.1.30版本，使用Restful进行数据插入。 源头进行查询导出时一切正常，但是在目标库使用Restful进行插入时就会出现这个错误：Database not specified or available（一部分数据成功一部分出错，就算INSERT时候是 DB.TABLE 形式指定表明也没用）

**Comment by jadedrip** [comment]
这个问题还没解决吗？个人觉得是 jdbc-restful 的问题，我去看了它的代码，他执行命令用的 http 链接池，所以我怀疑是执行 use databasse 以后，切换了个链接执行下一个命令，导致新命令执行前没调用过 use database. 
不过我没用过 jdbc-restful ，也只是怀疑

**Comment by IZ-ONE** [comment]
源码这里有一段这样的；不知道这有何意义
![QQ截图20210712100308](https://user-images.githubusercontent.com/49674640/125219985-7c4b2b80-e2f8-11eb-955c-9ba1f07ec912.png)

**Comment by zyyang-taosdata** [comment]
> 这个问题还没解决吗？个人觉得是 jdbc-restful 的问题，我去看了它的代码，他执行命令用的 http 链接池，所以我怀疑是执行 use databasse 以后，切换了个链接执行下一个命令，导致新命令执行前没调用过 use database.
> 不过我没用过 jdbc-restful ，也只是怀疑

（1）如果是使用2.1.3.0之前的版本，建议更换jdbc到taos-jdbcdriver-2.0.30
（2）同时，在sql中指定database的名称来避免这个错误。例如：
insert into dbname.tableName using dbname.stablename values(...)

**Comment by xleili** [comment]
restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。

**Comment by IZ-ONE** [comment]
> restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。

我试过 insert into db.table，甚至还试过这种看起来很奇葩的 use db; insert into.....；都没用，还是会有部分成功部分报错的情况，后者就更奇怪(use db, insert into....)，在命令行能执行成功，用rest也成功，但是没有任何数据进去

**Comment by IZ-ONE** [comment]
> restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。
我试过 insert into db.table，甚至还试过这种看起来很奇葩的 use db; insert into.....；都没用，还是会有部分成功部分报错的情况，后者就更奇怪(use db, insert into....)，在命令行能执行成功，数据能进去；用rest也成功，但是没有任何数据进去

**Comment by IZ-ONE** [comment]
> restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。
我试过 insert into db.table，甚至还试过这种看起来很奇葩的 use db; insert into.....；都没用，还是会有部分成功部分报错的情况，后者就更奇怪(use db, insert into....)，在命令行能执行成功数据也进去了；用rest也成功，但是没有任何数据进去

**Comment by IZ-ONE** [comment]
> restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。

我试过insert into db.table 这种形式，依然部分成功部分报错；而且我在命令尝试过，如果你没有事先执行use db命令，直接执行 insert into db.table这种语句会直接报错；甚至 use db;insert into table.... 这种当成一条sql执行也不行(在命令行是成功的，用rest也成功但是没数据进去)

**Comment by zyyang-taosdata** [comment]
> > restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。
> 
> 我试过insert into db.table 这种形式，依然部分成功部分报错；而且我在命令尝试过，如果你没有事先执行use db命令，直接执行 insert into db.table这种语句会直接报错；甚至 use db;insert into table.... 这种当成一条sql执行也不行(在命令行是成功的，用rest也成功但是没数据进去)

（1）尝试在postman或者其他restful工具中，使用TDengine的restful接口来执行你的SQL，如果有执行成功，能数据没有进去的情况，请查看服务端的taosdlog日志（一般位于/var/log/taos/taosdlogx.x）。
（2）建议将server端的日志登记配置成135，这样能打印更多日志信息。配置/etc/taos/taos.cfg，将debugFlag参数的注释打开，并设置为135,重启taosd进程，使用restful接口执行你报错的sql，在日志中查找错误信息。

**Comment by IZ-ONE** [comment]
> > > restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。
> > 
> > 
> > 我试过insert into db.table 这种形式，依然部分成功部分报错；而且我在命令尝试过，如果你没有事先执行use db命令，直接执行 insert into db.table这种语句会直接报错；甚至 use db;insert into table.... 这种当成一条sql执行也不行(在命令行是成功的，用rest也成功但是没数据进去)
> 
> （1）尝试在postman或者其他restful工具中，使用TDengine的restful接口来执行你的SQL，如果有执行成功，能数据没有进去的情况，请查看服务端的taosdlog日志（一般位于/var/log/taos/taosdlogx.x）。
> （2）建议将server端的日志登记配置成135，这样能打印更多日志信息。配置/etc/taos/taos.cfg，将debugFlag参数的注释打开，并设置为135,重启taosd进程，使用restful接口执行你报错的sql，在日志中查找错误信息。

更换成了2.0.30驱动，并且Insert语句使用了db.table形式指定表名，依然会出现如下形式的错误(错误日志取自服务端日志文件)：
![QQ图片20210712144036](https://user-images.githubusercontent.com/49674640/125242345-2342be00-e31f-11eb-8237-7d1c55200b1e.png)

[error.zip](https://github.com/taosdata/TDengine/files/6799087/error.zip)

**Comment by xleili** [comment]
> > > > restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。
> > > 
> > > 
> > > 我试过insert into db.table 这种形式，依然部分成功部分报错；而且我在命令尝试过，如果你没有事先执行use db命令，直接执行 insert into db.table这种语句会直接报错；甚至 use db;insert into table.... 这种当成一条sql执行也不行(在命令行是成功的，用rest也成功但是没数据进去)
> > 
> > 
> > （1）尝试在postman或者其他restful工具中，使用TDengine的restful接口来执行你的SQL，如果有执行成功，能数据没有进去的情况，请查看服务端的taosdlog日志（一般位于/var/log/taos/taosdlogx.x）。
> > （2）建议将server端的日志登记配置成135，这样能打印更多日志信息。配置/etc/taos/taos.cfg，将debugFlag参数的注释打开，并设置为135,重启taosd进程，使用restful接口执行你报错的sql，在日志中查找错误信息。
> 
> 更换成了2.0.30驱动，并且Insert语句使用了db.table形式指定表名，依然会出现如下形式的错误(错误日志取自服务端日志文件)：
> ![QQ图片20210712144036](https://user-images.githubusercontent.com/49674640/125242345-2342be00-e31f-11eb-8237-7d1c55200b1e.png)
> 
> [error.zip](https://github.com/taosdata/TDengine/files/6799087/error.zip)

从报错的日志来看是你的表不存在的错。 首先要确定你的表存在，然后再看你的sql写的对不对。你把报错的sql拿到taos shell （window 客户端直接打开taos.exe,linux 直接输入taos ）去执行，看看是否还报table not exists的错。

**Comment by IZ-ONE** [comment]
> > > > > restful写sql的时候需要指定db_name; eg:insert into db.table_name (col1,col2....) values(x,y,z...);源码中写了use databases；你不指定db的话，程序是不会知道是哪个db的。
> > > > 
> > > > 
> > > > 我试过insert into db.table 这种形式，依然部分成功部分报错；而且我在命令尝试过，如果你没有事先执行use db命令，直接执行 insert into db.table这种语句会直接报错；甚至 use db;insert into table.... 这种当成一条sql执行也不行(在命令行是成功的，用rest也成功但是没数据进去)
> > > 
> > > 
> > > （1）尝试在postman或者其他restful工具中，使用TDengine的restful接口来执行你的SQL，如果有执行成功，能数据没有进去的情况，请查看服务端的taosdlog日志（一般位于/var/log/taos/taosdlogx.x）。
> > > （2）建议将server端的日志登记配置成135，这样能打印更多日志信息。配置/etc/taos/taos.cfg，将debugFlag参数的注释打开，并设置为135,重启taosd进程，使用restful接口执行你报错的sql，在日志中查找错误信息。
> > 
> > 
> > 更换成了2.0.30驱动，并且Insert语句使用了db.table形式指定表名，依然会出现如下形式的错误(错误日志取自服务端日志文件)：
> > ![QQ图片20210712144036](https://user-images.githubusercontent.com/49674640/125242345-2342be00-e31f-11eb-8237-7d1c55200b1e.png)
> > [error.zip](https://github.com/taosdata/TDengine/files/6799087/error.zip)
> 
> 从报错的日志来看是你的表不存在的错。 首先要确定你的表存在，然后再看你的sql写的对不对。你把报错的sql拿到taos shell （window 客户端直接打开taos.exe,linux 直接输入taos ）去执行，看看是否还报table not exists的错。

正因为表是存在的这问题才令人困惑。目标表是一张超级表，事先已经建立好的，然后对这张超级表不断插入数据(指定tag 和表名后子表是会自动建立的)，但是有部分数据可以成功保存，有部分会报错未指定数据库(Restful返回的Http响应就是这个错误)

**Comment by shaoguanlee** [comment]
同样遇到这个问题;
数据库url配置为:
jdbc:TAOS-RS://localhost:6041/pro_iot?timezone=Asia/Beijing&charset=utf-8
url里已经指定了数据库名字

在执行sql时偶尔会出现 TDengine ERROR (217): Database not specified or available 这样的错误

我是这么理解的:
1)我数据库连接里已经指定了数据库名,
2)如果像上面说的要先use db,那么为什么我没有手动use db,绝大部分sql都能正确执行,就是偶尔有sql报Database not specified or available的错误

驱动版本为:2.0.33

```
Caused by: java.sql.SQLException: TDengine ERROR (217): Database not specified or available
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:73)
	at com.taosdata.jdbc.rs.RestfulStatement.executeOneUpdate(RestfulStatement.java:129)
	at com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:50)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:546)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:543)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)
	... 38 more

```

**Comment by shaoguanlee** [comment]
这几天发现就算每次都提前使用use db;也会出现这个问题;当springboot项目刚启动时立刻执行插入必然会出现这个问题;而且每次都必然出现至少一次;而且只在刚启动的时候出现;也不是第一条sql就失败;


```
2021-08-20 14:35:43.617 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [use pro_iot;]
2021-08-20 14:35:43.619 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [INSERT INTO ....
2021-08-20 14:35:43.634 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [use pro_iot;]
2021-08-20 14:35:43.637 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [INSERT INTO .....
2021-08-20 14:35:43.642 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [use pro_iot;]
2021-08-20 14:35:43.645 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [INSERT INTO .....
2021-08-20 14:35:43.648 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [use pro_iot;]
2021-08-20 14:35:43.651 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [INSERT INTO .....
2021-08-20 14:35:43.660 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [use pro_iot;]
2021-08-20 14:35:43.664 DEBUG 21868 --- [pro-iot-exchange.message-1] o.s.jdbc.core.JdbcTemplate               : Executing SQL update [INSERT INTO .....
2021-08-20 14:35:43.733  WARN 21868 --- [pro-iot-exchange.message-1] c.p.taos.mq.pro_iot.ProIotMqConsumer     : 消息处理失败,错误类型:处理失败,异常信息:UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [INSERT INTO ...;]; SQL state []; error code [535]; TDengine ERROR (217): Database not specified or available; nested exception is java.sql.SQLException: TDengine ERROR (217): Database not specified or available
2021-08-20 14:35:44.138  INFO 21868 --- [RMI TCP Connection(1)-172.18.32.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-08-20 14:35:44.138  INFO 21868 --- [RMI TCP Connection(1)-172.18.32.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-08-20 14:35:44.139  INFO 21868 --- [RMI TCP Connection(1)-172.18.32.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
```

具体的sql语句我删掉了

**Comment by tankpanv** [comment]
同遇到这个问题，不知道各位解决没有

**Comment by zyyang-taosdata** [comment]
https://github.com/taosdata/TDengine/issues/4916

**Comment by zyyang-taosdata** [comment]
this issue was closed due to a lack of maintenance and sufficient information for a long time

**Comment by lijinzedev** [comment]
同遇到这个问题，不知道各位解决没有
