### ISSUE TITLE
 SQL state []; error code [-2147483628]; TDengine Error: Database not ready; nested exception is java.sql.SQLException: TDengine Error: Database not ready

### ISSUE THREAD

**Issue by sunyunsheng** [taosdata/TDengine#5260]
服务器64核处理器， 并发128个线程  往3个节点的集群中   每个线程都是执行批量插入，  数据库连接池使用druid，连接池初始化50个连接，最大为500  ,频繁的有些线程抛出了下面这种错误， 是啥原因？
2021-02-24 11:30:57.110 [pool-2-thread-19] ERROR com.jkr.monitor.provider.track.ConsumerQueue - 批量持久化位置信息至TDengine时出错，原因:
### SQL: insert into                       _15500021366506             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661482             USING d_track      
       TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366646             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)     
                   _155000213661569             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661067             USING d_track             TAGS (?)        
     values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661656             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15
5000213661704             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _1550002136611             USING d_track             TAGS (?)             values             
    (?, ?,?,?,                 ?,?,?,?)                        _1550002136643             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366107             U
SING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661222             USING d_track             TAGS (?)             values                 (?, ?,?,?,           
      ?,?,?,?)                        _155000213661858             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366276             USING d_track           
  TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366334             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)          
              _155000213661941             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661978             USING d_track             TAGS (?)             
values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661474             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _1550002
1366591             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661031             USING d_track             TAGS (?)             values                 
(?, ?,?,?,                 ?,?,?,?)                        _155000213661599             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661640             US
ING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366856             USING d_track             TAGS (?)             values                 (?, ?,?,?,             
    ?,?,?,?)                        _155000213661124             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661155             USING d_track            
 TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _1550002136657             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)            
            _155000213661201             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366183             USING d_track             TAGS (?)             val
ues                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366235             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _15500021366
1892             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)                        _155000213661913             USING d_track             TAGS (?)             values                 (?,
 ?,?,?,                 ?,?,?,?)                        _15500021366402             USING d_track             TAGS (?)             values                 (?, ?,?,?,                 ?,?,?,?)
### Cause: java.sql.SQLException: TDengine Error: Database not ready
; uncategorized SQLException; SQL state []; error code [-2147483628]; TDengine Error: Database not ready; nested exception is java.sql.SQLException: TDengine Error: Database not ready
java.sql.SQLException: TDengine Error: Database not ready
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:135)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:100)
	at com.taosdata.jdbc.SavedPreparedStatement.executeSql(SavedPreparedStatement.java:450)
	at com.taosdata.jdbc.SavedPreparedStatement.executeBatchInternal(SavedPreparedStatement.java:259)
	at com.taosdata.jdbc.TSDBPreparedStatement.execute(TSDBPreparedStatement.java:304)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3461)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	at sun.reflect.GeneratedMethodAccessor334.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy220.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy218.update(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy217.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	at com.sun.proxy.$Proxy163.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy169.batchInsert(Unknown Source)
	at com.jkr.monitor.provider.service.impl.LocationInfoServiceImpl.batchSaveLocation(LocationInfoServiceImpl.java:57)
	at com.jkr.monitor.provider.service.impl.LocationInfoServiceImpl$$FastClassBySpringCGLIB$$7c387e5c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.jkr.monitor.provider.service.impl.LocationInfoServiceImpl$$EnhancerBySpringCGLIB$$5b0ef0c4.batchSaveLocation(<generated>)
	at com.jkr.monitor.provider.track.ConsumerQueue.run(ConsumerQueue.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

![微信图片_20210224114542](https://user-images.githubusercontent.com/24600975/108944558-eccd1500-7695-11eb-9673-e52cdef07e6a.png)

note:  测试了另外一种情形，连接池初始化连接数 设置为200，就是能超过预知的128个并发入库线程数，  貌似就没有上面那个错误，  上面的错误现象 目前貌似只出在了 初始一段时间内， 之后就没再报这个错误 。 入库操作等不及连接池增加新的连接

**Comment by Shawshank-Smile** [comment]
Check the cluster status：
show dnodes；
show mnode；
show vgroups；
