### ISSUE TITLE
mac使用TAOS-RS连接数据库插入数据时报this operation is NOT supported currently!

### ISSUE THREAD

**Issue by zhanngyun** [taosdata/TDengine#5296]
td配置：
tdengine-server:
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      jdbc-url: jdbc:TAOS-RS://192.168.3.5:6041/test?charset=utf-8
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource

使用语言：Java

错误信息：
Exception in thread "pool-3-thread-5" org.springframework.dao.InvalidDataAccessApiUsageException: 
### Cause: java.sql.SQLFeatureNotSupportedException: this operation is NOT supported currently!
; this operation is NOT supported currently!; nested exception is java.sql.SQLFeatureNotSupportedException: this operation is NOT supported currently!

**Comment by zhanngyun** [comment]
驱动版本替换成2.0.20之后还是有问题
Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #6 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLFeatureNotSupportedException: this operation is NOT supported currently!
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:75)
	at org.apache.ibatis.scripting.defaults.DefaultParameterHandler.setParameters(DefaultParameterHandler.java:87)
	... 29 more

**Comment by X-Chuck** [comment]
INSERT INTO d1111 USING METERS TAGS (?, ?) VALUES (?, ?, ?);这个语句也是报同样的错误

**Comment by X-Chuck** [comment]
@zhanngyun 你的问题解决了吗？
