### ISSUE TITLE
Using crown or taos to connect to TDengine  ,sometimes it is slow

### ISSUE THREAD

**Issue by nieyuanqing** [taosdata/TDengine#5329]
Hi 
TDegnine版本：2.0.8.0， 采用crown或者 taos客户端连接TDengine，有时连接非常快，有时需要约3 ~ 4秒，什么原因会导致连接TDengine慢？

**Comment by yu285** [comment]
您好，或许是计算机资源不足，或许是数据库参数配置不合理。请提供具体信息，否则不易排查。

**Comment by nieyuanqing** [comment]
/etc/taos/taos.cfg仅配置了 ：
# first port number for the connection (12 continuous UDP/TCP port number are used) 
serverPort                6030

# log file's directory
logDir                    /opt/soft/taos/log

# data file's directory
dataDir                   /opt/soft/taos/data
其他全部默认配置。

连接数据的方式：
self.db = TdEngineDatabase(setting.taosdb_name, host=setting.taosdb_host)
self.db.connect()

报错信息：
Traceback (most recent call last):
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/data1/git_workspace/xxx/yyy/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by yu285** [comment]
可以提供一下TDengine客户端的日志吗？
