### ISSUE TITLE
java connect taos, report "TDengine Error: Unable to establish connection"

### ISSUE THREAD

**Issue by chenqunjian** [taosdata/TDengine#5441]
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: TDengine Error: Unable to establish connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:84)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:70)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 45 more
Caused by: java.sql.SQLException: TDengine Error: Unable to establish connection
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:105)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:66)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:52)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:121)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)

taos 连接jdbc 用的是
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.19</version>
        </dependency>

客户端用的是
TDengine-client-2.0.16.0-Windows-x64.exe
安装了能再客户端连接taos查询，但是再代码里面报上面错

**Comment by cpvmrd** [comment]
请参考这里的第5条检测一下：https://www.taosdata.com/cn/documentation/faq
