### ISSUE TITLE
When use RestDriver, if there is some special character, then can't connect 

### ISSUE THREAD

**Issue by shaoguanlee** [taosdata/TDengine#5487]
经过观察,发现RestDriver的登录使用的是如下接口:
http://host:6041/rest/login/${name}/${pass}
当存在特殊字符时,则会发生异常

具体信息如下:

```
taos> select server_version();
 server_version() |
===================
 2.0.16.0         |
Query OK, 1 row(s) in set (0.000097s)
```

```
<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.18</version>
</dependency>
```

当使用的密码带有特殊字符时,会报错如下
报错信息
```
2021-03-18 16:25:18.639  INFO 22584 --- [2)-172.30.240.1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
java.lang.IllegalArgumentException: Illegal character in path at index 43: http://localhost:6041/rest/login/root/xxxxx^20210318
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at com.taosdata.jdbc.rs.util.HttpClientPoolUtil.getRequest(HttpClientPoolUtil.java:150)
	at com.taosdata.jdbc.rs.util.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:179)
	at com.taosdata.jdbc.rs.RestfulDriver.connect(RestfulDriver.java:44)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:122)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:105)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:100)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:71)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:39)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:99)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:110)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:96)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:74)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:61)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:65)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:121)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:96)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 43: http://localhost:6041/rest/login/root/xxxxx^20210318
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 61 more
log:调用 HttpClientPoolUtil execute get request exception, url:http://localhost:6041/rest/login/root/mtech^20210318, exception:java.lang.IllegalArgumentException: Illegal character in path at index 43: http://localhost:6041/rest/login/root/mtech^20210318,cost time(ms):109

```

另外我要吐槽一下你们的Java版客户端,简直问题不要太多...
比如:
ResultSet 不支持 getObject,直接就抛出异常了
另外ResultSet 的 getString方法没有做 null 判断
class RestfulResultSet
```
    @Override
    public String getString(int columnIndex) throws SQLException {
        if (isClosed())
            throw new SQLException(TSDBConstants.WrapErrMsg(TSDBConstants.RESULT_SET_IS_CLOSED));

        if (columnIndex > resultSet.get(pos).size()) {
            throw new SQLException(TSDBConstants.WrapErrMsg("Column Index out of range, " + columnIndex + " > " + resultSet.get(pos).size()));
        }

        columnIndex = getTrueColumnIndex(columnIndex);
        return resultSet.get(pos).get(columnIndex).toString();    // line 144
    }
```
第144行 return resultSet.get(pos).get(columnIndex).toString();  如果get(columnIndex)为null时直接就NPE了

求解决方案!!!

**Comment by cpvmrd** [comment]
收到，我们检查一下再反馈。

**Comment by zyyang-taosdata** [comment]
把taos-jdbcdriver的版本更新到最新版本，上面说的：特殊字符、getObject、getString这些问题在后面的taosdriver里面都已经修改了

**Comment by zyyang-taosdata** [comment]
![image](https://user-images.githubusercontent.com/69311263/113234304-988c0500-92d3-11eb-9a9e-2180621ee8a7.png)
就这？

**Comment by zyyang-taosdata** [comment]
![image](https://user-images.githubusercontent.com/69311263/113234559-16e8a700-92d4-11eb-9533-a7fc656823a6.png)
就这？

**Comment by shaoguanlee** [comment]
我收到了你给我发的邮件 "就这" ;
我想不管我的github主页是否有内容,并不妨碍我给你们提bug吧;而且你们的rest-driver目前确实做到不完善,任何一个人都可以对此做出评价;
不知道贵司是怎么看待这个事情的

**Comment by zyyang-taosdata** [comment]
> 我收到了你给我发的邮件 "就这" ;
> 我想不管我的github主页是否有内容,并不妨碍我给你们提bug吧;而且你们的rest-driver目前确实做到不完善,任何一个人都可以对此做出评价;
> 不知道贵司是怎么看待这个事情的

欢迎您友好交流，不建议带情绪。
