### ISSUE TITLE
nodejs connector err?

### ISSUE THREAD

**Issue by sexbee** [taosdata/TDengine#573]
nodejs  query.execute()...

间断报错：
{ TDError.DatabaseError.ProgrammingError: -48
 at TDengineCursor.execute (/usr/local/koa/node_modules/td-connector/nodetaos/cursor.js:143:11)
 at /usr/local/koa/node_modules/td-connector/nodetaos/taosquery.js:40:25
 at new Promise (<anonymous>)
 at TaosQuery.execute (/usr/local/koa/node_modules/td-connector/nodetaos/taosquery.js:35:26)
 at MongoService.taosDatasave (/usr/local/koa/services/MongoService.js:156:13)
 at /usr/local/koa/routes/api.js:20:26
 at dispatch (/usr/local/koa/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
 at next (/usr/local/koa/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
 at /usr/local/koa/node_modules/koa-router/lib/router.js:345:16
 at dispatch (/usr/local/koa/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
 at /usr/local/koa/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
 at dispatch (/usr/local/koa/node_modules/koa-router/lib/router.js:350:31)
 at dispatch (/usr/local/koa/node_modules/koa-compose/index.js:42:32)
 at dispatch (/usr/local/koa/node_modules/koa-router/lib/router.js:332:32)
 at dispatch (/usr/local/koa/node_modules/koa-compose/index.js:42:32)
 at dispatch (/usr/local/koa/node_modules/koa-router/lib/router.js:332:32)
 at dispatch (/usr/local/koa/node_modules/koa-compose/index.js:42:32)
 at createGenerator (/usr/local/koa/node_modules/koa-convert/index.js:24:16)
 at createGenerator.next (<anonymous>)
 at onFulfilled (/usr/local/koa/node_modules/co/index.js:65:19)
 at /usr/local/koa/node_modules/co/index.js:54:5
 at new Promise (<anonymous>)
 at Object.co (/usr/local/koa/node_modules/co/index.js:50:10)
 at Object.toPromise (/usr/local/koa/node_modules/co/index.js:118:63)
 at next (/usr/local/koa/node_modules/co/index.js:99:29)
 at onFulfilled (/usr/local/koa/node_modules/co/index.js:69:7)
 at /usr/local/koa/node_modules/co/index.js:54:5
 at new Promise (<anonymous>) name: 'TDError.DatabaseError.ProgrammingError' }

**Comment by sexbee** [comment]
connection.js  :55
this._conn = this._chandle.connect(this._host, this._user, this._password, **this._database,** this._port);
* var conn = new TDengineConnection({host:"127.0.0.1", user:"root", password:"taosdata", **config:"/etc/taos"**,port:0})

**Comment by sexbee** [comment]
ProgrammingError: -48    请问-48 提示什么？ @StoneT2000

**Comment by hzcheng** [comment]
非nodejs接口会有这种问题吗？

**Comment by StoneT2000** [comment]
把你写的代码comment到这里，看你的stack trace 就觉得应该是你的syntax error

**Comment by sexbee** [comment]
let  query = c1.query('insert into'+ dataid + 'values(' + insertData.join(',')+');') 
qurey.execute()
关键是 启动是可以正常运行一段时间，然后就报错。

**Comment by sexbee** [comment]
直接将sql代码info出来后，粘帖到Taos>运行是正常的。

**Comment by StoneT2000** [comment]
After discussion, determined source of error was a syntax error in the original query being sent to taos.
