### ISSUE TITLE
an heap-buffer-overflow error happened

### ISSUE THREAD

**Issue by WLLS253** [taosdata/TDengine#5924]
stack trace：
=================================================================
	==691058==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6190000c258a at pc 0x0000004c385f bp 0x7fffde1ec480 sp 0x7fffde1ebc48
	WRITE of size 8 at 0x6190000c258a thread T38
	    #0 0x4c385e in __asan_memset /home/wzy/opt/projects/llvm/src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3
	    #1 0x757f9e in function_setup /home/wzy/opt/projects/databases/TDengine/src/query/src/qAggMain.c:390:3
	    #2 0xa9ae25 in setResultRowOutputBufInitCtx /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:3260:7
	    #3 0xa9cc88 in setWindowOutputBufByKey /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:631:3
	    #4 0xaa398b in hashIntervalAgg /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:1306:20
	    #5 0xaa2902 in doIntervalAgg /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:4813:5
	    #6 0xa72594 in qTableQuery /home/wzy/opt/projects/databases/TDengine/src/query/src/queryMain.c:238:28
	    #7 0xa6a802 in vnodeProcessQueryMsg /home/wzy/opt/projects/databases/TDengine/src/vnode/src/vnodeRead.c:289:23
	    #8 0xb07c8b in vnodeProcessRead /home/wzy/opt/projects/databases/TDengine/src/vnode/src/vnodeRead.c:52:10
	    #9 0xb07790 in dnodeProcessReadQueue /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeVRead.c:131:20
	    #10 0x7ffff7e3f608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
	    #11 0x7ffff7d45292 in clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
	
	0x6190000c258a is located 0 bytes to the right of 1034-byte region [0x6190000c2180,0x6190000c258a)
	allocated by thread T38 here:
	    #0 0x4c4272 in calloc /home/wzy/opt/projects/llvm/src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
	    #1 0x85e24c in getNewDataBuf /home/wzy/opt/projects/databases/TDengine/src/query/src/qResultbuf.c:314:17
	    #2 0xa9a724 in addNewWindowResultBuf /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:576:13
	    #3 0xa9cd1b in setWindowOutputBufByKey /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:622:19
	    #4 0xaa3243 in hashIntervalAgg /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:1245:17
	    #5 0xaa2902 in doIntervalAgg /home/wzy/opt/projects/databases/TDengine/src/query/src/qExecutor.c:4813:5
	    #6 0xa72594 in qTableQuery /home/wzy/opt/projects/databases/TDengine/src/query/src/queryMain.c:238:28
	    #7 0xa6a802 in vnodeProcessQueryMsg /home/wzy/opt/projects/databases/TDengine/src/vnode/src/vnodeRead.c:289:23
	    #8 0xb07c8b in vnodeProcessRead /home/wzy/opt/projects/databases/TDengine/src/vnode/src/vnodeRead.c:52:10
	    #9 0xb07790 in dnodeProcessReadQueue /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeVRead.c:131:20
	    #10 0x7ffff7e3f608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
	
	Thread T38 created by T18 here:
	    #0 0x4aeeaa in pthread_create /home/wzy/opt/projects/llvm/src/projects/compiler-rt/lib/asan/asan_interceptors.cpp:214:3
	    #1 0xa4edaf in tWorkerAllocQueue /home/wzy/opt/projects/databases/TDengine/src/util/src/tworker.c:77:11
	    #2 0xa02586 in dnodeAllocVQueryQueue /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeVRead.c:86:10
	    #3 0x9fd7b5 in vnodeOpen /home/wzy/opt/projects/databases/TDengine/src/vnode/src/vnodeMain.c:274:20
	    #4 0x9fceee in dnodeOpenVnode /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeVnodes.c:99:9
	    #5 0x7ffff7e3f608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
	
	Thread T18 created by T0 here:
	    #0 0x4aeeaa in pthread_create /home/wzy/opt/projects/llvm/src/projects/compiler-rt/lib/asan/asan_interceptors.cpp:214:3
	    #1 0x708c46 in dnodeInitVnodes /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeVnodes.c:149:9
	    #2 0x705b7e in dnodeStepInit /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeStep.c:58:20
	    #3 0x705a1b in dnodeInitComponents /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeMain.c:103:10
	    #4 0x70384b in dnodeInitSystem /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeMain.c:154:7
	    #5 0xb2a2f6 in main /home/wzy/opt/projects/databases/TDengine/src/dnode/src/dnodeSystem.c:131:7
	    #6 0x7ffff7c4a0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
	
	SUMMARY: AddressSanitizer: heap-buffer-overflow /home/wzy/opt/projects/llvm/src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset
	Shadow bytes around the buggy address:
	  0x0c3280010460: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x0c3280010470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x0c3280010480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x0c3280010490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x0c32800104a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	=>0x0c32800104b0: 00[02]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
	  0x0c32800104c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
	  0x0c32800104d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x0c32800104e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x0c32800104f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	  0x0c3280010500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	Shadow byte legend (one shadow byte represents 8 application bytes):
	  Addressable:           00
	  Partially addressable: 01 02 03 04 05 06 07 
	  Heap left redzone:       fa
	  Freed heap region:       fd
	  Stack left redzone:      f1
	  Stack mid redzone:       f2
	  Stack right redzone:     f3
	  Stack after return:      f5
	  Stack use after scope:   f8
	  Global redzone:          f9
	  Global init order:       f6
	  Poisoned by user:        f7
	  Container overflow:      fc
	  Array cookie:            ac
	  Intra object redzone:    bb
	  ASan internal:           fe
	  Left alloca redzone:     ca
	  Right alloca redzone:    cb
	  Shadow gap:              cc
ubuntu 20.04 
version: 2.0.19

**Comment by attritionorg** [comment]
@WLLS253 can you describe what you did to trigger the error?

**Comment by arielyang** [comment]
This issue was closed because it has been inactive for too many days.
