### ISSUE TITLE
RestfulPreparedStatement when no parameters throw NullPointerException

### ISSUE THREAD

**Issue by pope12389** [taosdata/TDengine#6081]
**Bug Description**
2021-05-11 11:39:13,540-[ERROR]-[main] --> close statement error -- [com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:109)]
java.lang.NullPointerException: null
	at com.taosdata.jdbc.rs.RestfulPreparedStatement.clearParameters(RestfulPreparedStatement.java:213)
	at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:158)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:201)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:98)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:323)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1917)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:325)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:270)
	at org.springframework.jdbc.datasource.DataSourceUtils.doCloseConnection(DataSourceUtils.java:404)
	at org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:391)
	at org.springframework.jdbc.datasource.DataSourceUtils.releaseConnection(DataSourceUtils.java:358)
	at org.mybatis.spring.transaction.SpringManagedTransaction.close(SpringManagedTransaction.java:115)
------------------------------------
 public RestfulPreparedStatement(RestfulConnection conn, String database, String sql) {
        super(conn, database);
        this.rawSql = sql;
        // ----------------------- here 
        if (sql.contains("?")) {
            int parameterCnt = 0;
            for (int i = 0; i < sql.length(); i++) {
                if ('?' == sql.charAt(i)) {
                    parameterCnt++;
                }
            }
            parameters = new Object[parameterCnt]; // not initial
            this.isPrepared = true;
        }

**Comment by yu285** [comment]
which jdbc version and DB version u are using ？

**Comment by pope12389** [comment]
i found that 2.0.30 still has this problem.  parameters  is null when sql has no '?' character。when call clearParameters method throw this exception.

**Comment by xleili** [comment]
please provide some more exception trace log, at least the  part include taos-jdbc. to help us locate the issue.

**Comment by xleili** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by aiuni** [comment]
**taos-jdbcdriver 版本 2.0.38**
使用mybatisplus操作taos数据库 当Preparing SQL没有需要注入的参数时会报以下错误。

----------------------------------------------------------
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@2c03678] will not be managed by Spring
==>  Preparing: select * from cable_db_realtime.temp_1m order by ts desc limit 1; 
==> Parameters: 
<==    Columns: ts, p, v, channel_number, cable_number, pt
<==        Row: 2022-06-11 03:00:15.000046098, 45853, 20.0, <<BLOB>>, <<BLOB>>, 45853
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@548051d7]
ERROR:2022-06-13 14:29:05.044 com.alibaba.druid.util.JdbcUtils:Line:86  - close statement error
java.lang.NullPointerException: null
	at com.taosdata.jdbc.TSDBPreparedStatement.clearParameters(TSDBPreparedStatement.java:239)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_clearParameters(FilterChainImpl.java:3381)
	at com.alibaba.druid.filter.logging.LogFilter.preparedStatement_clearParameters(LogFilter.java:895)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_clearParameters(FilterChainImpl.java:3378)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_clearParameters(FilterAdapter.java:1075)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_clearParameters(FilterChainImpl.java:3378)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.clearParameters(PreparedStatementProxyImpl.java:151)
	at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:156)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:202)
	at com.alibaba.druid.util.JdbcUtils.close(JdbcUtils.java:84)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:291)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1688)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:323)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:4997)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_releaseConnection(LogFilter.java:866)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:4993)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_releaseConnection(StatFilter.java:665)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:4993)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:266)
	at org.springframework.jdbc.datasource.DataSourceUtils.doCloseConnection(DataSourceUtils.java:360)
	at org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:347)
	at org.springframework.jdbc.datasource.DataSourceUtils.releaseConnection(DataSourceUtils.java:314)
	at org.mybatis.spring.transaction.SpringManagedTransaction.close(SpringManagedTransaction.java:115)
	at org.apache.ibatis.executor.BaseExecutor.close(BaseExecutor.java:90)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.close(MybatisCachingExecutor.java:73)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.close(DefaultSqlSession.java:263)
	at org.mybatis.spring.SqlSessionUtils.closeSqlSession(SqlSessionUtils.java:195)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:437)
	at com.sun.proxy.$Proxy151.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:90)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy202.queryLastOne(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy203.queryLastOne(Unknown Source)
	at com.cable.taos.service.Impl.TaosDataServiceImpl.queryLastOne(TaosDataServiceImpl.java:47)
	at com.cable.taos.TestTaosDB.query(TestTaosDB.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Comment by xiaofuliang** [comment]
同样有这样的问题，如果没有注入查询条件，就会报这个错
