### ISSUE TITLE
GoConnect on Windows_x64  , connection is not stable

### ISSUE THREAD

**Issue by yaofei517** [taosdata/TDengine#6194]
GoConnect在Windows_x64平台上连接严重不稳定，执行4-5次，有一次可以成功连接服务器
命令行客户端可以正常连接
运行的服务器为本机docker，端口映射正常

建立连接时，服务器显示登录成功，客户端返回连接失败
![image](https://user-images.githubusercontent.com/41509375/119117813-32626980-ba5c-11eb-959d-aa1376c47789.png)

==================================================
                new log file                      
==================================================
05/21 17:38:33.097000 00002944 UTL localEp is: 222.222.231.201:6030
05/21 17:38:33.097000 00002944 UTL timezone not configured, use default
05/21 17:38:33.106000 00002944 UTL locale not configured, set to default:Chinese_China.936
05/21 17:38:33.106000 00002944 UTL charset not configured, set to default:cp936
05/21 17:38:33.106000 00002944 UTL    check global cfg completed
05/21 17:38:33.106000 00002944 UTL ==================================
05/21 17:38:33.106000 00002944 UTL    taos config & system info:
05/21 17:38:33.106000 00002944 UTL ==================================
05/21 17:38:33.106000 00002944 UTL  firstEp:                222.222.231.201:6030 
05/21 17:38:33.106000 00002944 UTL  secondEp:               222.222.231.201:6030 
05/21 17:38:33.106000 00002944 UTL  fqdn:                   222.222.231.201 
05/21 17:38:33.106000 00002944 UTL  serverPort:             6030 
05/21 17:38:33.106000 00002944 UTL  configDir:              C:\TDengine\cfg 
05/21 17:38:33.106000 00002944 UTL  logDir:                 C:\TDengine\log 
05/21 17:38:33.106000 00002944 UTL  scriptDir:              C:/TDengine/script 
05/21 17:38:33.106000 00002944 UTL  arbitrator:              
05/21 17:38:33.106000 00002944 UTL  numOfThreadsPerCore:    1.000000 
05/21 17:38:33.106000 00002944 UTL  rpcTimer:               1000(ms)
05/21 17:38:33.106000 00002944 UTL  rpcMaxTime:             600(s)
05/21 17:38:33.106000 00002944 UTL  shellActivityTimer:     3(s)
05/21 17:38:33.106000 00002944 UTL  compressMsgSize:        -1 
05/21 17:38:33.106000 00002944 UTL  maxSQLLength:           1048576(byte)
05/21 17:38:33.106000 00002944 UTL  maxNumOfOrderedRes:     100000 
05/21 17:38:33.106000 00002944 UTL  keepColumnName:         0 
05/21 17:38:33.106000 00002944 UTL  timezone:               not configured 
05/21 17:38:33.106000 00002944 UTL  locale:                 Chinese_China.936 
05/21 17:38:33.106000 00002944 UTL  charset:                cp936 
05/21 17:38:33.106000 00002944 UTL  numOfLogLines:          10000000 
05/21 17:38:33.106000 00002944 UTL  logKeepDays:            0 
05/21 17:38:33.106000 00002944 UTL  asyncLog:               1 
05/21 17:38:33.106000 00002944 UTL  debugFlag:              0 
05/21 17:38:33.106000 00002944 UTL  rpcDebugFlag:           131 
05/21 17:38:33.106000 00002944 UTL  tmrDebugFlag:           131 
05/21 17:38:33.106000 00002944 UTL  cDebugFlag:             131 
05/21 17:38:33.106000 00002944 UTL  jniDebugFlag:           131 
05/21 17:38:33.106000 00002944 UTL  odbcDebugFlag:          131 
05/21 17:38:33.106000 00002944 UTL  uDebugFlag:             131 
05/21 17:38:33.106000 00002944 UTL  qDebugFlag:             131 
05/21 17:38:33.106000 00002944 UTL  tsdbDebugFlag:          131 
05/21 17:38:33.106000 00002944 UTL  gitinfo:                no git commit id 
05/21 17:38:33.106000 00002944 UTL  gitinfoOfInternal:      237fcab5d0cd5ab2899a35fd305c948b25899465 
05/21 17:38:33.106000 00002944 UTL  buildinfo:              Built at 2021-05-01 22:39:20 
05/21 17:38:33.106000 00002944 UTL  version:                2.1.0.0 
05/21 17:38:33.106000 00002944 UTL  maxBinaryDisplayWidth:  30 
05/21 17:38:33.106000 00002944 UTL  tempDir:                C:\Users\YF6B11~1.WOR\AppData\Local\Temp 
05/21 17:38:33.106000 00002944 UTL  os numOfCores:          8
05/21 17:38:33.106000 00002944 UTL  os totalDisk:           0.000000(GB)
05/21 17:38:33.106000 00002944 UTL  os usedDisk:            0.000000(GB)
05/21 17:38:33.106000 00002944 UTL  os availDisk:           0.000000(GB)
05/21 17:38:33.106000 00002944 UTL  os totalMemory:         16114(MB)
05/21 17:38:33.106000 00002944 UTL ==================================
05/21 17:38:33.106000 00002944 UTL  dataDir: C:/TDengine/data level:0 primary:1
05/21 17:38:33.106000 00002944 UTL ==================================

API server listening at: 127.0.0.1:19407

============= args parse result: =============
hostName:             222.222.231.201
serverPort:           6030
usr:                  root
password:             taosdata
dbName:               test
mode:                 r
tablePrefix:          d
numOftables:          2
numOfRecordsPerTable: 10
numOfRecordsPerReq:   3
numOfThreads:         1
startTimestamp:       2020-10-01 08:00:00[1601510400000]
================================================
Please press enter key to continue....
root:taosdata@/tcp(222.222.231.201:6030)/
drop database if exists test
panic: Unable to establish connection

控制台输出
//////////////////////////////////////////////////////////////////////////////////////
goroutine 1 [running]:
main.checkErr(0x5bfc38, 0xc000188010, 0xc00008c280, 0x1c)
	D:/Workpace/taosdemo/taosdemo.go:560 +0xe6
main.createDatabase(0x5919e4, 0x4, 0x591d61, 0x6)
	D:/Workpace/taosdemo/taosdemo.go:172 +0x21a
main.main()
	D:/Workpace/taosdemo/taosdemo.go:143 +0x253

**Comment by yaofei517** [comment]
检查发现多次卸载历史动态链接库遗留，导致实际调用的客户端dll与服务端版本不一致
