### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector

### ISSUE THREAD

**Issue by abnerhuangshen** [taosdata/TDengine#6443]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:119)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:874)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1246)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1242)
	at com.zhenergy.bigdata.quality.detection.sink.Sink2TDenginAlarm.open(Sink2TDenginAlarm.java:58)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:46)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:437)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:574)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:554)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:756)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:748)
可是我已经安装了TDegine的客户端，我的版本是2.0.16.0
很奇怪的是，刚开始时，程序不报错，是过了很久就会报这个错误

**Comment by abnerhuangshen** [comment]
is there anyone who can answer my question

**Comment by abnerhuangshen** [comment]
我用节点hadoop02上使用taos -h 10.162.201.62 -P 6030 -s 'show databases';是可以显示结果的，但是代码一运行就出现上面这个问题

**Comment by arielyang** [comment]
Still have questions now? You can try upgrading to the latest client version

**Comment by fenghuazzm** [comment]
Closing this issue since there is no response for too many days.
