### ISSUE TITLE
when execute show db.tables with no resultset RestfulResultSet.metaData is null . RestfulDriver 2.1.30

### ISSUE THREAD

**Issue by pope12389** [taosdata/TDengine#6582]
**Bug Description**

Caused by: java.lang.NullPointerException: null
	at org.apache.ibatis.executor.resultset.ResultSetWrapper.<init>(ResultSetWrapper.java:57)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:250)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:187)

/**
     * 由一个result的Json构造结果集，对应执行show databases, show tables等这些语句，返回结果集，但无法获取结果集对应的meta，统一当成String处理
     *
     * @param resultJson: 包含data信息的结果集，有sql返回的结果集
     ***/
    public RestfulResultSet(String database, Statement statement, JSONObject resultJson) throws SQLException {
        this.database = database;
        this.statement = statement;

        // get column metadata
        JSONArray columnMeta = resultJson.getJSONArray("column_meta");
        // get row data
        JSONArray data = resultJson.getJSONArray("data");
        if (data == null || data.isEmpty()) {
            columnNames.clear();
            columns.clear();
            this.resultSet.clear();
            return;
        }

    //when returned metaData is null
    this.metaData = new RestfulResultSetMetaData(this.database, columns, this);

**Comment by yu285** [comment]
we will check on this
