### ISSUE TITLE
taos-jdbcdriver version update to 2.0.31, serious error : java.lang.NoSuchMethodError: setTimestamp

### ISSUE THREAD

**Issue by NickZhang1024** [taosdata/TDengine#6584]
Caused by: java.lang.NoSuchMethodError: setTimestamp
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:58)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:126)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
	at org.springframework.boot.jdbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:184)
	at org.springframework.boot.jdbc.init.DataSourceScriptDatabaseInitializer.isEmbeddedDatabase(DataSourceScriptDatabaseInitializer.java:64)
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.isEnabled(AbstractScriptDatabaseInitializer.java:87)
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:74)
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:65)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 84 more

**Comment by limshu** [comment]
+1

**Comment by Brand960** [comment]
+1 RESTful方式可以连接但是无法使用参数化SQL

**Comment by yu285** [comment]
JDBC 2.0.31  and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond

**Comment by Brand960** [comment]
I am using docker tdengine latest which is 2.1.3.0&nbsp;
Java springboot maven package jdbc 2.0.31 jar


Eventually error shows no such methods setTimestamp as same as issue #6584



发自我的iPhone


------------------ Original ------------------
From: Yu Chen ***@***.***&gt;
Date: Thu,Jun 24,2021 2:25 PM
To: taosdata/TDengine ***@***.***&gt;
Cc: YuePeng ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [taosdata/TDengine] taos-jdbcdriver version update to 2.0.31, serious error : java.lang.NoSuchMethodError: setTimestamp (#6584)





 
JDBC 2.0.31  and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond

**Comment by NickZhang1024** [comment]
jdbcdriver 升级到 2.0.31， TDengine 客户端和服务端都升级到2.1.3.0，这个问题可以解决了，但是之前提的BINARY、NCHAR字段类型均不能插入除数字之外的字符，比如a、b、c等 #6461，仍然未解决。这个问题比较急的 


org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: TDengine ERROR (80000216): syntax error near 'abc123,
0,
,
1,
1624186800000,
1624188600000,
1800,
100.0,




' (invalid data or symbol)

**Comment by NickZhang1024** [comment]
字符串为空 “” 也不行

**Comment by NickZhang1024** [comment]
> jdbcdriver 升级到 2.0.31， TDengine 客户端和服务端都升级到2.1.3.0，这个问题可以解决了，但是之前提的BINARY、NCHAR字段类型均不能插入除数字之外的字符，比如a、b、c等 #6461，仍然未解决。这个问题比较急的
> 
> org.springframework.jdbc.UncategorizedSQLException:
> 
> ### Error updating database. Cause: java.sql.SQLException: TDengine ERROR (80000216): syntax error near 'abc123,
> 0,
> ,
> 1,
> 1624186800000,
> 1624188600000,
> 1800,
> 100.0,
> 
> ' (invalid data or symbol)

jdbcdriver 升级到 2.0.31， TDengine 客户端和服务端都升级到2.1.3.0

**Comment by Brand960** [comment]
兄弟们，蚌埠住了，我发现我没设置hostname连接docker里面的tdengine，光开放端口用localhost是连不上的，要进容器用taped 看下hostname



发自我的iPhone


------------------ Original ------------------
From: NickZhang1024 ***@***.***&gt;
Date: Thu,Jun 24,2021 4:44 PM
To: taosdata/TDengine ***@***.***&gt;
Cc: YuePeng ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [taosdata/TDengine] taos-jdbcdriver version update to 2.0.31, serious error : java.lang.NoSuchMethodError: setTimestamp (#6584)





 
字符串为空 “” 也不行

**Comment by sunboy1** [comment]
> > jdbcdriver 升级到 2.0.31， TDengine 客户端和服务端都升级到2.1.3.0，这个问题可以解决了，但是之前提的BINARY、NCHAR字段类型均不能插入除数字之外的字符，比如a、b、c等 #6461，仍然未解决。这个问题比较急的
> > org.springframework.jdbc.UncategorizedSQLException:
> > ### Error updating database. Cause: java.sql.SQLException: TDengine ERROR (80000216): syntax error near 'abc123,
> > 0,
> > ,
> > 1,
> > 1624186800000,
> > 1624188600000,
> > 1800,
> > 100.0,
> > ' (invalid data or symbol)
> 
> jdbcdriver 升级到 2.0.31， TDengine 客户端和服务端都升级到2.1.3.0

目前没有推送 2.1.3.0 的镜像包吧
2.1.2.0 用TSDBDriver 也是这个问题，resuful 没问题

**Comment by NickZhang1024** [comment]
> JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond

jdbcdriver 版本和TDengine 服务的版本匹配清单有吗？

**Comment by sunboy1** [comment]
> > JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond
> 
> jdbcdriver 版本和TDengine 服务的版本匹配清单有吗？
jdbcdriver: 2.0.31
TDengine: 2.1.2.0
windows的client也是安装的 2.1.2.0

**Comment by NickZhang1024** [comment]
> > > JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond
> > 
> > 
> > jdbcdriver 版本和TDengine 服务的版本匹配清单有吗？
> > jdbcdriver: 2.0.31
> > TDengine: 2.1.2.0
> > windows的client也是安装的 2.1.2.0

之前提的BINARY、NCHAR字段类型均不能插入除数字之外的字符，比如a、b、c等 #6461，仍然未解决。这个问题比较急的

**Comment by NickZhang1024** [comment]
> JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond

之前提的BINARY、NCHAR字段类型均不能插入除数字之外的字符，比如a、b、c等 #6461，仍然未解决。这个问题比较急的

**Comment by NickZhang1024** [comment]
> > > JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond
> > 
> > 
> > jdbcdriver 版本和TDengine 服务的版本匹配清单有吗？
> > jdbcdriver: 2.0.31
> > TDengine: 2.1.2.0
> > windows的client也是安装的 2.1.2.0

TDengine-client-2.0.20.4-Windows-x64.exe 这个版本哪里可以下载？

**Comment by NickZhang1024** [comment]
> > JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond
> 
> 之前提的BINARY、NCHAR字段类型均不能插入除数字之外的字符，比如a、b、c等 #6461，仍然未解决。这个问题比较急的

目前我只能把服务端退回到2.1.0.1，Windows 客户端退回到2.1.0.0，JDBC Driver 退回到 2.0.27，这个组合目前是可以正常运行的

**Comment by dcygody** [comment]
> JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond

JDBC-RESTful是没有问题的, 但是使用JDBC-JNI的话,可以建立数据库,使用show databases;这样的命令,但是不能查询数据, 难受了

**Comment by dcygody** [comment]
> JDBC 2.0.31 and TDengine 2.1.3.0 muse be matched because we add some important function like nanosecond

JDBC-RESTful是没有问题的, 但是使用JDBC-JNI的话,可以建立数据库,使用show databases;这样的命令,但是不能查询数据, 难受了

**Comment by Yang-Jiang** [comment]
jdbcdriver: 2.0.31
TDengine: 2.1.3.0
windows client 2.1.3.0
没有此问题
但是使用Linux client 2.1.3.0有此问题

**Comment by yu285** [comment]
目前使用JDBC 2.0.31和database 2.1.3之后仍然遇到问题的，请添加微信15652223354
