### ISSUE TITLE
more dnodes are needed

### ISSUE THREAD

**Issue by xujiesh0510** [taosdata/TDengine#668]
Enviroment:
docker image from official.
when i  try to create 100000 tables , server throws exceptions：
 
Maikebing.Data.Taos.TaosException (0x80004005): Server is not available
   at Maikebing.Data.Taos.TaosException.ThrowExceptionForRC(String _commandText, TaosErrorResult taosError)
   at Maikebing.Data.Taos.TaosCommand.ExecuteReader(CommandBehavior behavior)
   at Maikebing.Data.Taos.TaosCommand.ExecuteNonQuery()

Maikebing.Data.Taos.TaosException (0x80004005): more dnodes are needed
   at Maikebing.Data.Taos.TaosException.ThrowExceptionForRC(String _commandText, TaosErrorResult taosError)
   at Maikebing.Data.Taos.TaosCommand.ExecuteReader(CommandBehavior behavior)
   at Maikebing.Data.Taos.TaosCommand.ExecuteNonQuery()

Is there any limitations for community version of tdengine? How can i solve this problem?

**Comment by xujiesh0510** [comment]
seems duplicated issue of https://github.com/taosdata/TDengine/issues/436
