### ISSUE TITLE
taos.error.ProgrammingError: Database unsynced

### ISSUE THREAD

**Issue by dingbo8128** [taosdata/TDengine#6717]
**Bug Description**

This error occur as soon as increasing the number of writing threads.

**To Reproduce**

insert data using python with above 10 threads

**Expected Behavior**
 no error

**Screenshots**
```
Traceback (most recent call last):
  File "/opt/python38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/python38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hytp/.local/lib/python3.8/site-packages/autotdimport/taos_util.py", line 82, in do_work
    cs.execute(q)
  File "/home/hytp/.local/lib/python3.8/site-packages/taos/cursor.py", line 146, in execute
    raise ProgrammingError(
taos.error.ProgrammingError: Database unsynced
```
**Environment (please complete the following information):**
 - OS: CentOS 8.0
 - 64G, 40 CPU, 3T
 - TDengine Version 2.1.2.0

**Additional Context**
taos.cfg

```
blocks 32
vnodeBak 0
keepColumnName 1
balance 0
minTablesPerVnode 50
tableIncStepPerVnode 50
enableCoreFile 1
```

**Comment by dingbo8128** [comment]
new discovery: If I create table in a thread and insert data in another thread , the error will likely occur; If creating table and inserting table using the same thread, the error will not occur.
