### ISSUE TITLE
Restful problem with Server unavailable

### ISSUE THREAD

**Issue by Handonghuang** [taosdata/TDengine#6791]
**Bug Description**
Jul 07 06:27:15 ubuntu java[390783]: java.lang.Exception: execute post request exception, url:http://xxxxxxx/rest/sql, exception:java.net.SocketException: Connection timed out (Read failed), cost time(ms):973563
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.utils.HttpClientPoolUtil.execute(HttpClientPoolUtil.java:104)
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeOneUpdate(RestfulStatement.java:123)
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:61)
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:96)
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulPreparedStatement.execute(RestfulPreparedStatement.java:235)
Jul 07 06:27:15 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:56)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
Jul 07 06:27:15 ubuntu java[390783]:         at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
Jul 07 06:27:15 ubuntu java[390783]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 07 06:27:15 ubuntu java[390783]:         at java.lang.reflect.Method.invoke(Method.java:498)
Jul 07 06:27:15 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
Jul 07 06:27:15 ubuntu java[390783]:         at com.sun.proxy.$Proxy112.insert(Unknown Source)
Jul 07 06:27:15 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
Jul 07 06:27:15 ubuntu java[390783]:         at com.sun.proxy.$Proxy115.insertOne(Unknown Source)
Jul 07 06:27:15 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.slaveLoop(SlavesQueryService.java:123)
Jul 07 06:27:15 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.lambda$init$0(SlavesQueryService.java:75)
Jul 07 06:27:15 ubuntu java[390783]:         at java.lang.Thread.run(Thread.java:748)
Jul 07 06:27:15 ubuntu java[390783]: org.springframework.jdbc.UncategorizedSQLException:
Jul 07 06:27:15 ubuntu java[390783]: ### Error updating database.  Cause: java.sql.SQLException: Error
Jul 07 06:27:15 ubuntu java[390783]: ### The error may exist in com/qkl/mapper/AioParseMapper.java (best guess)
Jul 07 06:27:15 ubuntu java[390783]: ### The error may involve com.qkl.mapper.AioParseMapper.insertOne-Inline
Jul 07 06:27:15 ubuntu java[390783]: ### The error occurred while setting parameters
Jul 07 06:27:15 ubuntu java[390783]: ### SQL: insert into test.t_104 using aio_parse tags('0','11') values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
Jul 07 06:27:15 ubuntu java[390783]: ### Cause: java.sql.SQLException: Error
Jul 07 06:27:15 ubuntu java[390783]: ; uncategorized SQLException; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error
Jul 07 06:27:15 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
Jul 07 06:27:15 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Jul 07 06:27:15 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Jul 07 06:27:15 ubuntu java[390783]:         at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
Jul 07 06:27:15 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
Jul 07 06:27:15 ubuntu java[390783]:         at com.sun.proxy.$Proxy112.insert(Unknown Source)
Jul 07 06:27:15 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
Jul 07 06:27:15 ubuntu java[390783]:         at com.sun.proxy.$Proxy115.insertOne(Unknown Source)
Jul 07 06:27:15 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.slaveLoop(SlavesQueryService.java:123)
Jul 07 06:27:15 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.lambda$init$0(SlavesQueryService.java:75)
Jul 07 06:27:15 ubuntu java[390783]:         at java.lang.Thread.run(Thread.java:748)
Jul 07 06:27:15 ubuntu java[390783]: Caused by: java.sql.SQLException: Error
Jul 07 06:27:15 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1770)
Jul 07 06:27:15 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:133)
Jul 07 06:27:15 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:82)
Jul 07 06:27:15 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:501)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:56)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
Jul 07 06:27:15 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
Jul 07 06:27:15 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
Jul 07 06:27:15 ubuntu java[390783]:         at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
Jul 07 06:27:15 ubuntu java[390783]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 07 06:27:15 ubuntu java[390783]:         at java.lang.reflect.Method.invoke(Method.java:498)
Jul 07 06:27:15 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
Jul 07 06:27:15 ubuntu java[390783]:         ... 9 more
Jul 07 06:27:15 ubuntu java[390783]: Caused by: java.lang.NullPointerException
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeOneUpdate(RestfulStatement.java:125)
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:61)
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:96)
Jul 07 06:27:15 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulPreparedStatement.execute(RestfulPreparedStatement.java:235)
Jul 07 06:27:15 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
Jul 07 06:27:15 ubuntu java[390783]:         ... 20 more
Jul 07 06:27:15 ubuntu java[390783]: MessagingControl.send: 0a05019352
Jul 07 06:27:15 ubuntu java[390783]: MessagingConnection.read: 0b050118000008000008000000000000e8030c881308000000000000b601
Jul 07 06:27:16 ubuntu java[390783]: org.springframework.jdbc.UncategorizedSQLException:
Jul 07 06:27:16 ubuntu java[390783]: ### Error updating database.  Cause: java.sql.SQLException: TDengine ERROR (217): Database not specified or available
Jul 07 06:27:16 ubuntu java[390783]: ### The error may exist in com/qkl/mapper/AioParseMapper.java (best guess)
Jul 07 06:27:16 ubuntu java[390783]: ### The error may involve com.qkl.mapper.AioParseMapper.insertOne-Inline
Jul 07 06:27:16 ubuntu java[390783]: ### The error occurred while setting parameters
Jul 07 06:27:16 ubuntu java[390783]: ### SQL: insert into test.t_102 using aio_parse tags('0','11') values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
Jul 07 06:27:16 ubuntu java[390783]: ### Cause: java.sql.SQLException: TDengine ERROR (217): Database not specified or available
Jul 07 06:27:16 ubuntu java[390783]: ; uncategorized SQLException; SQL state []; error code [535]; TDengine ERROR (217): Database not specified or available; nested exception is java.sql.SQLException: TDengine ERROR (217): Database not spe>
Jul 07 06:27:16 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
Jul 07 06:27:16 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Jul 07 06:27:16 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
Jul 07 06:27:16 ubuntu java[390783]:         at com.sun.proxy.$Proxy112.insert(Unknown Source)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
Jul 07 06:27:16 ubuntu java[390783]:         at com.sun.proxy.$Proxy115.insertOne(Unknown Source)
Jul 07 06:27:16 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.slaveLoop(SlavesQueryService.java:123)
Jul 07 06:27:16 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.lambda$init$0(SlavesQueryService.java:75)
Jul 07 06:27:16 ubuntu java[390783]:         at java.lang.Thread.run(Thread.java:748)
Jul 07 06:27:16 ubuntu java[390783]: Caused by: java.sql.SQLException: TDengine ERROR (217): Database not specified or available
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:73)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeOneUpdate(RestfulStatement.java:126)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:61)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:96)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulPreparedStatement.execute(RestfulPreparedStatement.java:235)
Jul 07 06:27:16 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:56)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
Jul 07 06:27:16 ubuntu java[390783]:         at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
Jul 07 06:27:16 ubuntu java[390783]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 07 06:27:16 ubuntu java[390783]:         at java.lang.reflect.Method.invoke(Method.java:498)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
Jul 07 06:27:16 ubuntu java[390783]:         ... 9 more
Jul 07 06:27:16 ubuntu java[390783]: MessagingControl.send: 0a060193a2
Jul 07 06:27:16 ubuntu java[390783]: MessagingConnection.read: 0b0601120000080000080000000000000000000000005ffa
Jul 07 06:27:16 ubuntu java[390783]: org.springframework.jdbc.UncategorizedSQLException:
Jul 07 06:27:16 ubuntu java[390783]: ### Error updating database.  Cause: java.sql.SQLException: TDengine ERROR (217): Database not specified or available
Jul 07 06:27:16 ubuntu java[390783]: ### The error may exist in com/qkl/mapper/AioParseMapper.java (best guess)
Jul 07 06:27:16 ubuntu java[390783]: ### The error may involve com.qkl.mapper.AioParseMapper.insertOne-Inline
Jul 07 06:27:16 ubuntu java[390783]: ### The error occurred while setting parameters
Jul 07 06:27:16 ubuntu java[390783]: ### SQL: insert into test.t_103 using aio_parse tags('0','11') values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
Jul 07 06:27:16 ubuntu java[390783]: ### Cause: java.sql.SQLException: TDengine ERROR (217): Database not specified or available
Jul 07 06:27:16 ubuntu java[390783]: ; uncategorized SQLException; SQL state []; error code [535]; TDengine ERROR (217): Database not specified or available; nested exception is java.sql.SQLException: TDengine ERROR (217): Database not spe>
Jul 07 06:27:16 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
Jul 07 06:27:16 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Jul 07 06:27:16 ubuntu java[390783]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
Jul 07 06:27:16 ubuntu java[390783]:         at com.sun.proxy.$Proxy112.insert(Unknown Source)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
Jul 07 06:27:16 ubuntu java[390783]:         at com.sun.proxy.$Proxy115.insertOne(Unknown Source)
Jul 07 06:27:16 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.slaveLoop(SlavesQueryService.java:123)
Jul 07 06:27:16 ubuntu java[390783]:         at com.qkl.job.SlavesQueryService.lambda$init$0(SlavesQueryService.java:75)
Jul 07 06:27:16 ubuntu java[390783]:         at java.lang.Thread.run(Thread.java:748)
Jul 07 06:27:16 ubuntu java[390783]: Caused by: java.sql.SQLException: TDengine ERROR (217): Database not specified or available
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:73)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeOneUpdate(RestfulStatement.java:126)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.executeUpdate(RestfulStatement.java:61)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulStatement.execute(RestfulStatement.java:96)
Jul 07 06:27:16 ubuntu java[390783]:         at com.taosdata.jdbc.rs.RestfulPreparedStatement.execute(RestfulPreparedStatement.java:235)
Jul 07 06:27:16 ubuntu java[390783]:         at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:56)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
Jul 07 06:27:16 ubuntu java[390783]:         at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
Jul 07 06:27:16 ubuntu java[390783]:         at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
Jul 07 06:27:16 ubuntu java[390783]:         at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
Jul 07 06:27:16 ubuntu java[390783]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 07 06:27:16 ubuntu java[390783]:         at java.lang.reflect.Method.invoke(Method.java:498)
Jul 07 06:27:16 ubuntu java[390783]:         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
Jul 07 06:27:16 ubuntu java[390783]:         ... 9 more

**To Reproduce**
1.start server
2.start client
3.stop server
4.client shows errors (That is right) 
5.restart server 
6.client shows errors(That is wrong)
7.any actions to server e.g.   curl
8.client works

**Expected Behavior**
after server online the client should connect.

**Screenshots**

**Environment (please complete the following information):**
 - TDengine Version  2.0.19.0 and lastest

**Comment by yu285** [comment]
请添加微信15652223354做具体排查

**Comment by xleili** [comment]
From the trace log, i found the most of you the  TDengine ERRORs are " Database not specified or available" , please try to add database name as prefix in your sql before table name. like "select * from db.table_name"

**Comment by xleili** [comment]
This issue is stale because it has been open for 30 days with no activity.
