### ISSUE TITLE
java.lang.NoSuchMethodError: setTimestamp

### ISSUE THREAD

**Issue by akingbr** [taosdata/TDengine#6897]
java.lang.NoSuchMethodError: setTimestamp
	at com.taosdata.jdbc.TSDBJNIConnector.initImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:74)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:121)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at test.taosi.TDEngineTemplate.init(TDEngineTemplate.java:27)
	at test.taosi.Startup.main(Startup.java:17)

         <dependency>
             <groupId>com.taosdata.jdbc</groupId>
             <artifactId>taos-jdbcdriver</artifactId>
             <version>2.0.22</version>
         </dependency>

window client 已经安装， 执行样例代码，
            Class.forName("com.taosdata.jdbc.TSDBDriver");
            String jdbcUrl = "jdbc:TAOS://taosdemo.com:6030/test?user=root&password=taosdata";
            Connection connection = DriverManager.getConnection(jdbcUrl);

报上述异常？

**Comment by caizhenboy** [comment]
您好，请问解决了吗，我这边也遇到了同样的问题

**Comment by sangshuduo** [comment]
TDengine 和 JDBC 是什么版本？

**Comment by akingbr** [comment]
Class.forName("com.taosdata.jdbc.TSDBDriver");
jdbs依赖
 <dependency>
         <groupId>com.taosdata.jdbc</groupId>
         <artifactId>taos-jdbcdriver</artifactId>
         <version>2.0.22</version> 2.0.18也一样
     </dependency>
  
server是2.0.18 -centos7
window client 2.0.18 好像

**Comment by akingbr** [comment]
刚才又仔细看了下说错了，之前第一次安装的是TDengine-client-2.1.3.2-Windows-x64.exe client，是不是和jdbc不匹配，后第2次下载2.0.18是x86的，后换成x64，目前不报哪个异常，报连接的异常，那基本应该是域名配置问题，感觉。

**Comment by akingbr** [comment]
有个文档，说配置域名和ip的，然后把服务的防火墙，关了，目前ok

**Comment by yu285** [comment]
2.1.3.2的数据库版本要和2.0.31以上的jdbc版本配合使用。

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/74105241/126061437-67f52661-33a3-4209-b645-77a9ccba2913.png">

**Comment by ranningw** [comment]
> 有个文档，说配置域名和ip的，然后把服务的防火墙，关了，目前ok

我也遇到您说的问题。
想跑JDBC的demo。

如何解决呢？

我用mvn报错。还没到编译demo的步骤。

**Comment by ranningw** [comment]
我也遇到您说的问题。
想跑JDBC的demo。

如何解决呢？

我用mvn报错。还没到编译demo的步骤。

**Comment by ranningw** [comment]
> TDengine 和 JDBC 是什么版本？

TDengine 2. 1.4.1 client version
 JDBC 2.0.30 version

遇到同样的问题，没有解决。

**Comment by zyyang-taosdata** [comment]
Please change your taos-jdbcdriver to the latest version(2.0.34 for now), and try again.
we solved this problem in taos-jdbcdriver-2.0.33 to adapt early TDengine versions.

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by ZJUlmh11** [comment]
把taos-jdbcdriver依赖的版本改成2.0.31版本及以上就可以了
