### ISSUE TITLE
java.sql.SQLException: JNI ERROR (2354): JNI connection is NULL

### ISSUE THREAD

**Issue by caizhenboy** [taosdata/TDengine#6899]
tdengine服务端版本：TDengine-server-2.1.2.0
tdengine客户端版本：TDengine-client-2.1.2.0-Windows-x64
taos-jdbcdriver依赖：
<dependency>
    <groupId>com.taosdata.jdbc</groupId>
    <artifactId>taos-jdbcdriver</artifactId>
    <version>2.0.30</version>
</dependency>

使用JDBC-JNI方式进行连接

执行代码：
private static void init() throws Exception {
        Class.forName("com.taosdata.jdbc.TSDBDriver");
        String jdbcUrl = "jdbc:TAOS://tdengine-4:6030/test?user=root&password=taosdata";
        Connection conn = DriverManager.getConnection(jdbcUrl);
}

报错：
Exception in thread "main" java.sql.SQLException: JNI ERROR (2354): JNI connection is NULL
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:72)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:56)
	at com.taosdata.jdbc.TSDBJNIConnector.connect(TSDBJNIConnector.java:88)
	at com.taosdata.jdbc.TSDBConnection.connect(TSDBConnection.java:47)
	at com.taosdata.jdbc.TSDBConnection.<init>(TSDBConnection.java:33)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:128)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.cz.tdengine.config.Test.init(Test.java:34)
	at com.cz.tdengine.config.Test.main(Test.java:23)

使用JDBC-RESTful方式连接没有问题

**Comment by yu285** [comment]
请问客户端可以正常连接吗。

**Comment by yu285** [comment]
JNI connection is NULL，这个报错的原因主要是：
你使用的是JDBC-JNI的方式，在建立连接时，JNI方法返回了一个NULL值，jdbcdriver报错。这个报错通常是由于网络配置或者client与taosd的时区不一致等问题产生的。

请检查一下客户端本身的连接有没有问题

**Comment by langzijiang** [comment]
> JNI connection is NULL，这个报错的原因主要是：
> 你使用的是JDBC-JNI的方式，在建立连接时，JNI方法返回了一个NULL值，jdbcdriver报错。这个报错通常是由于网络配置或者client与taosd的时区不一致等问题产生的。
> 
> 请检查一下客户端本身的连接有没有问题

我这边客户端可以正常连接，但是在docker里面报JNI ERROR (2354): JNI connection is NULL

**Comment by yu285** [comment]
现在还有问题吗，这类问题可以添加微信 15652223354 做具体排查
