### ISSUE TITLE
Python TDengine Connector - issue when using "create database" query

### ISSUE THREAD

**Issue by vibhubithar** [taosdata/TDengine#7292]
**Is your feature request related to a problem? Please describe.**

I have  edge devices that will use single python script to collect telemetry data from a a series of sensors and insert it into the local TaosDB instance ussing Python connector.

I would like the script to create DB when it executes first time and in the next run just use the already created database.

Problem is if the database already exists and i run

conn = taos.connect(host="127.0.0.1", user="root", password="XXXXX", config="/etc/taos")
c1 = conn.cursor()
c1.execute('create database gpsLogger')

i get:
Traceback (most recent call last):
  File "berryIMU-Gforce-TPA-GPS-taosdb.py", line 92, in <module>
    c1.execute('create database gpsLogger')
  File "/home/vibhu/.local/lib/python3.6/site-packages/taos/cursor.py", line 123, in execute
    self._result = taos_query(self._connection._conn, stmt)
  File "/home/vibhu/.local/lib/python3.6/site-packages/taos/cinterface.py", line 258, in taos_query
    raise ProgrammingError(errstr, errno)
taos.error.ProgrammingError: [0x0381]: Database already exists

**Describe your desired behavior**
Like in influxDB i would like taosDB to handle "database already exists" and createDB if it doesn't exists and ignore/throw a warning if al ready exits

benefits:
i can run the same python script and avoid creating and handling first time vs second time execution scenarios

**Comment by stevel032** [comment]
Thank you Vibhu for submitting this issue to us, we'll get moving on it and please follow our discussion thread here.

**Comment by sangshuduo** [comment]
@vibhubithar 

> 
> 
> **Is your feature request related to a problem? Please describe.**
> 
> I have edge devices that will use single python script to collect telemetry data from a a series of sensors and insert it into the local TaosDB instance ussing Python connector.
> 
> I would like the script to create DB when it executes first time and in the next run just use the already created database.
> 
> Problem is if the database already exists and i run
> 
> conn = taos.connect(host="127.0.0.1", user="root", password="XXXXX", config="/etc/taos")
> c1 = conn.cursor()
> c1.execute('create database gpsLogger')
> 
> i get:
> Traceback (most recent call last):
> File "berryIMU-Gforce-TPA-GPS-taosdb.py", line 92, in
> c1.execute('create database gpsLogger')
> File "/home/vibhu/.local/lib/python3.6/site-packages/taos/cursor.py", line 123, in execute
> self._result = taos_query(self._connection._conn, stmt)
> File "/home/vibhu/.local/lib/python3.6/site-packages/taos/cinterface.py", line 258, in taos_query
> raise ProgrammingError(errstr, errno)
> taos.error.ProgrammingError: [0x0381]: Database already exists
> 
> **Describe your desired behavior**
> Like in influxDB i would like taosDB to handle "database already exists" and createDB if it doesn't exists and ignore/throw a warning if al ready exits
> 
> benefits:
> i can run the same python script and avoid creating and handling first time vs second time execution scenarios

@vibhubithar  InfluxDB and TDengine use different principle for such creating-database scenario. TDengine provides "create database if not exist dbname" SQL, please refer to https://www.taosdata.com/en/documentation/taos-sql#management for detail, to handle the user don't know if the database is exist or not. TDengine keens on to be like the traditional relational database behavior by default, which InfluxDB is not.

If application side want gracefully handle error passed from TDengine, still be possible to handle it by "try..except".

**Comment by vibhubithar** [comment]
@sangshuduo thanks that helps, i modified my SQL to use [if not exists] as was able to proceed without issues

**Comment by stevel032** [comment]
Thank you @vibhubithar for reporting the issue and collaborating with us!
