### ISSUE TITLE
error happens when using Druid connection pool 

### ISSUE THREAD

**Issue by AlexForMRD** [taosdata/TDengine#745]
**Bug Description**
使用Druid连接池时, 报错如下:

`
15:32:57.225 [main] WARN com.alibaba.druid.pool.DruidDataSource - removeAbandoned is true, not use in production.
15:32:57.232 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testOnBorrow is true, testOnReturn is true, testWhileIdle is true, validationQuery not set
15:32:57.305 [main] ERROR com.alibaba.druid.pool.DruidDataSource - {dataSource-1} init error
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.taosdata.jdbc.TSDBDriver.parseURL(TSDBDriver.java:282)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:128)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1645)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1709)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:932)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1369)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1365)
	at cn.meirenji.core.service.TestTDengineDruid.main(TestTDengineDruid.java:68)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.taosdata.jdbc.TSDBDriver.parseURL(TSDBDriver.java:282)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:128)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1645)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1709)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:932)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1369)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1365)
	at cn.meirenji.core.service.TestTDengineDruid.main(TestTDengineDruid.java:68)
`

**To Reproduce**
2. Type in '....'
3. See error

**我的代码如下**
`package cn.meirenji.core.service;

import com.alibaba.druid.pool.DruidDataSource;
import com.alibaba.druid.pool.DruidDataSourceFactory;
import com.taosdata.jdbc.TSDBPreparedStatement;

import java.sql.*;
import java.util.Properties;

/**
 * All rights Reserved, Designed By www.uuhui.vip
 *
 * @version V1.0
 * @Description: TODO
 * @author: Alex
 * @Copyright: 2019 www.uuhui.vip Inc. All rights reserved.
 */
public class TestTDengineDruid {

    private static final String TSDB_DRIVER = "com.taosdata.jdbc.TSDBDriver";

    private static DruidDataSource druidDataSource = null;

    public static void main(String[] args) {

        String host = "10.0.0.105";
        int port = 0;
        String username = "root";
        String password = "";

        Properties properties = new Properties();
        String jdbcUrl = "jdbc:TAOS://"+host+":"+port+"/mrd_data_batch?user="+username+"&password="+password+"&config=/etc/taos";
        properties.setProperty("driverClassName", TSDB_DRIVER);
        properties.setProperty("url", jdbcUrl);
        properties.setProperty("username", username);
        properties.setProperty("password", password);

        properties.setProperty("filters", "stat");

        properties.setProperty("maxActive", "100");
        properties.setProperty("initialSize", "20");
        properties.setProperty("maxWait", "60000");
        properties.setProperty("minIdle", "8");

        properties.setProperty("timeBetweenEvictionRunsMillis", "60000");
        properties.setProperty("minEvictableIdleTimeMillis", "30000");

        properties.setProperty("testWhileIdle", "true");
        properties.setProperty("testOnBorrow", "true");
        properties.setProperty("testOnReturn", "true");

        properties.setProperty("poolPreparedStatements", "false");
        properties.setProperty("maxOpenPreparedStatements", "20");
        properties.setProperty("asyncInit", "true");

        properties.setProperty("removeAbandoned", "true");
        properties.setProperty("removeAbandonedTimeout", "180");
        properties.setProperty("logAbandoned", "false");

        if (druidDataSource == null) {
            try {
                druidDataSource = (DruidDataSource) DruidDataSourceFactory.createDataSource(properties);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        try {
            Connection connection = druidDataSource.getConnection();
            String rawSql = "select * from batch_342465909421506560";
            PreparedStatement pstmt = (TSDBPreparedStatement) connection.prepareStatement(rawSql);
            ResultSet resSet = pstmt.executeQuery();
            while(resSet.next()) {
                System.out.println(resSet.getLong("data_time"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

}
`

***************
希望官方的同事帮忙看看, 同时建议开发一个Druid连接池的demo, 毕竟已经支持了说明是调试过的.

**Comment by suninformation** [comment]
把配置的testOnBorrow和testOnReturn暂时关闭，不启用validationQuery，目前我是这样使用的没有问题。
同时希望官方支持该特性！

15:32:57.232 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testOnBorrow is true, testOnReturn is true, testWhileIdle is true, validationQuery not set

**Comment by xieyinglin** [comment]
你好，异常原因是用户密码为空正好促发了一个 ArrayIndexOutOfBoundsException , 这个异常已经修复等待 merge, 目前可以先加上密码使用。

关于 Druid 的使用 demo ，我们近期会整理常用的 demo 一起发布出来。

**Comment by AlexForMRD** [comment]
> 报异常的原因是你没有设置validationQuery参数值，但如果设置了也会报错！！
> 所以把配置的testOnBorrow和testOnReturn暂时关闭，不启用validationQuery，目前我是这样使用的没有问题。
> 同时希望官方支持该特性！
> 
> 15:32:57.232 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testOnBorrow is true, testOnReturn is true, testWhileIdle is true, validationQuery not set

是因为我没有设置密码, 官方在密码解析这个地方有问题.

**Comment by AlexForMRD** [comment]
> 你好，异常原因是用户密码为空正好促发了一个 ArrayIndexOutOfBoundsException , 这个异常已经修复等待 merge, 目前可以先加上密码使用。
> 
> 关于 Druid 的使用 demo ，我们近期会整理常用的 demo 一起发布出来。

非常感谢
