### ISSUE TITLE
Query in mybatis ，if no data ， mybatis will report an error

### ISSUE THREAD

**Issue by kitttyHappy** [taosdata/TDengine#7699]
java.lang.NullPointerException: null
	at org.apache.ibatis.executor.resultset.ResultSetWrapper.<init>(ResultSetWrapper.java:58) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:251) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:188) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.5.7.jar:3.5.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) ~[mybatis-3.5.7.jar:3.5.7]
	at com.sun.proxy.$Proxy186.query(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.7.jar:3.5.7]

大概的查看了下，RestfulResultSet.getMetaData() 返回了null值，这就导致mybatis无法正常获取列的数量，从而抛出异常。您看下这块是否需要修复

**Comment by zyyang-taosdata** [comment]
please update your taos-jdbcdriver to 2.0.34 and try.

**Comment by xForMe** [comment]
这个在最新版本已经修复了

**Comment by kitttyHappy** [comment]
已经收到您的来信，辛苦啦！
