### ISSUE TITLE
Arm  create table or database  show “java.sql.SQLException: ERROR (2308): Can not issue SELECT via executeUpdate()”

### ISSUE THREAD

**Issue by coffeenan** [taosdata/TDengine#7747]
**Bug Description**
在树莓派上，JDK1.8环境，安装Taos-V2.1.0.0 aarch32版本数据库，使用2.0.30JDBC驱动，执行Create table或database语句时，报出“java.sql.SQLException: ERROR (2308): Can not issue SELECT via executeUpdate()"异常。

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 10
 - ARM Cortext A72 
 - TDengine V2.1.0.0
 - JDK1.8
 - taos-jdbc-driver 2.0.30

**Program output:**
java.sql.SQLException: ERROR (2308): Can not issue SELECT via executeUpdate()
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:71)
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:58)
        at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:63)
        at com.taosdata.jdbc.TSDBPreparedStatement.executeUpdate(TSDBPreparedStatement.java:143)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
        at com.cetc.cn.dao.TaosTimeSerialResourceDao.createDevDatabase(TaosTimeSerialResourceDao.java:59)
        at com.cetc.cn.service.StartupController.run(StartupController.java:61)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.cetc.cn.Application.main(Application.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
   
**source code:**
	public boolean createDevDatabase() throws DaoException {
		boolean result = false;

		Connection conn = null;
		PreparedStatement st = null;

		try {
			conn = dbSource.getConnection();

			String strQuery = "";
			strQuery += "CREATE DATABASE IF NOT EXISTS ? KEEP 365000";

			st = conn.prepareStatement(strQuery);

			int index = 1;

			st.setString(index++, config.getDcsp());

			st.executeUpdate();  //TaosTimeSerialResourceDao.java:59

			result = true;
		} catch (SQLException e) {
			try {
				if (conn != null)
					conn.rollback();
			} catch (SQLException e1) {
			}
			e.printStackTrace();
			LOG.error(e.getMessage());
			if (e.getMessage().contains("唯一性约束"))
				throw new DaoException(DaoExceptionType.RECORD_CONFLICT);
			if (e.getMessage().contains("非空约束"))
				throw new DaoException(DaoExceptionType.PARAMETER_MISSING);
			else
				throw new DaoException(DaoExceptionType.DATABASE_ACCESS_ERROR);
		} finally {
			closeDatabase(conn, st);
		}
		return result;
	}

**Comment by xleili** [comment]
please try "st.execute()"  instead of "st.executeUpdate() " to see will this error occur again.

**Comment by coffeenan** [comment]
After "st.execute()" instead of "st.executeUpdate() " I get JNI error. And same program is working right on win10.  I think there is some bugs in jdbc jni part of arrche32 

java.sql.SQLException: JNI ERROR (2356): invalid num of fields
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:74)
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:58)
        at com.taosdata.jdbc.TSDBResultSet.<init>(TSDBResultSet.java:68)
        at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:93)
        at com.taosdata.jdbc.TSDBPreparedStatement.execute(TSDBPreparedStatement.java:266)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
        at com.cetc.cn.dao.TaosTimeSerialResourceDao.createDevDatabase(TaosTimeSerialResourceDao.java:59)
        at com.cetc.cn.service.StartupController.run(StartupController.java:61)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.cetc.cn.Application.main(Application.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
2021-09-02 08:27:01.729 ERROR 1989 --- [           main] c.cetc.cn.dao.TaosTimeSerialResourceDao  : JNI ERROR (2356): invalid num of fields

**Comment by coffeenan** [comment]
After use st.execute() instead of st.executeUpdate() I get "JNI ERROR (2356): invalid num of fields" exception, and same program is working right on win10. I think maybe there is some bugs in your jdbc jni part of arm aarch32 version

java.sql.SQLException: JNI ERROR (2356): invalid num of fields
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:74)
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:58)
        at com.taosdata.jdbc.TSDBResultSet.<init>(TSDBResultSet.java:68)
        at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:93)
        at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:632)
        at com.cetc.cn.dao.TaosTimeSerialResourceDao.createDevDatabase(TaosTimeSerialResourceDao.java:55)
        at com.cetc.cn.service.StartupController.run(StartupController.java:61)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.cetc.cn.Application.main(Application.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
2021-09-02 08:48:57.013 ERROR 2512 --- [           main] c.cetc.cn.dao.TaosTimeSerialResourceDao  : JNI ERROR (2356): invalid num of fields

**Comment by xleili** [comment]
能打印一下执行的sql吗？看着像是sql的问题。
can you print the sql please, it seems that there are some errors in sql.

**Comment by coffeenan** [comment]
Just a simple sql for creating database.

2021-09-02 11:15:53.275  INFO 3112 --- [           main] o.s.boot.ApplicationRunner               : DCSP platform name: [dcsp]
sql: CREATE DATABASE IF NOT EXISTS dcsp KEEP 365000
java.sql.SQLException: JNI ERROR (2356): invalid num of fields
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:74)
        at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:58)
        at com.taosdata.jdbc.TSDBResultSet.<init>(TSDBResultSet.java:68)
        at com.taosdata.jdbc.TSDBStatement.execute(TSDBStatement.java:93)
        at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:632)
        at com.cetc.cn.dao.TaosTimeSerialResourceDao.createDevDatabase(TaosTimeSerialResourceDao.java:57)
        at com.cetc.cn.service.StartupController.run(StartupController.java:61)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.cetc.cn.Application.main(Application.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
2021-09-02 11:15:53.427 ERROR 3112 --- [           main] c.cetc.cn.dao.TaosTimeSerialResourceDao  : JNI ERROR (2356): invalid num of fields

@Override
	public boolean createDevDatabase() throws DaoException {
		boolean result = false;

		Connection conn = null;
		Statement st = null;

		try {
			conn = dbSource.getConnection();

			String strQuery = "";
			strQuery += "CREATE DATABASE IF NOT EXISTS " + config.getDcsp() + " KEEP 365000";

			st = conn.createStatement();
			
			System.out.println("sql: " + strQuery);

			st.execute(strQuery);
			
			result = true;
		} catch (SQLException e) {
			try {
				if (conn != null)
					conn.rollback();
			} catch (SQLException e1) {
			}
			e.printStackTrace();
			LOG.error(e.getMessage());
			if (e.getMessage().contains("唯一性约束"))
				throw new DaoException(DaoExceptionType.RECORD_CONFLICT);
			if (e.getMessage().contains("非空约束"))
				throw new DaoException(DaoExceptionType.PARAMETER_MISSING);
			else
				throw new DaoException(DaoExceptionType.DATABASE_ACCESS_ERROR);
		} finally {
			closeDatabase(conn, st);
		}
		return result;
	}

![树莓派告警1](https://user-images.githubusercontent.com/6970189/131776255-52005e1e-df7a-4cab-be60-a1e3017c9856.JPG)

**Comment by xleili** [comment]
how many node dose your cluster have? are they have same version 2.1.0.0.  Do you run you application on dn02 ? change your client version same as your server client.
您的集群又几个节点，各个节点的tdengine 版本一致吗？这个java程序是在dn02上跑的吗？这个机器的客户端版本和上提到tdengine 2.1.0.0的版本不一致，可以换个相同版本客户端在试试吗？

**Comment by zyyang-taosdata** [comment]
please update your tdengine-client to solve this problem.

**Comment by coffeenan** [comment]
I have three nodes for taos db, and first time I find this problem in version 2.1.0.0 and I use the client version 2.0.30 as document required. Today I think maybe  update the taodb will solve this problem. so I change all taos node to the version 2.1.3.2. Then problem same. I have no idea how to deal with it. so I change access method from jdbc-jni to the jdbc-restful(also have some little parsing problem but I have fixed it from taos jdbc source). then you known what? problem solved. now I as so sure that must be JNI problem. please check it!

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
