### ISSUE TITLE
idea Tdengine configuration issue

### ISSUE THREAD

**Issue by 784134748** [taosdata/TDengine#8080]
![image](https://user-images.githubusercontent.com/16873072/134803128-07045e4f-b462-4211-b06a-de31234e8efd.png)

![image](https://user-images.githubusercontent.com/16873072/134803154-921fd120-c18c-40e1-8f6d-9c122d13d9c1.png)

![image](https://user-images.githubusercontent.com/16873072/134803190-bae48f76-837e-477b-86af-89d46b9e731b.png)

<failed to load>
java.sql.SQLException: ERROR (2315): unknown taos type in tdengine
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:69)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:56)
	at com.taosdata.jdbc.TSDBConstants.taosType2JdbcType(TSDBConstants.java:133)
	at com.taosdata.jdbc.TSDBResultSetMetaData.getColumnType(TSDBResultSetMetaData.java:151)
	in RemoteResultSetMetaDataImpl.getFixedColumnType(RemoteResultSetMetaDataImpl.java:105)
一路配置过来没啥问题，使用的时候报错了

**Comment by yu285** [comment]
https://github.com/taosdata/TDengine/issues/6602

any help?
