### ISSUE TITLE
jdbc driver hang when insert into TDengine  in loop

### ISSUE THREAD

**Issue by huyuemiss** [taosdata/TDengine#8647]
**Bug Description**
使用长连接执行循环插入，中途网络断开再恢复，程序会卡住较长时间（时长不确定）, 然后继续执行。此时查看线程信息如下：
"main" #1 prio=5 os_prio=0 tid=0x00007f529c00f000 nid=0x1c28a1 runnable [0x00007f52a0c30000]
   java.lang.Thread.State: RUNNABLE
	at com.taosdata.jdbc.TSDBJNIConnector.executeQueryImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:98)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:59)

程序打印执行时长如下，其中第二次为断网再恢复
1, 2021-11-10T16:51:39.087, insert :1, used:62.248532 ms
2, 2021-11-10T17:08:53.628, insert :1, used:1034040.293917 ms
3, 2021-11-10T17:08:54.209, insert :1, used:81.080271 ms

示例代码：

public static void main(String[] args) throws Exception {
        Class.forName("com.taosdata.jdbc.TSDBDriver");
        Connection connection = DriverManager.getConnection("jdbc:TAOS://:/data",
                "user",
                "pass");

        while (true) {
            String sql = " a insert sql";
            try (Statement statement = connection.createStatement()) {
                long start = System.nanoTime();
                int result = statement.executeUpdate(sql);
                System.out.println(LocalDateTime.now()
                        + ", insert :" + result + ", used:"
                        + (System.nanoTime()- start)/ 1000000.0 + " ms");
            }
            TimeUnit.MILLISECONDS.sleep(500L);
        }
    }

环境信息：
OS: Ubuntu 20.04
TDengine version : 2.2.1.1
taos-driver version : 2.0.34

**Comment by zyyang-taosdata** [comment]
从描述来看，是说在第2次执行insert的sql时需要很长的时间。
线程信息显示在执行native方法executeQueryImp，这种情况可能和TDengine的Client有关。您可以开启client端的日志，检查具体的sql语句的执行时间。
我会使用您提供的代码，尝试复现这个问题。

**Comment by huyuemiss** [comment]
您可以开启client端的日志，检查具体的sql语句的执行时间。

您好，可以描述一下怎么操作吗？

**Comment by huyuemiss** [comment]
还有一种情况是可以抛出异常：
Exception in thread "main" java.sql.SQLException: TDengine ERROR (8000000b): Unable to establish connection
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75)
	at com.taosdata.jdbc.TSDBJNIConnector.executeQuery(TSDBJNIConnector.java:123)
	at com.taosdata.jdbc.TSDBStatement.executeUpdate(TSDBStatement.java:59)

但如上文提到，有时候会在如下方法卡住，从代码看这个是native方法，所以因为看不到到底在执行什么。 com.taosdata.jdbc.TSDBJNIConnector#executeQueryImp 

从代码路径看不管是卡住还是抛出异常，都会执行这个方法，不知道到底是因为什么会有不同表现。

**Comment by huyuemiss** [comment]
有什么进展吗

**Comment by zyyang-taosdata** [comment]
This issue is stale because it has been open for 30 days with no activity.
