### ISSUE TITLE
TDengine ERROR (2350): failed to execute batch bind

### ISSUE THREAD

**Issue by gamechanger3** [taosdata/TDengine#8812]
spark 使用JAVA JNI 参数绑定方法批量写tdengine，只能写进去部分数据，日志报错如下：
java.sql.SQLException: TDengine ERROR (2350): failed to bind column data
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:75)
	at com.taosdata.jdbc.TSDBJNIConnector.bindColumnDataArray(TSDBJNIConnector.java:328)
	at com.taosdata.jdbc.TSDBPreparedStatement.columnDataAddBatch(TSDBPreparedStatement.java:956)
	at com.example.tech.service.TDengineService.lambda$null$1(TDengineService.java:135)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at com.example.tech.service.TDengineService.lambda$static$d25029bb$1(TDengineService.java:105)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:225)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:225)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1870)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1870)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
是参数绑定会限制一个batch的插入数量吗？
还是超过了sql的长度？
还是其他原因呢？
求解惑！
感谢！

**Comment by huolibo** [comment]
1. 确实存在长度限制，但最大值为6W多。建议做下尝试，对插入条数做下限制，防止数据量过大由于网络原因导致写入失败。
2. 如果是sql过长，应该都不能写入成功。
现在需要确认的是： 是否为同一次调用有些成功而另一些写入失败，还是多次调用一些调用成功另一些调用失败了。
另外，需要提供下执行时/var/log/taos/taoslog0.0日志，方便进行问题分析。

**Comment by gamechanger3** [comment]
> 

多谢！
确实是sql长度的原因
应该是部分调用失败，部分成功的原因是，某些设备的数据量少，sql长度没有超过限制。

**Comment by gamechanger3** [comment]
> 1. 确实存在长度限制，但最大值为6W多。建议做下尝试，对插入条数做下限制，防止数据量过大由于网络原因导致写入失败。
> 2. 如果是sql过长，应该都不能写入成功。
>    现在需要确认的是： 是否为同一次调用有些成功而另一些写入失败，还是多次调用一些调用成功另一些调用失败了。
>    另外，需要提供下执行时/var/log/taos/taoslog0.0日志、安装tdengine的版本，方便进行问题分析。

多谢！
确实是sql长度的原因
应该是部分调用失败，部分成功的原因是，某些设备的数据量少，sql长度没有超过限制。

**Comment by huolibo** [comment]
嗯，可以限制batch size再尝试下，看能否全部写入成功。

**Comment by huolibo** [comment]
还有什么需要帮助吗？

**Comment by gamechanger3** [comment]
> 还有什么需要帮助吗？

还有一个关于OOM的一个问题：
问题描述：用idea本地执行spark stmt方式写数据到tdengine，数据量小的时候可以成功，数据量大的时候会报错
Process finished with exit code -1073740791 (0xC0000409)
把程序拿到集群上执行的时候，会有很多task，报OOM，加内存后还是会有
但是，分配的内存是足够去处理这些数据的

我看到有一个这样的issue https://github.com/taosdata/TDengine/issues/7893
是不是和这个有关系？
有没有什么好的方式去优化？
谢谢！

**Comment by huolibo** [comment]
加内存后，是否有调整spark使用的参数。如果spark内部使用队列来处理这些信息（仅是怀疑，spark没有使用经验）。taos消费速度小于写入速度就会造成oom，其实应该扩大队列的大小，而不仅仅是加jvm内存。

**Comment by gamechanger3** [comment]
> 加内存后，是否有调整spark使用的参数。如果spark内部使用队列来处理这些信息（仅是怀疑，spark没有使用经验）。taos消费速度小于写入速度就会造成oom，其实应该扩大队列的大小，而不仅仅是加jvm内存。

好的，谢谢！
没其他问题了。

**Comment by kinghuisFFFF** [comment]
How to solve
