### ISSUE TITLE
When writing data through parameter binding, tagName cannot be specified

### ISSUE THREAD

**Issue by lrzl** [taosdata/TDengine#9142]
**Bug Description**
通过参数绑定写入数据时，不能指定tagName
一旦指定会造成jni报错，不指定又可能会导致tag错位

**To Reproduce**
#### 前提条件
1. 超级表建表语句 
> `CREATE STABLE IF NOT EXISTS wind (ts TIMESTAMP,direction DOUBLE,speed DOUBLE) TAGS(sensor NCHAR(32),city NCHAR(32))`
2. java语句
```java
String sql = "..."//下面列出此处sql两种写法出现的现象
try (Connection connection = hikariDataSource.getConnection();
             PreparedStatement pst = connection.prepareStatement(sql)) {
            TSDBPreparedStatement ps = pst.unwrap(TSDBPreparedStatement.class);
            // 设定数据表名：
            ps.setTableName("wind_test");
            // 设定 TAGS 取值：
            int i = 0;
            ps.setTagString(i++, "211207095244587");
            ps.setTagString(i++, "Guangdong.Shaoguan");
            
            // VALUES 部分以逐列的方式进行设置：
            i = 0;
            ArrayList<Long> ts = new ArrayList<>();
            ts.add(System.currentTimeMillis());
            ts.add(System.currentTimeMillis() + 1);
            ts.add(System.currentTimeMillis() + 2);
            ts.add(System.currentTimeMillis() + 3);
            ps.setTimestamp(i++, ts);
            ArrayList<Double> speed = new ArrayList<>();
            speed.add(9.222671643691767);
            speed.add(6.527509904778147);
            speed.add(2.1735372340976533);
            speed.add(9.605662156544678);
            ps.setDouble(i++, speed);
            ArrayList<Double> direction = new ArrayList<>();
            direction.add(2.217319622244439);
            direction.add(1.9570507396870918);
            direction.add(3.1581005507983226);
            direction.add(3.893938024794453);
            ps.setDouble(i++, direction);
            // AddBatch 之后，缓存并未清空。为避免混乱，并不推荐在 ExecuteBatch 之前再次绑定新一批的数据：
            ps.columnDataAddBatch();
            // 执行绑定数据后的语句：
            ps.columnDataExecuteBatch();
            // 执行语句后清空缓存。在清空之后，可以复用当前的对象，绑定新的一批数据（可以是新表名、新 TAGS 值、新 VALUES 值）：
            ps.columnDataClearBatch();
            // 执行完毕，释放资源：
            ps.columnDataCloseBatch();
}
```

#### ~~按照文档示例写法~~
~~`INSERT INTO ? USING wind TAGS ( ?,? ) ( ts,speed,direction ) VALUES ( ?,?,? )`~~

~~此写法会导致数据的tag错位~~
~~我的目的是想把`Guangdong.Shaoguan`写到`city`列，时间戳写到`sensor`列~~
~~实际数据库查询结果tag列是反的~~
![image](https://user-images.githubusercontent.com/32292315/146341883-3402cdd6-d4a2-42a8-807b-1570016f58b1.png)

#### 参考单条插入补充tagName写法
`INSERT INTO ? USING wind ( city,sensor ) TAGS ( ?,? ) ( ts,speed,direction ) VALUES ( ?,?,? )`

会导致jni报错
![image](https://user-images.githubusercontent.com/32292315/146342464-f58e2727-0810-4b48-9f68-bca061a35a15.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 -  ~~TDengine Version2.2.2.0~~
 - TDengine Version 2.2.0.5
 - taos-jdbcdriver Version 2.0.34

**Additional Context**
[hs_err_pid42700.log](https://github.com/taosdata/TDengine/files/7725921/hs_err_pid42700.log)

**Comment by huolibo** [comment]
最新版jdbc测试没有复现这个问题，可以尝试升级下jdbc版本。
我根据提供的版本信息搭建环境再测试一下。

**Comment by lrzl** [comment]
> 我的环境使用目前最新版taos-jdbcdriver 2.0.35无法初始化连接，使用2.0.34就没这个问题。异常信息为
```
Caused by: java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;
	at com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:54)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
```

**Comment by lrzl** [comment]
环境变量描述错误：
实际 TDengine Version 为 2.2.0.5
因为我本机系统环境有个2.2.0.5版本的客户端，java指定的2.2.2.0 jni path未生效。
我正在尝试更换

**Comment by lrzl** [comment]
TDengine Version 升级至 2.2.2.10 后正常
## Environment 
OS: Arch Linux
TDengine Version 2.2.2.10
taos-jdbcdriver Version 2.0.34
# 升级至 2.2.2.10 后现象更新：
## 1.参考单条插入补充tagName写法 （程序恢复正常）
`INSERT INTO ? USING wind ( city,sensor ) TAGS ( ?,? ) ( ts,speed,direction ) VALUES ( ?,?,? )`
升级后此方式已无错误，程序执行正常。数据也正常
## 2.使用taos-jdbcdriver 2.0.35无法初始化连接 （仍存在）
依然无法初始化连接
```
Caused by: java.lang.UnsatisfiedLinkError: com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Ljava/lang/String;)Lcom/taosdata/jdbc/TSDBException;
	at com.taosdata.jdbc.TSDBJNIConnector.setConfigImp(Native Method)
	at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:54)
	at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:135)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
```

## 按照文档示例写法 （个人操作不当）
`INSERT INTO ? USING wind TAGS ( ?,? ) ( ts,speed,direction ) VALUES ( ?,?,? )`
查明属于我操作不当引起的
原因：
初次建`wind_test`表时tag列的值是错位的，后续测试`wind_test`表未删除 tag值不会更新导致


因初始问题目前已都解决，此问题可以关闭。taos-jdbcdriver 2.0.35 问题是否需要重新开个issues跟进由你们决定

**Comment by huolibo** [comment]
好的,感谢反馈。
我查下2.0.35依然存在无法初始化连接的原因。
