### ISSUE TITLE
ProgrammingError [TDError.DatabaseError.ProgrammingError]: invalid operation: '303列头柜', 'I01柜','0303F303-00AF-AB0A-0002-09','PDU_Line1' (Invalid argument)

### ISSUE THREAD

**Issue by luxs-yy** [taosdata/TDengine#9900]
将如下的sql，放在taos是可以正常执行的。
INSERT INTO tab26494 USING stb_report TAGS ('303列头柜', 'I01柜','0303F303-00AF-AB0A-0002-09','PDU_Line1_Output_I02') VALUES ('2022-01-19 17:19:50', 37.29);
用nodejs 执行，就报如下的错误：
ProgrammingError [TDError.DatabaseError.ProgrammingError]: invalid operation: '303列头柜', 'I01柜','0303F303-00AF-AB0A-0002-09','PDU_Line1' (Invalid argument)
    at TDengineCursor.execute (D:\ideaProjects-vue\TDengine\node_modules\td2.0-connector\nodetaos\cursor.js:142:11)
    at saveData (D:\ideaProjects-vue\TDengine\src\createTable.js:57:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

我的超级表结构：

taos> DESCRIBE  stb_report ;
             Field              |         Type         |   Length    |   Note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 current                        | FLOAT                |           4 |          |
 ltg_name                       | NCHAR                |          50 | TAG      |
 cabinet_name                   | NCHAR                |          50 | TAG      |
 device_id                      | NCHAR                |         100 | TAG      |
 param_code                     | NCHAR                |         100 | TAG      |

**Comment by xleili** [comment]
我们排查一下

**Comment by xleili** [comment]
![image](https://user-images.githubusercontent.com/85657333/151095937-d6f6676a-61c7-4081-b0bf-3358529f483a.png)
我这是可以的，你在检查一下看看。和我截图有有什么不一样吗

**Comment by xleili** [comment]
This issue is stale because it has been open for 30 days with no activity.
